### ISSUE TITLE
Feature Request: Trigger Templater template fields when using Daily Note feature

### ISSUE THREAD

**Issue by pauljacobson** [SilentVoid13/Templater#10]
### Summary

It would be super helpful to somehow have Templater fields trigger when running the Daily Note plugin, so the fields translate into data, as opposed to separately triggering the Templater templates after opening a blank Daily Note.

### Steps to reproduce

1. I added Templater fields to my Daily Note template;
2. When I create a Daily Note using the Daily Note plugin, the Templater placeholders don't render as expected;
3. If I trigger the Templater template specifically, it renders.

### What I did

This is what I added to my template:

```
Tags: #dailynote

{{weather}}

# {{today}}
```

Here are my templates:

<img width="1350" alt="Screen Shot 2020-11-16 at 8 21 20" src="https://user-images.githubusercontent.com/2912202/99219154-bbb28e00-27e4-11eb-934a-cd34e0e61312.png">

Here is a demo of what happens: https://d.pr/v/kJ4FuD/sY2w43DZXe

### System details

Obsidian v0.9.11
OS: macOS 11.0.1

**Comment by SilentVoid13** [comment]
Hello @pauljacobson, thanks for this well explained feature request !

You are right, this would be nice if I could find find a way to trigger the templater plugin when using the core Daily Notes plugin or the core Templates plugin. 
I'll add that to my todo list for future improvements !

**Comment by pauljacobson** [comment]
>thanks for this well explained feature request !

My pleasure. I spend a bit of my time at work submitting GitHub issues, and our developers are very particular about properly structured issues. 😜

> You are right, this would be nice if I could find find a way to trigger the templater plugin when using the core Daily Notes plugin or the core Templates plugin.
> I'll add that to my todo list for future improvements !

Hi there. You're welcome. I wasn't sure if this is practical given how plugins can interact (or not - I'm not familiar with how it all works behind the scenes). If it is feasible, it will be a really handy integration.

Thanks for your feedback!
