### ISSUE TITLE
Ability to use ISO 8601 for offset in dates

### ISSUE THREAD

**Issue by louisboulagnon** [SilentVoid13/Templater#100]
Thanks for the great plugin, I thought of a possible improvement regarding date parsing.

**Is your feature request related to a problem? Please describe.**
I think it could be interesting to have the ability to use ISO 8601 durations (https://en.wikipedia.org/wiki/ISO_8601#Durations) in the offset, this would allow to have fairly dynamic and granular date navigation, specifically for months which don't always have the same number of days.
The end goal being to be able to create dates like `[[<% tp.date.now("YYYY-MM-DD", "P-1M") %>|This day last month]]` for example

**Describe the solution you'd like**
Probably have the signature of days be `days?: number|string` (no issue with keeping `number` defaulting to days for backward-compatibility and ease of use) and pass a `moment.duration` (https://momentjs.com/docs/#/durations/creating/ which thankfully already support this ISO format) to the `.add` call.
https://github.com/SilentVoid13/Templater/blob/d708ea4f39f8a44b9b40ac52043d362aeeff64dc/src/InternalTemplates/InternalUtils.ts#L1-L3

**Additional context**
I haven't deep dived into the source code, but if you would like me to look into creating a pull request for this issue, I could probably contribute this when I have some free time.

**Comment by SilentVoid13** [comment]
Hey @louisboulagnon thanks for the suggestion! This has been implemented as of Templater 1.5.0.

Can you update and tell me if this works for you ?

**Comment by louisboulagnon** [comment]
It works perfectly, thank you !

Honored to have been the 100th issue on this project haha

**Comment by Moonbase59** [comment]
@louisboulagnon This turns out to be real useful, thanks for thinking about it!
And thanks @SilentVoid13 for implementing it!
