### ISSUE TITLE
Template parsing error only on mobile

### ISSUE THREAD

**Issue by Tiim** [SilentVoid13/Templater#1002]
**Plugin information (please complete the following information):**

-   OS: Android 13
-   Templater version: 1.16.0
-   Obsidian version: 1.4.1 (83) API v1.0.3
-   Templater settings: 

**Describe the bug**
When trying to insert a template, or when creating a new file, templater always shows the message "Templater Error: Template parsing error, aborting. Check console for more information". This happens with any template, even one without any template tags inside like this one:

```
 🔗 URL::
```
I finally figured out how to access the console on mobile with the [obsidian dev tools plugin](https://github.com/KjellConnelly/obsidian-dev-tools) and the error is the following:

```
templater-obsidian:61:13
"Templater plugin: Error:" "Template parsing error, aborting."
" "Cannot read properties of undefined
(reading 'promises')"
at log_error (plugin: templater-
obsidian:61:13)
at errorWrapper (plugin:templater-
obsidian:81:7)
at async
Templater.append_template_to_active_file
(plugin: templater-obsidian:3700:28)
```

**Expected behavior**
There should not be an error and the template should be inserted just like on desktop. 

**Screenshots**
The console from the dev tools plugin. 

![SmartSelect_20230123_012405_Obsidian](https://user-images.githubusercontent.com/1063187/213948589-22324978-760a-4c0a-81b1-7eff7edd3169.jpg)

**Additional context**
It used to work a while ago, unfortunately I don't remember when it broke.

**Comment by Zachatoo** [comment]
This is likely related to #1212, can you check to see if it's an issue with a user script?

**Comment by Tiim** [comment]
Yes, you are right, it was related to an issue in a user script. I'm glad to see that better error messages are on the way!
