### ISSUE TITLE
Missing comma in style.css?

### ISSUE THREAD

**Issue by jaymaleoca** [SilentVoid13/Templater#1008]
Hi SilentVoid13,

Not a bug per se—but I think a comma is missing at the end of line 138 of the style CSS file?

https://github.com/SilentVoid13/Templater/blob/487805b5ad1fd7fbc145040ed82b4c41fc2c48e2/styles.css#L138

Thanks,
Jason

PS: Sorry, not confident enough to make an edit and push changes.

**Plugin information (please complete the following information):**

-   OS: [e.g. Windows 10]
-   Templater version: [e.g. 0.3.4]
-   Obsidian version: [e.g. 0.9.11]
-   Templater settings: [e.g. Template folder location: "Templates/", Timeout: "5" (add the templates not working with their associated command)]

**Describe the bug**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by welpdx** [comment]
Hey @jaymaleoca, I created a PR based on what you said. I feel like that was a really good catch and honestly, I feel like you should do one next time, it's not that bad!
