### ISSUE TITLE
translate date from title to new format

### ISSUE THREAD

**Issue by filmgal** [SilentVoid13/Templater#101]
I'm afraid to update to the new version because I rely too much on the following, and it wasn't clear to me how to translate it into the new format. Can someone help? If I get this going, then everything else I can figure out on my own.
My titles include the date format as follows: YYYYMMDD

Current code:
`{{tp_title_date:f="YYYYMMDD"}}`  which just gives me the date format in the title, and
`{{tp_title_date:f="dddd MMMM DD YYYY"}} ` which transforms the date format in the title into a different format.

**Comment by I-Pch** [comment]
Hi @filmgal 😊 

I think you can rename your notes by creating a template with this 👇 : 
```
<% tp.file.rename(tp.date.now("dddd MMMM DD YYYY", 0, tp.file.title, "YYYYMMDD")) %>
```
(I've tested in my vault and it seems to work 😊 )

It's a "nested" function which when called through templater or at the creation of the note will first "transform" the date from your title into the desire format (See here : https://github.com/SilentVoid13/Templater/issues/79#issuecomment-814420169)
```
tp.date.now("New_Date_Format", 0, tp.file.title, "Old_Date_Format_Based_on_the_Title")
``` 
and then rename the note with the new format :
```
<% tp.file.rename(New_Title_with_the_New_Date_Format) %>
```

> `{{tp_title_date:f="YYYYMMDD"}}` which just gives me the date format in the title, and

For this part though, it might depend on how you use it generally 🤔 .
If it's just to put the title of the note somewhere in the note, without renaming it, you could just use `<% tp.file.title %>`

**Comment by SilentVoid13** [comment]
Hey @filmgal, as @I-Pch said (thanks for the answer!), the strict equivalent of `{{tp_title_date:f="YYYYMMDD"}}` is 
```
<% tp.date.now("YYYYMMDD", 0, tp.file.title, "YYYY-MM-DD") %>
```

Tell me if this works for you

**Comment by filmgal** [comment]
Yes - sorry, I didn't get a chance to try it until just now. I'm not exactly certain why my the YYYYMMDD date in my title comes after "tp.date.now" rather than after "tp.file.title", but it works, so thank you!

**Comment by SilentVoid13** [comment]
@filmgal The first format is for the date output, while the second format is the title's date format. More informations here: https://silentvoid13.github.io/Templater/docs/internal-variables-functions/internal-modules/date-module
