### ISSUE TITLE
Templater automatically renames a new script.js with the name of the opened note.

### ISSUE THREAD

**Issue by tiagobrc** [SilentVoid13/Templater#1014]
**Plugin information (please complete the following information):**

-   OS: macOS Ventura 13.0.1
-   Templater version: 1.16.0
-   Obsidian version: 1.1.9
-   Templater settings: Template folder location: "Templates/", Timeout: "5" (add the templates not working with their associated command)]

**Describe the bug**
Templater renames any new_script.js in the folder Templater/scripts with the name of the opened note at the time. 

**Expected behavior**
A new_script.js should not be renamed to the name of the opened note.

**Screenshots**
<img width="944" alt="Screenshot 2023-01-30 at 11 49 15 AM" src="https://user-images.githubusercontent.com/12516337/215541650-1293fb33-7cd2-4c52-8a47-f62f2b934d7b.png">

<img width="852" alt="Screenshot 2023-01-30 at 11 49 59 AM" src="https://user-images.githubusercontent.com/12516337/215541657-6ae3aceb-b24c-49b8-8525-80801172f850.png">

<img width="503" alt="Screenshot 2023-01-30 at 11 50 13 AM" src="https://user-images.githubusercontent.com/12516337/215541668-f04ab46b-93d0-4108-b687-4b65d6615a9e.png">
<img width="232" alt="Screenshot 2023-01-30 at 11 50 21 AM" src="https://user-images.githubusercontent.com/12516337/215541683-781f5afa-00a5-42da-bee9-f7425ea5fb00.png">

**Comment by welpdx** [comment]
That's a strange one. Some how the new note title is tied to the /scripts folder in the vault?

Anyways, I've started a new note and I can not reproduce the bug (on Windows). The script works fine tho.

![img](https://i.imgur.com/RgnUfx4.png)

**Comment by tiagobrc** [comment]
Strange indeed. However, if I create the script outside of the scripts folder and move it there. No name modification happens.

**Comment by welpdx** [comment]
Strange.

Do you happen to have Folder Template on or a plugin that changes file names?

Yea, it does seem local and not really a bug with Templater. Although I have not tested in on mac yet. If you want, what you can do is just create a new vault with just templater installed. Then try with your user script and see if the same problem come up again.

**Comment by Zachatoo** [comment]
Marking as removed due to no response from issue author.
