### ISSUE TITLE
Can tp.system.suggester accept values not on the list

### ISSUE THREAD

**Issue by HyperEpsilon** [SilentVoid13/Templater#1017]
**Is your feature request related to a problem? Please describe.**  
I am somewhat often using the template suggester to add values of people I play board games with. Generally I have a consistent group, but sometimes I play with folks outside my normal group. I have my typical playgroup in a list, but I can't add random one-off folks.

**Describe the solution you'd like**  
I would like to be able to use the auto complete capabilities of `tp.system.suggester`, but also input values that are not present in the list.

**Describe alternatives you've considered** 
I've just been adding them in afterwards manually.

In theory, I could also rig up a dummy answer to trigger the `tp.system.prompt` when entered, which I think will be my next step

**Comment by welpdx** [comment]
Could you provide an example of what you want specifically?
I understand this:
> I would like to be able to use the auto complete capabilities of tp.system.suggester, but also input values that are not present in the list.

But I dont understand this:
> In theory, I could also rig up a dummy answer to trigger the tp.system.prompt when entered, which I think will be my next step


Thanks

**Comment by welpdx** [comment]
Anyways, in order to input a value, one could implement a "[hack](https://github.com/SilentVoid13/Templater/discussions/656#discussioncomment-2876420)", which adds an additional option in the original suggester, and after that is clicked, it will open up prompt to input that value. 

rough pseudo code:
arrayA = ["valueA", "valueB"...]
arrayB = ["value1", "value2"...]
arrayA.push("enter custom value")
arrayB("custom")

var output = await tp.system.suggester(arrayA, arrayB);

if output == "custom"
     let new output be: tp.system.prompt("What is your customer value?")
else if value empty
     exit with Notice("you didnt select anything")

do stuff with output here

---

If you have a specific example, I can program a more detailed "hack".


If you want to make a change to Templater code, feel free to look at it [here](https://github.com/SilentVoid13/Templater/tree/master/src/core/functions/internal_functions/system) and make a PR.

**Comment by HyperEpsilon** [comment]
Yeah that's basically the exact hack I had in mind

**Comment by HyperEpsilon** [comment]
This is probably a little over engineered, but here's my solution for anyone else. It will loop through until the user selects DONE or hits escape (which also returns `null`)

```js
<%* 
var final_name_list = [];
const list_names = ["Person-1", "Person-2"];
const list_data = ["#Person-1", "#Person-2"];

// Add control elements
const other_placeholder = -1;
list_names.unshift("= DONE =");
list_data.unshift(null);
list_names.push("= OTHER =")
list_data.push(other_placeholder);

i = 0;
var name = await tp.system.suggester(list_names, list_data, false, `Select the ${format_index(++i)} player`);
while (name) {
  if (name === other_placeholder) {
    name = await tp.system.prompt(`Enter the name of the ${format_index(i)} player`)
  } else {
    remove_name(name);
  }
  
  final_name_list.push(name);
  name = await tp.system.suggester(list_names, list_data, false, `Select the ${format_index(++i)} player`);
}

var name_string = final_name_list.join(", ");

function remove_name(name_rm) {
  var i = list_data.indexOf(name_rm);
  if (i > 0) {
    list_names.splice(i, 1);
    list_data.splice(i, 1);
  }
}

function format_index(i) {
  switch(i) {
    case 1:
      return "1st";
      break;
    case 2:
      return "2nd";
      break;
    case 3:
      return "3rd"
      break;
    default:
      return `${i}th`;
  }
}
_%>

<% name_string %>

```

**Comment by welpdx** [comment]
Excellent! This works very well.

Btw, I noticed that there are no hashtags in front of the new names added in that while loop. To add a hashtag, I just did:

```js
while (name) {
  if (name === other_placeholder) {
    name = "#" +  await tp.system.prompt(`Enter the name of the ${format_index(i)} player`)
```


Great work, love this hack!

**Comment by HyperEpsilon** [comment]
That was a deliberate choice on my part, but it's good that you added that option in.

I might try and turn this into a user function so that I can call it from other notes, but currently I'm pretty happy with it as is

**Comment by welpdx** [comment]
@HyperEpsilon Ah I see! Yea this hack is pretty good! Let me know how it goes with the user script!

Btw, how do you feel about making changes (PR) to Templater's Suggester to add additional functions? Since I'm not too good with typescript, it seems very complex lol. What do you think?

**Comment by HyperEpsilon** [comment]
While I have a passing familiarity with TypeScript, I'm by no means proficient.

I haven't looked into changing any of the actual code, but maybe I will when I have some free time.

**Comment by NihilityT** [comment]
Try this hook:
``` js
function hookSuggestionsQuery() {
    if (this.___getSuggestions == null) {
        this.___getSuggestions = this.getSuggestions;
        this.getSuggestions = function (query) {
            this.___query = new String(query);
            this.___query.___isInputByUser = true;
            return this.___getSuggestions(query);
        }
        this.getItems = function () {
            if (this.___query.length) {
                return [...this.items, this.___query];
            }
            return this.items;
        }
    }
}
function textWithQuery(item) {
    hookSuggestionsQuery.call(this);
    if (item.___isInputByUser) {
        return '> ' + item;
    }
    return item;
}
tp.system.suggester(textWithQuery, ["Happy", "Sad", "Confused"]);
```

I'll try to create a PR when I have time.
