### ISSUE TITLE
no activate view, can't append templates

### ISSUE THREAD

**Issue by wzy1120433847** [SilentVoid13/Templater#1018]
Thank you for your work!

-   OS: Windows 11
-   Templater version:1.16.0
-   Obsidian version: 1.1.9
-   Templater settings: [e.g. Template folder location: "Templates/", Timeout: "5" (add the templates not working with their associated command)]

Hi, I want to use kanban's card to automatically insert new notes with templates. kanban's authors say they support Templater, but when I use Templater, I'm prompted with "no activate view, can't append templates". What does this hint mean?How can I solve this problem?

![image](https://user-images.githubusercontent.com/61544043/215976122-d32657d8-7696-4e43-be7e-d35cd31df061.png)
![image](https://user-images.githubusercontent.com/61544043/215976277-ae7ede1a-1b4f-4138-b2f4-2f4bb5687d3f.png)

kanban ’s configuration
![image](https://user-images.githubusercontent.com/61544043/215976765-e8489389-fa22-4195-8ad2-7fa968644615.png)

create a note:
![image](https://user-images.githubusercontent.com/61544043/215976534-65f99542-592d-499d-afd9-591f88c768c8.png)

no activate view, can't append templates
![image](https://user-images.githubusercontent.com/61544043/215976992-940699cc-305a-4c15-a008-41f3cb8149b5.png)

At the same time the new note is empty and no template is used
![image](https://user-images.githubusercontent.com/61544043/215977130-dcc6cbbd-8aa2-4306-b800-e52adf0738fd.png)

**Comment by wzy1120433847** [comment]
In normal notes I can insert templates as normal

**Comment by Zachatoo** [comment]
There was a recent change that now only requires an active editor, not an active view. It's possible that this was resolved by that. Can you verify?

**Comment by Zachatoo** [comment]
Marking as resolved, see above comment.

**Comment by billowssun** [comment]
I have the same problem using dust calendar!

**Comment by Zachatoo** [comment]
@billowssun Do you mind creating a new issue with reproduction steps? I tried clicking around in the dust calendar plugin a bit, but I don't understand the language, so I'm not sure how Templater works with the Dust Calendar plugin.
