### ISSUE TITLE
Accessing Dataview API - Cannot read properties of undefined

### ISSUE THREAD

**Issue by cocofoco** [SilentVoid13/Templater#1023]
**Plugin information (please complete the following information):**

-   OS: Windows 10
-   Templater version: 1.16.0 (also on 1.15.3)
-   Obsidian version: 1.1.12
-   Templater settings: Folder location: Resources/Templates; Template code: https://pastebin.com/8MX7zZ4x

**Describe the bug**
Templater is not accessing the Dataview API properly. 

**Expected behavior**
Templater should access the Dataview API, and then be able to use its functions, thus allowing me to use functions like `suggester()` with arrays created with Dataview.

**Screenshots**
![immagine](https://user-images.githubusercontent.com/71672080/216840217-3d7139dc-2715-49cc-8c78-ca5f3d664d88.png)

![immagine](https://user-images.githubusercontent.com/71672080/216840577-b8becec7-82c4-43fa-a8e3-f3612339fcd9.png)

**Additional context**
According to [the docs](https://blacksmithgu.github.io/obsidian-dataview/api/intro/), all that one needs to do is add `app.plugins.plugins.dataview.api` to access it, but for some reason it doesn't work.

I know for sure that it worked fine until some time ~20th december 2022 (maybe even later, but I'm not sure, because I haven't used this template since, until today, when I suddenly realised that it's not working anymore).

**Comment by cocofoco** [comment]
Turns out, I didn't have Dataview installed.

**Comment by welpdx** [comment]
It do be like that some times lol.

Thanks for replying and closing this btw!
