### ISSUE TITLE
tp.file.tags not working in obsidian yaml

### ISSUE THREAD

**Issue by rachelemoore** [SilentVoid13/Templater#1029]
**Plugin information:**

-   OS: Mac Monterey
-   Templater version: 1.16.0
-   Obsidian version: 1.1.9
-   Templater settings: Template folder location: "Templates/"

**Describe the bug**
First - apologies for the probably ignorant question! I'm very much a beginner here so have tried searching for this on multiple forums but haven't been able to find a solution.

I have the following in my frontmatter:

up: [[2.0 Project_RNA MOC]]
title: <%+ tp.file.title %>
ID: 202301222148
alias: E017
date_created: <%+ tp.file.creation_date("DD MM YYYY") %>
date_modified: <%+ tp.file.last_modified_date("DD MM YYYY") %>
date_completed: 
tags: <%+ tp.file.tags %>
Status: "#INCOMPLETE"

When I switch to read view, all of the templater fields work perfectly except for tp.file.tags (see screenshot below). 

**Expected behavior**
I expect an output of a list of tags.

**Screenshots**
<img width="664" alt="Screen Shot 2023-02-10 at 16 05 22" src="https://user-images.githubusercontent.com/124698533/218139190-877a18a0-4b85-4d1c-92f4-7952dddf52fd.png">
<img width="646" alt="Screen Shot 2023-02-10 at 16 05 31" src="https://user-images.githubusercontent.com/124698533/218139197-09f5fc83-3b9e-4abb-85df-54b8ada5d816.png">

**Additional context**
I had to make each of the other templater fields dynamic for them to work
eg: <%+ tp.file.title %> instead of <% tp.file.title %>
I think this is because I am working with a note that already existed rather than creating a new note? However, this trick hasn't worked with tp.file.tags.

**Comment by welpdx** [comment]
After adding tags to your document, refresh the document (close and reopen) or `Reload app without saving` in the command palate. See if that fixes the issue. Doing this helps fresh the cache.

**Comment by rachelemoore** [comment]
Thanks for the reply. Yep, I have tags in the document and had already tried closing and reopening the document (and also Obsidian itself). I hadn't tried "Reload app without saving" but unfortunately that hasn't helped either. 

Most of the tags in this document are associated with a task or list and/or using the Colourful Tag community plugin. I've now added a couple of test tags in different parts of the document that don't fall into these categories and this hasn't helped either. (No idea if this is a reasonable thing to try, but figured worth mentioning!)

**Comment by realfr** [comment]
I'm having a similar issue with mine. None of the templater fields work anymore in frontmatter and on the body. They were working fine yesterday with no changes to the commands. I keep getting this error: 
![image](https://user-images.githubusercontent.com/120209053/222580119-17aa1df6-ff7d-4ad1-8b76-92baa87d4918.png)

**Comment by Zachatoo** [comment]
I'm impressed that dynamic commands work at all in frontmatter, didn't know that some of them worked.

I don't think this is going to be fixed anytime soon, since [dynamic commands might be deprecated at some point](https://github.com/SilentVoid13/Templater/issues/913). You may want to consider other plugin alternatives for dynamic content, like Dataview.

**Comment by rachelemoore** [comment]
OK that's great to know re deprecation, thanks. I'm using Dataview for other tasks so will try it out for this too. In frontmatter I can *only* get dynamic commands to work, so if they go I'm stuck!

Cheers.

**Comment by Zachatoo** [comment]
For tags specifically, I believe the Linter plugin can auto-add tags to frontmatter on save, may be worth looking into that?

**Comment by Zachatoo** [comment]
Going to close this since there aren't plans to make fixes for dynamic commands since it's planned to be deprecated
