### ISSUE TITLE
Code duplicates when starting the template with triple dashes

### ISSUE THREAD

**Issue by Scynevir** [SilentVoid13/Templater#1030]
**Plugin information:**

-   OS: Windows 10
-   Templater version: 1.16.0
-   Obsidian version: 1.1.9
-   Templater settings: Templates folder is "templates", script folder is "scripts"

**Describe the bug**
A template that starts with three dashes makes it behave weirdly.

Example : 
"notion.js" is written as follows
```
---
banner: "<% tp.user.random_banner("1500x300","galaxy, space, stars, HD") %>"
cssclass: banner-bug
banner_icon: 🔯
---
***
```

(the user code will be written in additional context, although it is irrevelant since using a single image rather than the fetch code creates the same issu)

doing alt+n and creating a new page using notion.js template makes the code messy : 

```
---
banner: "https://images.unsplash.com/photo-1519810755548-39cd217da494?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=300&ixid=MnwxfDB8MXxyYW5kb218MHx8Z2FsYXh5LCBzcGFjZSwgc3RhcnN8fHx8fHwxNjc2MTI5MzU3&ixlib=rb-4.0.3&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=1500"
---
---
banner: "https://images.unsplash.com/photo-1519810755548-39cd217da494?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=300&ixid=MnwxfDB8MXxyYW5kb218MHx8Z2FsYXh5LCBzcGFjZSwgc3RhcnN8fHx8fHwxNjc2MTI5MzU3&ixlib=rb-4.0.3&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=1500"
cssclass: banner-bug
banner_icon: 🔯
---
***
```

The banner url is written 2 times, there are 2 rows of unintended dashes in the middle too.

**Expected behavior**
the banner command shouldn't appear twice. There should only be 2 rows of dashes : first and last lines.

**Additional context**
random banner generation (although using a single image from my hard drive creates the same issue, so probably irrelevant) : 

```
// scripts/random_banner.js
async function random_banner(size, query) {
	const resp = await fetch(`https://source.unsplash.com/random/${size ?? ""}?${query ?? ""}`);
	if (!resp.ok) {
		return "Error: Couldn't fetch banner";
	}
	return resp.url;
}

module.exports = random_banner;
```

Thanks a lot for the upcoming help.

**Comment by welpdx** [comment]
Sorry I couldn't replicate your issue. 

<details>
           <summary style="font-size:20">it is working for me</summary>
           <img src="https://i.imgur.com/AygHmXl.gif" alt="demo" />
</details>


May I ask if you have a Folder Templater configured already or something? Or are you sure there is only one template in your `notion.js` template that you `Alt + n` 'd? 

It just seems like there are two templates here, one with:
```js
---
banner: "<% tp.user.random_banner("1500x300","galaxy, space, stars, HD") %>"
---
``` 

and the other one:

```js
---
banner: "<% tp.user.random_banner("1500x300","galaxy, space, stars, HD") %>"
cssclass: banner-bug
banner_icon: 🔯
---
```


Sorry if I cant help further. 


I am using:
Obsidian v1.1.9
Templater v1.16.0
New Vault with just Templater and Banner plugins
Windows 11 22H2



~welp

**Comment by Zachatoo** [comment]
Marking as removed due to no response from issue author.
