### ISSUE TITLE
Templater could not insert template in a note embedded in Obsidian Canvas

### ISSUE THREAD

**Issue by dimonier** [SilentVoid13/Templater#1034]
**Plugin information (please complete the following information):**

-   OS: Windows 10 x64
-   Templater version: 1.16.0
-   Obsidian version: 1.1.9

**Describe the bug**
Currently an attempt to invoke Templater from a note embedded in Obsidian Canvas ends up with a message saying:
> Templater Error: No active view, can't append templates.

That is, the error appears after I:
1. Embed a note in Canvas
2. Click in the note's body
3. Invoke **Templater: Open Insert Template modal** command
4. Select a template

**Expected behavior**
I'd like Templater working there the same way it works in a regular note, i.e. inserting selected template.

**Screenshots**
![image](https://user-images.githubusercontent.com/1196191/218439084-9a32ef13-40f1-4773-aa14-94290fecd4f8.png)

**Additional context**
Currently I have to type template's content manually instead or open the note in a separate tab to insert a template.

**Comment by Zachatoo** [comment]
To whoever decides to tackle this issue (I may take this on, but not until there's more maintainer activity).

Canvas support can be added by using `app.workspace.activeEditor` instead of `app.workspace.getActiveViewOfType`. [Here](https://github.com/Zachatoo/obsidian-inbox/commit/cdceec53a9f48682ec511a16810aa95edc23112d) is an example of how to migrate to that.

**Comment by tallguyjenks** [comment]
Also chiming in here that i GREATLY desire this as well

**Comment by Zachatoo** [comment]
Released in 1.16.1!

**Comment by tallguyjenks** [comment]
sandbox vault with default settings and only templater installed.
issue persists :/

![image](https://github.com/SilentVoid13/Templater/assets/29872822/1441c2dd-09ef-4f7e-8f28-891cd29ed6dd)

**Comment by Zachatoo** [comment]
I just checked in the sandbox vault as well. Though in the sandbox vault, notes by default show their file name in the card. Are you maybe expecting templates to work on cards that are not notes? That is not something that has been implemented as part of this issue.

<img width="1440" alt="image" src="https://github.com/SilentVoid13/Templater/assets/6936914/89d71741-4991-4040-ba35-239de6f39856">

**Comment by dimonier** [comment]
> Released in 1.16.1!

Yeah! it works now. Thank you so much!
