### ISSUE TITLE
Ability to Insert output of Javascript inline

### ISSUE THREAD

**Issue by ab-ll** [SilentVoid13/Templater#104]
I'd like to be able to create a javascript object / class / function in a template and then call it later with the output going into the text.

I.e. Declare a random function that selects a value from a list and then I can put that value into the text

i.e.

<%* getValue(); %> 

and have the value appear in the final output.  Trying this with document.write(getValue());  does not work causing an obsidian crash, but if I console.log the value I can see that I do have a value that is there.  Trying to do a replace on tR causes all sorts of performance / order execution issues if I try to create my own place to put it in.

**Comment by SilentVoid13** [comment]
Hey @ab-ll this is already possible! Check out the documentation for instructions: https://silentvoid13.github.io/Templater/docs/eta-features/execution-command#how-to-output-a-value-from-a-javascript-execution-command-

Using `tR` shouldn't cause any performance / order execution problems.
If it does, please share your full template so I can debug it.

In your example, this would give: `<%* tr += getValue(); %>`

Tell me if this works for you.

**Comment by SilentVoid13** [comment]
Hey @ab-ll, you can now also use script user functions if you don't want to bother with the `tR` variable.
Documentation at https://silentvoid13.github.io/Templater/docs/user-functions/script-user-functions
