### ISSUE TITLE
Mdnotes with Templater: code is not run with titles containing ":" (colon)

### ISSUE THREAD

**Issue by DaniEstevezBarcia** [SilentVoid13/Templater#1040]
**Plugin information (please complete the following information):**

-   OS: Ventura 13.2
-   Templater version: 1.16
-   Obsidian version: 1.1.15
-   Templater settings: Template folder location: "Templates/"

**Describe the bug**

I cannot say for sure if it can be called a "bug", I believe it is normal behaviour. The templater code within my template merely changes the title of the mdnotes imported from Zotero. The code does not work however if the title contains a colon, and the name of the mdnote remains unchanged. Since I also use zotero to insert citations and generate bibliography, I have to keep the original name, so I cannot remove the colon from the title. Is there any way around this?

Thank you

**Expected behavior**
The code should change the name of an mdnote upon import from Zotero in obsidian

**Comment by welpdx** [comment]
can you please provide your templater code?

Also, afaik, ":" is an invalid character for file titles. 
I haven't used mdnotes for a while but I remember I changed mdnotes such that md file would be named to something like "@lastnameFirstnameYearLetter"

**Comment by DaniEstevezBarcia** [comment]
Yep, that could be one way- changing the naming system. The code is:

<%*
	let title = "{{title}}";
	await tp.file.rename(`01. ${title}`);
_%>

**Comment by DaniEstevezBarcia** [comment]
Well, it was worth a try to ask ;) For now I am circumnavigating this by removing the colon from the title upon export.

Thanks
