### ISSUE TITLE
Templater with desktop hotkey shift + N gets unexpectedly applied when typing n on mobile after 11th line, ad infinitum.

### ISSUE THREAD

**Issue by szfkamil** [SilentVoid13/Templater#1047]
**Plugin information (please complete the following information):**

-   OS: iOS 13
-   Templater version: 1.16.0
-   Obsidian version: 1.1.16
-   Templater settings: [e.g. Template folder location: "Templates/", Timeout: "5" (add the templates not working with their associated command)]

**Describe the bug**

When typing "n" after 11 ish line on mobile, the template with hotkey shift + n gets triggered and pasted inside the note.

**Expected behavior**
The template not being invoked.
**Screenshots**
[Templater settings](https://imgur.com/a/46ZRMZ3)
[Screenrecording of the bug.](https://imgur.com/a/0dfDWkP)
**Additional context**
Add any other context about the problem here. It's 100% Templater when the plugin is disabled, the issue does not occur.

I posted about this on Obsidian Forum too, you should find additional useful information [here](https://forum.obsidian.md/t/template-is-applied-on-mobile-when-typing/52326)

**Comment by Zachatoo** [comment]
To confirm that it's Templater and not a combination of Templater and another plugin, can you try creating a new vault, just installing Templater, and seeing if the issue still persists?

**Comment by szfkamil** [comment]
Done, but it still persists. It does not persist in safe mode in my original vault, by the way.
