### ISSUE TITLE
tp.file.last_modified_date, No working in obsidian

### ISSUE THREAD

**Issue by iamfeiyu** [SilentVoid13/Templater#1051]
**Plugin information (please complete the following information):**

-   OS: [Windows 10]
-   Templater version: [1.16.0]
-   Obsidian version: [1.1.16]
-   Templater settings: [e.g. Template folder location: "Templates/", Timeout: "5" (add the templates not working with their associated command)]
```
{
  "command_timeout": 5,
  "templates_folder": "zob_resources/zob-templates",
  "templates_pairs": [
    [
      "",
      ""
    ]
  ],
  "trigger_on_file_creation": true,
  "auto_jump_to_cursor": true,
  "enable_system_commands": false,
  "shell_path": "",
  "user_scripts_folder": "",
  "enable_folder_templates": true,
  "folder_templates": [],
  "syntax_highlighting": true,
  "enabled_templates_hotkeys": [],
  "startup_templates": [],
  "enable_ribbon_icon": true
}
```
![image](https://user-images.githubusercontent.com/25132486/223977948-c6086765-4dea-46e8-a2be-da57ae8bc890.png)

**Describe the bug**
tp.file.last_modified_date("YYYY-MM-DD HH:mm ddd") in My Daily, Today, I find that tp.file.last_modified_date don't working in my note! It is shocked.

**Expected behavior**
When I modified my note, zhe date of ”updated“ string will being modified by tp.file.last_modified_date

**Screenshots**
My Templater:
![image](https://user-images.githubusercontent.com/25132486/223977700-91f052af-a40e-4204-8540-f3e323246517.png)

Actual result: 
![image](https://user-images.githubusercontent.com/25132486/223977483-6f0ef948-eb75-40b2-9a8a-8ffb791ea1b8.png)

**Comment by welpdx** [comment]
I couldn't replicate the bug. 

After I apply the template via `Templater: Open insert templater modal`, I get the actual result that you wrote.

I only had the below in my template:
```js
Today: <% tp.file.last_modified_date("YYYY-MM-DD HH:mm ddd")%>
```


Can you go into your use case in detail and explain how you produce your bug? (A gif screenshot would be nice)  


---

我无法复现这个 bug。

我通过“Templater：打开插入模板对话框”应用代码后，得到了您编写的实际结果。

而我在我的template中只有以下代码：
```js
Today: <% tp.file.last_modified_date("YYYY-MM-DD HH:mm ddd")%>
```

请详细说明您的使用情况，并解释您如何产生这个 bug？（最好提供一个 gif ） 谢谢

**Comment by Zachatoo** [comment]
Maybe you're looking for [dynamic commands](https://silentvoid13.github.io/Templater/commands/dynamic-command.html)?

However, dynamic commands may be deprecated at some point (see #913).

I highly recommend investigating [Dataview](https://github.com/blacksmithgu/obsidian-dataview) for displaying dynamic values. Or, for this case, you could use the [Linter](https://github.com/platers/obsidian-linter) plugin to auto-set the modified date when saving a note.

**Comment by iamfeiyu** [comment]
> I couldn't replicate the bug.
> 
> After I apply the template via , I get the actual result that you wrote.`Templater: Open insert templater modal`
> 
> I only had the below in my template:
> 
> ```js
> Today: <% tp.file.last_modified_date("YYYY-MM-DD HH:mm ddd")%>
> ```
> 
> Can you go into your use case in detail and explain how you produce your bug? (A gif screenshot would be nice)
> 
> 我无法复现这个 bug。
> 
> 我通过“Templater：打开插入模板对话框”应用代码后，得到了您编写的实际结果。
> 
> 而我在我的template中只有以下代码：
> 
> ```js
> Today: <% tp.file.last_modified_date("YYYY-MM-DD HH:mm ddd")%>
> ```
> 
> 请详细说明您的使用情况，并解释您如何产生这个 bug？（最好提供一个 gif ） 谢谢
> 
> Edit: added gif. ![img](https://camo.githubusercontent.com/f581de27088e9c33b9009f3c812d9f5e62a74f32eee9d46908ea0ea0b122e064/68747470733a2f2f692e696d6775722e636f6d2f53626d4d7953612e676966) [ ![img](https://camo.githubusercontent.com/f581de27088e9c33b9009f3c812d9f5e62a74f32eee9d46908ea0ea0b122e064/68747470733a2f2f692e696d6775722e636f6d2f53626d4d7953612e676966) ](https://camo.githubusercontent.com/f581de27088e9c33b9009f3c812d9f5e62a74f32eee9d46908ea0ea0b122e064/68747470733a2f2f692e696d6775722e636f6d2f53626d4d7953612e676966) [ ](https://camo.githubusercontent.com/f581de27088e9c33b9009f3c812d9f5e62a74f32eee9d46908ea0ea0b122e064/68747470733a2f2f692e696d6775722e636f6d2f53626d4d7953612e676966)

Thanks, @Zachatoo I solved all my problems

**Comment by iamfeiyu** [comment]
> Maybe you're looking for [dynamic commands](https://silentvoid13.github.io/Templater/commands/dynamic-command.html)?
> 
> However, dynamic commands may be deprecated at some point (see #913).
> 
> I highly recommend investigating [Dataview](https://github.com/blacksmithgu/obsidian-dataview) for displaying dynamic values. Or, for this case, you could use the [Linter](https://github.com/platers/obsidian-linter) plugin to auto-set the modified date when saving a note.

Thanks, You solved my confusion. I don't think I can use the [dynamic command](https://silentvoid13.github.io/Templater/commands/dynamic-command.html), the dynamic command needs to keep clearing the cache, I can't solve. I decided to enable this dynamic command

**Comment by danteali** [comment]
> Maybe you're looking for [dynamic commands](https://silentvoid13.github.io/Templater/commands/dynamic-command.html)?
> 
> However, dynamic commands may be deprecated at some point (see #913).
> 
> I highly recommend investigating [Dataview](https://github.com/blacksmithgu/obsidian-dataview) for displaying dynamic values. Or, for this case, you could use the [Linter](https://github.com/platers/obsidian-linter) plugin to auto-set the modified date when saving a note.

Just a quick additional note, you can trigger Linter from templater with this in your template:
```
app.commands.executeCommandById("obsidian-linter:lint-file");
```
