### ISSUE TITLE
Selected text is deleted if template does nothing

### ISSUE THREAD

**Issue by karmeye** [SilentVoid13/Templater#1058]
**Plugin information (please complete the following information):**

-   OS: android
-   Templater version: latest
-   Obsidian version: latest
-   Templater settings: [e.g. Template folder location: "Templates/", Timeout: "5" (add the templates not working with their associated command)]

**Describe the bug**
If selecting text before executing a template, the selected text is:
- deleted, if template uses <%* 
- replaced with `undefined` if using <%

**Expected behavior**
Selected text should not change if template dis not write/output anything.

**Screenshots**

**Additional context**
I noticed this in templates that displays a selector to choose what to do with selected text. If I canceled the selector (doing nothing as it returns `null`) the selected text was deleted.

**Comment by AB1908** [comment]
You can probably use tp.file.selection() to return the originally selected test.

**Comment by FelipeRearden** [comment]
@karmeye  I think this post will help you to achieve want you want 

https://github.com/SilentVoid13/Templater/discussions/419

I hope it helps 🙏

**Comment by MSBack** [comment]
> So it's not regarded as a bug? It doesn't seem like expected behavior to me. 🤔🧐

I would regard it as a bug for sure.

**Comment by Zachatoo** [comment]
Marking as closed as this is working as intended.
