### ISSUE TITLE
Hotkey not working ?

### ISSUE THREAD

**Issue by I-Pch** [SilentVoid13/Templater#106]
**Plugin informations (please complete the following information):**
 - OS: MacOS - Big Sur 11.2.3
 - Templater version: 1.5.0
 - Obsidian version: 0.11.13
 - Templater settings: [Template folder location: "/-Templates/Meta", Timeout: "15" ]

**Describe the bug**
When wanting to create a new note with a template using the hotkey `⌥ N` (per default hotkeys settings) nothing happen.

**Expected behavior**
Using `⌥ N` should open the menu to select the template to be used in the new notes (like it does when right-click a folder in the `File Explorer` > `Create new note from template` or using the `Command Palette`)

**Screenshots**
Settings Hotkeys for Templater (the default ones, as I didn't modified any 😊 )

<img width="1153" alt="Templater Hotkeys" src="https://user-images.githubusercontent.com/77828085/114707526-9e013a80-9d2a-11eb-803c-542212abf41c.png">
 
Screen recording using Command Palette 😊 (which works perfectly 😁 )

https://user-images.githubusercontent.com/77828085/114708659-ed943600-9d2b-11eb-8e69-20fc737becad.mp4

Screen recording using `⌥ N` (and trying different variation, just in case 😇 ) and where nothing happen

https://user-images.githubusercontent.com/77828085/114709524-fafdf000-9d2c-11eb-998b-dba0e9c8e92f.mp4

**Additional context**
None (I think 😊 )

**Comment by luckman212** [comment]
I noticed this too - thought I created an issue for it but now I can't seem to find it. I think this is a CodeMirror bug or gotcha. Perhaps related to [this](https://github.com/obsidianmd/obsidian-releases/pull/212#issuecomment-805117331) and [this](https://forum.obsidian.md/t/some-letters-ss-arent-available-on-mac/15068/33).

I worked around it by using <kbd>⌘cmd</kbd><kbd>⇧shift</kbd><kbd>N</kbd> instead.

**Comment by SilentVoid13** [comment]
Hey @I-Pch as @luckman212 said, I don't think this bugs comes from Templater, it's working for me (I'm on Linux).

Can you try changing the hotkey to something else and tell me if this works ?

**Comment by I-Pch** [comment]
Thanks for the input @luckman212 😊 !

Not an important bug but I just thought it was worth mentioning it, in case someone run into the same trouble 😊 ... and if it's potentially CodeMirror related... there's not much to solve here anyway 😊 .

> Can you try changing the hotkey to something else and tell me if this works ? This might be a mac only bug.

I just did that and used the suggested ` ⌘cmd + ⇧shift + n` and it works 👍 😁 !

Thanks @SilentVoid13 😁 !
(And Thank you very much for this amazing plugin too 👍 !)

**Comment by SilentVoid13** [comment]
Alright, thanks for the feedback, I'll link to this issue if anyone is encountering the same issue, nothing I can do to fix that unfortunately.

**Comment by trydalch** [comment]
I imagine it has something to do with special characters. The  ` ⌥` key is used as a modifier for characters. I've also worked around it by changing the default hotkey to `⌘cmd + ⇧shift +[key]`

**Comment by erichalldev** [comment]
> I imagine it has something to do with special characters. The ` ⌥` key is used as a modifier for characters. I've also worked around it by changing the default hotkey to `⌘cmd + ⇧shift +[key]`

@trydalch I'm having the same issue now. I've gone so far as trying to define a custom keyboard layout defined [here](https://stackoverflow.com/questions/11876485/how-to-disable-generating-special-characters-when-pressing-the-alta-optiona/24100077#24100077) but haven't had any luck.

My advice is to implement a different hotkey like you did. That's what I'll be doing.

**Comment by ashleybartlett** [comment]
Just encountered this problem. The default Alt keys on mac OS do not work. Is there any way of having different default keybinds based on OS?

**Comment by AB1908** [comment]
Hmm I feel like I've run into this too but haven't been able to reliably reproduce. Can anyone add some steps for me after trying it out in the sandbox vault?

**Comment by ashleybartlett** [comment]
Option E conflicts with using Dead Keys on the MacOS https://support.apple.com/en-au/guide/mac-help/mh27474/mac

this example explains it better https://macpaw.com/amp/how-to/type-accents-on-mac

**Comment by dljsjr** [comment]
> Option E conflicts with using Dead Keys on the MacOS [support.apple.com/en-au/guide/mac-help/mh27474/mac](https://support.apple.com/en-au/guide/mac-help/mh27474/mac)
> 
> this example explains it better [macpaw.com/amp/how-to/type-accents-on-mac](https://macpaw.com/amp/how-to/type-accents-on-mac)

`⌥ + N` is in fact the dead key for `tilde`. I believe that's what's going on here.
