### ISSUE TITLE
sigmoid-azoth / obsidian-templates link is dead

### ISSUE THREAD

**Issue by Gregor-zbjk** [SilentVoid13/Templater#1060]
It seems like the link is dead.. please delete or close the discussion.

### Discussed in https://github.com/SilentVoid13/Templater/discussions/310

<div type='discussions-op-text'>

<sup>Originally posted by **sigmoid-azoth** July 28, 2021</sup>
Hi everyone,

Feel free to check out my template repo: https://github.com/sigmoid-azoth/obsidian-templates
</div>

**Comment by Zachatoo** [comment]
There's already a comment on that discussion thread saying the link is dead.
