### ISSUE TITLE
Readd locale selection

### ISSUE THREAD

**Issue by mileyvirus** [SilentVoid13/Templater#107]
Hey there!

**Describe the solution you'd like**
Before the big update we had a dropdown menu to select a custom locale added in #14 that's been removed. Would it be possible to add it again?

Thanks for the excellent plugin!

**Comment by SilentVoid13** [comment]
Hey @mileyvirus I removed it on purpose to avoid code duplication and redundancy with other plugins and to make the plugin a bit lighter.
If you're using the calendar plugin from @liamcain it already has an option in the settings to do that.

With that being said, I think it could be a good idea to have a tiny plugin called something like "override locale" whose only mission would be to that. Or maybe an API that plugins could use.

**Comment by mileyvirus** [comment]
Thank you, I just checked and Calendar does indeed have a locale override that works. My use case was that I wanted (it_IT) locale for my note contents and the (en_US) locale for the filenames. I could've sweared Templater worked in the way I described but maybe I'm mistaken.

Anyway since mine is an edge (and weird) use case I'll manage. Thanks again!
