### ISSUE TITLE
New line added to user template replacements

### ISSUE THREAD

**Issue by rummers** [SilentVoid13/Templater#108]
**Plugin informations:**
 - OS: Mac
 - Templater version: 1.5
 - Obsidian version: 0.11.13

**Describe the bug**
Recently (since updating to 1.0+??) user defined template replacements have a new-line automatically appended, breaking uses where the template is inserted in the middle of a line of other text, for example using the echo template from the help doc:

`<% tp.user.echo() %> <% tp.user.echo() %>`

Get's replaced as:
```
I love templater
 I love templater

```

**Expected behavior**
Previously user defined templates were consistent with internal templates, e.g.
`<% tp.date.now() %> <% tp.date.now() %>`

gets replaced as:

`2021-04-14 2021-04-14`

**Comment by SilentVoid13** [comment]
Hey @rummers, this has been discussed in #92, but actually I think you're right, I'll trim the newline at the end of a user command.
This is more natural and makes more sense.
