### ISSUE TITLE
Can't access variables a using $a

### ISSUE THREAD

**Issue by stealzy** [SilentVoid13/Templater#1081]
**Plugin information (please complete the following information):**

-   OS: Windows
-   Templater version: 1.16.0
-   Obsidian version: 1.1.16
-   Templater settings: Template folder location: "Templates/", Timeout: "5", Template: "<% tp.user.shell({a: tp.file.selection()}) %>", shell: "cmd.exe /c echo $a"

**Describe the bug**
"$a" not substituted to content of variable "a", so "echo $a" executed. 

**Expected behavior**
Variable "a" content ( tp.file.selection() ) passed to cmd.

**Additional**
There is no checkbox in Templater **"General Settings"** against **"Internal Variables and Functions"**.

![img](https://s1.hostingkartinok.com/uploads/images/2023/04/f5d67125e889b9326b40e81bc2304542.png)

**Comment by stealzy** [comment]
My mistake: should use `cmd.exe /c "%Templater%"` on windows and create such EnvVar.
It would be nice add example in docs.

**Comment by Zachatoo** [comment]
If this is a non-issue, mind closing this issue?
