### ISSUE TITLE
Make "Trigger templater on new file creation" more granular

### ISSUE THREAD

**Issue by JimWolff** [SilentVoid13/Templater#1085]
To avoid being vurnerable to random code execution by enabling "trigger Templater on new file creation".
It would be great to have a more granular way to enable it.

Solution 1.
Have a meta data field that you can add to your frontmatter, "trigger_templater: true" for example.
And then only enabling triggers for those, then i can just add it in my templates that i want to trigger.

Solution 2. 
Being able to add folders it should listen to for creation events. then it would at least be granular on a folder level.

**Comment by Zachatoo** [comment]
Removing in favor of #1100 since there has been more discussion there around this
