### ISSUE TITLE
Templater not renaming or moving even with await keyword

### ISSUE THREAD

**Issue by OishikGuha** [SilentVoid13/Templater#1086]
**Plugin information (please complete the following information):**

-   OS: Windows 11
-   Templater version: 1.16.0
-   Obsidian version: 1.1.9
-   Templater settings: template folder location: Templates/

My entire template:
```
<%tp.file.creation_date()%>
<%* 
const titleA = tp.system.prompt("Enter your title")
const subject = tp.system.suggester(["Physics", "Chemistry", "Maths"], ["Physics", "Chemistry", "Maths"])
if (subject == "Physics") {
	await tp.file.functions.move("../Physics/" + tp.file.title)
}
else if (subject == "Chemistry") {
	await tp.file.functions.move("./Chemistry" + tp.file.title)
}
else if (subject == "Maths") {
	await tp.file.functions.move("./Maths" + tp.file.title)
}
await tp.file.rename(titleA)
%>
Subject: <% subject %>

----

# <%titleA%>
```

**Describe the bug**
using `await tp.file.rename(titleA)` leads to:
`Templater Error: Template parsing error, aborting. 
 new_title.match is not a function`

and using `await tp.file.functions.move("./Maths" + tp.file.title)` does nothing

**Expected behavior**
I expected to be able to create a new note from this template and input my subject and title. Based on the subject, it would move the file to a specific folder and the `titleA` variable would set the file's name.

**Screenshots**
![image](https://user-images.githubusercontent.com/57310936/231948557-764c75ae-a06d-4875-9d76-be5dc90f8bf8.png)

**Comment by AB1908** [comment]
Your syntax is incorrect. Please look at the examples listed here: https://silentvoid13.github.io/Templater/internal-functions/internal-modules/file-module.html#examples

**Comment by Zachatoo** [comment]
Another note, you'll want to `await` the `tp.system.prompt` and `tp.system.suggester` functions, since those two functions are asynchronous.

**Comment by Zachatoo** [comment]
Has this issue been resolved for you?

**Comment by Zachatoo** [comment]
Marking as removed due to no response from issue author.
