### ISSUE TITLE
Example commands not working

### ISSUE THREAD

**Issue by yeders** [SilentVoid13/Templater#11]
Thanks for the work!

I tried to replicate the original example:
My template [Template] Daily in my 999 Templater\ folder
`Note type: #daily-note

---
<< [[{{yesterday}}]] | [[{{tomorrow}}]] >>
```
{{weather}}
```

Daily quote:
{{templater_daily_quote}}

# {{today}}

## Day Planner
`

As pictured here: 
![image](https://user-images.githubusercontent.com/35711815/99408863-d4d25080-2944-11eb-9ba9-79469cba6cab.png)

These are my user defined functions:
![image](https://user-images.githubusercontent.com/35711815/99407673-7b1d5680-2943-11eb-8b2b-223ad78a6565.png)

And this is my 'view' output when creating a new template:

![image](https://user-images.githubusercontent.com/35711815/99408711-9f2d6780-2944-11eb-9f68-a340de98ea92.png)

As similarly reported, it says I get an error on the console. But I am not able to find a console / log file. I've asked on the discord channel, waiting to hear back.

I'm running windows 10.

**Comment by SilentVoid13** [comment]
Hello @yeders, thanks for the well explained issue !

Unfortunately, the command `date` with date format arguments is not working for Windows. It's reserved for MacOS or Linux.
You may use the internal template `{{templater_today}}` for now, in the `YYYY-MM-DD` format.
I plan on adding arguments to the internal templates so that you could specify your own date format in the future.

**Comment by kypi** [comment]
I think I figured out a work around for windows:
![image](https://user-images.githubusercontent.com/5155266/99490364-50c19e00-292f-11eb-9b34-d4c2fb70ee2e.png)

Template:
![image](https://user-images.githubusercontent.com/5155266/99490420-6a62e580-292f-11eb-91fd-e971f2dde2e4.png)

Result:
![image](https://user-images.githubusercontent.com/5155266/99490445-78186b00-292f-11eb-9b97-b6cfb4c743c1.png)

you can change the format however you want.

**Comment by SilentVoid13** [comment]
Thanks for the commands, i updated the README to include them for Windows commands examples.
Closing this.

**Comment by kypi** [comment]
> 
> 
> Thanks for the commands, i updated the README to include them for Windows commands examples.
> Closing this.

I believe curl works in windows 10 (at least recent versions of windows 10). if you use the powershell command it doesn't format correct in windows (since powershell doesn't support emoji)

![image](https://user-images.githubusercontent.com/5155266/99611183-d2b9d180-29d8-11eb-8d79-4b2d17c6e287.png)
