### ISSUE TITLE
Template page with Templater syntax doesn't work as a folder template

### ISSUE THREAD

**Issue by YousufSSyed** [SilentVoid13/Templater#1101]
**Plugin information (please complete the following information):**

-   OS: macOS 13.1
-   Templater version: 1.16.0
-   Obsidian version: 1.11.6
-   Templater settings: [data.json.zip](https://github.com/SilentVoid13/Templater/files/11328649/data.json.zip)

**Describe the bug**
I have a page set as a folder template for the root folder (written as `/` in the folder name box) so if I create a new note anywhere the template would be inserted. This is the content of the template page:

````
<%*
const head = `\`\`\`dynbedded
[[Heading Template]]
\`\`\`
${tp.file.cursor()}`;

const tf = tp.file.find_tfile(tp.file.title);
await app.vault.modify(tf, head + tp.file.content);
-%>
````

But when I create a new note: I see the text flash real quick: for one moment it's there and a split second later its gone.

**Expected behavior**
The templater syntax should stay.

**Comment by Zachatoo** [comment]
In general, trying to modify a file immediately after creating it has issues.

Why not make your template the following instead? Much simpler and has no issues.

````
```dynbedded
[[Heading Template]]
```
<% tp.file.cursor() %>
````

**Comment by YousufSSyed** [comment]
> In general, trying to modify a file immediately after creating it has issues.

Could that be fixed though?

I currently do what you described, it's just that when I insert the template manually into a note, I want it to be at the top and the cursor to be focused there. I'd be nice if I had that template I showed to be set as both a hotkey command and the template for a new note.

**Comment by Zachatoo** [comment]
> Could that be fixed though?

I wouldn't hold your breath for it to be fixed, since the last release was in November 2022, but yes it could be fixed. I'm not really sure where the maintainer went, haven't seen any activity on GitHub at all from them since then.

Definitely still keep this bug report open for the time when fixes can be merged into this repo.
