### ISSUE TITLE
Doc issue

### ISSUE THREAD

**Issue by xiongwei0714** [SilentVoid13/Templater#1106]
![image](https://github.com/SilentVoid13/Templater/assets/15872815/6ba23796-f03e-4008-976e-ed453f7970f4)
I am studying the doc of templater.
In above picture, it says "3 types of opening tags", but there are only two types listed. So What is the 3rd type of opening tags?

**Comment by Zachatoo** [comment]
It's [dynamic commands](https://silentvoid13.github.io/Templater/commands/dynamic-command.html).

It should be listed there, though they may be deprecated at some point, so I wouldn't recommend using them.
