### ISSUE TITLE
JS code executes but reverts changes if await is used. 

### ISSUE THREAD

**Issue by statix531441** [SilentVoid13/Templater#1108]
This is the code I'm trying to run.
![image](https://github.com/SilentVoid13/Templater/assets/46532726/5c198ca3-bccd-46da-9a18-b791d9ed5e02)

As it runs task1 and task2 are changed.
![image](https://github.com/SilentVoid13/Templater/assets/46532726/5bef9928-4d11-44eb-8884-feaa0caf14e2)
![image](https://github.com/SilentVoid13/Templater/assets/46532726/9f3de25b-6275-48c6-aaba-9564311e70d0)

When the templater code is removed, all changes made by it are also undone. 
![image](https://github.com/SilentVoid13/Templater/assets/46532726/e9cc9586-57fe-49bf-aee0-61c2dd999983)

Dropping the await keyword for task1, task2 or both result in different results. For example
![image](https://github.com/SilentVoid13/Templater/assets/46532726/d3dba7cd-b4dc-4726-8063-7e61a37f1921)
Here, the changes remained but code was not removed.

The same logic was implemented using the new obsidian metadata api and results were same so the issue is not linked to MetaEdit plugin.

**Comment by Zachatoo** [comment]
Can you include what Templater command you're using for this? I believe some Templater commands work fine with this sort of template and some don't.

**Comment by statix531441** [comment]
I'm using the "Replace templates in the active file" command. My goal is to use buttons to update the metadata which had the same issue. I'm assuming it's because it appends the template and runs the replace command.

Based on your suggestion I tried using the "Open Insert Template modal" command and the code seems to work as intended.

Here is the button I'm trying to implement:
![image](https://github.com/SilentVoid13/Templater/assets/46532726/a8bd1c6a-e149-42e6-ad9f-21364e9a720b)

This is the template:
![image](https://github.com/SilentVoid13/Templater/assets/46532726/fe2f2932-c574-4939-bede-f35a9a8317a2)

I made a button that calls the "Open Insert Template modal" command but then I'll have to specify which template to use manually so it's still not the ideal solution.

**Comment by Zachatoo** [comment]
I'm guessing this is bug with the Buttons plugin, I'm pretty sure there's an issue on that repo for this already, you can comment in your experience there.

Buttons hasn't been updated in a while, but I believe it's going to start getting updates again soon.

**Comment by Zachatoo** [comment]
Marking this as closed since I haven't heard anything about this and is likely an issue with the buttons plugin.
