### ISSUE TITLE
Input prompt to replicate ability of window.prompt

### ISSUE THREAD

**Issue by GitMurf** [SilentVoid13/Templater#111]
**Is your feature request related to a problem? Please describe.**

When I run a template I would like to be able to re-use the same template for several scenarios but input some dynamic values to provide to the templater engine. So for example, I am creating a template that will create a new page for a "Task" so I can assign meta data in YAML to the Task. One of the items I'd like when I run the template is to input a "Due Date" so I need a pop up to ask me "What is the Due Date?" and then I enter "Next Wednesday" and then Temmplater will "process" that string and add accordingly into my template based on the JS etc. I have in my template.

**Describe the solution you'd like**

The easiest way to describe the solution I need is just the JS native window.prompt. A pop up appears, asks the user for input, and that input can be used as a variable in <%* My custom JS code / templater commands will use the input string as a variable to do stuff with.... %>

**Comment by SilentVoid13** [comment]
This has been implemented, and will be shipped in next release!

**Comment by GitMurf** [comment]
> This has been implemented, and will be shipped in next release!

You are amazing! Thank you! This is a game changer in my book :) so excited to use this.
