### ISSUE TITLE
`[object Object]` upon inserting new file from template

### ISSUE THREAD

**Issue by I7T5** [SilentVoid13/Templater#1117]
**Plugin information:**

-   OS: macOS 13.3.1(a)
-   Templater version: 1.16.0
-   Obsidian version: 1.3.4
-   Templater settings: 
  -   Template folder location: "Templates/", 

**Describe the bug**
I have two template files, "Diary Template" and "Diary Creation". 

Diary Template
```
---
cssclass: lxgw-wenkai-gb
---
# <% moment().locale('zh_cn').format("llll") %> ☀️ 🌥️ ☁️ 🌧️ ⛈️ 💨

Flashback
- 

Today
- 🏠 -->
- 🤙
- 👥
```

Diary Creation
```
<% await tp.file.create_new(tp.file.find_tfile("Diary Template"), tp.date.now("YYYY-MM-DD"), true, app.vault.getAbstractFileByPath("Diary")) %> 
```

Every time I try to insert "Dairy Creation", the file that is created have an extra `[object Object]` in the frontmost of the file, like this:
```
[object Object] ---
cssclass: lxgw-wenkai-gb
---
# 2023年5月28日星期日 11:23 ☀️ 🌥️ ☁️ 🌧️ ⛈️ 💨

Flashback
- 

Today
- 🏠 -->
- 🤙
- 👥
```

But when I create a new file using "Diary Template" instead of inserting "Diary Creation", it works well. 

**Expected Behavior**
No `[object Object]` upon insertion. 

Edit: I just found that I can create new note using the daily notes plugin. But I'm still curious why is this the case.

**Comment by I7T5** [comment]
Nvm, I just found that I can create new note using the daily notes plugin. But I'm still curious why is this the case.

**Comment by AB1908** [comment]
<% commands insert the returned value I believe. Run it inside <%* block instead.

**Comment by I7T5** [comment]
Very strange. I had the exact same templates, but this time inserting `Diary Creation` outputs `undefined`. 

Console
```
Templater Error: Template parsing error, aborting. 
Cannot read properties of null (reading 'length')
```

Creating new note from `Diary Template` still works.

**Comment by Zachatoo** [comment]
Are you still experiencing this issue?

**Comment by Zachatoo** [comment]
Marking as removed due to no response from issue author.
