### ISSUE TITLE
Prompt input is not focused on mobile

### ISSUE THREAD

**Issue by mihaiconstantin** [SilentVoid13/Templater#1120]
Please consider the following template:

```js
<%-*
let textPromise = tp.system.prompt("Type something...", multiline = true)
let textValue = await textPromise
_%>

<% textValue %>
```

Upon inspecting the `HTML` it seems that the input in the modal is lacking the `autofocus` attribute, as seen below:

![Input lacking autofocus attribute](https://github.com/SilentVoid13/Templater/assets/20051042/c127787d-375d-4424-a187-d6e8fd0ff26f)

Because of this, when the template is triggered on mobile, the input is not focused, i.e.:

![Input out of focus on mobile](https://github.com/SilentVoid13/Templater/assets/20051042/cfbbfb0a-db36-464c-8b09-fbfca6f8f971)

I can work around this, by focusing the element programmatically, i.e.:

```js
<%-*
let textPromise = tp.system.prompt("Type something...", multiline = true)

// Focus the input element programmatically.
document.getElementsByClassName("templater-prompt-input")[0].focus()

let textValue = await textPromise
_%>

<% textValue %>
```

But I think it would be helpful, and unobtrusive if you add the `autofocus` attribute on the prompt element. This way, the prompt input will also behave in line with its `suggester` counterpart.

Also, thanks a lot for the awesome plugin!

**Comment by FelipeRearden** [comment]
Hello @mihaiconstantin !!!

> I can work around this, by focusing the element programmatically, i.e.:

I just wanna say thank for sharing this script 🙏

I have been struggling with focus on prompt on Mobile for a long time and your script saved me on this issue.

I hope we can get a fix for this on a future release 🙏

Again, thank you very much for sharing this script, you have no idea how happy I am to finally be able to get the focus on my prompts :)

I wish you a fantastic day ☀️

**Comment by mihaiconstantin** [comment]
@FelipeRearden, I'm glad to hear it helps. If you need to apply the above to more complex scenarios than maybe [these scripts](https://obsidian-scripts.mihaiconstantin.com/) will help as well.

**Comment by FelipeRearden** [comment]
Woowww @mihaiconstantin this is amazing, thank you very much for sharing and creating this amazing site. 

I am gonna read the scripts and I am sure that I will improve my workflow using your scripts !

Have a great day!

**Comment by AB1908** [comment]
Hey Mihai, want to push a PR that adds this?

**Comment by mihaiconstantin** [comment]
Hey @AB1908, sure thing, will submit a PR.

**Comment by Zachatoo** [comment]
Unfortunately, adding the `autofocus` attribute on the input element doesn't appear to resolve the issue on mobile. I've tried a few other options like running the `.focus()` method on the input element and even using `document.getElementsByClassName("templater-prompt-input")[0].focus()`, but no dice. Only works if I add it to the template, not in the Templater code.

I'm sure there's something simple I'm missing.

**Comment by itsonlyjames** [comment]
Issue is resolved on mobile using `textInput.inputEl.focus()`. Playing around with numeric keyboards and solved this. Will open a PR later. 

<img width="468" alt="image" src="https://github.com/user-attachments/assets/fa1a1427-5e42-4710-901c-cc98cc6eabc3">

**Comment by Zachatoo** [comment]
This has been released!
