### ISSUE TITLE
Obsidian 1.3.5 evaluates dynamic commands on insert

### ISSUE THREAD

**Issue by Synertry** [SilentVoid13/Templater#1124]
**Plugin information (please complete the following information):**

-   OS: Windows 11
-   Templater version: 1.16.0
-   Obsidian version: 1.3.5
-   Templater settings: -

**Describe the bug**
Before, I could insert <%+ tp.file.last_modified_date() %> in a template and it would get inserted plainly in the new note.
But now Obisidian tries to evaluate it, which results in NaN

**Expected behavior**
The plain dynamic command in the new note.

**Screenshots**
Before:
![image](https://github.com/SilentVoid13/Templater/assets/60792595/fccc8791-d7b4-48cb-9dd0-e0bfe3c93fe7)
After:
![image](https://github.com/SilentVoid13/Templater/assets/60792595/2346ae33-da67-4638-b033-a24676c81f21)

**Additional context**
Problem could have existed longer. Just noticed it now. If no fix for this is applicable, please show me another way to have dynamic commands in the end note.

**Comment by AB1908** [comment]
Is this related to #910 ?

**Comment by Synertry** [comment]
Yes, you are right. I'm sorry for the duplicate.
