### ISSUE TITLE
Documentation for tp.date

### ISSUE THREAD

**Issue by jonline3** [SilentVoid13/Templater#113]
In the Documentation, 

File's title date + 1 day (tomorrow): <% tp.date.now("YYYY-MM-DD", 1, tp.file.title, "YYYY-MM-DD") %>
File's title date - 1 day (yesterday): <% tp.date.now("YYYY-MM-DD", 1, tp.file.title, "YYYY-MM-DD") %>

Should the second line be: 
File's title date - 1 day (yesterday): <% tp.date.now("YYYY-MM-DD", -1, tp.file.title, "YYYY-MM-DD") %>

Thanks.

**Comment by SilentVoid13** [comment]
Hey @jonline3, you are right that's a mistake, this is now fixed. Thanks for warning me!
