### ISSUE TITLE
Template syntax error: Octal escape sequences are not allowed in template strings.

### ISSUE THREAD

**Issue by CoffeeDrinkRabbit** [SilentVoid13/Templater#1132]
🚧 Because the `\{number}` way of referencing a regular expression's capture group is not currently supported, I can't complete my workflow. Regular expressions can reference previously captured groups in the same match. A backslash plus a group number (starting from 1) can be used in a regular expression to refer to a previously captured group.

Here's an example:

```
"Working at Apple, I love apples."
```

Here's my templater code:

```
const regexPattern = new RegExp(`Working at (Apple), I love \1s.`, 'i');
```

Here's the error information：

> Templater Error: Template parsing error, aborting. 
 Template syntax error: Octal escape sequences are not allowed in template strings.

If I remove the `\1` syntax, Templater works fine.

**Comment by CoffeeDrinkRabbit** [comment]
My bad , I solved this problem with this post:

https://stackoverflow.com/a/55867746.

**Comment by AB1908** [comment]
Anti DenverCoder9. Ya love to see it.
