### ISSUE TITLE
Dynamic Commands should not parse in code block.

### ISSUE THREAD

**Issue by HIDE-r** [SilentVoid13/Templater#1137]
**Plugin information (please complete the following information):**

-   OS: ArchLinux
-   Templater version: 1.16.0
-   Obsidian version: 1.3.5
-   Templater settings: 
![image](https://github.com/SilentVoid13/Templater/assets/51672711/41fe385a-1478-4e84-9962-e6313ae6f7da)

**Describe the bug**
In code block , Dynamic Commands also parse..

**Expected behavior**
It should not parse in code block

**Screenshots**
![image](https://github.com/SilentVoid13/Templater/assets/51672711/fdfe172f-84c9-48ae-8d5a-5740eef20e4a)

**Additional context**

Nearly, I learn some about code, but the code also use the `<%+` syntax, I add it in code block, but obsidian give me some warning.

![image](https://github.com/SilentVoid13/Templater/assets/51672711/9b1d0c3d-0435-434f-9a89-7c93176af00a)

**Comment by Zachatoo** [comment]
Should be solved by #913, once dynamic commands are deprecated this shouldn't be an issue anymore.

**Comment by HideOnLie** [comment]
> Should be solved by #913, once dynamic commands are deprecated this shouldn't be an issue anymore.

Got it~ Thank you for your response.
