### ISSUE TITLE
Unexpected identifier 'that' - Error when inserting template

### ISSUE THREAD

**Issue by tomasvalkering** [SilentVoid13/Templater#1141]
**Plugin information (please complete the following information):**

-   OS: Linux EndeavourOS (Arch under the hood)
-   Templater version: 1.16.0
-   Obsidian version: v1.3.5
-   Templater settings: 
    -   Template Folder Location: "08 Misc/templates"
    -   Trigger Templater on new file creation: Yes
    -   Folder Templates: 
        -   "02 Journal/weekly" -> "08 Misc/templates/weekly-note-template"
        -   "02 Journal" -> "08 Misc/templates/daily-note-template"
        -   "01 Notes" -> "08 Misc/templates/blank-note-template"
-   Templater as *the only plugin activated*, Obsidian restarted

**Describe the bug**
_This bug does not happen all of the time, but it has been affecting me about once a month for the last half a year._

I'm trying to insert a template (either as new note or just insert a template into an existing note). The standard error message pops up, saying "Template Parsing Error", and in the console, I get `Templater Error: Template parsing error, aborting. Unexpected identifier 'that'`. My templates do not contain the word "that". If I ignore templates for some time, it'll start working again somehow. 

**Expected behavior**
No Error

**Screenshots**
![image](https://github.com/SilentVoid13/Templater/assets/69592428/82093021-d140-46d6-8992-903d42ad5e29)

**Additional context**
I do a bit of coding, so if someone could give a hint on what the problem with `that` could be, I might try to fix it.

**Comment by Zachatoo** [comment]
I've updated some of the error logging to contain more information recently (#1212). I'm hoping that is what was causing your issue and can help narrow down the issue for you if you see this again.

**Comment by AB1908** [comment]
Do you have any comments that contain the word "that"? Can you also check if you have any user scripts?

**Comment by Zachatoo** [comment]
Marking as removed due to no response from issue author.
