### ISSUE TITLE
Templater does not execute template commands on "Insert template"

### ISSUE THREAD

**Issue by mattiasflodin** [SilentVoid13/Templater#1145]
**Plugin information**

-   OS: Ubuntu 22.04.2
-   Templater version: 1.16.0
-   Obsidian version: 1.3.5
-   Templater settings:
    - Template folder location: zz/mallar
    - Syntax Syntax highlighting: On
    - Automatic jump to cursor: Off
    - Trigger Templater on new file creation: Off
    - Show icon in sidebar: off
    - Template hotkeys: none
    - Startup templates: none
    - User script functions: none
    - Enable User System Command functions: off

**Template**
```markdown
---
creation date: <% tp.file.creation_date() %>
modification date: <% tp.file.last_modified_date("dddd Do MMMM YYYY HH:mm:ss") %>
---

<< [[<% tp.date.now("YYYY-MM-DD", -1) %>]] | [[<% tp.date.now("YYYY-MM-DD", 1) %>]] >>

# <% tp.file.title %>

<% tp.web.daily_quote() %>
```

**Description**
I installed Templater and made a template using the [example](https://silentvoid13.github.io/Templater/introduction.html#quick-example) in the introduction in the documentation. I then created a new note and selected "Templater: Insert template" from the command palette and selected my template. But everything from the template gets inserted verbatim instead of being interpolated by Templater. I see no messages in the developer console.

I'm new to this so I could certainly be misunderstanding something, but I just followed the instructions in the documentation which seem clear enough.

**Expected behavior**
The interpolations get evaluated by Templater and inserted into the file.

**Screenshots**
![image](https://github.com/SilentVoid13/Templater/assets/788233/165fe8c5-65cd-4e01-9646-a65b14460b74)

**Comment by Zachatoo** [comment]
There is no "Templater: Insert Template" command. Are you sure you're using the correct command, and not a command from another plugin?

<img width="713" alt="image" src="https://github.com/SilentVoid13/Templater/assets/6936914/9cfe4566-5717-4cdd-bec3-69f95ddf38f5">

**Comment by mattiasflodin** [comment]
You're right, I misread. It was the core Templates plugin that said "Templates: Insert template". Thanks and sorry for the noise.
