### ISSUE TITLE
Enhancement Request: Add Offset Parameter to tp.file.creation_date

### ISSUE THREAD

**Issue by esamecar** [SilentVoid13/Templater#1148]
I kindly request an enhancement for the `tp.file.creation_date` function to include an offset parameter, similar to `tp.date.now`.

cu Marco

**Comment by Zachatoo** [comment]
You can use them together to get what you want, by passing a `reference` to `tp.date.now()`, see the [docs](https://silentvoid13.github.io/Templater/internal-functions/internal-modules/date-module.html#tpdatenowformat-string--yyyy-mm-dd-offset-numberstring-reference-string-reference_format-string).

```js
<% tp.date.now("YYYY-MM-DD", -1, tp.file.creation_date()) %>
```

**Comment by Zachatoo** [comment]
Going to mark this as resolved, feel free to reopen if you feel this hasn't been resolved
