### ISSUE TITLE
auto-completion

### ISSUE THREAD

**Issue by lbgws2** [SilentVoid13/Templater#1150]
Is it possible to support the OBSIDIAN code suggestion API? When entering certain specific characters, a completion list will pop up. Of course, if it supports remote API calls and returns JSON data, it would be even better

almose like https://github.com/tadashi-aikawa/obsidian-various-complements-plugin
or https://github.com/tth05/obsidian-completr
![image](https://user-images.githubusercontent.com/36999320/146680359-ae572473-8919-4927-a6f5-bc39800a5c23.gif)

or https://github.com/zazaji/obsidian-SenGener

**Comment by Zachatoo** [comment]
I think we already have this?

https://github.com/SilentVoid13/Templater/assets/6936914/1a456e27-efba-4907-9c3c-2e33262e71e3

You might have to turn on syntax highlighting in settings.

<img width="806" alt="image" src="https://github.com/SilentVoid13/Templater/assets/6936914/3d36cd55-5681-43bf-a2c0-3052e5f4482c">

**Comment by lbgws2** [comment]
Thank you for your reply @Zachatoo 

Sorry, I didn't explain the problem clearly

What I mean is to use a Template to define input completion related options, such as related phrases or custom dic


The example you provided seems to have built-in syntax prompts

**Comment by Zachatoo** [comment]
I'm not sure I understand. This sounds like an idea for a different plugin, how would it fit into Templater?

**Comment by lbgws2** [comment]
andone know the popup api abuout ob,and templater can use it
