### ISSUE TITLE
A command to reverse a template (long after adding it). Would that be possible?

### ISSUE THREAD

**Issue by YousufSSyed** [SilentVoid13/Templater#1153]
**Is your feature request related to a problem? Please describe.** A clear and
concise description of what the problem is. Ex. I'm always frustrated when [...]

If I apply a template to a note with markdown and I want to remove much later, when I can no longer quickly press `CMD Z` to undo it, I have to undo it manually.

**Describe the solution you'd like** A clear and concise description of what you
want to happen.

There should be a command to reverse or toggle a templater template, when I want to undo a template, templater does the opposite of what's specified. For example, let's say I have this template: `[[<%tp.file.cursor() %>|<% tp.file.selection() %>]]`, It will take `selected text` and convert it to `[[|selected text]]`. If I invoke a command to reverse it, it does the opposite.

**Comment by AB1908** [comment]
This is nigh impossible or at least very difficult to implement. Your best bet would be to use version history.

**Comment by YousufSSyed** [comment]
OK. I now opened a new issue that's a little related: https://github.com/SilentVoid13/Templater/issues/1154.
