### ISSUE TITLE
Update <%tp.file.title%> after changing the file name

### ISSUE THREAD

**Issue by ih8snow** [SilentVoid13/Templater#116]
Hi,

thanks for the real cool plugin. 
When I'm using the variable <%tp.file.title%> in a fresh (untitled) note, it shows the current name (untitled).

If I then change that name of the file, this change is not visible in <%tp.file.title%>. = remains "untitled"

Is that the way it works or is this some kind of error that I need to fix?

Thanks,
Jörn

**Comment by SilentVoid13** [comment]
Hey @ih8snow, yes that's normal behavior of Templater.
Once a command has been replaced, in your case `<% tp.file.title %>` has been replaced with `Untitled`, it's permanent.
I may add a new option to specify a default filename for new created files in the settings in the future, but for now that's how it goes.

**Comment by SilentVoid13** [comment]
A little trick I use is to put the file title in a "self-link" like so:

```
# [[<% tp.file.title %>]]

Content ...
```

That way, when you modify the file name, the links gets updated with the new file name.
