### ISSUE TITLE
Extract to new note core plugin does not trigger templater

### ISSUE THREAD

**Issue by danielo515** [SilentVoid13/Templater#1161]
**Plugin information (please complete the following information):**

- Obsidian version: v1.3.7
- Installer version: v1.1.9
- Operating system: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000 22.5.0
- Templater v1.16.0

-   Templater settings: "templates/"

**Describe the bug**
When extracting text to a new note using the core plugin the newly created template does not trigger templater

**Expected behavior**
To behave like any other newly created note

**Screenshots**

**Additional context**
Thanks for this awesome plugin

**Comment by Zachatoo** [comment]
Appears to have been fixed in [1.16.4](https://github.com/SilentVoid13/Templater/compare/1.16.3...1.16.4), thanks for the report!
