### ISSUE TITLE
User scripts not working

### ISSUE THREAD

**Issue by aminel91** [SilentVoid13/Templater#1164]
Hi,

I'm trying to run a function from a js file for the first time. Not sure what I'm doing wrong or if it's bug of some sort.
I'm having an issue running user functions from a script folder.
I have created a folder, inside of which I have added a js file (myfunc.js)) that has the following content : 
I have used double backticks in code to make it format correctly, it's not a typo, the js code is fine.

`function myfunc (msg) {
    return ``Message from my script: ${msg}``;
}
module.exports = myfunc;
`
a simple enough function only to test but I couldn't get it to work, straight from the documentation.

Below is information about my system : 

**Plugin information:**

-   OS: Windows11
-   Templater version: 1.16.0
-   Obsidian version: 1.3.7
-   Templater settings: [e.g. Template folder location: "Templates/Templater", Timeout: "15".
-  User scripts folder : "Templates/Templater/scripts".

For context these are things to take note of 

- Templater has detected the user functions (screenshot 3).
- The function I'm interested in debugging shows up in the settings as **tp.user.myfunc**.
- When I open the console while typing the moment I type **tp.user.** before even entering the function name an error shows up on the console (see first screenshot below). 
- When I use **Alt+E** to get Templater template insertion modal, **myfunc** is detected in the menu.
- When I run the function the console logs an error (Templater Error: Template parsing error, aborting. 
 Cannot read properties of undefined (reading 'myfunc') ). See second screenshot below.
- same thing happens if I run `<% tp.user.myfunc("whatever") %>`.

<img width="413" alt="screen1" src="https://github.com/SilentVoid13/Templater/assets/29245458/a5b25a7c-3549-4535-b55d-c323c00a7c39">
<img width="417" alt="screen2" src="https://github.com/SilentVoid13/Templater/assets/29245458/3f531ec8-e4b0-4d84-9119-b0eadbfcd7f1">
<img width="596" alt="screen3" src="https://github.com/SilentVoid13/Templater/assets/29245458/e6779a42-2c63-4ae1-bdda-80c16f917ccc">

Thanks in advance for your help.

**Comment by Zachatoo** [comment]
I tried to reproduce and wasn't able to. Here is my setup:

OS: MacOS
Templater version: 1.16.0
Obsidian version: 1.4.2
Template folder location: "templater/templates"
User scripts folder: "templater/scripts"

In templater/scripts/myfunc.js
```js
function myfunc (msg) { return `Message from my script: ${msg}`; } module.exports = myfunc;
```

In templater/templates/template2.md
```js
<% tp.user.myfunc("whatever") %>
```

Then I opened a new note, ran the `Templater: Open Insert Template modal` command while that note was focused, selected `template2`, and the resulting note was
```
Message from my script: whatever
```

---

It is a known issue that you'll get errors when typing `tp.user`, see #1159. It should not affect the functionality of your user scripts.

**Comment by Zachatoo** [comment]
Is this issue resolved for you?

**Comment by marblewraith** [comment]
User scripts is broken for me. Templater doesn't even detect they exist.

- OS: Win11
- Obsidian: v1.4.16 (latest)
- Installer: v1.4.14 (latest)
- Templater: v1.16.4 (latest)

All other functionality appears to work as normal.

https://github.com/SilentVoid13/Templater/assets/45786628/d182e161-683b-4ae4-b5e4-dca321d96d64

**Comment by Zachatoo** [comment]
Marking as removed due to no response from issue author.
