### ISSUE TITLE
tp.include allow inclusion of note section

### ISSUE THREAD

**Issue by fscheidt** [SilentVoid13/Templater#117]
It would be pretty helpful (at least for me) to be able to include not only another note but also a specific section inside the note. For example:

To include the note "NoteABC" i use the tp.file.include like:
`<% tp.file.include("lecture/2020/NoteABC") %>`

But, templater could also allow us to include only a section existing inside NoteABC, like:
`<% tp.file.include("lecture/2020/NoteABC#^data") %>`

So in this case, only the section data would be included.

**Comment by SilentVoid13** [comment]
Hey @fscheidt good idea! This feature has been implemented and will be shipped in next release.
`tp.file.include` will now only accept obsidian links in the form `[[MyFile]]`. This is way more flexible and adds supports for sections and blocks inclusions.
