### ISSUE TITLE
Button templater inceret functionality bug

### ISSUE THREAD

**Issue by UsefullPartBrad** [SilentVoid13/Templater#1172]
**Plugin information (please complete the following information):**

-   OS: [e.g. Windows 10]
-   Templater version: [e.g. 1.16]
-   Obsidian version: [e.g. 1.3.7]
-   Templater settings: [e.g. Template folder location: "Templates/", Timeout: "5" (add the templates not working with their associated command)]

**Describe the bug**
The bug is, when inserting a template that has a button with a templater command stored as a string (to be inserted at run time) I get an open parenthesis error and the code won't run. 

**Expected behavior**
The string is not interpreted by templater as a template command, but is inserted as live templater code at run time (to be run later)

**Screenshots**
![image](https://github.com/SilentVoid13/Templater/assets/128540255/35b2240e-a3ea-411f-97cc-9629c01195b1)
![image](https://github.com/SilentVoid13/Templater/assets/128540255/1cbfc045-cd74-4ba7-90a2-8b53e1b280e1)

**Additional context**

**Comment by Zachatoo** [comment]
This started happening when the templating engine was upgraded to rusty_engine.

You can get around this by escaping the templater tags in your string.

```js
<% "\<% tp.file.title %\>" %>
```

**Comment by UsefullPartBrad** [comment]
tried that, still got the same error. I even escaped every character individually and then removed the \s as a regex replace. The less than sign seems to still be caught and tokenized, unless there is something else going on. I mean I could add carrots using character codes. Just seems overly complicated.

**Comment by Zachatoo** [comment]
Ah, found it. You can only define variables in [execution commands](https://silentvoid13.github.io/Templater/commands/execution-command.html). The error is not very clear.

````js
```button
name Bake
type command
action Templater: Replace templates in the active file
templater true <%* let payload = "\<% await tp.file.rename(tp.frontmatter.name) %\>" %>
```
````

Though I don't know what you're trying to do with the button by having that text there, it doesn't appear to do anything.

**Comment by Zachatoo** [comment]
Is this issue resolved for you?

**Comment by JLC-Sc** [comment]
Hi Zachatoo I'm running into the same issue and unfortunately your fix does not work for me. 

My original button looked like this:
```button
name Rename
type command
action <%+ await tp.file.rename(tp.frontmatter.due + " " + tp.frontmatter.title) %>
templater true
```

and with your suggestions looks like the following:
```button
name Rename
type command
action Templater: Replace templates in the active file
templater true <%* let payload = "\<%+ await tp.file.rename(tp.frontmatter.due + " " + tp.frontmatter.title) %\>" %>
```
do you have any further suggestions? 

thanks!

**Comment by JLC-Sc** [comment]
Nevermind! i found a solution here after hours of searching!!! https://forum.obsidian.md/t/buttons-with-templater-code-in-templater-template/70068

**Comment by Zachatoo** [comment]
Marking as resolved since this appears to be resolved.
