### ISSUE TITLE
Add multi-select suggester option

### ISSUE THREAD

**Issue by Giuliano1993** [SilentVoid13/Templater#1178]
While using templater i would like to have the possibility to add multiple items when using the suggested call.

For example, I have a template for my social posts, and I usually add some tags or arguments to search the meta fields.
So I would add a boolean parameter  to the suggested; when true, the user can select multiple options

**Comment by Zachatoo** [comment]
There's several duplicates of this same issue (#1130 for example)

**Comment by sujyotraut** [comment]
I have submitted PR #1149 for this, you can try that out and me if it needs improvements.
