### ISSUE TITLE
"Invalid date" using moment(tp.file.title) with YYYY-[Q]Q

### ISSUE THREAD

**Issue by certainlyNotHeisenberg** [SilentVoid13/Templater#1188]
**Plugin information:**

-   OS: macOS Ventura 13.2.1
-   Templater version: 1.16.0
-   Obsidian version: 1.4.5
-   Templater settings: [e.g. Template folder location: "Templates/", Timeout: "5" (add the templates not working with their associated command)]

**Describe the bug**
Using `moment(tp.file.title)` with date format `YYYY-[Q]Q` gives an `Invalid date` error. There is NOT an error using date formats `YYYY-[W]ww`, `YYYY-MM-DD`, `YYYY-MM`, or `YYYY`. All of these (including `YYYY-[Q]Q`) are standard dates formats used, for example, in the [Periodic Notes](https://github.com/liamcain/obsidian-periodic-notes) plugin.

**Expected behavior**
Using `moment(tp.file.title)` with date format `YYYY-[Q]Q` should give a valid date like it does with all other date formats.

I'm guessing this is just a small parsing error somewhere. Thanks for providing such a fantastically useful plugin!

**Comment by Zachatoo** [comment]
You need to tell moment what format you're giving it if it's not a "standard" format, as per the momentjs [docs](https://momentjs.com/docs/#/parsing/string-format/).

```js
moment(tp.file.title, "YYYY-[Q]Q")
```

This is likely what other plugins are doing under the hood for you to be able to support any format. Templater will not (and should not) override how moment works.

**Comment by certainlyNotHeisenberg** [comment]
@Zachatoo Ah, my mistake! I was under the impression this was a standard format. The fix you described works. Thank you!
