### ISSUE TITLE
Templater is not working anymore ?

### ISSUE THREAD

**Issue by SilentVoid13** [SilentVoid13/Templater#119]
After a discussion with Licat (https://discord.com/channels/686053708261228577/707816848615407697/832656791262724096), I decided to "restrict" Templater features that could pose a security risk.

You can still execute arbitrary JavaScript code as soon as you install Templater, but I can't really restrict that since this is at the core functioning of Templater.

You can now enable user functions (system commands) and set Templater to be triggered on new file creation (good for other plugins compatibility) in the settings.
Sets these options to **on** and everything should be back to normal.

**Comment by Moonbase59** [comment]
Thanks for pinning. I stumbled over this with my Daily Notes: The templates were shown but not auto-expanded anymore on daily notes.

You will have to set "Trigger Templater on new file creation" for this to work again.

**Comment by filmgal** [comment]
Can someone please give me the exact way to write out the new tp include? I keep getting a message telling me to look at the console but I can't get at the console. (And I did activate the new "Trigger Templater on new file" switch.)

As of a couple of weeks ago, the "new" way was: 
`<%tp.file.include("Admin/Templates/Frontmatter Date from Title")%>`

From the very quick error note I get in Obsidian, I'm to include a link to the file from now on. I've tried:
`<%tp.file.include([[Frontmatter Date from Title]])%>`
`<%tp.file.include_filename([[Frontmatter Date from Title]])%>`
and a few other things but nothing works.
