### ISSUE TITLE
Support for modifying frontmatter/properties

### ISSUE THREAD

**Issue by brychanmd** [SilentVoid13/Templater#1191]
**Is your feature request related to a problem? Please describe.** A clear and
concise description of what the problem is. Ex. I'm always frustrated when [...]

With the introduction of Obsidian's new properties feature (introduced in version 1.4) - templater syntax no longer works within the property fields as it did when YAML was simply plain text.  Even though it does work with 'Properties in document' set to 'source' I want to still use the properties in the visible mode with user interface enabled and be able to programatically populate or update the values.

It's particularly frustrating that some property types such as 'date' won't even allow templater syntax to be inputted into the fields at all.

**Describe the solution you'd like** A clear and concise description of what you
want to happen.

Could there be a solution where templater allows you to access the values of the property fields and modify them? E.g. `tp.file.properties["attendees"] = [Joe Bloggs, Adam Sandler]` or `tp.file.properties["date"] = tp.date.now("YYYY-MM-DD")`

**Describe alternatives you've considered** A clear and concise description of
any alternative solutions or features you've considered.

No alternatives considered.

**Additional context** Add any other context or screenshots about the feature
request here.

![Screenshot 2023-09-12 at 16 01 19](https://github.com/SilentVoid13/Templater/assets/31450021/4fdaa270-df76-45f5-9d56-18e5ad02a3c9)

**Comment by AB1908** [comment]
I'm not sure I understand. Can you explain what you're trying to accomplish? Templater is meant to replace the template with an appropriate value, this fundamentally won't work with a date type in preview mode.

**Comment by brychanmd** [comment]
Hi @AB1908 ,

Thanks for your response.

What I was hoping to accomplish is to use templater syntax to modify the value of the properties, whilst still using the properties in the preview mode rather than plain YAML.

I understand this simply isn't possible with properties that are not of type text as Obsidian itself will not validate the templater syntax.

I was hoping Obsidian would have an API to allow property values to be modified.

**Comment by Zachatoo** [comment]
It should still work when the template is applied using one of the Templater commands. The syntax will be invalid in the template, but not when it's applied to a note.

One suggestion I have for you is to escape the frontmatter in your template, so it isn't parsed as frontmatter in your template, avoiding the syntax error, while still getting the benefits of having properties on files created from your template.

You can escape your frontmatter by wrapping your frontmatter with `<% "---" %>` instead of `---`.

```js
<% "---" %>
Date: <% tp.date.now("DD-MM-YYYY") %>
Attendees:
tags:
<% "---" %>
```

**Comment by brychanmd** [comment]
@Zachatoo thanks for pointing that out. Great suggestion and entirely resolves my issue

**Comment by paolo-santucci** [comment]
The Templates core plug-in now merges the YAML properties in the template with the ones already in the note. 

Template:
```
---
category: test
tags: 
  - test
---

Some test text
```

Note:
```
---
tags: 
  - draft
---
This is my text
```

When I apply the template, the text in the note becomes:
```
---
tags: 
  - draft
  - test
category: test
---
This is my text

Some test text
```

If I do the same with Templater, what I get is:
```
---
tags: 
  - draft
---
This is my text
---
category: test
tags: 
  - test
---

Some test text
```

**Comment by Zachatoo** [comment]
> The Templates core plug-in now merges the YAML properties in the template with the ones already in the note.

You are correct that the Templater plugin does not also have this new feature that the Templates plugin added. I think this would be a good feature to add.

**Comment by xieve** [comment]
For now, you can use the native frontmatter API like this:
https://github.com/SilentVoid13/Templater/issues/302#issuecomment-1781497890

**Comment by paolo-santucci** [comment]
OK, using the API works really well for me, thank you very much!

**Comment by Zachatoo** [comment]
Going to close this since everyone seems happy with the current solutions, and there's now a new issue for specifically handling merging of properties automatically. Thanks for everyone's contributions to this issue!
