### ISSUE TITLE
Mobile not found on Laptop

### ISSUE THREAD

**Issue by DreamerDon** [SilentVoid13/Templater#1199]
**Plugin information (please complete the following information):**

-   OS: Windows 10 on Lenovo Legion laptop
-   Templater version: v1.16.0
-   Obsidian version: v1.4.13
-   Templater settings: "90 - 99 Templates"

**Describe the bug**
When trying to run user scripts or frontmatter scripts, it kicks back that Mobile is not defined.

**Expected behavior**

**Screenshots**
![Screenshot 2023-09-21 094447](https://github.com/SilentVoid13/Templater/assets/145690214/9a2c2420-2f74-419d-843c-5a3195d2eefa)

**Additional context**
I noticed this starting out with User Scripts that worked at most a half hour before bug emerged.

**Comment by DreamerDon** [comment]
**Additional context**
I opened another vault to find Templater working unaffected by the bug.  Seeing that, I deleted the user scripts I worked on and found the bug gone on original vault.

**Re-Description of Bug**
By having too many user scripts, Mobile becomes undefined.

**Comment by Zachatoo** [comment]
That is very likely an issue with a specific user script or template. Can you further diagnose which user script or template is causing the issue?

**Comment by DreamerDon** [comment]
It was a total of four scripts, where it would add a line of text onto a value if the input value matches exactly.  It then would spit out that value at the end.  The text looks like:
"- The Right Honourable The Earl [[Link]] [[Link]]\n";

Attached is one of the scripts in three parts.
![Screenshot 2023-09-22 021333 Script part1](https://github.com/SilentVoid13/Templater/assets/145690214/66f66db9-5c51-4f00-86df-45d681297820)
![Screenshot 2023-09-22 021333 Script part2](https://github.com/SilentVoid13/Templater/assets/145690214/1d3e9a84-44ed-43c9-9820-e8452371ff6f)
![Screenshot 2023-09-22 021333 Script part3](https://github.com/SilentVoid13/Templater/assets/145690214/b8be1883-b55f-4b89-a12d-251898d49dbc)

**Comment by Zachatoo** [comment]
Do any of your user scripts or templates contain the word `mobile`? Or any other files in your user scripts folder? That is likely where the error is happening.

**Comment by DreamerDon** [comment]
None do.  I didn't even know it was an option.

**Comment by Zachatoo** [comment]
Can you try the following steps to narrow down which user script is causing the issue?

1. Add back in one of your user scripts into your vault.
2. Open the command palette (<kbd>Cmd</kbd> + <kbd>P</kbd> by default)and run the command `Reload app without saving`.
3. In an empty file, run the `Templater: Replace templates in the active file` command from the command palette.
4. Repeat steps 1-3 until an error is thrown.

When the error is thrown, we'll know that that is the user script that is causing the issue.

If you're able to bring in all of your user scripts into your vault and no error happens, then it's not an issue with one of your user scripts, and is likely an issue with a specific template. You'll have to try executing each template until you find which one throws an error.

**Comment by DreamerDon** [comment]
Okay.  So I had to recreate the removed scripts from scratch due to deleting them in the first place.  But performed the steps as instructed.  No error was detected, thus I now believe that I must have mistyped Mobile as Module on one of the scripts.

**Comment by Zachatoo** [comment]
Glad you figured it out!

**Comment by DreamerDon** [comment]
Thank you very much for the help! Sorry that this was a user-error.
