### ISSUE TITLE
Allow non-valid templates in the template folder 

### ISSUE THREAD

**Issue by YousufSSyed** [SilentVoid13/Templater#1203]
**Is your feature request related to a problem? Please describe.** 
I have set a template folder but I'd like to have more than templates in it, like JS files. If I place JS files in there then it causes errors in whatever template I try to insert. 

**Describe the solution you'd like** 
Just allow any kind of file in the template folder.

**Comment by Zachatoo** [comment]
I'm not able to reproduce this. In fact, surprisingly, Templater picks up the .js files and will insert the contents of the js file if it's selected as the template to insert.

1. Created a file called `test-js.js` in my templates folder.
2. Contents of the test-js.js` file is `console.log("hello world");`.
3. In a markdown file, run the `Templater: Open Insert Template modal` command from the command palette.
4. Select `test-js` from the list.
5. `console.log("hello world");` is inserted in the current markdown file at my cursor position.

Am I missing anything?

**Comment by YousufSSyed** [comment]
OK I just did some troubleshooting and it turns out it because I set the same folder for user scripts as for templates. I don't have any so I just turned that off. Thanks for help anyway.
