### ISSUE TITLE
Since 1.16.1 it is no longer possible to create a note from a template when a non-md file is active

### ISSUE THREAD

**Issue by ItsFullOfCode** [SilentVoid13/Templater#1210]
**Plugin information**

-   OS: Windows 10
-   Templater version: [1.16.1]
-   Obsidian version: [1.4.14]

**Describe the bug**
It seems since [1.16.1](https://github.com/SilentVoid13/Templater/releases/tag/1.16.1) is is no longer possible to execute "Create new note from template" when a non-md file is the active file.

**Error message**
"plugin:templater-obsidian:61 Templater Error: Template parsing error, aborting. Cannot read properties of undefined (reading 'basename').
Caused by: const baseName = tp.config.active_file.basename;

**Workaround**
In Template replace `const baseName = tp.config.active_file.basename` with `const baseName = app.workspace.getActiveFile()`

This regression might be related to this [commit](https://github.com/SilentVoid13/Templater/commit/06b99386203dfd5a933ba7aab7c8c94b95564b6c) - ("Use `app.workspace.activeEditor?.file` instead of `app.workspace.getActiveFile()` to get the active file").

Being able to "Create a new note from template" on a non-md File (i.e. an .pdf File) allows to access the properties of the .pdf File (basename, parent, ..) and utilize that information in the newly created note. Example use case: quickly create markdown "wrapper" notes for binary files.

**Comment by Zachatoo** [comment]
I didn't know about this use case, fixed in 1.16.2 🙂

**Comment by AB1908** [comment]
Should we start committing templates like these to a test vault in the repo? That way we can do some basic smoke tests if we ever rewrite certain features or the plugin in its entirety.

Or do you think we can try building a regression test suite instead? Maybe both ideas are overkill for a small open source plugin like this.

**Comment by Zachatoo** [comment]
@AB1908 I definitely think we should start adding more tests, I think that will help in a lot of ways. I'm not totally sure how I want to go about it yet. I think ideally we'd be able to run the test suite in any vault, and the tests will build the contents it needs itself, but not sure how feasible that is with creating binary files, not something I've had to do before.
