### ISSUE TITLE
Note composer core plugin is no longer working with Templater triggering option enabled

### ISSUE THREAD

**Issue by oliviercarizzoni** [SilentVoid13/Templater#1219]
-   OS: Windows 11
-   Templater version: 1.16.3
-   Obsidian version: 1.4.14
-   Templater settings: [Template folder location: "06 Modeles"]

**Describe the bug**
- Make sure the option `Trigger Templater on new file creation` is enabled
- Activate Note composer in core plugins
- Set a template for it, and just put some text in it (no even a need for templater instructions or variables, it is an explicit bug)
- Open a note and select some text
- Right click and select `Extract current selection`
- Enter the new note name and press Enter, **it has to be a new file**
- Open the new note, nothing is inside

**Expected behavior**
Note composer makes use of a template like any other plugins, template should be inserted fine. I am certain that it has worked before.

**Comment by AlexanderKhmelnytsky** [comment]
The same problem

**Comment by Zachatoo** [comment]
Found the issue, will be fixed in the next release tonight, thanks for the report!

**Comment by oliviercarizzoni** [comment]
Thanks to you for processing that, that quick ! 👌
