### ISSUE TITLE
tp.file.rename not accepting user function input

### ISSUE THREAD

**Issue by quintrino** [SilentVoid13/Templater#122]
**Plugin informations (please complete the following information):**
 - OS: Mac
 - Templater version: 1.5.4
 - Obsidian version: 0.11.13
 - Templater settings: 
 - folder: templates/
 - timeout: 15

I have 
`<% tp.user.youtube_title({VIDEO: tp.frontmatter["link"] }) %>`
which successfully gets the title of a youtube video from the youtube link in the frontmatter. 
but when I do

`<% tp.file.rename( tp.user.youtube_title({VIDEO: tp.frontmatter["link"] })) %>`

It renames my file to [object Promise]

youtube_title = `/usr/local/bin/youtube-dl --get-filename -o '%(title)s' "$VIDEO"`

Frontmatter:

---
link: https://www.youtube.com/watch?v=QgbLb6QCK88
---

**Comment by SilentVoid13** [comment]
Hey @quintrino this isn't a bug, this is because user functions are asynchronous, which means you need to explicitly wait for by adding the `await` keyword.
In your case, this would give:

```
<% tp.file.rename( await tp.user.youtube_title({VIDEO: tp.frontmatter["link"] })) %>
```

Tell me if this works for you.

**Comment by quintrino** [comment]
Yep, all working, thanks so much!
