### ISSUE TITLE
tp.file.cursor expands all collapsed sections

### ISSUE THREAD

**Issue by dburkes** [SilentVoid13/Templater#1222]
**Plugin information (please complete the following information):**

-   OS: MacOS 14.0 Sonoma
-   Templater version: 1.16.3
-   Obsidian version: 1.4.14
-   Templater settings: Automatic Jump to Cursor

**Describe the bug**
When a template is inserted, and tp.file.cursor() is executed, all collapsed sections in the entire document are expanded. 

**Expected behavior**
tp.file.cursor() should not expand any collapsed sections, except perhaps if the section where the cursor is placed was collapsed.

**Additional context**
You can also reproduce this bug, without inserting a template, by doing the following:
- Create a blank note
- Create a new Heading paragraph like "# Heading 1", then type some text below it
- Create a new Heading paragraph like "# Heading 2", then type <% tp.file.cursor() %> below it
- Collapse the "Heading 1" paragraph, so that the text below it is no longer visible
- Execute the "Templater: Jump to next cursor location" command, which is by default mapped to Option+Tab

Result- the cursor does jump to the correct location, but the "Heading 1" paragraph is also expanded

**Comment by Zachatoo** [comment]
Will be fixed in the next release, thanks for the report!
