### ISSUE TITLE
Can I import a Javascript library in the user template?

### ISSUE THREAD

**Issue by EgeCaglarDurmaz** [SilentVoid13/Templater#123]
Can I import a Javascript library in my user template?
If I can, how? Can you give an example?

**Comment by SilentVoid13** [comment]
Hey @EgeCaglarDurmaz you can now use user scripts in Templater 1.6.0. In your js script file, you can require a static library javascript file, if you'd like to.

Documentation is at https://silentvoid13.github.io/Templater/docs/user-functions/script-user-functions
