### ISSUE TITLE
Bug when creating a new note with a default template and start typing.

### ISSUE THREAD

**Issue by albertoloscerritos** [SilentVoid13/Templater#1231]
When I create a new note that has a default template from templater, if type something I will start typing over the properties. 

Here is a link to the report about this bug I did in the obsidian forum.
https://forum.obsidian.md/t/if-i-create-a-new-note-with-a-template-and-start-typing-i-start-typing-inside-the-properties-code/67270
There are all the details regarding the bug.
Obsidian devs said it is a problem with templater

I'm currently using obsidian 1.4.16
and templater 1.16.4

Thanks for your time.

**Comment by Zachatoo** [comment]
Can reproduce.

A workaround is to add a `<% tp.file.cursor() %>` after the properties to force your cursor to be where it should be.

```
---
key: value
---
<% tp.file.cursor() %>
```

Adding relevant video from forum post here.

![af4fcc16990098aa4bb6e637cc8426593fecb205](https://github.com/SilentVoid13/Templater/assets/6936914/6f5499a1-db4a-4a0d-bd6a-258ab0b68b82)

**Comment by albertoloscerritos** [comment]
Thanks for the workaround. 
Hopefully, it gets fixed in the future. Have a nice day.

**Comment by Zachatoo** [comment]
Will be fixed in the next release!

**Comment by albertoloscerritos** [comment]
thanks
