### ISSUE TITLE
Template file in templates directory disappears

### ISSUE THREAD

**Issue by baderk** [SilentVoid13/Templater#1233]
**Plugin information (please complete the following information):**

-   OS: Windows 11
-   Templater version: 1.16.4
-   Obsidian version: 1.4.16
-   Templater settings: Template folder location: "Templates/"

**Describe the bug**
This is the second time it happens. The template file I have (Issues Template.md) inside the Templates/ directory suddenly disappears. As in not in the recycling bin or anywhere to be found with no trace. I thought it was a weird one time thing when it happened the first time, but it just happened again and I have no idea where to find it.

I tried to see if there are some logs to look into but there is nothing sadly. Maybe that could be helpful for this plugin to have a log file on the system?

It works and I used the template, but just suddenly it disappears and get an error that Templater can't find the template.

**Expected behavior**
I shouldn't lose my templates. I expect them to be in the directory I create them in.

**Additional context**
I have the template running as a "Startup Template" which I'm not sure if it has anything to do with its disappearance. But I also realized that I don't want it to be a startup template, but I had it as such due to misunderstanding to what startup actually was.

I realized the template was running whenever I open Obsidian, and I had some prompts in the template, so I kept closing the prompts and enter nothing, which resulted to empty notes in the destination directory, which is fine, but I wonder now if that caused something that ended up deleting the template? Because when I not enter any input to the prompts, everything is 'null'. But again, that would be strange if it just made the template disappear without a trace.

Another thing I'm suspecting is maybe the fact that my Obsidian Vault is in OneDrive? I don't know why that would be an issue, but even in one drive history there is no trace of that template file that I lost. So now I need to rewrite it from scratch for the second time.

**Comment by Zachatoo** [comment]
I haven't heard of template files being deleted, unless it was from the OS or a sync/cloud service.

Just in case though, what is your template? Maybe there's something in there that is deleting files.

**Comment by Zachatoo** [comment]
Marking as removed due to no response.
