### ISSUE TITLE
Including a block from another note containing a code block fails

### ISSUE THREAD

**Issue by RoamanEmpire** [SilentVoid13/Templater#124]
**Plugin informations:**
 - OS: macOS 11.2.3
 - Templater version: 1.5.4
 - Obsidian version: 0.11.13
 - Templater settings: 
<img width="1055" alt="image" src="https://user-images.githubusercontent.com/69714537/115155650-38da7b80-a081-11eb-9ac6-5404fe9ee34e.png">

**Describe the bug**
I have this sample note with a mermaid code block (but I get the same error with any code block):
<img width="693" alt="image" src="https://user-images.githubusercontent.com/69714537/115155755-8b1b9c80-a081-11eb-867c-e47509def249.png">

When I try to embed it in another note with `<%tp.file.include("[[Test#Mermaid]]")%>`, I get this error:
<img width="609" alt="image" src="https://user-images.githubusercontent.com/69714537/115155787-b605f080-a081-11eb-8b87-47583cb1eca5.png">

If I include the entire note with `<%tp.file.include("[[Test]]")%>` it works just fine.

**Comment by SilentVoid13** [comment]
Hey @RoamanEmpire thanks for the heads up! I fixed it, the fix will be available in next release!

**Comment by SilentVoid13** [comment]
You can now update to Templater 1.5.5 to fix this bug!
