### ISSUE TITLE
Interaction between Templater and Excalidraw resulting in file content change

### ISSUE THREAD

**Issue by atyopsis** [SilentVoid13/Templater#1246]
**Plugin information:**

-   OS: GNU/Linux (debian 11)
-   Templater version: 1.18.1 (the bug occurs also with 1.16.0)
-   Obsidian version: 1.4.16, AppImage
-   Templater settings: default settings, except Template folder location: "a/"

**Describe the bug**

Install and enable both Excalidraw 2.0.1 and Templater (1.18.1 or even 1.16.0).
Create a note in a/ containing the following templater code:
`<%*
const regexp = /\(foo\)/
%>`

Run the "Reload app without saving" command. The templater code then turns into
`<%*
const regexp = /foo/
%>`

**Expected behavior**

Nothing. Neither plugin is supposed to modify file content without being prompted in any way.

**Screenshots**

![2023-11-17-172617_913x250_scrot](https://github.com/SilentVoid13/Templater/assets/151197672/51aa0220-0c48-4c37-8870-487830f0c5dc)

**Additional context**

Attached above is a diff screenshot from Sync version history. The bug does not occur if either plugin is turned off.

**Comment by Zachatoo** [comment]
I've tried to reproduce this in my test vault and the sandbox vault and couldn't reproduce in either. In my test vault I tried on Excalidraw 2.0.1 and Templater 1.18.1. In the sandbox vault I tried on Excalidraw 2.0.4 and Templater 1.18.1.

Is there any steps I might be missing? Are you still facing this issue?

https://github.com/SilentVoid13/Templater/assets/6936914/f6732baf-fda4-438c-a855-a0f963b27d4e

**Comment by atyopsis** [comment]
The issue does seem to be gone in Obsidian 1.5.0 (Excalidraw 2.0.4 & Templater 1.18.1). I was able to reproduce this in Obsidian 1.4.16 (Excalidraw 2.0.4 & Templater 1.18.1). If I remember correctly, I was still facing this problem with Obsidian 1.5.0 and some intermediate version of Excalidraw beween 2.0.1 and 2.0.4, so let's just hope that whatever fixed this will stick.

**Comment by Zachatoo** [comment]
Thanks for checking this! Will mark as resolved for now, feel free to comment on this if it shows up again.
