### ISSUE TITLE
Templater Syntax Highlight is broken on Obsidian 1.5.0 (Desktop - Catalyst/Insider release)

### ISSUE THREAD

**Issue by I-Pch** [SilentVoid13/Templater#1251]
Hi there 😊 ! 

This is much more a visual bug than anything else (apparently) but the Desktop Catalyst release of Obsidian `1.5.0` broke Templater's syntax higlighter 😔 ... 

Hoping this is something that can be fixed (🍀 ), here I am 😊 ...
   
---
## Plugin information:

-   OS: `MacOS Big Sur 11.7.10` 
-   Templater version: `1.18.1`
-   Obsidian version: `1.5.0` (Catalyst/Insider release)
-   Templater settings: 
    - Fresh install in the Sandbox Vault
    - Template folder location: `/Temp`
    - Syntax Highlighting on Desktop: `On`
    - Syntax Highlighting on Mobile: `Off`
    - Automatic jump to cursor: `On`
    - Trigger Templater on new file creation: `On` 
    - Show icon in sidebar: `On`
    - Template Hotkeys: `None` set up
    - Folder Templates: `Enabled` but none set up
    - Startup Templates: `None`
    - User Script Functions: Not set up
    - User System Command Functions: `Disabled`  

---    
## Describe the bug:
Apparently, the Catalyst release of `Obsidian 1.5.0` (Desktop) doesn't seem to play well with Templater's syntax highlighter and all templates are now rendered as simple `.md` files 😔 .
In terms of functionality, the templates still seem to work as expected but writing and/or re-reading a long and complex template can now be a bit hard and confusing experience 🥺 ...

---   
## Expected behavior: 
If possible 🥺 , I really would like to have Templater's syntax highlight back 😊 

--- 
## Screenshots:
I wish I would be able to do a before/after comparison but:

### Screenshot 1: From the Sandbox Vault (+ Templater)
Here's how a template now looks like in the Sandbox Vault. 
(The template works as expected though 😊 )

<img width="791" alt="Sandbox - Broken Syntax Highlight - Templater" src="https://github.com/SilentVoid13/Templater/assets/77828085/df6be363-c319-444b-babf-1b8d0ccc0e00">

### Screenshot 2: From a messy "Test" vault  
And here's a weird looking templater's template from one of my messy test vaults 🙃 : `Live Preview` vs. `Source Mode`

It seems like Obsidian is actively trying to render the `HTML` and markdown link used in this template, leading to some gaps in Live Preview, instead of considering this `.md` file as what it actually is: a template 😔 .
   
<img width="1396" alt="templater - syntax highlight" src="https://github.com/SilentVoid13/Templater/assets/77828085/f96caa84-a2b2-4990-b58a-7f2d12d77088">

---
## Additional context:
I didn't change anything in my vaults other than rebooting Obsidian once the Catalyst/Insider release was installed 😊 .

I really really do hope a fix exists for this visual issue 🍀 😇 (for the sake of the template's readability) ... 

Thank you so very much in advance for any help regarding this 🙌 !!!

**Comment by Zachatoo** [comment]
Can reproduce, will investigate. Thanks!

**Comment by Zachatoo** [comment]
Update: This will be tricky for me to fix. Looks like with the deprecation of CodeMirror 5 in Obsidian 1.5.0, the previous way of adding syntax highlighting will no longer work and will have to be rewritten. I am not very experienced in CodeMirror, so migrating the code to CodeMirror 6 will take some time. When it is fixed, it may not be exactly the same as it was before.

**Comment by iamrecursion** [comment]
Given that highlighting still works on mobile, which is CM6, you can likely just unify the both of those now.

**Comment by Zachatoo** [comment]
I don't think it's the deprecation of CM5 itself that broke it, rather some side effect of that change broke it.

I've tried a few things trying to get the `token` function for the templater mode to run at all, but it's never being called. The `token` function for the hypermd mode is being called. The templater mode is being registered as an editor extension, though I don't know if it's being done correctly since it isn't being called.

**Comment by iamrecursion** [comment]
According to some discussions I've had internally, the removal of CM5 has resulted in `cm.setOption` used [here](https://github.com/SilentVoid13/Templater/blob/master/src/handlers/EventHandler.ts#L41) no longer working. Templater uses it to toggle the highlight mode on and off. 

Strangely enough, this should never have worked on mobile, but I cannot see where else in the codebase the mode would be handled for mobile specifically.

The syntax is created [here](https://github.com/SilentVoid13/Templater/blob/master/src/editor/Editor.ts#L68) as an overlay on HyperMD, and is defined correctly using `StreamParser` as best I can tell. One thing that isn't clear to me is whether `StreamParser` is sufficient as an `Extension` itself in CM6 terms. Perhaps it needs to be wrapped in a `ViewPlugin.define`.

**Comment by iamrecursion** [comment]
Possibly [mixed language parsing](https://codemirror.net/examples/mixed-language/) might be helpful.

**Comment by iamrecursion** [comment]
I have a PR open #1263 that fixes this.

**Comment by Zachatoo** [comment]
Released in 2.0.0 of Templater! Thank you so much @iamrecursion !

Note: Syntax highlighting will not work on mobile if you sync your vault between desktop and mobile and are therefore able to install the latest version of Templater on your mobile device. I do not think this is a concern. If you're syncing between desktop and mobile, you can manage your templates on desktop if you want syntax highlighting until mobile reaches Obsidian 1.5.x feature parity.

**Comment by iamrecursion** [comment]
@Zachatoo Are you sure about the mobile thing? I have plugin sync on and it was working on mobile during my testing!

**Comment by mProjectsCode** [comment]
It might be worthwhile to port the syntax highlighting to a CM6 [View Plugin](https://docs.obsidian.md/Plugins/Editor/View+plugins) that creates [mark decorations](https://codemirror.net/docs/ref/#view.Decoration%5Emark). That approach should be a lot simpler, more powerful and future-proof. I am using such an approach in [Meta Bind](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/blob/master/src/cm6/Cm6_ViewPlugin.ts).
