### ISSUE TITLE
Templater Hides Properties on Obsidian 1.5.0 

### ISSUE THREAD

**Issue by Comprehensive-Jason** [SilentVoid13/Templater#1253]
The Desktop Catalyst release of Obsidian 1.5.0 messed with how Templater interacts with Obsidian properties, making them disappear after adding a template.

**Plugin information (please complete the following information):**

-   OS: Windows 11
-   Templater version: 1.18.1
-   Obsidian version: 1.5.0
-   Templater settings: fresh install, no settings changed

**Describe the bug**
After adding a template to a new note, the properties fail to appear in Live Preview Mode unless I close the note and open it again. Switching between Live Preview and Source Mode **does not** make properties appear in Live Preview. 

**Expected behavior**
Properties should simply appear alongside the rest of the template I add.

**Screenshots**
![ezgif com-video-to-gif (1)](https://github.com/SilentVoid13/Templater/assets/68677082/5234dc2a-436b-4f6b-9646-ee8527a9f635)

**Additional context**
This problem was replicated in Sandbox. This issue does not happen with the Templates core plugin.

**Comment by FeralFlora** [comment]
Try pressing enter after inserting. I have line numbers enabled, and when I tested this behavior, I could see the line number change from line 1 to line 5, even though the cursor didn't move further down. If I press enter, the properties appear, without having to reopen. This might hold some clues as to how this can be resolved.

![Obsidian_Ec13bZq38y](https://github.com/SilentVoid13/Templater/assets/33608083/66526a23-e796-4d5b-b3ca-12c7992c35c9)

**Comment by I-Pch** [comment]
I have one template where I'm getting similar results (live preview appears to not refreshed/is not in sync with source mode unless you insert a newline after applying the template) but inconsistently 🤨 ... 

I mean, using 2 different templates doing the same thing (erasing completely the content of a note, Properties included) relying on 2 different Obsidian API methods, I get 2 different results: 

The first one relies on `app.workspace.activeEditor.editor ...` and for that one, I can also see the template working as expected, underneath, as like in your screen recording, the line number is refreshed (going from the initial line number `12` to `1`) but then I need to add a newline to effectively have live preview displaying the same result as in Source mode.

Here's a screen-recording illustrating that 😇 : Left side is the `Testing` note opened in `Source` and the right side is LP 😊 .

https://github.com/SilentVoid13/Templater/assets/77828085/a0fa98b3-8f3c-4467-8a4c-2fa99d189500

On the other side, a template relying on `app.vault.process ...` doesn't display such behavior 🤷‍♀️  ... I.e.: no newline needed and both source and LP are in sync (displaying the same content) ...

https://github.com/SilentVoid13/Templater/assets/77828085/0617800e-92ce-4f68-8d15-80e86abb0040

I'm just mentioning this in case it could help 😇 ... as in both cases, 99% of the template uses Obsidian API only and I just thought this could potentially give some hint as to where the issue my be 😊 ...

**Comment by jcrum** [comment]
I am experience the same thing on some of my templates but I noticed the templates that are working make use of the tp.file.cursor, tp.file.move, or custom scripts.  Attached is video that shows how adding tp.file.cursor will trigger the properties to be shown. 

Uploading ObsidianTemplaterBug1253.mov…

**Comment by I-Pch** [comment]
> tp.file.cursor
Can confirm for that one at least 😊 ...

I used a template adding properties to a note with a `tp.file.cursor()` somewhere in it and didn't encountered the issue 🤷‍♀️ ... 
I mean, there didn't seem to have any delay between Source/Live Preview, everything was rendered at once and my cursor was placed where wanted...

I can only guess that `tp.file.cursor()` somewhat replace manually adding a newline (while setting the focus on the specific note in Live Preview) ?

**Comment by Zachatoo** [comment]
Should be resolved in 1.18.2!

**Comment by SedesGobhani** [comment]
With Templater 2.1.3 to avoid this behavior I needed to include this cursor command (as above) and enable option "Automatic jump to cursor".

**Comment by Comprehensive-Jason** [comment]
As @SedesGobhani said, the problem is back in version 2.13.

**Comment by Zachatoo** [comment]
Thanks, I'll add some tests so I don't accidentally break this again in the future.

**Comment by Zachatoo** [comment]
I believe this has been fixed again in 2.1.4
