### ISSUE TITLE
if tp.file.rename() is called from 'Create new note from template', content is lost/pasted into the wrong file

### ISSUE THREAD

**Issue by luckman212** [SilentVoid13/Templater#126]
- Obsidian 0.11.13
- Templater 1.5.4
 
I found that if `tp.file.rename()` is called as part of a "Create new note from template" action, then you end up with TWO notes:

1. an "Untitled.md", which receives the content from your template
2. a **blank** file, with your desired renamed name 

### Example repro

Put this content in a template and call it via "Create new note from template"

```md
---
<%*
  var p = await tp.system.prompt('Note Topic?', 'Mischievous cats');
  tp.file.rename(p + ' - ' + tp.date.now()) %>date: <% tp.date.now() %>
topic: <%* tR += p ? p : 'blank' %>
---

- Garfield
- Sylvester
- Cheshire Cat
- Heathcliff
- <% tp.file.cursor(1) %>
```

You should end up with 2 notes:

1. **"Untitled"** (containing the frontmatter and text from above)
2. **"Mischievous cats - 2021-04-18"** - which is completely empty

**Comment by leonvanbokhorst** [comment]
Same issue here, same versions, probably related. 

Menu goes wild as well

![20210419-templater](https://user-images.githubusercontent.com/1336023/115221274-c5c91780-a109-11eb-886e-3c19b3135dfd.png)

**Comment by luckman212** [comment]
@leonvanbokhorst what's wrong with that menu? I think that's the way it's supposed to look 😐

**Comment by leonvanbokhorst** [comment]
Seriously...? Oops. My bad. I jumped to conclusions. Please ignore my ignorance. I can see now why it's designed like this.

**Comment by luckman212** [comment]
Hmm @SilentVoid13 I am not 100% sure but it seems that adding `await` in front of the `tp.file.rename()` fixes this problem. So maybe just always force that function to run async? (Limited testing so far... @leonvanbokhorst can you try this and see if it works for you?)

```
---
<%*
  var p = await tp.system.prompt('Note Topic?', 'Mischievous cats');
  await tp.file.rename(p + ' - ' + tp.date.now()) %>date: <% tp.date.now() %>
topic: <%* tR += p ? p : 'blank' %>
---
```

**Comment by leonvanbokhorst** [comment]
Works like expected. I get a single 'Mischievous cats - 2021-04-19' note:

```
---
date: 2021-04-19
topic: Mischievous cats
---

- Garfield
- Sylvester
- Cheshire Cat
- Heathcliff
-
```

**Comment by luckman212** [comment]
Great, we just need to wait for @SilentVoid13's feedback

**Comment by Moonbase59** [comment]
@luckman212 Great creative use of Templater in the front matter! Didn’t even think of that—opens new possibilities, thanks for sharing.

**Comment by SilentVoid13** [comment]
Hey @luckman212 @leonvanbokhorst, sorry for the late response. 
This is not really a bug, you need to use `await` when using `tp.file.rename`.
If you don't, you end up with a race condition because the `TFile` object hasn't been updated, so some content is added to the new one and some to the old one.
The same thing could happen with the new `tp.file.move` function, be careful with async functions.
