### ISSUE TITLE
Root folder template is triggering twice

### ISSUE THREAD

**Issue by danielo515** [SilentVoid13/Templater#1265]
**Plugin information (please complete the following information):**

-   OS: [e.g. Windows 10] android
-   Templater version: 1.18.0
-   Obsidian version: 0.15
-   Templater settings: Template folder location: "templates/"

**Describe the bug**
The root folder template is triggering twice. This was a bug that I think was reintroduced with the latest version.
My root template opens a selector, then when you select one it moves the file to the expected folder and applies the template. This is anflow that worked fine before and it is showcased in the community. 
However, it is now triggering the folder template again when the file is moved, which is erasing my current file content

**Expected behavior**
Not trigger the template for actions of templater moving files

**Screenshots**

**Additional context**
https://github.com/SilentVoid13/Templater/discussions/1122

**Comment by Zachatoo** [comment]
I'm not experiencing this. Maybe this is related to Templater not properly unloading between 1.18.0 and 1.18.2? Restarting Obsidian should resolve that.

https://github.com/SilentVoid13/Templater/blob/master/CHANGELOG.md#1182-2023-12-01

**Comment by danielo515** [comment]
@Zachatoo that was indeed the problem. Restarting obsidian fixed it. Thanks
