### ISSUE TITLE
need create canvas from the template.

### ISSUE THREAD

**Issue by Lustrewilkin** [SilentVoid13/Templater#1266]
**Is your feature request related to a problem? Please describe.** 
no

**Describe the solution you'd like** 
creat file not note

**Describe alternatives you've considered** 
copy+paste

**Additional context** 
none

**Comment by ctwhome** [comment]
Please make this possible! thanks

**Comment by Zachatoo** [comment]
Were you thinking of a new Templater API like `tp.file.create_canvas(...)`? Or using a canvas file as a template? Both? Something else?

There's not a lot of details here so I have no idea what you're looking for.

**Comment by ctwhome** [comment]
ey @Zachatoo, thanks!
I watn to create new canvas from a template. I have created the template.canvas in the template folder, but when creating a new canvas from the template... It doen'st create a new .canvas but a .md file.

It would be awesome to create new canvas from a template. For example, I use projects, brainstorms, ideas.. from canvas.

Steps: 
1. create a .canvas template
![image](https://github.com/SilentVoid13/Templater/assets/4195550/fb20861a-3c1e-4168-a03d-9dff74c00778)

2. select new note from template: 
![image](https://github.com/SilentVoid13/Templater/assets/4195550/01d81eba-33a7-49a6-814f-8c94b6e833a0)

3. then the result is like this:

![image](https://github.com/SilentVoid13/Templater/assets/4195550/2a5baaa7-ac35-4472-af28-a0253132613b)

**Comment by Zachatoo** [comment]
Would creating a canvas from a template create copies of any notes in the canvas, or just reference them?

Right now Templater commands only work in an editor, they'd need to be updated to work in a canvas text card to make this truly useful.

The ordering of command execution may be confusing, we'd probably want to go from top to bottom in the JSON structure, but that'd be annoying to figure out in the canvas UI. Would be easier if there was a "source" mode for canvas where you can edit the JSON directly, but that would be out of scope for Templater to add.

**Comment by ctwhome** [comment]
I guess that obsidian needs to do some improvements to canvas to extend these functionalities?

**Comment by Zachatoo** [comment]
Or a separate plugin that can edit the canvas JSON. I have some ideas on how to implement that.

I'm really just asking questions around how canvas templates should work before anyone actually starts working on it.

**Comment by Zachatoo** [comment]
Well, I think I accidentally got it working, so that's fun! I did a very basic test using a `.canvas` file as a template file and it appeared to work for me. Can I get someone else to verify that they can use `.canvas` files as templates in Templater 2.2.0+?

**Comment by Zachatoo** [comment]
I'm going to assume this is working for others, and that the feature I added is the feature the OP was looking for. Marking as resolved. Feel free to make a few feature request if you're looking for something else.
