### ISSUE TITLE
How to add Obsidian URL to template

### ISSUE THREAD

**Issue by hepabolu** [SilentVoid13/Templater#127]
I am trying to set up a project structure with project info, ideas and such in Obsidian, tasks in OmniFocus and additional files in a specific folder. I prefer this setup to everything in Obsidian

I am now creating a little 'meta template' that simply adds a table to the Obsidian project file with links to the parts of the project. I want to fill in the Obsidian URL so I can grab the entire table and add it to the OmniFocus project note.

I've built the URL but I'm running into the fact that I need to urlencode the filename.

How can I fix that? Do I need to write a javascript snippet or is there another way to get the 'actual' Obsidian URL of the file I'm pasting the template into?

This is what I have now:

```
 [obsidian](obsidian://open?vault=MYvault&file=<%~ tp.file.path(true) %>) 
```

**Comment by luckman212** [comment]
@hepabolu try this:

```
[obsidian](obsidian://open?vault=myvault&file=<% encodeURIComponent(tp.file.path(true)) %>)
```

**Comment by SilentVoid13** [comment]
Thanks @luckman212 for the answer! Closing this.

**Comment by hepabolu** [comment]
Sorry, should have reported that this works. Thanks @luckman212.
