### ISSUE TITLE
tp.obsidian.Notice API creates undismissable notifications

### ISSUE THREAD

**Issue by waffle-lord** [SilentVoid13/Templater#1275]
**Plugin information (please complete the following information):**

-   OS: Windows 11
-   Templater version: 1.18.3
-   Obsidian version: 1.4.16
-   Templater settings: n/a

**Describe the bug**
when calling `tp.obsidian.Notice` a notification is created, but it cannot be dismissed and the duration parameter appears to do nothing.

**Expected behavior**
A dismissable notification appears and times out when a duration is specified

**Screenshots**
![9a8dd6c5-eff7-417c-b0c7-a1a8e2f8eed5](https://github.com/SilentVoid13/Templater/assets/76401815/6f1aff00-aece-4089-8313-b54b2c60a0f2)

**Additional context**
The notifications can be removed by closing obsidian.

Notice API link:
https://github.com/obsidianmd/obsidian-api/blob/bbb696aeb8bf5126bf2ecbf84fc8284fe133bc20/obsidian.d.ts#L2735

**Comment by Zachatoo** [comment]
You don't need `tp.obsidian` you can just call `new Notice("text");`.

You're accessing the static class, not creating an instance of the class, which is why you're seeing unexpected behavior.

**Comment by waffle-lord** [comment]
ah, I see.  Thank you
