### ISSUE TITLE
Templater Error: Template parsing error, aborting (Error for all templates)

### ISSUE THREAD

**Issue by LRBLRBLRB** [SilentVoid13/Templater#1277]
**Plugin information (please complete the following information):**

-   OS: Windows 11
-   Templater version: 2.0.0
-   Obsidian version: 1.5.3
-   Templater settings: [e.g. Template folder location: "Templates/", Timeout: "5" (add the templates not working with their associated command)]
![image](https://github.com/SilentVoid13/Templater/assets/40015998/d0d481fa-ea69-459a-820e-25a0cb1c447c)

**Describe the bug**
Every time I use the template to load a template, error happens: Templater Error: Template parsing error, aborting.  Unexpected token '<'

**Expected behavior**
How can I load a template correctly?

**Screenshots**
![image](https://github.com/SilentVoid13/Templater/assets/40015998/049ede5f-6b34-4982-becc-6c3289f92fb2)
![image](https://github.com/SilentVoid13/Templater/assets/40015998/111039fe-ee0e-49b2-bae0-03748da216dd)
![image](https://github.com/SilentVoid13/Templater/assets/40015998/22d82c06-4496-4a21-8f3a-b14aa3bf28f6)

**Additional context**

**Comment by Zachatoo** [comment]
1. Does this happen for a completely empty template as well? If not, can you provide the exact markdown you're using in your template?
2. Have you setup any user scripts in Templater settings? If so, does the problem stop if you remove all user scripts and restart Obsidian?

**Comment by Zachatoo** [comment]
Marking as removed due to no response from issue author.
