### ISSUE TITLE
File creation time only using the start of Linux time `1/1/1970 00:00:00`

### ISSUE THREAD

**Issue by anujdatar** [SilentVoid13/Templater#1278]
**Plugin information (please complete the following information):**

-   OS: Fedora Workstation 39
-   Templater version: 2.0.0
-   Obsidian version: 1.5.3
-   Templater settings: Just the defaults -> Template folder location: "templates/"

**Describe the bug**
I just updated to templater version 2.0.0 today. I believe I was on v1.15.x before. My template has a file creation date in its frontmatter. I am using `<% tp.file.creation_date("dddd, Do MMMM YYYY") %>` as the command. Since the update it keeps using `Thursday, 1st January 1970`. I was working till last night. Not sure what happened.

**Expected behavior**
I guess expected behavior would be to use today's date `Thursday, 28th December 2023`

**Additional context**
I was using the `flatpak` version till yesterday, but I couldn't get the `pandoc` plugin to use `pdflatex` properly. So I switched to the `AppImage` today and updated all my plugins. Don't know if this caused the issue.

**Comment by Zachatoo** [comment]
I think this is a duplicate of #876

This is likely because you switched to appimage, not because of the Templater update.

**Comment by anujdatar** [comment]
Aah, I see. Thanks. I'll keep a track of the other issue then.
