### ISSUE TITLE
custom variables don't work on windows: they aren't being evaluated

### ISSUE THREAD

**Issue by yhoebeke** [SilentVoid13/Templater#128]
**Plugin informations (please complete the following information):**
 - OS: Windows 10
 - Templater version: 1.5.4
 - Obsidian version: 0.11.13
  - Templater settings: "assets/templates", Timeout: "5" 

**Describe the bug**
It looks like the variables aren’t getting evaluated when a user function is called.

**Expected behavior**
user-defined variables in custom function calls should be evaluated accordingly.
The code that made me find this error can be found here : [Adding your google calendar agenda to your daily journal - Share & showcase - Obsidian Forum](https://forum.obsidian.md/t/adding-your-google-calendar-agenda-to-your-daily-journal/16417/14)
I wasn't able to make the code work as the variables $from $to weren't replaced by the correct values.

**Screenshots**
This user function:
![image](https://user-images.githubusercontent.com/77568247/115293149-43674480-a157-11eb-992b-71578537b680.png)
![image](https://user-images.githubusercontent.com/77568247/115293165-47936200-a157-11eb-85a1-5003fd81fcd6.png)
Returns this
![image](https://user-images.githubusercontent.com/77568247/115293185-4cf0ac80-a157-11eb-908a-4df131efca2a.png)

**Comment by luckman212** [comment]
@yhoebeke I'm guessing this is because on Windows, the default shell is **PowerShell**, not `bash`. You should try to access the variables using PowerShell syntax, e.g. `$Env:from` etc. Take a look at https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_environment_variables

**Comment by yhoebeke** [comment]
I am really sorry, but this may go beyond my basic coding knowledge.
I tried using "$Env:from" but I still get the same results.

I also found this : https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_variables?view=powershell-7.1 
It seems `$variable` is a correct syntax for powershell variables.

The error seems to come from before the command is sent to the command line.
![image](https://user-images.githubusercontent.com/77568247/115295260-d7d2a680-a159-11eb-862e-0f8acacd3951.png)

**Comment by luckman212** [comment]
@yhoebeke See #129 ... on Windows it seems that Electron's default shell for `child_process` is `CMD.EXE`

So, your user template would need to reference the variables in "batch file" format
```bat
echo %from%
```

Or, you can use PowerShell via:
```powershell
powershell (Write-Host -NoNewLine $Env:from)
```

**Comment by yhoebeke** [comment]
Thank you @luckman212 for the explanations!

`echo %from%` worked.

Now I tried to combine it with the agenda code (without any variables first)
_Before, this code worked fine:_
```
C:/Users/adminuser/AppData/Local/Programs/Python/Python37-32/Scripts/gcalcli --calendar "01 - ME meetings and events" --calendar "02 - ME - time-blocking"  --calendar "03 - WORK - Meetings and events" --calendar "04 - WORK - Time-blocking for activities work-related" --nocolor agenda "12:00" "2021/04/22 23:00"
```

and `<% tp.user.gcalcli() %>`
So from my understanding, this was using cmd.exe
Now however, this user function leads to this result : "undefined"
And in the console log I get this error :
```js
Error with User Template echo Error: Command failed: powershell -command "C:/Users/adminuser/AppData/Local/Programs/Python/Python37-32/Scripts/gcalcli agenda 2021/04/20 2021/04/21"

Traceback (most recent call last):
  File "c:\users\adminuser\appdata\local\programs\python\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\adminuser\appdata\local\programs\python\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\adminuser\AppData\Local\Programs\Python\Python37-32\Scripts\gcalcli.exe\__main__.py", line 7, in <module>
  File "c:\users\adminuser\appdata\local\programs\python\python37-32\lib\site-packages\gcalcli\cli.py", line 152, in main
    gcal.AgendaQuery(start=parsed_args.start, end=parsed_args.end)
  File "c:\users\adminuser\appdata\local\programs\python\python37-32\lib\site-packages\gcalcli\gcal.py", line 1238, in AgendaQuery
    return self._display_queried_events(start, end)
  File "c:\users\adminuser\appdata\local\programs\python\python37-32\lib\site-packages\gcalcli\gcal.py", line 1187, in _display_queried_events
    return self._iterate_events(start, event_list, year_date=year_date)
  File "c:\users\adminuser\appdata\local\programs\python\python37-32\lib\site-packages\gcalcli\gcal.py", line 1056, in _iterate_events
    self._PrintEvent(event, prefix)
  File "c:\users\adminuser\appdata\local\programs\python\python37-32\lib\site-packages\gcalcli\gcal.py", line 710, in _PrintEvent
    event_color
  File "c:\users\adminuser\appdata\local\programs\python\python37-32\lib\site-packages\gcalcli\printer.py", line 89, in msg
    file.write(msg)
  File "c:\users\adminuser\appdata\local\programs\python\python37-32\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f4b0' in position 28: character maps to <undefined>

    at ChildProcess.exithandler (child_process.js:312)
    at ChildProcess.emit (events.js:310)
    at maybeClose (internal/child_process.js:1021)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286)
```

So I don't understand why the code that worked before, simply using cmd.exe, doesn't work anymore.

**Next, I tried using the powershell without variables.**
This command and user function
```js
<% tp.user.agenda() %>
```
```js
powershell  (C:/Users/adminuser/AppData/Local/Programs/Python/Python37-32/Scripts/gcalcli agenda --nocolor)
```
Leads to this result
![image](https://user-images.githubusercontent.com/77568247/115364278-85c66b00-a1c3-11eb-92cd-952b96d0ad7b.png)

So instead of giving me the results for the whole week, **it seems the result are cut off**.
![image](https://user-images.githubusercontent.com/77568247/115364240-7c3d0300-a1c3-11eb-8244-0cfee4b8cd90.png)

**Next, I tried using the powershell with variables.**
and long story short, it seems to be working, but the results from templater seem to be cut off
```
<% tp.user.agenda({from: tp.date.now("YYYY-MM-DD", 2, tp.file.title, "YYYY/MM/DD"),to: tp.date.now("YYYY-MM-DD", 5, tp.file.title, "YYYY/MM/DD")}) %>
```
```
powershell  (C:/Users/adminuser/AppData/Local/Programs/Python/Python37-32/Scripts/gcalcli --nocolor agenda %from% %to%)
```
result:
![image](https://user-images.githubusercontent.com/77568247/115364641-e3f34e00-a1c3-11eb-97aa-9ba8075434c2.png)

**Comment by SilentVoid13** [comment]
Hey @yhoebeke as @luckman212 said, if you're using cmd you must use `%from%`, but you already figured that out.
Concerning the text "crop" from Templater, it's weird, I never saw that. 
When you're executing the command in powershell (replacing `%from%` and `%to%`) what is the result ?

**Comment by luckman212** [comment]
We shouldn't mix the syntax. How about skipping `cmd.exe` completely, and invoking PowerShell via `ComSpec` (as per https://github.com/SilentVoid13/Templater/issues/129#issuecomment-823376280)

**edit:** so far it doesn't quite work (yet) - awaiting answer on #129 about overriding `ComSpec`

**Template:**
```
<% tp.user.TestFunc({ComSpec: 'C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe', from: '2021-04-19', to: '2021-04-20'}) %>
```

user function **TestFunc**:
```
Start-Process -FilePath 'C:/Users/adminuser/AppData/Local/Programs/Python/Python37-32/Scripts/gcalcli' -ArgumentList '--nocolor', 'agenda', $Env:from, $Env:to
```

_refs:_
- [Start-Process | Microsoft Docs](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/start-process?view=powershell-7.1)
- [Child process | Node.js Documentation](https://nodejs.org/api/child_process.html#child_process_default_windows_shell)
- https://ss64.com/ps/powershell.html

**Comment by luckman212** [comment]
@yhoebeke SV confirms that setting ComSpec doesn't work (yet) but he may add a switch for that. For now, I found a temporary solution, you may want to try this:

**Template** (example)
```
<% tp.user.MyFunc({from: tp.date.yesterday(), to: tp.date.now()}) %>
```

**User Function** (MyFunc)
```
powershell.exe -command "& { Start-Process -FilePath 'C:/Users/adminuser/AppData/Local/Programs/Python/Python37-32/Scripts/gcalcli' -NoNewWindow -ArgumentList '--nocolor', 'agenda', $Env:from, $Env:to }"
```

**Comment by yhoebeke** [comment]
Thank you for your help @luckman212 in debugging this.

I did some testing and your code works. And my piece of code works as well. They both return the same thing in the powershell and in Obsidian. But in Obsidian what is returned is cut off.

**Template** (asking for my calendar from today until five days from now)
```
<% tp.user.MyFunc({from:  tp.date.now("YYYY-MM-DD", 0, tp.file.title, "YYYY/MM/DD"),to: tp.date.now("YYYY-MM-DD", 5, tp.file.title, "YYYY/MM/DD")}) %>
```

**User function**
Either
```

```
or

**Comment by yhoebeke** [comment]
Is it just me or did my last message here disappear?

**Comment by luckman212** [comment]
I think it's just you, what was the message about?

**Comment by yhoebeke** [comment]
I had written a long message explaining some debugging I had done with quite some screenshots.
Both your user function and this user function `powershell  (C:/Users/adminuser/AppData/Local/Programs/Python/Python37-32/Scripts/gcalcli --nocolor agenda --details all --tsv --nodeclined %from% %to%)` work to fetch the calendar.

The bottom-line of my message was that I found two (I think related) issues:
- special characters like ° were displayed incorrectly.
- what was causing the calendar to be "cut off" in Obsidian were Emojies in the name of the events. In the powershell, I was able to get my calendar for several days, but in Obsidian the information would be cut off just before an event that starts with an emoji. Removing all the emojies from my calendar solved this problem.

@SilentVoid13 So in the end, perhaps there is a problem in how powershell returns/encodes certain characters and/or how templater processes certain characters and emojies ?

To replicate, try asking for your agenda with this command `powershell  (C:/Users/adminuser/AppData/Local/Programs/Python/Python37-32/Scripts/gcalcli --nocolor agenda` in powershell vs Templater in Obsidian. Then add emojies in the beginning of your events and repeat the process. You should get the same behavior as I experienced.

**Comment by SilentVoid13** [comment]
Hey @yhoebeke, this is a know problem with powershell, that does not come from Templater (re #9 #15). 
I have yet to find a solution for this, I did not looked deeply into it.
Anyway glad it's working now, you will be able to specify powershell as the default shell in the next release in the settings
Closing this.

**Comment by AB1908** [comment]
I ran into this today lol. I'll probably open another issue and tag it for documentation.
