### ISSUE TITLE
tp.frontmatter does not respect "quotation marks" --> "

### ISSUE THREAD

**Issue by mariusgerome** [SilentVoid13/Templater#1282]
**Describe the bug**
I build a template that should update my old metadata for a file.

Example:
I have a file with the property tag -> `category-example: "[[link]]"` 
the quotation marks don't get recognized with the `<% tp.frontmatter["category-example"] %>` command

**Expected behavior**
`category-example: "[[link]]"`
but what I get instead is: `category-example: [[link]]`

**Comment by Zachatoo** [comment]
You can wrap it in quotes like this as a workaround.

```
"<% tp.frontmatter["category-example"] %>"
```

**Comment by mariusgerome** [comment]
You're right,
but then "list-properties" would turn into something like this:
`category-example: "[[link 1]], [[link 2]], [[link 3]]"`

instead of:
```
category-example:
- "[[link 1]]"
- "[[link 2]]"
- "[[link 3]]"
```

:/ :D
– M

**Comment by Zachatoo** [comment]
You're right! For list properties, you can do this to wrap each entry in quotes.

```js
<% tp.frontmatter["category-example"].map(prop => `"${prop}"`) %>
```

**Comment by Zachatoo** [comment]
> But with multiple items in a row like that, it's invalid.

Right, needs to be wrapped in `[]` to be valid

```js
[<% tp.frontmatter["category-example"].map(prop => `"${prop}"`) %>]
```

> Do you have a similar epic-code hack, that puts all of those list-values in quotation marks AND puts them on a new line?

Could do something like this

```js
<% tp.frontmatter["category-example"].map(prop => `\n  - "${prop}"`) %>
```

**Comment by Zachatoo** [comment]
I'm the current maintainer of Templater, so yes I add features and fix bugs as I have time

**Comment by mariusgerome** [comment]
> Could do something like this
> 
> ```js
> <% tp.frontmatter["category-example"].map(prop => `\n  - "${prop}"`) %>
> ```

This seems to work, I got an correct output one time (only leaving an `,` at the end of one line, but thats fine.
But I cant replicate this, something is broken with my obsidian I think. I get this `Template parsing error, aborting` aaaallll the time. So weird that I cant run the same exact thing twice without restarting obsidian :D … anyway, thats on my site.

Thank you Zachatoo!
Maybe this finds a way into the docs, and as an extension to the current tp.frontmatter list.

**Comment by Zachatoo** [comment]
> something is broken with my obsidian I think. I get this Template parsing error, aborting aaaallll the time.

May be a user script, though we can continue that conversation over here

<https://github.com/SilentVoid13/Templater/discussions/1285#discussioncomment-8014529>

**Comment by Zachatoo** [comment]
Added an example to the docs, now doesn't have the `,` anymore

```js
<% tp.frontmatter.categories.map(prop => `  - "${prop}"`).join("\n") %>
```
