### ISSUE TITLE
system.prompt has unusual behaviour with alternate language input on mac

### ISSUE THREAD

**Issue by niall-byrne** [SilentVoid13/Templater#1284]
#### OS
-   OS: OSX 12.7.1 (Monterey)
-   Templater version: v1.16.0
-   Obsidian version: v1.4.16

#### Templater settings: 
- location: obsidian/templates
- syntax highlighting, automatic jump to cursor, trigger on file, show icon: all enabled
  
**Describe the bug**
When the Korean input language is activated and I'm inputting characters into a prompt, subsequent prompts will ALSO be populated.

To reproduce:
- enable Korean input, enter some Korean characters, and hit enter.
- subsequent prompts will ALSO be filled out with no ability to interactively enter data

**Expected behaviour**
- Each time I press ENTER only a SINGLE prompt is populated.

**Example Template**

```
<%-*
	const korean = await tp.system.prompt("Korean:", "", true);
	const naver = "https://korean.dict.naver.com/koendict/#/search?query=" + encodeURIComponent(korean)
	const english = await tp.system.prompt("English:"); 
-%> | [<% korean %>](<% naver %>)  |  <% english %> |
```

If I don't copy and paste the Korean text, and enter it manually with OSX's language input BOTH the Korean and English prompts will be populated with the Korean characters.

Two prompts are filled out at once ...

**Comment by Zachatoo** [comment]
I'm going to need your assistance on this one. For some reason, I can't get my keyboard on Mac to output Korean keys. Tried setting Korean to my only language on my computer and restarting, my keyboard still outputs English.

Try opening the developer tools (<kbd>Cmd</kbd><kbd>Shift</kbd><kbd>I</kbd>) and executing this template. I need to see the results that show up in the "Console" tab. Even better if you can get a screen recording so I can see the logs as they're happening.

```js
<%-*
    const start = performance.now();
    const korean = await tp.system.prompt("Korean:", "", true);
    console.log('korean', performance.now() - start, korean);
    const naver = "https://korean.dict.naver.com/koendict/#/search?query=" + encodeURIComponent(korean)
    console.log('naver', performance.now() - start, naver)
    const english = await tp.system.prompt("English:"); 
    console.log('english', performance.now() - start, english)
-%> | [<% korean %>](<% naver %>)  |  <% english %> |
<%* console.log('tR', tR) %>
```

**Comment by Zachatoo** [comment]
Nevermind, I was able to my keyboard working with Korean and was able to reproduce.

This appears to be a browser bug, interestingly enough (see vuejs/vue#10277).

I have a fix on the way!
