### ISSUE TITLE
The Templater Code is not converted to the corresponding text.

### ISSUE THREAD

**Issue by fishooo0815** [SilentVoid13/Templater#1287]
**Plugin information (please complete the following information):**

-   OS: Mac OS 12.3.1
-   Templater version: 2.0.0
-   Obsidian version: 1.5.3
-   Templater settings: Location: A/Templates

**Describe the bug**
The Templater Code is not converted to the corresponding text.

**Expected behavior**
In the first example: See the converted dates 2024-02-06 as links

**Screenshots**

**The Code**

Issue 1 (This code was working a few days ago)
[[<% tp.date.now("YYYY-MM-DD", -1, tp.file.title, "YYYY-MM-DD") %>]] <-> [[<% tp.date.now("YYYY-MM-DD", 1, tp.file.title, "YYYY-MM-DD") %>]]

Issue 2
<%* if (tp.date.now("M-D") == "1-1") { %>
**Make Yearly Note**
<%* } _%>
<%* if (tp.date.now("D") == 1) { %>
**Make Monthly Note**
<%* } _%>
<%* if (tp.date.now("ddd") == "Sun") { %>
**Make Weekly Note**
<%* } _%>
<% tp.file.cursor(0) %>

**Comment by Zachatoo** [comment]
Seems to be working fine for me.

https://github.com/SilentVoid13/Templater/assets/6936914/6b16e46b-ce3b-4d45-a966-4976a72de93a

I need more information.

1. How are you triggering the template? With another plugin, such as daily notes/calendar? With a Templater command (if so, which command)? With folder templates?
2. What is the title of your note when you try to trigger this template code? Your first issue code requires that the format of the note must match the `YYYY-MM-DD` format to work correctly.
3. Are there any errors in the dev console? To check for errors, first open the developer tools by pressing <kbd>Ctrl</kbd><kbd>Shift</kbd><kbd>I</kbd> on Windows/Linux or <kbd>Cmd</kbd><kbd>Opt</kbd><kbd>I</kbd> on macOS, and then go to the "Console" tab.

**Comment by Zachatoo** [comment]
Do you have the "Trigger Templater on new file creation" Templater setting turned on? You have to have that setting turned on for the Daily Notes plugin to trigger Templater.

![image](https://github.com/SilentVoid13/Templater/assets/6936914/984856c7-bfc5-48fb-a540-b03d8341db0e)

**Comment by Zachatoo** [comment]
Happy to help!

That setting basically tries to run Templater code anytime a new file is created, if that new file has Templater code in it.

If you want to trigger Templater code manually, you can use one of the Templater commands from the command palette (<kbd>Ctrl</kbd><kbd>P</kbd> or <kbd>Cmd</kbd><kbd>P</kbd> is the default hotkey). Each one works differently, it depends on if you want to create a new file from a template, replace template code in the active file, or insert a template into the current file and execute it.

![image](https://github.com/SilentVoid13/Templater/assets/6936914/18f1b603-c02a-4c52-a736-0adf82b0cf72)

**Comment by Zachatoo** [comment]
GitHub sponsors and [ko-fi](https://ko-fi.com/zachatoo) are what I have setup at the moment. Much appreciated!
