### ISSUE TITLE
UserTemplateParser.ts on Windows - PowerShell

### ISSUE THREAD

**Issue by luckman212** [SilentVoid13/Templater#129]
Not using Windows as my daily driver but #128 had me down a rabbit hole for a bit.

I wonder if https://stackoverflow.com/a/61219838/617864 is relevant? Is there a way to detect what platform we're on and adjust the shell that `child_process` spawns accordingly? Seems like it's `/bin/sh` on Linux/Mac and `cmd.exe` on Windows - so user templates that want to use the benefits of PowerShell end up needing to start with `powershell -command...`

**Comment by SilentVoid13** [comment]
Hey @luckman212, Windows users can specify their default shell with the `ComSpec` environment variable.
This is what `child_process` will use by default. Check this https://nodejs.org/api/child_process.html#child_process_default_windows_shell for more infos. Users can pass the `ComSpec` variable to override the default one. I could add some documentation for this
I don't want to hardcode a default shell for a specific platform, because it could break some users configs, and I don't want to restrict anyone.

**Comment by luckman212** [comment]
@SilentVoid13 great, I did not know that. Perfect!

**Comment by luckman212** [comment]
@SilentVoid13 I tried this but could not get it to work, have you tested it?

e.g. I am passing this:
```
<% tp.user.foo({ComSpec: 'C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe', myTest: 'Hello'}) %>
```
to a user function:
```
Write-Host -NoNewLine ('comspec = ' + $Env:myTest)
```

But it generates an error.

Manually setting the `ComSpec` env var from Windows itself (system > advanced properties) *does* work, but this is not recommended.

**Comment by SilentVoid13** [comment]
@luckman212 Hmm you're right, should have tested it. `child_process` actually reads it from the `process.env`, not the `env` argument.
How about a setting in Templater to specify a default shell (full path to the binary) ? That way you can set it to `powershell` on Windows, `zsh` on Linux, ...

**Comment by luckman212** [comment]
@SilentVoid13 That's awesome. If you want to make it a bit "dummy proof" I suggest a dropdown menu with these choices (I think leaving a wide-open field _could_ be dangerous and possibly more of a security hole)

- /bin/sh
- /bin/bash
- /bin/zsh
- C:\Windows\system32\cmd.exe
- C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe

**Comment by SilentVoid13** [comment]
@luckman212 I'm not sure it would be such a security hole, how is it different from running an arbitrary system command in the user functions ?
And it might be painful to list all possible shells on every platform: bash, zsh, fish, the 7 versions of powershell, possibly windows terminal, ...
I'm willing to do it if you really think this could pose a problem, but technically, it would require physical access to modify this setting (or another malicious plugin, but that's something else), do you have another example ?

**Comment by luckman212** [comment]
I see your point. Agree it could be a pain to maintain a list of all the different shells. You're right, the user can always shoot themselves in the foot with a misplaced quote, space, comma etc.

The only real gotchas (well, they got me at least) is when to use `"/path/to"` vs `"\path\to"` vs `"\\path\\to"` when specifying paths on Windows... so maybe at least a note in the docs about how to properly enter the pathname.

**Comment by SilentVoid13** [comment]
Alright, I'll add something to warn people in the description of the setting, thanks for the feedback!

**Comment by luckman212** [comment]
This is really great, working as expected
Big thank you @SilentVoid13 👍
