### ISSUE TITLE
Templater resets active document position, if it needs to render a document in the background

### ISSUE THREAD

**Issue by stoilis** [SilentVoid13/Templater#1297]
**Plugin information:**
-   OS: MacOS Sonoma 14.2.1
-   Templater version: 2.1.0
-   Obsidian version: 1.5.3
-   Templater settings: Folder Templates

**Describe the bug**
When all of the following are true:
- I enable the use of Folder Templates
- I have a template associated to a specific folder
- Some outside process creates a blank file on that folder(which means Templater needs to render it)

then the following happens: The cursor in the current active document jumps to the top of the document. If I am currently writing something, the cursors unexpectedly "resets" to the top.
Note: The active document is any other document in the vault. It's not related to either the template, the folder or the newly created document.

**Expected behavior**
I would expect the cursor to remain in its current position

**Screenshots**
Probably not going to be helpful here. I could produce a screen capture video, if that's helpful.

**Additional context**
This bug may not look like much and I'll be the first to admit it's an edge case. But the automatic document creation I am using runs every 1 minute, making this issue particularly annoying.
I'd be curious to see if there is any better way of running Templater in the background that doesn't trigger this issue.

**Comment by Zachatoo** [comment]
Thanks for the report! I've got a fix on the way in the next release!

**Comment by stoilis** [comment]
I've upgraded to the latest version and it's happening.

Uploading Screen Recording 2024-01-23 at 20.09.59.mov…

In this video I start by showing the version of both Obsidian and Templater.
Then I initiate a command line to create a file after 5 seconds and then I move to start writing on a different document.
Notice how when the file created, the focus of my cursor moves to the top of the page.
