### ISSUE TITLE
Creating a daily note by clicking a link doesn't trigger Templater

### ISSUE THREAD

**Issue by razetdinov** [SilentVoid13/Templater#1298]
**Plugin information (please complete the following information):**

-   OS: macOS Sonoma 14.2
-   Templater version: 1.18.3
-   Obsidian version: 1.5.3
-   Templater settings: [e.g. Template folder location: "Templates/", Timeout: "5" (add the templates not working with their associated command)]

**Describe the bug**
Clicking a link to a non-existent daily note (e.g. _Tomorrow_ link) creates an empty page not triggering Templater with the daily notes template.

**Expected behavior**
Clicking a link creates a page with the daily notes template.

**Comment by Zachatoo** [comment]
Do you have the `Trigger Templater on new file creation` Templater setting toggled on, as well as folder templates setup for your daily notes folder?

**Comment by razetdinov** [comment]
1. Yes. Click the Daily note button or a date in the calendar triggers the Daily note template as expected.
2. Templater doesn't allow setting up a template for the Daily folder:
<img width="317" alt="image" src="https://github.com/SilentVoid13/Templater/assets/2121838/5231449d-0df8-4d3d-8942-e6a64b476905">

**Comment by I-Pch** [comment]
> 2\. Templater doesn't allow setting up a template for the Daily folder:

Hmm 🤔 ... 

I've tested, using the Daily Note core plugin and associating the same template used by the Daily Note core plugin to the `Daily Notes` folder in Templater but I don't get any error 🤔 ...

This is the settings of the Daily Note Core plugin: 
<img width="826" alt="Daily Note Core plugin settings" src="https://github.com/SilentVoid13/Templater/assets/77828085/51d66443-b4dc-4498-a5fd-7b7c3c373c64">

This is the settings regarding "Folder Templates" in Templater: 
<img width="826" alt="Templater Folder Templates - Daily Notes" src="https://github.com/SilentVoid13/Templater/assets/77828085/c8ec8842-bfaa-437c-93e0-f34569625f18">

(I know it's not really visible in the screenshots 😅... but both uses `Meta/Templates/Today's daily note.md` as template)

When you say this though: 
> Clicking a link to a non-existent daily note (e.g. _Tomorrow_ link)

What does your "`Tomorrow`" link looks like ?

I mean, do you use just something like: 
```markdown
[[2024-01-19|Tomorrow]]
```
Which when clicked will only create a note titled `2024-01-19` in the folder you set as `Default location for new notes` in Obsidian's settings

or something like : 
```markdown
[[Daily Notes/2024/01 Jan/2024-01-19|Tomorrow]]
```
Which when clicked in a note will create a note titled `2024-01-19` in the nested folder `01 Jan` following the path in the link (`Daily Notes` > `2024` > `01 Jan` > `2024-01-19.md`) and, from my side of the screen, trigger the concerned Daily Notes template 🤷‍♀️  .

**Comment by Zachatoo** [comment]
I have a folder template setup for my daily notes folder. Do you already have a folder template setup for your daily notes folder, as that error message is suggesting?

**Comment by razetdinov** [comment]
Thank you all, I managed to fix the bug with the following steps:

1. Empty `Daily Note Template` setting of Period Notes plugin (which I use instead of Daily Notes).
2. Add Templater setting for `Daily` folder template. The setting applied correctly without the error mentioned above.
