### ISSUE TITLE
{{ }} not required in template document?

### ISSUE THREAD

**Issue by Robert-Forrest** [SilentVoid13/Templater#13]
When I include the parentheses {{ }} around a template name in the template document, the filled-in template still contains the {{ }} but with the actual value of the template inside, e.g.

{{tp_today}} becomes {{2020-11-06}}

If I instead just put tp_today in the template document, not wrapped in curly braces, this works fine and renders as 2020-11-06.

This also happens for user-defined templates.

Unsure if this is the intended behaviour? I'm running Windows 10 with Templater 0.4.2 and Obsidian 0.9.15
Thanks!

**Comment by SilentVoid13** [comment]
Hello @Robert-Forrest, that issue seems weird, i'm not able to reproduce it.
I'm testing on a fresh new vault with version 0.4.2 and obsidian 0.9.15 as well.
I'm running Linux, but I tried on a Windows VM and couldn't reproduce this bug either.
You're the first one having this issue, and this seems like a problem with your machine, or your obsidian app.
Try restarting obsidian and try disabling / re-enabling Templater.
If this doesn't work, try uninstalling Templater and re-installing it.
Tell me how this goes.

**Comment by Robert-Forrest** [comment]
I have now disabled+enabled the extension, restarted obsidian, and re-installed the extension, and the issue persists in all cases.

After some more consideration problems only seem to arise when I have user-defined templates.

The {{ }} are only present when a template is applied when they contain a user-defined template, e.g. {{tp_yesterday}} renders properly as 2020-11-19, but if I define a user template "today" as "powershell (Get-Date -UFormat '%A, %d %B %Y')", applying the template with {{today}} gives {{Friday, 20 November 2020}}.

Also, while having the user-defined "today" template, if I try to use the internal template {{tp_today}}, applying the template to a document produces {{tp_Friday, 20 November 2020}}. It seems that wherever the text containing the name of a user-defined template is found, that template is inserted - If I define a template just called "a" with the same formula as the "today" template above, and apply it to a document containing just the string "the cat sat on the mat", the document produced is: 

"The cFriday, 20 November 2020t sFriday, 20 November 2020t on the mFriday, 20 November 2020t"

I hope that this is useful info, if there are any more details about my environment that would be helpful let me know.

Thanks for this extension by the way, its much more useful than the core template functionality!

**Comment by SilentVoid13** [comment]
Oh, okay ! Sorry, I misunderstood your initial question.

The curly braces are only necessary for internal templates, so stuff like `{{tp_today}}`.
This is to recognize them and to avoid conflicts with user defined templates.

For user defined templates, you set whatever template keyword you want, like you experienced with the letter `a`. You could also define a template like so: `[[today]]`. This is up to you. Curly braces `{{ }}` are not added nor imposed to user template keywords.

Maybe the README is a bit confusing about this ?

**Comment by Robert-Forrest** [comment]
Ah! I see, I understand now - On reading the README again this has become clear, this was just down to me not grasping the way the template names worked properly. 

Thanks for your help!
