### ISSUE TITLE
lagged/advanced tp.date.now based on tp.file.title not parsing properly

### ISSUE THREAD

**Issue by TSSlade** [SilentVoid13/Templater#130]
**Plugin informations (please complete the following information):**
 - OS: Windows 10
 - Templater version: 1.5.4
 - Obsidian version: 0.11.13
 - Templater settings: "_templates/", Timeout: "5"

**Describe the bug**
Commands involving `tp.file.title` do not seem to parse properly.

**Expected behavior**
Given the input
+ `[[<% tp.date.now("YYYY-MM-DD", -1, tp.file.title, "YYYY-MM-DD") %> | << Yesterday]] | [[<% tp.date.now("YYYY-MM-DD", 1, tp.file.title, "YYYY-MM-DD") %>| Tomorrow >>]]`

and a file with the name e.g. `2021-04-19`, I expect  to have
+ `[[2021-04-18 | << Yesterday]] | [[2021-04-21| Tomorrow >>]]`

**Screenshots**
![image](https://user-images.githubusercontent.com/3211478/115316720-c0ca8f00-a12e-11eb-95ed-c110bd004987.png)

The console log is as follows:
![image](https://user-images.githubusercontent.com/3211478/115316786-e061b780-a12e-11eb-81c2-3ace32179b19.png)

**Comment by luckman212** [comment]
@TSSlade I'm using a very similar trick for my daily notes to add navigation links to the top. It's working for me.

I think maybe you're missing the offset parameter in the `tp.date.now()` on the 3rd line after your "## Meetings" header? Maybe that's causing the parsing error?

**Comment by TSSlade** [comment]
...yuuuuuuuup. You got it, @luckman212 . I'm a yutz. Thanks for sorting me out!

For my own future reference, is there a way to figure out from the console logs which specific line(s) might be throwing off the parser?
