### ISSUE TITLE
Support changing file extensions

### ISSUE THREAD

**Issue by sawft99** [SilentVoid13/Templater#1300]
**Is your feature request related to a problem?**

While using the plugin "Dataloom", I am attempting to create a template for it. When I make a template and then insert it into a page, it works fine as far as the text being inserted. All I need to do it rename the file to have the ".loom" extension and it then works properly.

**Describe the solution you'd like**

It would be great if Templater could support changing file extension as well so that I don't have to manually do so

**Describe alternatives you've considered**

I know of no other plugins that work as well as templater. Perhaps a user script could be created to fill this need, but I'm no developer, and I think other people could find a use for it too given my scenario with another popular plugin.

**Comment by Zachatoo** [comment]
I would like to suggest an alternative solution. You could create a new file from a template, and Templater could use the same extension for the newly created file as the extension from the template.

Would that also fit your use case? Or do you explicitly need to be able to insert content into an existing markdown file and convert that markdown file to a `.loom` file? Just feels like we could skip a step by creating the file with the desired extension in the first place.

**Comment by sawft99** [comment]
> I would like to suggest an alternative solution. You could create a new file from a template, and Templater could use the same extension for the newly created file as the extension from the template.
> 
> Would that also fit your use case? Or do you explicitly need to be able to insert content into an existing markdown file and convert that markdown file to a `.loom` file? Just feels like we could skip a step by creating the file with the desired extension in the first place.

What would that look like? `tp.file.create_new` doesn't look like it creates files with different extensions. and the `tp.file.rename` function can't rename to a different extension. The loom file isn't markdown but it is plain text essentially. Creating the loom file directly would be preferred rather than any kind of conversion step.

**Comment by Zachatoo** [comment]
You'd have a template file with a `.loom` extension. When using the `Create new note from template` command, instead of always making a markdown file, it would use whatever extension your template file has. Same concept would apply for `tp.file.create_new` if you pass it a TFile (see [docs](https://silentvoid13.github.io/Templater/internal-functions/internal-modules/file-module.html#tpfilecreate_newtemplate-tfile--string-filename-string-open_new-boolean--false-folder-tfolder)), it would use whatever extension that file has.

**Comment by sawft99** [comment]
> You'd have a template file with a `.loom` extension. When using the `Create new note from template` command, instead of always making a markdown file, it would use whatever extension your template file has. Same concept would apply for `tp.file.create_new` if you pass it a TFile (see [docs](https://silentvoid13.github.io/Templater/internal-functions/internal-modules/file-module.html#tpfilecreate_newtemplate-tfile--string-filename-string-open_new-boolean--false-folder-tfolder)), it would use whatever extension that file has.

Oh ok. so would it look something like `tp.file.find_tfile(Template.loom)`?

**Comment by sawft99** [comment]
Ok great thank you.
