### ISSUE TITLE
[mobile bug] unable to move to new line in multiline prompt

### ISSUE THREAD

**Issue by deathblade666** [SilentVoid13/Templater#1303]
**Plugin information (please complete the following information):**

-   OS: [e.g. Windows 10] android latest beta (as of 1/21/2024)
-   Templater version: [e.g. 0.3.4] 1.18.4
-   Obsidian version: [e.g. 0.9.11] 1.4.16
-   Templater settings: [e.g. Template folder location: "Templates/", Timeout: "5" (add the templates not working with their associated command)]

**Describe the bug**
When using a multiline prompt (I.e. tp.system.prompt("prompt", null, false, true) on mobile there is no way to move to a new line enter. One would assume pressing enter would do it but enter does nothing currently.

**Expected behavior**
When pressing enter the cursor should move to a new line in a mutliline prompt

**Screenshots**

**Additional context**

**Comment by Zachatoo** [comment]
Fixed in 2.1.2, thanks for the report!
