### ISSUE TITLE
Android creates new untitled file every time I run Templater

### ISSUE THREAD

**Issue by snovis** [SilentVoid13/Templater#1304]
**Plugin information (please complete the following information):**

-   OS: Android 14
-   Templater version: 1.18.3
-   Obsidian version: 1.4.16
-   Templater settings: folder /templater all other settings are default.

**Describe the bug**
When I run ANY templater macro, Obsidian creates a new untitled file and renders the output into the newly created file.  

**Expected behavior**
Templater would would NOT create a new **untitled** file. It would render the output into the current file.

**Screenshots**
I'm not skilled enough yet on Android to do this.

**Additional context**
My macros work on all other platforms.  I got a Galaxy Z-Fold for work and thought I would install Obsidian on it because of the wider screen. I rely heavily on Templater for my workflow and was shocked to find my most used macro had this behavior. After some debugging and searching I found ANY and ALL macros do this, not just my advanced ones (file creation with link generation and a template).

**Comment by Zachatoo** [comment]
Which Templater command are you using? Depending on which command you use, this is expected. For example the "Templater: Create new note from template" command will create a new note and apply the template to the note.

**Comment by SamH765** [comment]
I'm experiencing this issue as well on Mac. When I run templater for templates I have been using, it removes the template from my templates folder, and renames the file to "untitled."

**Comment by Zachatoo** [comment]
Marking as removed due to no response from issue author.
