### ISSUE TITLE
Creating a new file in a Templated Folder wipes current active document

### ISSUE THREAD

**Issue by stoilis** [SilentVoid13/Templater#1305]
This bug was introduced after this one was fixed:
https://github.com/SilentVoid13/Templater/issues/1297

**Plugin information (please complete the following information):**
-   OS: 14.2.1
-   Templater version: 2.1.1
-   Obsidian version: 1.5.3

**Describe the bug**
If you have a folder Templates enabled, and an external process creates a new file in them, then Templates will apply the associated template to the current open and active document instead.

**Expected behavior**
The template should be applied only to the newly created file in the Folder Templates.

**Screenshots**
N/A

**Additional context**
This bug was introduced after this one was fixed:
https://github.com/SilentVoid13/Templater/issues/1297

If I have to choose, I prefer bringing the old behaviour back!

**Comment by Zachatoo** [comment]
I can't reproduce, are there any other details you can provide? What is your template?

https://github.com/SilentVoid13/Templater/assets/6936914/5f86dbd4-8970-4833-b3dc-5bf2759f3bbb

**Comment by stoilis** [comment]
You are right, my bad.

My template had, among other things, some javascript which I missed:
`var file = app.workspace.getActiveFile();`

As a result, when the new file was created, my template actually applied to the current active file.

I have tested your plugin in isolation and it doesn't seem to be misbehaving at all.

Thank you for your time and I apologise for the incorrect bug.
