### ISSUE TITLE
File last modified date

### ISSUE THREAD

**Issue by ih8snow** [SilentVoid13/Templater#131]
Hi,

when I use `<% tp.file.last_modified_date("dddd Do MMMM YYYY HH:mm:ss") %>`
is this only a "one-time" read of the date or is there any update when I reopen the file?

In my vault I see only a new date when I insert a new template in this file".

When I save the file some minutes later, this date/time is till the same.

Thanks for your help!

Jörn

**Comment by SilentVoid13** [comment]
Hey @ih8snow this is a one time read, the command just gets replaced and that's it.
That being said, I'm working on "dynamic" templates that would get triggered when entering preview mode (not in editing mode).
Could that be what you're looking for ?

**Comment by ih8snow** [comment]
Hi,

yes, dynamic would be cool. I would use it in the metadata of the notes where I collect tags, linked topic.
So creation date and modified date would be a nice fit to that.

**Comment by SilentVoid13** [comment]
Hey @ih8snow, you can now use Dynamic commands.

In your use case, this would give:

```
<%+ tp.file.last_modified_date("dddd Do MMMM YYYY HH:mm:ss") %>
```

Documentation at https://silentvoid13.github.io/Templater/docs/commands/dynamic-command

**Comment by mrienstra** [comment]
New doc URL: https://silentvoid13.github.io/Templater/commands/dynamic-command
