### ISSUE TITLE
`;` at end of interpolation command throws an error

### ISSUE THREAD

**Issue by stracker-phil** [SilentVoid13/Templater#1317]
## Plugin information

-   OS: macOS 14.3 
-   Templater version: 2.1.3
-   Obsidian version: 1.5.3
-   Templater settings: 
    - Template folder location: `"_Template/"`
    - Syntax Highlight Desktop: ON
    - Syntax Highlight Mobile: OFF
    - Automatic jump to cursor: OFF
    - Trigger on file creation: OFF
    - Show icon in sidebar: ON
    - Hotkeys: NONE
    - Startup tempaltes: NONE
    - User script functions: NONE
    - Enable user system functions: OFF

## Bug
When using the `tp.file.include()` function, the template fails with an error.

**Error message:**
```
Templater Error: Template parsing error, aborting. 
 Template syntax error: missing ) after argument list
```

### Test case

I created a new Vault that only has Templater installed, all other settings are Obsidian defaults.
The Vault includes 3 files:

**File 1: _Template/Article.md**
```
# <% tp.file.title %>
```

**File 2: _Template/Test.md**
```
<% tp.file.include('[[Article]]'); %>
```
(I've also tried using `"` instead of `'`, adding/removing the `;`, but nothing works)

**File 3: Untitled**
(no content)

**Checks:**
In "Untitled" I try to include both templates.

1. Including "Article" template: Works. The file title is inserted ✅ 
2. Including "Test" template: An error is thrown ❌ 

## Screenshots
<img width="1024" alt="2024-02-09_03-18-28" src="https://github.com/SilentVoid13/Templater/assets/2669200/a4b6ac55-c494-4894-b122-8c5de004995b">

**Video:**
https://github.com/SilentVoid13/Templater/assets/2669200/16bdaf31-cdb9-4cdc-828b-ed21f96b61b2

**Comment by stracker-phil** [comment]
Hm, I found a workaround for the issue, I do not know why it works, though:

```js
<%* const res = tp.file.include( '[[Article]]' ); -%>
<% res %>
```

This correctly renders the included template in the current note

**Comment by Zachatoo** [comment]
You can also do this.

```js
<% tp.file.include('[[Article]]') %>
```

It appears that the `;` in an [interpolation command](https://silentvoid13.github.io/Templater/commands/overview.html) doesn't work. Same error message shows if I do this in the `Article.md` template:

```js
# <% tp.file.title; %>
```

So this doesn't really have anything to do with `tp.file.include()`, rather the use of `;` in interpolation commands. You can only use them in execution commands.

**Comment by stracker-phil** [comment]
Wow, I was so focused on the `.include()` function that I did not think about this being a general syntax issue.

Thanks for clarifying, with that change, the template works!

An idea: Maybe it's possible to trim the trailing `;` from the interpolation string before passing it to rusty for parsing. But that's a nice-to-have, and I'm not even sure if you can do this, or if that's part of rusty's internal logic.
