### ISSUE TITLE
Search boxes in config freeze UI

### ISSUE THREAD

**Issue by tsbertalan** [SilentVoid13/Templater#1319]
**Plugin information (please complete the following information):**
-   OS: Windows 10
-   Templater version: 2.1.3
-   Obsidian version: 1.5.3

**Describe the bug**

1. Open a vault with *many* files/directories.
2. Open preferences (ctrl+, on Windows/Linux).
3. Navigate to a preference page that includes the search box with a little magnifying glass inside, to find a path in the vault (e.g. the "Script files folder location").

**Expected behavior**
The UI should not hang, and slow search or autocomplete in the box should not prevent typing (and ideally should give some visual indication that search is happening)

**Additional context**
I have a few hundred thousand files/folders in my vault.

This may or may not be a Templater-specific problem, but similar search boxes on other preferences pages (e.g. "New file location" in the core "Daily notes" plugin) seem to be a simpler widget without the magnifying glass icon, although still with autocomplete.

**Comment by Zachatoo** [comment]
Should be fixed in 2.3.2!
