### ISSUE TITLE
How to escape characters within the reference_format argument?

### ISSUE THREAD

**Issue by johnkferguson** [SilentVoid13/Templater#132]
Hi,

I recently updated to the latest version of Templater and I am having a tough time figuring out how to get some of my weekday related functions to work properly.

In earlier versions of Templater, in my weekly note, I referred to each of the week's notes using this structure: `[[{{monday:YYYY-MM-DD}}]]`.

My weekly note is titled using the format `gggg-[W]ww`. This leads to a note with a title like "2021-W16".

I'm not sure how to properly escape the 'W' character in the `reference_format` argument when trying to embed a link to the daily notes for the week.

I've tried a couple options like the following:

```
[[<% tp.date.weekday("YYYY-MM-DD", 0, tp.file.title, "gggg-Www") %>]]

[[<% tp.date.weekday("YYYY-MM-DD", 0, tp.file.title, "gggg-\[W\]ww") %>]]

[[<% tp.date.weekday("YYYY-MM-DD", 0, tp.file.title, `${gggg}-W${ww}`) %>]]
```

but all raise console errors.

What would be the proper format to reference a daily note from within my weekly note?

Thanks a lot.

**Comment by SilentVoid13** [comment]
Hey @johnkferguson, the answer is in your question :smile: 

The correct format would be `gggg-[W]ww` which would give the following command: `<% tp.date.weekday("YYYY-MM-DD", 0, tp.file.title, "gggg-[W]ww") %>`

Tell me if this works now.

**Comment by johnkferguson** [comment]
Haha, you're right, that works.

I had some other broken template functions at the bottom of my weekly template and I didn't realize that they were the ones causing the template error. Oops.

Thanks again for the super quick response. 😄
