### ISSUE TITLE
Error generating daily quote

### ISSUE THREAD

**Issue by icedany36** [SilentVoid13/Templater#1320]
**Plugin information (please complete the following information):**

-   OS: Linux
-   Templater version: 2.1.3
-   Obsidian version: 1.5.3

**Describe the bug**
When I 'replace templates in the active file' for a quote (<% tp.web.daily_quote() %>) it gives me a message with 'Error generating daily quote'

**Expected behavior**
It is expected that instead of the error it should give me a random quote

**Comment by MaryseBucking** [comment]
Same here. I get the following error in the console log:
plugin:templater-obsidian:2596     GET https://api.quotable.io/random net::ERR_CERT_DATE_INVALID

**Comment by tomatau** [comment]
Just started happening for me yesterday

**Comment by Zachatoo** [comment]
Thanks. The quotable API is down again, same as last month, see https://github.com/lukePeavey/quotable/issues/204

**Comment by Zachatoo** [comment]
Hopefully they'll implement automatic renewals soon instead of relying on manual renewals
https://github.com/lukePeavey/quotable/issues/210

**Comment by Zachatoo** [comment]
Resolved since the quotable API is now up, at least in the US, should be up globally within a few hours.
