### ISSUE TITLE
Composite add template

### ISSUE THREAD

**Issue by ParadiseFallen** [SilentVoid13/Templater#1322]
**Is your feature request related to a problem? Please describe.** 
I want to see multiple prompts in single modal.
So i can easilly type what i need and navigate it with tab / shift + tab to fill areas, 

**Describe the solution you'd like**
make some api that will allow to access context of template and api that will allow group prompts
```js
tp.???.requestData((grpup)=>{
  group.textField('key','title','defaultValue', /*etc*/)
  // ... etc
});
```
```js
tp.context.key // to retrive value
```

**Comment by ParadiseFallen** [comment]
it also can be kinda 
```js
group['key'].textField(...)
```

**Comment by Zachatoo** [comment]
The [Form Modal](https://github.com/danielo515/obsidian-modal-form) plugin already solves this issue and works great with Templater. No need for Templater to re-invent the wheel.

**Comment by ParadiseFallen** [comment]
Solved with FormModal plugin
