### ISSUE TITLE
tp.file.create_new() doesn't create missing sub-folders anymore

### ISSUE THREAD

**Issue by holroy** [SilentVoid13/Templater#1327]
**Plugin information (please complete the following information):**

-   OS:Mac 10.14.6
-   Templater version: 2.2.1
-   Obsidian version: 1.5.3

**Describe the bug**

It seems like this commit,  368e511,  breaks a very useful side effect of the `tp.file.create_new` to create sub-folders directly when needed. 

**Expected behavior**
Two use cases:
- When I'm creating a new forum related folder, I want this to appear in a folder like `ForumStuff/f77/f77279/f77279 my file.md`, and I use a call like `await tp.file.create_new("My string content", "f77/f77279/f77279 my file", true, app.vault.getAbstractFileByPath("ForumStuff")`. This has in earlier version created either the `f77` and/or `f77279` if needed
- A similar case happens when wanting to create a file like: `journal/YYYY/MM/YYYY-MM-DD.md`, where a typical way to call this would be: `await tp.file.create_new(dailyTemplate, "2024/02/2024-02-21", true, app.vault.getAbstractFileByPath("journal")`

In both of these cases in previous versions it would create all the needed folders, _as long as_ the main folder in `getAbstractFileByPath()` existed. 

**Screenshots**
![image](https://github.com/SilentVoid13/Templater/assets/11348165/f52834d0-027c-49d1-af60-23243f562824)

**Additional context**
I experienced this immediately after upgrading to 2.2.1, but I'm not quite sure on which version I updated from, but when I used git blame, this seems like a very candidate to introduce this change in behavior.

**Comment by Zachatoo** [comment]
I didn't realize `tp.file.create_new` did this, very cool!

I'll add some code to do this, it should be fairly simple to recursively create the folders.

**Comment by holroy** [comment]
I've not looked into what you changed, but it did for sure do this beforehand, and I've grown accustomed to using it. Both within Templater, and when creating daily journals.

**Comment by Zachatoo** [comment]
Should be fixed in 2.2.2, thanks for the report!
