### ISSUE TITLE
JS Parse Error

### ISSUE THREAD

**Issue by Quorafind** [SilentVoid13/Templater#133]
**Plugin informations (please complete the following information):**
 - OS: Windows 10
 - Templater version: 1.5.4
 - Obsidian version: 0.12.0
 - Templater settings: Template folder location: "Template/", Timeout: "5" 

**Describe the bug**
Using code:
```js
<%*
//'first' will add to top of file. 'last' will add to bottom of file
let firstOrLastLine = 'first';
let curDateFormat = '[' + '[' + tp.date.now("YYYY-MM-DD") + ']]';
let finalTimestamp = curDateFormat;
let curTimeFormat = tp.date.now("hh:mm A");
if(curTimeFormat != ''){finalTimestamp = finalTimestamp + ' ' + curTimeFormat}

let qcFolderLocation = this.app.fileManager.getNewFileParent().path;
if(qcFolderLocation != '' && qcFolderLocation != '/'){qcFolderLocation = qcFolderLocation + '/'}
if(qcFolderLocation == '/'){qcFolderLocation = ''}
let qcFilePath = qcFolderLocation + 'Quick Capture' + '.md';
let qcFile = this.app.vault.getAbstractFileByPath(qcFilePath);
if(!qcFile) {
    await this.app.fileManager.createNewMarkdownFile(this.app.fileManager.getNewFileParent(), 'Quick Capture')
    qcFile = this.app.vault.getAbstractFileByPath(qcFilePath);
}

if(qcFile) {
    let qcNote = await tp.system.prompt("Enter a Quick Capture note");
    let isTodo = qcNote.startsWith(';');
    let finalNote = (isTodo ? '\n- [ ] ' : '') + finalTimestamp + ' - ' + (isTodo ? qcNote.substring(1) + '\n' : qcNote);
    let curContent = await this.app.vault.read(qcFile);
    let newContents;
    if(firstOrLastLine == 'last'){newContents = curContent + '\n' + finalNote}else{newContents = finalNote + '\n' + curContent}
    this.app.vault.modify(qcFile, newContents);
}
%>
```
Console:  `Template parsing error, aborting. TypeError: Cannot read property 'lastIndexOf' of undefined`

And then output the whole text of the template without any output.

**Expected behavior**
https://discord.com/channels/686053708261228577/707816848615407697/834603726727413800

**Screenshots**
None

**Additional context**
None

**Comment by SilentVoid13** [comment]
Hey @Quorafind sorry for the late response, is it fixed if you use the latest version of Murf's script? You can find it here: https://gist.github.com/GitMurf/817a6c9e73e1d1e312fc1a1735edb8d6

**Comment by Quorafind** [comment]
Let me try it! @SilentVoid13  Thanks, if it works, I will close the issue soon

**Comment by SilentVoid13** [comment]
@Quorafind any updates ? Should I close this ?
