### ISSUE TITLE
Add merge support for Frontmatter

### ISSUE THREAD

**Issue by jettil** [SilentVoid13/Templater#1330]
**Is your feature request related to a problem? Please describe.** A clear and
concise description of what the problem is. Ex. I'm always frustrated when [...]
I use a couple of notes as "endless" notes. For Example, at regular Meetings, I have one Note for the Meeting Series (Project Meeting XY) with a couple of Tags and other Frontmatter (including date (which I use for every meeting). I have a header for each time, I had this meeting. For example, # 29/02/2024 and so on. I want to use a templater Template that easily adds a new header, changes the date frontmatter to today date etc. This is possible with the core Plugin, but not with the templater Plugin. The Templater Plugin only adds a horizontal rule at the moment.

**Describe the solution you'd like**
Add a method, that allows you to add and set a specific frontmatter. It could be like tp.frontmatter.set(Frontmattername, newValue, Append=False) or something like that

Thanks for the great Plugin, btw!

**Comment by Zachatoo** [comment]
You're in luck, this is already possible! There's an example in the documentation [here](https://silentvoid13.github.io/Templater/internal-functions/internal-modules/hooks-module.html#examples).

**Comment by jettil** [comment]
Ah great, completly overlooked that sorry.
Thanks a lot
