### ISSUE TITLE
Incorrect Placement of Examples for tp.file.content in Documentation @ silentvoid13.github.io

### ISSUE THREAD

**Issue by abstarstrong** [SilentVoid13/Templater#1346]
**This is an issue with the documentation written at silentvoid13.github.io** 

The examples for `tp.file.content` are misplaced in the documentation. They should be moved to the section where `tp.file.content` is actually explained.

**Plugin information (please complete the following information):**

-   OS: N/A
-   Templater version: N/A
-   Obsidian version: N/A
-   Templater settings: N/A

**Describe the bug**
The examples for tp.file.content are not correctly placed within the documentation.

**Expected behavior**
The examples for tp.file.content should be located within the section that explains the functionality and usage of tp.file.content.

**Screenshots**
N/A

**Additional context**
The documentation needs to be revised to ensure that examples are placed in the appropriate sections to enhance clarity and usability for users referencing the documentation.

**Comment by Zachatoo** [comment]
Can you clarify where the examples for `tp.file.content` currently are and why it is incorrect? I'm seeing examples right under where it is described, see link below.

https://silentvoid13.github.io/Templater/internal-functions/internal-modules/file-module.html#tpfilecontent

**Comment by Zachatoo** [comment]
Marking as removed due to no response.
