### ISSUE TITLE
Plugin fails to load on Android

### ISSUE THREAD

**Issue by garbosz** [SilentVoid13/Templater#1356]
**Plugin information (please complete the following information):**

-   OS: Android 14 (AP1A.240405.002)
-   Templater version: 2.2.3
-   Obsidian version: 1.5.12(134) 
-   Templater settings: [e.g. Template folder location: "Templates/", Timeout: "5" (add the templates not working with their associated command)]

**Describe the bug**
When I try to enable the plugin or when my vault loads I get an error saying obsidian could not load the plugin

**Expected behavior**
To be able to use the plugin on all my devices.

**Screenshots**
![Screenshot_20240420-124251.png](https://github.com/SilentVoid13/Templater/assets/111667522/bf4330ee-bd46-4b25-9595-ab3618335591)

**Additional context**
I'm enrolled in the android 15 public beta but I do not have it installed. It shouldn't cause any issues but maybe there's some extra diagnostics that android does in the background.

**Comment by Zachatoo** [comment]
I can't reproduce on my Android device. Does this happen in a new vault as well, to ensure no other plugins are interfering? Can you get some logs from when the plugin is trying to load? You can get logs in a few ways, the quickest is probably to use the Logstravaganza plugin.

**Comment by Zachatoo** [comment]
Closing due to no response.
