### ISSUE TITLE
Request for adding Chinese language support to Templater templates

### ISSUE THREAD

**Issue by chu610234940** [SilentVoid13/Templater#1358]
Dear developers,

I enjoy using the Templater tool, but I've noticed that it doesn't seem to support Chinese characters. As a Chinese user, I'd like to be able to freely use Chinese characters in my templates to better suit my needs.

In the current version, when attempting to use Chinese characters in a template, it may result in incorrect rendering or other unforeseen issues. This makes it difficult for me to fully utilize Templater's powerful features and adds to my workload.

Therefore, I'd like to request your team to consider adding comprehensive support for Chinese language in Templater. This would enable Chinese users to conveniently use Templater and create and manage their templates more flexibly.

If possible, I suggest clearly indicating in the documentation the level of support Templater offers for Chinese, to help users better understand its capabilities and limitations.

Thank you very much for your attention and support. I look forward to your response and consideration of this feature request.

**Comment by Zachatoo** [comment]
Is this specific to Templater or is this an issue with Obsidian in general? Can you provide more information and examples for how Chinese characters are not compatible with Templater? I don't use Chinese characters so I'm not sure what issues I would need to look out for.

**Comment by Zachatoo** [comment]
Closing due to lack of details.
