### ISSUE TITLE
Create new file from template

### ISSUE THREAD

**Issue by dxcore35** [SilentVoid13/Templater#1361]
### Discussed in https://github.com/SilentVoid13/Templater/discussions/514

<div type='discussions-op-text'>

<sup>Originally posted by **Ampa** April  3, 2021</sup>
At present we can create a new file, and then as a second step insert a template.

Would you consider a new action: Create new from template?

This would carry out both steps as a single action.
</div>

It is 2024 and it still does'nt work.

My settings:

![Screenshot 2024-04-26 at 16 13 22](https://github.com/SilentVoid13/Templater/assets/7279156/c2aea3db-58a2-4e66-8943-5a6383d4a9d8)

When there is no active note in Obsidian and i will trigger the hotkey im getting this:

![Screenshot 2024-04-26 at 16 09 12](https://github.com/SilentVoid13/Templater/assets/7279156/948bc263-b0d0-4bea-982c-95077f5c502c)

And this is the template:

![Screenshot 2024-04-26 at 16 15 18](https://github.com/SilentVoid13/Templater/assets/7279156/9b138580-a645-4cb6-9567-085adf1ded06)

There is no append command in the code!

**Comment by Zachatoo** [comment]
You can achieve the desired result by using [tp.file.create_new](https://silentvoid13.github.io/Templater/internal-functions/internal-modules/file-module.html#tpfilecreate_newtemplate-tfile--string-filename-string-open_new-boolean--false-folder-tfolder) in your template to create a new file.

**Comment by FeralFlora** [comment]
> This would carry out both steps as a single action.

Are you looking for the "Create new note from template" command? Sounds like that's what you need. 

The discussion you linked to is from 2021, and the aforementioned command was implemented shortly thereafter.

**Comment by itribs** [comment]
> > This would carry out both steps as a single action.
> 
> @dxcore35 Are you looking for the "Create new note from template" command? Sounds like that's what you need.
> 
> The discussion you linked to is from 2021, and the aforementioned command was implemented shortly thereafter.

I believe what he means is: When there is no active note, it is not possible to create a new file from a template using hotkey, just like in the screenshot that prompts: "No active editor, can't append templates."， which is also the feature I need.

**Comment by madigan** [comment]
@Zachatoo what would you think of adding a "Sidebar Templates" section in the Templater config which would allow the user to specify a list of templates and icons that they'd like to appear on the sidebar? Each button would create a new note using that template? Maybe the note location as well? It seems like it would be relatively straightforward to make.

**Comment by Zachatoo** [comment]
@madigan I think I'm more leaning towards having two sections for hotkeys, one for "insert" and one for "create". The "create" section would have a folder associated with each template, similar to how folder templates works.

Then if a user wants to put a "create template" button in the ribbon, they could associate a create template command/hotkey with a ribbon icon using another plugin, such as the Commander plugin. I don't think we necessarily need to add that functionality ourselves if it's relatively straightforward to hook everything up with an additional plugin.

**Comment by madigan** [comment]
That's a good point. Would you like two sections for hotkeys or a way to toggle them as insert/update to avoid adding more sections?

I would totally use this, so I can take a stab at it if no one else is and we could play around with the UX.

**Comment by Zachatoo** [comment]
I would probably prefer one hotkeys section, with a toggle for each hotkey to say whether it's an insert or create command. If that ends up feeling weird we can try other approaches.

It's all yours! Happy to help as needed.

**Comment by madigan** [comment]
One thing that occurred to me is that an even easier way to support this would just be to register both "modes" (Create and Insert) as commands even if the user only chooses to use one of them. It'd keep the setup very simple.

**Comment by Zachatoo** [comment]
I like that. The only potential downside is if you use the command palette instead of hotkeys there will be two for each template with no way to remove one of them. I think that is better than adding additional configuration though, the less configuration the average user has to do the better.
