### ISSUE TITLE
Add native AI support

### ISSUE THREAD

**Issue by dxcore35** [SilentVoid13/Templater#1364]
Its time about adding the native AI support for ChatGPT and Ollama.... somebody already started the job https://github.com/TfTHacker/obsidian-ai-templater, but it will be better if this support is in-build inside templater.  The Quickadd plugin already added support long time ago. https://quickadd.obsidian.guide/docs/AIAssistant it will be nice to catchup the game. Just this feature will open 101% more possibilities of Templater

**Comment by Zachatoo** [comment]
I'm not sure I understand what we gain by bringing AI into the Templater codebase. Wouldn't the end result be the same as what we have now? Seems like a lot of effort for little or no impact. There are far more urgent things that I think should be fixed or added in Templater that would have a much bigger impact.

**Comment by FeralFlora** [comment]
> There are far more urgent things that I think should be fixed or added in Templater that would have a much bigger impact.

Agree!

> The Quickadd plugin already added support long time ago.

Yeah, and most of the updates since then have pertained to AI, while issues like this one https://github.com/chhoumann/quickadd/issues/533 persist.
