### ISSUE TITLE
Console error: app.js:1 No file creator assigned to create file with extension com. Falling back to markdown file creator.

### ISSUE THREAD

**Issue by ybalkind** [SilentVoid13/Templater#1372]
**Plugin information (please complete the following information):**

-   OS: Mac OS latest
-   Templater version: 2.24
-   Obsidian version: 1.5.12
-   Templater settings: 

**Describe the bug**
I have a template that triggers on new note creation and prompts me to select a folder and name the file. Thereafter Templater folder templates would kick in and apply the right template. 

When a new note is created I get the following error in console. 

app.js:1 No file creator assigned to create file with extension com. Falling back to markdown file creator.

**Expected behavior**
No error in console

**Screenshots**
![image](https://github.com/SilentVoid13/Templater/assets/10196054/ff3a05ca-5160-46a8-96e6-c062c49e7571)

**Additional context**
I know the error does not reference Templater but seems linked

Template attached 
[Templater new note creation flow.md](https://github.com/SilentVoid13/Templater/files/15244383/Templater.new.note.creation.flow.md)

**Comment by Zachatoo** [comment]
Are you perhaps clicking on a link to create a file, and the link has `.com` at the end of it? For example `[[google.com]]`? If I click on a link like that, I get an error, regardless of if I have Templater enabled or not, so this is not related to Templater. Please provide more details if this is not the scenario you are facing.
