### ISSUE TITLE
Execution of the tp.file.selection() function erase the selection in the note

### ISSUE THREAD

**Issue by OXiOSDev** [SilentVoid13/Templater#1374]
Hello, I hope you can help me.
When I use the tp.file.selection() function, the part of the text that I have selected is deleted from the note in which I selected it.
Thanks for your help

**Plugin information (please complete the following information):**

-   OS: MacOS Sonoma 14.4.1
-   Templater version: 2.3.1
-   Obsidian version: 1.6.0
-   Templater settings: Template folder location: "ZZ-SYSTEM-CONFIGURATION/PLUGINS-CONFIGURATION/TEMPLATES", 

**Describe the bug**
When I Use the tp.file.selection ( ) function the selected text is erased from the note

**Expected behavior**
I'd like to be able to assign the selected text to a constant without deleting the text of the original note.

**Screenshots**
The text from a note
![CleanShot 2024-05-13 at 16 31 18@2x](https://github.com/SilentVoid13/Templater/assets/30770206/d5e99a36-e1c2-49f4-8b24-4d26ba49df7c)
The selected text
![CleanShot 2024-05-13 at 16 31 46@2x](https://github.com/SilentVoid13/Templater/assets/30770206/46cc338e-c728-46aa-9c67-8852d5bea560)
The simplest possible script execute with `Templater: Open Insert Template modal`
![CleanShot 2024-05-13 at 16 32 21@2x](https://github.com/SilentVoid13/Templater/assets/30770206/d5789ed4-a21b-4aad-9ed9-5e091fa63f56)
The note after the execution of the script
![CleanShot 2024-05-13 at 16 35 47@2x](https://github.com/SilentVoid13/Templater/assets/30770206/52c66f15-bd3b-45f1-a9ad-3a8e6a543654)

**Additional context**
I've deactivated all the plugins except templater to test the interactions.

**Comment by Zachatoo** [comment]
This isn't related to `tp.file.selection()`. You can have an empty template file and your selection will be replaced. This is expected behavior.

If you don't want to have your selection removed, then you need to re-add your selection to the note. Here's a few ways to do that.

```
<% tp.file.selection() %>
```
```
<%*
const selectedContent = tp.file.selection();
tR += selectedContent;
%>
```

**Comment by OXiOSDev** [comment]
Thank you very much for your prompt reply
