### ISSUE TITLE
invalid reference date format, try specifying one with reference format 

### ISSUE THREAD

**Issue by AppleElephants** [SilentVoid13/Templater#1382]
I have used templater for 2 years 

but suddenly it has something wrong

![20240522_020926](https://github.com/SilentVoid13/Templater/assets/123480707/5b8e376c-fde4-47ce-b33e-c9037f68d8c2)

I got error like that 

and when I insert templater, it dosent work 

like this

![20240522_011739](https://github.com/SilentVoid13/Templater/assets/123480707/a7237093-8e40-4168-b87f-2813c4c4dbb4)

**Comment by Zachatoo** [comment]
1. Can you please provide your entire template as plain text, not as a screenshot? It makes it way easier to test.
2. Do you have any [user scripts](https://silentvoid13.github.io/Templater/user-functions/script-user-functions.html)? If so, try disabling user scripts, and if it works, then there's a syntax error in one of your user scripts, not your template.

**Comment by Zachatoo** [comment]
Strange, your template works fine for me. My test note is titled `2024-05-21` or `2024-05-21-Tuesday`, following the format of `YYYY-MM-DD` or `YYYY-MM-DD-dddd`, as defined in your template.

Can you try reproducing in the sandbox vault with just Templater installed and this template, in a file matching your date format?
