### ISSUE TITLE
app.fileManager.processFrontMatter doesn't work

### ISSUE THREAD

**Issue by MarioCurie** [SilentVoid13/Templater#1386]
**Plugin information (please complete the following information):**

-   OS: [Windows 10]
-   Templater version: [e.g. 2.3.2]
-   Obsidian version: [e.g. 1.5.12]

**Describe the bug**
The latest version of Templater has a bug that prevents, among other things, to update frontmatter with the command:
await app.fileManager.processFrontMatter(file, (frontmatter) => {...}
About a month ago there was an identical problem with one of the earlier versions, but the next version solved it.

**Comment by Zachatoo** [comment]
Should be fixed in 2.3.3
