### ISSUE TITLE
Applying Text Color in Obsidian Without Unwanted New Lines

### ISSUE THREAD

**Issue by yuzzznh** [SilentVoid13/Templater#1388]
#### Description

I am trying to create a workflow in Obsidian using the Templater extension, where I can select text and apply a specific color to it using a hotkey. However, I am encountering an issue where applying the template results in an unwanted new line after the colored text. I have tried several approaches to solve this, including using JavaScript to manipulate the text, but none have resolved the issue.

#### My Attempts

1. **Basic Template Code**

   ```markdown
   <%*
   const selectedText = tp.file.selection().trim();
   if (selectedText) {
       const color = '#bdd2ea';
       const coloredText = `<span style='color: ${color}'>${selectedText}</span>`;
       tR += coloredText;
   }
   %>
   ```

2. **Attempt to Remove New Line with JavaScript**

   ```markdown
   <%*
   const selectedText = tp.file.selection().trim();
   if (selectedText) {
       const color = '#bdd2ea';
       const coloredText = `<span style='color: ${color}'>${selectedText}</span>`;
       tR += coloredText;
   }
   %>
   <script>
     const editor = this.app.workspace.activeLeaf.view.editor;
     const cursor = editor.getCursor();
     editor.setLine(cursor.line, editor.getLine(cursor.line).replace(/\n$/, ""));
     setTimeout(() => editor.exec('goLineEnd'), 100);
     setTimeout(() => editor.exec('deleteLineRight'), 200);
   </script>
   ```

Despite these attempts, the new line issue persists. Ideally, I would like the colored text to be inserted without any additional new lines.

#### Desired Workflow

1. Select text.
2. Press a hotkey (e.g., Ctrl + Alt + 1).
3. The selected text is wrapped with a span tag with a specific color without any additional new lines.

#### Environment

- **Obsidian Version**: [Last updated March 31, 2024](https://obsidian.md/changelog)
- **Templater Version**: 2.3.3
- **Operating System**: Windows 11

#### Steps to Reproduce

1. Create a template file (e.g., `color-template.md`) with the provided code.
2. Assign a hotkey to the template using Templater settings.
3. Select any text in a note.
4. Press the hotkey to apply the template.

#### Request for Assistance

I am seeking guidance on how to achieve the desired workflow without introducing unwanted new lines. If there are alternative methods or any adjustments that I can make to the template or settings, I would greatly appreciate your advice.

Thank you for your assistance!

**Comment by Zachatoo** [comment]
You'll need to apply [whitespace control](https://silentvoid13.github.io/Templater/commands/whitespace-control.html)

**Comment by yuzzznh** [comment]
Wow that’s amazing! Sorry for disturbing and thank you so much for your help!
