### ISSUE TITLE
Templater no longer works with console error "Plugin failure: templater-obsidian TypeError: c is not a constructor" 

### ISSUE THREAD

**Issue by codyburleson** [SilentVoid13/Templater#1389]
**Plugin information (please complete the following information):**

-   OS: Windows 10
-   Templater version: 2.3.3
-   Obsidian version: 1.6.1
-   Templater settings: Unknown, plugin cannot be enabled

**Describe the bug**

I cannot toggle the plugin on (enable). The electron browser console provides the following error:

```
app.js:1 Plugin failure: templater-obsidian TypeError: c is not a constructor
    at e.<anonymous> (app.js:1:2288970)
    at app.js:1:237079
    at Object.next (app.js:1:237184)
    at a (app.js:1:235902)
```

**Expected behavior**

The plugin should get enabled with no errors when the "Enable" toggle is turned on.

**Comment by Zachatoo** [comment]
I haven't heard anyone else report this, you could try uninstalling and reinstalling, perhaps there was a blip in the network so it didn't download properly?
