### ISSUE TITLE
{{date}} fail to work after updating to 2.3.3

### ISSUE THREAD

**Issue by wuzhanmin** [SilentVoid13/Templater#1392]
**Plugin information (please complete the following information):**

-   OS: MACOS 14.4.1
-   Templater version: 2.3.3
-   Obsidian version: 1.5.12
-   Templater settings: [e.g. Template folder location: "Templates/", Timeout: "5" (add the templates not working with their associated command)]

**Describe the bug**
There is '{{date}}' string in my template which can be replaced automatically by real date when create a new note using templater before updating to 2.3.3, but fail to work after updating to 2.3.3. I forgot what is the previous version.

**Expected behavior**
{{date}} can be replaced by real date

**Screenshots**
template:
<img width="180" alt="image" src="https://github.com/SilentVoid13/Templater/assets/23700945/34f08c2a-02d0-44f6-822d-a10aab3781da">
expected:
<img width="163" alt="image" src="https://github.com/SilentVoid13/Templater/assets/23700945/9e0f3d67-fd70-4eb4-8a47-09f55b5a35ab">

**Additional context**

**Comment by Zachatoo** [comment]
That is not Templater syntax, that comes from another plugin. Templater syntax is `<% tp.date.now() %>`, documented [here](https://silentvoid13.github.io/Templater/internal-functions/internal-modules/date-module.html#tpdatenowformat-string--yyyy-mm-dd-offset-numberstring-reference-string-reference_format-string).
