### ISSUE TITLE
Ability to use {{date}} in Folder Templates

### ISSUE THREAD

**Issue by Riffaells** [SilentVoid13/Templater#1401]
**Is your feature request related to a problem? Please describe.** A clear and
concise description of what the problem is. Ex. I'm always frustrated when I try to create in a structure and the template is not accepted.
My structure for daily notes now looks like this:
YYYYy
├── YYYY-[Q]Q
│   ├── YYYY-MM
│   │   ├── gggg-[W]ww
│   │   │   └── YYYY-MM-DD

And I want that when creating a note in gggg-[W]ww, for example, 2024-W25, the template is applied automatically

periodic/{{date:YYYY}}/{{date:YYYY-[Q]Q}}/{{date:YYYY-MM}}/{{date:gggg-[W]ww}}/{{date}}
**Describe the solution you'd like** A clear and concise description of what you
want to happen.

Adding a feature to Folder Templates:

![изображение](https://github.com/SilentVoid13/Templater/assets/63253896/f67a0aa3-4411-48f2-aa2e-db7020b46b2a)

so you can insert the date: {{date:YYYY}}

**Comment by McGlear** [comment]
I assume you don't have _only_ daily notes within `periodic` _exclusively_, and therefore don't want `daily-template.md` to be applied to _all_ notes you create within (a subfolder of) `periodic`?
If so: You can create a "Meta template" and outsource your pattern matching into javascript code within that meta template file. Then include the appropriate template (`daily-template.md`, `monthly-template.md`, etc.) based on what the Meta Template matches to.

Simple example that assumes Daily Notes are always named "Daily Note YYYY-MM-DD"
```
<%*
if (tp.file.title.startsWith("Daily Note")){
  tp.file.include("[[daily-template.md]]")
} else {
  tp.file.include("[[generic-periodic-template.md]]")
}
%>
``` 

You can get creative with how to identify the correct template: 
- you could get the note's parent folder and match that folder's name to different date formats using string-matching or regex
- You could make use of javascripts `date` objects and turn folder paths into dates, then select the appropriate template based on that
- you could include a fallback that prompts a user input if no condition was matched and lets the user choose what kind of periodic note it is
- ...

Good Luck :)

**Comment by Riffaells** [comment]
Thank you very much, here I understood, that is, it was possible to specify the default template. And it will all work, true slower, but yes okay:

```javascript

<%*
const folderPath = tp.file.folder(true);

// Разбиваем путь на составляющие
const yearPattern = /(\d{4})y/;
const quarterPattern = /(\d{4}-Q[1-4])/;
const monthPattern = /(\d{4}-\d{2})/;
const weekPattern = /(\d{4}-W\d{2})/;
const dayPattern = /(\d{4}-\d{2}-\d{2})\.md$/;

// Проверяем путь на соответствие структуре
const isYear = yearPattern.test(folderPath);
const isQuarter = quarterPattern.test(folderPath);
const isMonth = monthPattern.test(folderPath);
const isWeek = weekPattern.test(folderPath);
const isDay = dayPattern.test(folderPath);

if (isDay) {
  tR += await tp.file.include("[[daily-template]]");
} else if (isWeek) {
  tR += await tp.file.include("[[weekly-template]]");
} else if (isMonth) {
  tR += await tp.file.include("[[monthly-template]]");
} else if (isQuarter) {
  tR += await tp.file.include("[[quarterly-template]]");
} else if (isYear) {
  tR += await tp.file.include("[[yearly-template]]");
}
%>
```
