### ISSUE TITLE
Daily Quote errors

### ISSUE THREAD

**Issue by theinhumaneme** [SilentVoid13/Templater#1407]
**Plugin information (please complete the following information):**

-   OS: Fedora 40
-   Templater version: 2.3.3
-   Obsidian version: 1.6.5

**Describe the bug**
when using `<% tp.web.daily_quote() %>` it errors out with the message 

**Expected behavior**
Should generate a quote

**Screenshots**
![image](https://github.com/SilentVoid13/Templater/assets/71078441/81cb7b92-1308-4a55-b3c6-9ff3f0a0886d)

**Additional context**
Started to since yesterday, worked after a few tries, today even after 10 tries no generation of daily quote

Best Regards,
Kalyan Mudumby

**Comment by theinhumaneme** [comment]
I have just gone through the codebase and seems like the API server for quotable is down

https://github.com/lukePeavey/quotable/issues/218 is one the issues stating it along with 2 others at the time of writing.

**Comment by theinhumaneme** [comment]
@TheBrightSoul is that available as a plugin? if yes, it would be great :D

**Comment by theinhumaneme** [comment]
> > @TheBrightSoul is that available as a plugin? if yes, it would be great :D
> 
> @theinhumaneme I'll make the repo for it soon on my profile
> 

Thank you @TheBrightSoul

**Comment by CryptoRhinoGH** [comment]
For everyone having this problem, I was able to fix the issue locally. 

Depending on your OS, find your hosts file (linux and mac, available at /etc/hosts

Edit the file (Note you might need sudo/root permissions to edit the file and save).

Try any of the following (add only one of the lines at a time, not all. These are all the ip's service lies on)

3.232.242.170 api.quotable.io
54.91.59.199 api.quotable.io
3.220.57.224 api.quotable.io
3.220.57.224 api.quotable.io

Confirm by going to your browser and heading to 
https://api.quotable.io/random

Enjoy for the time being! While devs get their stuff back up fixed

**Comment by theinhumaneme** [comment]
I am not able to access these through my Cloudflare DNS, I would assume that Cloudflare should be able to resolve the DNS record. please correct me if I am wrong, thanks

I have the following in my _resolv.conf_ on my Fedora 40 workstation

```
nameserver 1.1.1.1
nameserver 1.0.0.1
```

**Comment by RasmusAChr** [comment]
Meanwhile we're waiting for it to get fixed, this is what I use to get daily quotes:
```
<%*
const rssUrl = "https://api.allorigins.win/get?url=https://www.brainyquote.com/link/quotebr.rss";

// Fetch the XML response from BrainyQuote
const response = await tp.web.request(rssUrl);

// Convert the response into a usable XML structure
const parser = new DOMParser();
const xmlDoc = parser.parseFromString(response.contents, "text/xml");

// Extract the first <item> element, which contains the latest quote
const firstItem = xmlDoc.getElementsByTagName("item")[0];

// Get the <title> and <description> within the first <item>
const author = firstItem.getElementsByTagName("title")[0].textContent;
const quote = firstItem.getElementsByTagName("description")[0].textContent;

// Output the result
tR += `>${quote}\n>- ${author}`;
%>
```

**Comment by mkkhg** [comment]
> Meanwhile we're waiting for it to get fixed, this is what I use to get daily quotes:
> 

Thanks, here is another one, basing on your solution:

```
const jsonUrl = "https://api.allorigins.win/get?url=https://zenquotes.io/api/random";

const response = await tp.web.request(jsonUrl);

const obj = JSON.parse(json);

tR += `>${obj[0].q}\n>- ${obj[0].a}`;
```

**Comment by twright169** [comment]
Hope this helps, works for me.
`<%*
const jsonUrl = "https://api.allorigins.win/get?url=https://zenquotes.io/api/random";

let response = await fetch(jsonUrl);
let json = await response.json(); // Parsing the outer JSON object
let obj = JSON.parse(json.contents); // Parsing the inner JSON contents

let quote = obj[0].q;
let author = obj[0].a;

// Format the output according to your requirements
tR += `> [!quote] "${quote}" - [[${author}]]`;
%>`

**Comment by twright169** [comment]
Hope this help it works for me.

```
<%*
const jsonUrl = "https://api.allorigins.win/get?url=https://zenquotes.io/api/random";

let response = await fetch(jsonUrl);
let json = await response.json(); // Parsing the outer JSON object
let obj = JSON.parse(json.contents); // Parsing the inner JSON contents

let quote = obj[0].q;
let author = obj[0].a;

// Format the output according to your requirements
tR += `> [!quote] "${quote}" - [[${author}]]`;
%>
```

**Comment by Zachatoo** [comment]
I'm going to open this up for discussion around which daily quote API provider to use. I've seen zenquotes mentioned, though it will require us to include attribution as per https://docs.zenquotes.io/zenquotes-documentation/#use-limits, which I would prefer not to do.

Any other providers we should consider?

**Comment by johentsch** [comment]
https://en.m.wikiquote.org/wiki/Wikiquote:Quote_of_the_day would be the obvious choice for me.

E.g. through https://javiramoslab.com/wikiquote-API/ but I suppose there are multiple ways of retrieving the QOTD.

Cool thing: it would enable a new parameter for choosing a language.

**Comment by ms3056** [comment]
I use https://api-ninjas.com in a Templater script. It requires a free API key but has been rock solid for me for a couple of years now.

**Comment by johentsch** [comment]
> I use https://api-ninjas.com in a Templater script. It requires a free API key but has been rock solid for me for a couple of years now.

Nice one! It has only language but allows for choosing from a bunch of different categories. And, compared to Wikiquotes, which often has quite lengthy quotes, these are are nice and aphoristic. E.g. I got:

```json
[
  {
    "quote": "There is something curiously boring about somebody else's happiness.",
    "author": "Aldous Huxley",
    "category": "happiness"
  }
]
```

**Comment by chance-nelson** [comment]
Another option could be to simply forgo any API calls for quotes, whatsoever, and include a quotes database in the plugin. There are a variety of quotes databases already parsed into JSON format available on GitHub. For example, [micheleriva/the-quotes-database](https://github.com/micheleriva/the-quotes-database/blob/master/src/data/quotes.json) is available under MIT license, so presumably we can simply include a reference to their work and copy their file at build time/download it at runtime.

**Comment by ms3056** [comment]
> Nice one! 

I also like they have many other feeds besides quotes - it really is a one stop shop.

**Comment by Zachatoo** [comment]
> Another option could be to simply forgo any API calls for quotes, whatsoever, and include a quotes database in the plugin.

I don't know if I want to add an extra 700kb+ to the plugin size, but we could certainly request that data from GitHub and grab a random quote on the fly. I'm leaning towards hosting the quotes inside the Templater repository to avoid any possibility of it going down, unless GitHub is down, which Obsidian relies on heavily for other functions anyways.

I'm going to move forward with hosting our own quotes database on GitHub in the next week or so, unless there's any opposition.

**Comment by johentsch** [comment]
Sounds a bit like an overkill to me when @ms3056 has suggested a very simple alternative. Personally, in my very own interest, I would be more interested in having it working by tomorrow than wait a few weeks but, obviously, the person who does the work gets to decide...

**Comment by chrsdk** [comment]
> I use https://api-ninjas.com in a Templater script. It requires a free API key but has been rock solid for me for a couple of years now. 

Could you share your templater script?

**Comment by Zachatoo** [comment]
The quotes will be hosted in this repo https://github.com/Zachatoo/quotes-database

The fix to use this as the quotes database will be going out in the next release tonight.

**Comment by ms3056** [comment]
> > I use https://api-ninjas.com in a Templater script. It requires a free API key but has been rock solid for me for a couple of years now.
> 
> Could you share your templater script?

Sorry I was so late on this - I guess the ship has sailed, but this is what I use for inserting quotes into my daily note. It is free and has topics. I call it like this: `<% tp.user.quoter("business") %>` - there are a bunch of topics you can choose from. 

```js
async function start(category) {
  const headers = { 'X-Api-Key': 'insert free api key here' };
  // const category = 'inspirational';
  const url = `https://api.api-ninjas.com/v1/quotes?category=${category}`;
  const quoteData = await requestUrl({ url: url, headers });

  if (quoteData.status >= 400 && request.throw) {
    console.log(quoteData);
    return `*Something went wrong!*`;
  }

  const data = quoteData.json;

  let quote;
  let author;

 
  quote = data[0].quote;
  author = data[0].author;
 

  return `${quote}— *${author}*`;
}

module.exports = start;
``
