### ISSUE TITLE
Template folder location should allow subfolders

### ISSUE THREAD

**Issue by jcesguerram** [SilentVoid13/Templater#1409]
If templates are an important part of your workflow, subfolfers  make a lot of sense son that you can keep things organized. Templates for mermaid charts, templates for project management, templates for periodic notes etc...
It would be great if subfolders could be included in the template folder location

**Comment by Zachatoo** [comment]
I'm not sure I understand, isn't this how it works today?

I have subfolders for Pathfinder and daily note sections, and I can use those templates in the same ways I can use templates not in subfolders in my templates folder.

**Comment by Zachatoo** [comment]
And what makes this request different from #1223 ?

**Comment by Zachatoo** [comment]
Marking as closed due to lack of information.
