### ISSUE TITLE
Support for Folder Templates specific to subfolders

### ISSUE THREAD

**Issue by ct2034** [SilentVoid13/Templater#1413]
I am not sure if #1409 is a duplicate. In case it is clarified there, feel free to close this one.
What I am intereseted in is the [Folder Templates](https://silentvoid13.github.io/Templater/settings.html#folder-templates) feature to suppurt subfolders.

To give an example:
I have a Folder structure like
```
Daily/2024/
Daily/2024/24-01/
Daily/2024/24-01/24-01-01.md
Daily/2024/24-01/24-01-02.md
Daily/2024/24-01/24-01-03.md
```
for my Daily notes. 
And I create them with the Folder Templates feature, by seetting the Daily notes template for the Daily Folder.
But if I now additionally want to create monthly or yearly notes in the Daily/2024/ and Daily/2024/24-01/ respectivley, I would need a setting where the Daily template is only valid for folders `Daily/*/*/*`, Monthly only for `Daily/*/*` and yearly for `Daily/*`.

**Comment by Zachatoo** [comment]
You should be able to do this with the new [file regex templates](https://silentvoid13.github.io/Templater/settings.html#file-regex-templates) feature.
