### ISSUE TITLE
Feature request: allow for ordering which templater code is excuted first

### ISSUE THREAD

**Issue by AnasImr** [SilentVoid13/Templater#1423]
**Is your feature request related to a problem? Please describe.**: So templater excuting the syntax inside a note in a reversed order was always a problem for me (it excutes syntax from the lowest on the note to the highest),

**Describe the solution you'd like**: An additional syntax option/argument to add a number to order how inline templates are handled and which code is excuted first
**Describe alternatives you've considered**: I tried javascript snippets but not all of them work how we usually want them to, an 'excution order' number argument inside the normal templater syntax would be way cleaner and faster as a workflow

**Additional context**: There is [this similar question on reddit](https://reddit.com/r/ObsidianMD/comments/11v89gl/change_the_order_of_questions_in_templater/), and here's the syntax i would love to get if this feature is ever added:
```markdown
- [ ] '<% tp.system.prompt("Add a design", null, true, 1) %>' Design
- [ ] Digitized ?
- [ ] Embroidered on a '<% tp.system.suggester(["T-shirt", "Polo", "Patch"], ["T-shirt", "Polo", "Patch"], true, "Embrodiered on what ?", 2) %>' ?
```
the last number inside the arguments for both the templater syntaxes is what defines the order of which syntax gets escuted first, going from 0 to 100++

**Comment by Zachatoo** [comment]
The prompts appear to execute from bottom to top because the first prompt is opened, and then the second prompt is opened without waiting for the first prompt to be answered. 

You can wait for the first prompt to be answered before opening the second prompt by using the `await` keyword.

```js
- [ ] '<% await tp.system.prompt("Add a design", null, true) %>' Design
- [ ] Digitized ?
- [ ] Embroidered on a '<% await tp.system.suggester(["T-shirt", "Polo", "Patch"], ["T-shirt", "Polo", "Patch"], true, "Embrodiered on what ?") %>' ?
```

**Comment by Zachatoo** [comment]
Marking as closed because I do not think it is feasible to support using a number parameter to determine order of execution. Writing the code in the order you want it executed, and using `await` when needed, is a solution that works today and is easier to reason about in code. Especially for those using other JS features such as loops, a number parameter for order of execution wouldn't make sense.
