### ISSUE TITLE
SImple syntax not displaying values correctly

### ISSUE THREAD

**Issue by paulsybrandy** [SilentVoid13/Templater#1427]
![image](https://github.com/user-attachments/assets/fa393553-37e5-411e-a22f-dda41493a416)

**Plugin information (please complete the following information):**

-   OS: Windows 11 Pro build 22635.4000
-   Templater version: 2.4.1
-   Obsidian version: 1.6.7
-   Templater settings: Template folder location: "Templates/", 

**Describe the bug**
As several videos show, using <% tp.date.tomorrow("Do  MMMM YYYY") %> under alias (or aliases) sets up newly created daily notes with a date for tomorrow. In combination, using the following at the top of the template, will allow for the specified date to be shows along with a backlink to the previous daily note and the next day's daily note.

`<% tp.date.tomorrow("dddd Do MMMM YYYY") %><< [[<% tp.date.now("YYYY-MM-DD") %>]] | [[<% tp.date.now("YYYY-MM-DD", 2) %>]] >>`

However, all that is shown is the syntax I used as opposed to the values (dates) that I was calling for.

I have tried with a simple "creation date" as well but the corresponding values doesn't display what it should, just the syntax I typed in to being with. I am not sure how this got broken but first time I attempted to use this plugin and this is what resulted.

**Expected behavior**
The date of the daily note should be shown with a link to the previous and next daily notes underneath it.

**Screenshots**
![image](https://github.com/user-attachments/assets/99712500-54d8-4ed4-acb7-25b7a19a5b79)

**Additional context**
Not sure what other information to include off the top of my head but if something is needed, I would be happy to provide it, so please ask. Thanks.

**Comment by yaxirhuxxain** [comment]
It’s working well for me without any modifications.

**Result:**
![image](https://github.com/user-attachments/assets/5e4e496c-5fa6-4516-a15b-a85294e72c7e)

**Template:**
![image](https://github.com/user-attachments/assets/c7cf264a-f152-4892-ab12-7f73e2697328)

**Comment by Zachatoo** [comment]
There may be some confusion around how Templater works. 

Templater can either be triggered with a `Templater: ` command from the command palette, or by having "Trigger Templater on new file creation" turned on and creating a file with Templater code in it (daily notes template, etc).

Templater doesn't do anything automatically, it must be triggered.

**Comment by Zachatoo** [comment]
Closing due to no response.
