### ISSUE TITLE
tp.system.clipboard() excludes image links

### ISSUE THREAD

**Issue by ShreyasKallingal** [SilentVoid13/Templater#143]
When using the tp.system.clipboard(), linked images are removed from the text. For example, if I copy an image and paste it as normal using cmd+V, I would get the following:
`![](link_to_image.png)`

However, the output from `<%tp.system.clipboard()%>` is empty. 

Is there a work-around for this?

**Comment by SilentVoid13** [comment]
Hey @ShreyasKallingal, sorry for the late response.
I'm not sure I understand your problem, are you talking about the obsidian feature that auto-creates an image file when pasting an image from the clipboard ?
If that's the case, Templater can't do that, that's an obsidian feature and it wouldn't make much sense to implement that.

**Comment by ShreyasKallingal** [comment]
No problem at all! I was interested in pasting linked images, so not the files themselves. But I think the better option is just to make a separate plugin to handle that. I'll close this then. Thank you :)
