### ISSUE TITLE
Bug | tp.date.now() will incorrectly parse the last week of the year and first week of the next year

### ISSUE THREAD

**Issue by LeCheenaX** [SilentVoid13/Templater#1431]
**Plugin information (please complete the following information):**

-   OS: Windows 10
-   Templater version: 2.4.1

**Describe the bug**
When I use templater to generate weekly report, every report seems fine except the report of 2024 Week 53 or 2025 Week 1, the number of week is depended on your locale. 

Scripts I use: 
```
<%*
const referdate = "2024-12-30"; //This should be the beginning of 2025 Week 1 in my locale. 
%>
Reference date: <% referdate %> 
Week Number: <% tp.date.now("YYYY-w",0,"referdate","YYYY-MM-DD") %> //This will convert the reference date to week format. 
```

Factually, the number of week is correct. when you execute the scripts above it will output week 1. 

However, the full output is: 
```
Reference date: 2024-12-30
Week Number: 2024-1
```

I managed to skip this trap in another way, where I could have the correct filename "2025-1". Now all I need to do is to duplicate the filename to my content by tp.file.title

However, this still failed. 

**You can duplicate the issue with the following brief case:**
```
<% tp.date.now("YYYY-w",0,"2025-1","YYYY-w") %>
```

And the Output will be: 
```
2024-1
```
![image](https://github.com/user-attachments/assets/023e1af3-10c4-451b-9536-0fe49eb12ba2)

**Expected behavior**
The correct Output of 
```
<% tp.date.now("YYYY-w",0,"2025-1","YYYY-w") %>
```
should be: 
```
2025-1
```

**Comment by McGlear** [comment]
Dangerous edge case with moment.js formatting, but not a templater bug! Your reference date is still within 2024! Just imagine the opposite case:
```
<% tp.date.now("YYYY-MM-DD",0,"2025-1","YYYY-w") %> - The first week of the new year actually starts... in 2024!
```
In theory, it should be possible to play with offsets based on day-of-the-week (making sure you always reference the _last_ day of the week, avoiding the edge cases where the first half is still within the previous year).
