### ISSUE TITLE
Add support for vanilla template variables like {{data}} for enhanced compatibility

### ISSUE THREAD

**Issue by MatteoPalazzolo** [SilentVoid13/Templater#1438]
I've been using a collection of templates that utilize the {{date}} template variable before I installed this plugin. Now that I'm using Templater, I need to update all of them to use <% tp.date.now() %>. However, doing so would prevent me from reverting to the vanilla template system if I ever choose to do so.

Would it be possible to implement support for vanilla template variables in Templater as a small quality of life improvement? This would allow for greater flexibility and backward compatibility with existing templates.

**Comment by Zachatoo** [comment]
I don't think this is worth the effort. It should be fairly easy to switch back and forth between Templates and Templater using a global find a replace tool to switch between `{{date}}` and `<% tp.date.now() %>` and the other Templates variables.
