### ISSUE TITLE
Documentation typo: tp.file.clipboard() remains

### ISSUE THREAD

**Issue by ShreyasKallingal** [SilentVoid13/Templater#144]
On this [page of the documentation](https://silentvoid13.github.io/Templater/docs/internal-variables-functions/internal-modules/system-module/), I believe the first function should be `tp.system.clipboard()` instead of `tp.file.clipboard()`.

**Comment by SilentVoid13** [comment]
Hey @ShreyasKallingal, nice catch! Thanks for warning me, this should be fixed now.
