### ISSUE TITLE
template mis-applied when a note is created but not opened

### ISSUE THREAD

**Issue by lorenzoferrone** [SilentVoid13/Templater#1445]
**Plugin information (please complete the following information):**

-   OS: [macOS 14.3.1]
-   Templater version: [2.7.1]
-   Obsidian version: [1.6.7]

**Describe the bug**
I have a very simple template that inserts some text into every new note that is created inside a specific folder and then sets the cursor position after the inserted text:

```
SOME TEXT: <% tp.file.cursor(1) %>
```
everything works fine when I create a new note (usually with an hotkey). However I'm writing a new plugin that creates some file programmatically **without** opening it right after creation (I do this by calling `app.vault.create("new note.md", "")`). This works fine (the file gets created), however, when the note is opened some time later, one find that the template has been mis-applied: everything is copied verbatim inside the new note, including the string `<% tp.file.cursor(1) %>`

**Expected behavior**
I expect the template to be applied just as if the note was created and then opened the usual way

**Comment by Zachatoo** [comment]
That is expected behavior. If Templater can't get the active editor for the newly created note, then Templater will leave any cursor code there. You can then run the "Jump to next cursor location" command to replace the cursor code with your cursor at a later time.

Note that it is just cursors that will be left, other Templater code will be executed.

Changing this behavior would be a breaking change for other workflows.

**Comment by Zachatoo** [comment]
Marking as closed due to no response and because it is working as intended, and I don't see a path forward to fix this that won't break existing workflows.

**Comment by camplowell** [comment]
Is there a workaround for cases where the user deems it more important that all templates be removed, over preserving the information about where the cursor is supposed to start?

Something like `<%* try { tp.file.cursor(); } catch {} %>`

This doesn't actually do it: it doesn't leave the statement, but it also doesn't work when you open the template straight away.

**Comment by Zachatoo** [comment]
Can you help me understand the use case? My initial response is to not use `tp.file.cursor` in templates where you don't care about cursor positions. But I imagine I'm missing something where maybe you're using the same template in different ways that I'm not understanding?

**Comment by camplowell** [comment]
It's for allowing one template with 2 use cases:

case 1: You create this note in the foreground.

`<% tp.file.cursor() %>` is used to set an explicit initial cursor position.

case 2: The note is created in the background (possibly as part of a batched operation).

In this case, I only care about the markdown output of the template. I would like the cursor template to either automatically resolve when I first open the file, or simply go away, so I don't have to go back and delete it later, or memorize an extra keyboard shortcut to execute and delete the remaining template(s).

**Comment by Zachatoo** [comment]
I couldn't find a solution that works in all situations, but this works in some situations and could potentially be adapted to work for your situation if it doesn't work as is.

The premise is you check to see if the active file matches the file that Templater is executing on, if it isn't, then don't insert a cursor.

You can convert this to a user script so you don't have to add the function block to the top of every template that needs this.

```js
<%*
function cursor_if_active_note() {
    const active_note = tp.app.workspace.getActiveFile();
    if (active_note.path === tp.config.target_file.path) {
        return `<\% tp.file.cursor() %\>`;
    }
    return '';
}
-%>

# <% tp.file.title %>

<% cursor_if_active_note() %>
```
