### ISSUE TITLE
Templater web requests not working on Obsidian mobile

### ISSUE THREAD

**Issue by Pietroro** [SilentVoid13/Templater#1455]
**Plugin information (please complete the following information):**

-   OS: iPadOS 17.6.1
-   Templater version: 2.7.1
-   Obsidian version: 1.6.7

**Describe the bug**
When making API calls using the `tp.web.request` function I get a "Templater Error: Error Fetching and Extracting Value".
On the console I only get a cryptic error "{"name":"w"}". I have also tried splitting the `tp.web.request` into js' native `fetch()` and `json()` functions. The response is a "Templater Error: Template parsing error, aborting. Load Failed" error. 

I have googled around a bit and I have come across these Cross-origin resource sharing (CORS) errors. After enabling CORS on the API backend it seems to be working. 

Is there a way to access APIs that don't support this within Obsidian mobile?

**Comment by DudeThatsErin** [comment]
+1 here

**Comment by Zachatoo** [comment]
I've pushed a fix that should resolve CORS errors, please let me know if you are still getting CORS errors!
