### ISSUE TITLE
Local variable overwriting occurs

### ISSUE THREAD

**Issue by snario** [SilentVoid13/Templater#1466]
I just want to document something that maybe should become a footnote in some future documentation, but I don't quite understand how it's all working, so just putting here as a note for now.

If you have a template with something like ...

```js
<%*
let day = moment(tp.file.title);
let nextDay = day.clone().add(1, 'day');
%>
<% nextDay.format('YYYY-MM-DD') %>
```

For a file with title `2024-01-01` you should see:

```md
2024-01-02
```

Which makes sense.

However, I observed that if I triggered opening a new file managed by Templater, `2024-02-01` then what I observed as the output was:

```md
2024-01-02
```

The same thing!

⚠️ Something is going on with the `day` variable, where it is persisting across files.

**The Fix**

```diff
<%*
- let day = moment(tp.file.title);
+ let day = () => moment(tp.file.title);
- let nextDay = day.clone().add(1, 'day');
+ let nextDay = day().clone().add(1, 'day');
%>
<% nextDay.format('YYYY-MM-DD') %>
```

Defining it in this way seems to fix it.

**Comment by Zachatoo** [comment]
I don't understand what the bug is or how to reproduce it. Is there any way you can record a video of the bug, or provide very specific step by step instructions for how to reproduce?

**Comment by snario** [comment]
I figured it out. Sorry, it was my mistake.

I was using [`.startOf`](https://momentjs.com/docs/#/manipulating/start-of/) which **mutates** the object, and I didn't realize it.
