### ISSUE TITLE
configurations about ribbon icon

### ISSUE THREAD

**Issue by yc-gao** [SilentVoid13/Templater#1473]
Hello, I am an obsidian user. I noticed that templater does not have an option to configure whether to display the ribbon icon.

Before asking the question, I looked up the modification records of the relevant logic:

1. 2022-09-02 shabegom added the logic for configuring the ribbon icon, https://github.com/SilentVoid13/Templater/pull/653

2. 2024-05-24 joethei deleted the logic for configuring the ribbon icon, https://github.com/SilentVoid13/Templater/commit/d95fdb0b20f2ae2b86fd215f00fbfcd0538ff25b

I would like to ask if this is an expected change, and what are the considerations for deleting the configuration logic?

**Comment by yc-gao** [comment]
I submitted a PR to re-support the configuration of the ribbon icon.

https://github.com/SilentVoid13/Templater/pull/1474

**Comment by Zachatoo** [comment]
It is an expected change. It was requested by a member of the Obsidian team to remove that functionality, as it is now built in functionality for all ribbon icons.

<img width="1119" alt="image" src="https://github.com/user-attachments/assets/deea55a0-e1d1-4c60-848a-dadf966c2df6">
