### ISSUE TITLE
Feature Request: Folder-based Template Selection

### ISSUE THREAD

**Issue by Zizipack** [SilentVoid13/Templater#1477]
Hi! I’m an active user of Templater, and I frequently add new templates to my vault. Currently, when I use the ALT-N shortcut to create a new note from a template, all templates appear in a single list.

It would be very helpful to have the ability to see the folder structure where templates are stored and select a folder first, followed by choosing a template from within that folder. This way, I can organize my templates by category and avoid clutter.

I’ve tried using QuickAdd, but it’s not a practical solution for me, as it requires manually adding each template one by one. Since I actively add new templates, I need a more dynamic solution that reflects the folder structure automatically.

Would it be possible to implement a folder-based template selection feature for better organization and usability?

**Comment by Zizipack** [comment]
![image](https://github.com/user-attachments/assets/102dfff1-2755-4da6-801d-87929e883b35)

**Comment by Zachatoo** [comment]
It's pretty rare in Obsidian that you go through sequential dropdown menus to get to what you want, this feature would make Templater's template selector dropdown feel out of place.

You can certainly build your own using `tp.file.suggester` and some Obsidian APIs.

How I manage this is by searching in the dropdown to filter down the results to the folder. Or searching for the template itself and viewing which folder it's in to confirm it's the one I want.
