### ISSUE TITLE
New hotkeys are being created instead of changing path of the existing one

### ISSUE THREAD

**Issue by aldrinmathew** [SilentVoid13/Templater#1481]
-   OS: Ubuntu 22.04
-   Templater version: 2.8.1
-   Obsidian version: 1.6.7
-   Templater settings: None

**Describe the bug**
Creates many unnecessary hotkeys

**Expected behavior**
As I change the path of a template for an existing hotkey, I expect it to change the path of the existing one. Instead as I type each character, new hotkey slots are being created.

**Screenshots**
![Screenshot from 2024-10-11 11-57-28](https://github.com/user-attachments/assets/b29ca07f-7c34-4fcc-92ea-99bfaed79c3e)

**Comment by Zachatoo** [comment]
@madigan Would you be interested in looking into this? If not I'll pick it up this weekend.

**Comment by madigan** [comment]
Sure, I'd be happy to.
