### ISSUE TITLE
Create new note from template - Error: Failed to open "" 

### ISSUE THREAD

**Issue by Aaron-von-Awesome** [SilentVoid13/Templater#1484]
## Plugin information (please complete the following information):

-   OS: Linux Mint 21.3
-   Templater version: 2.8.0
-   Obsidian version: 1.6.7
-   Templater settings:
```json
{
  "command_timeout": 5,
  "templates_folder": "Extras/Templates",
  "templates_pairs": [
    [
      "",
      ""
    ]
  ],
  "trigger_on_file_creation": true,
  "auto_jump_to_cursor": true,
  "enable_system_commands": false,
  "shell_path": "",
  "user_scripts_folder": "",
  "enable_folder_templates": true,
  "folder_templates": [
    {
      "folder": "<redacted>",
      "template": "<redacted>"
    }
  ],
  "enable_file_templates": false,
  "file_templates": [
    {
      "regex": ".*",
      "template": ""
    }
  ],
  "syntax_highlighting": true,
  "syntax_highlighting_mobile": false,
  "enabled_templates_hotkeys": [
    ""
  ],
  "startup_templates": [
    ""
  ]
}
```

## Describe the bug

When using the hotkey `Alt+n` to run "Templater: Create new note from template", the new note is created, but Obsidian does not jump to the new note, and I receive the error `Failed to open ""`.

Additionally, in my template, the file should rename itself to the title I enter, but the note remains as "Untitled".

*(Template code is below)*

## Expected behaviour

Able to create a new note in Obsidian using `Alt+n` hotkey against the given template below.

## Screenshots

![image](https://github.com/user-attachments/assets/ca64456a-6c95-4b48-ba01-46c41df60899)

## Additional context

- **This only started happening after I upgraded from Templater 2.7.1 to 2.8.0**
- If I assign a template to a given folder, then right-click on said folder, and click "New note"; the template runs without issue.

### Template

This is the template I am trying to use:

```
<%*
  let title = tp.file.title
  if (title.startsWith("Untitled"))
  {
    title = await tp.system.prompt("Enter the Title: ");
    title_no_spaces = title.replace(/ /g, "-");
    await tp.file.rename(`${title_no_spaces}`);
  }
%>
%%
related_to: 
%%
# <%* tR += `${title}` %>

<% tp.file.cursor() %>
```

**Comment by madigan** [comment]
Hey @Aaron-von-Awesome, that template seems to work fine when I add it to my test vault. Have you tried upgrading the plugin to 2.8.2 to get the latest bug fixes?

**Comment by Aaron-von-Awesome** [comment]
> Hey @Aaron-von-Awesome, that template seems to work fine when I add it to my test vault. Have you tried upgrading the plugin to 2.8.2 to get the latest bug fixes?

Howdy @madigan - I did some more digging...it looks like it is the [Better Markdown Links](https://github.com/mnaoumov/obsidian-better-markdown-links) most recent version that is causing the issue :innocent:.  When I disable that plugin, everything works as expect.

My apologies for the mistake!
