### ISSUE TITLE
Template parsing error when using the Web Clipper

### ISSUE THREAD

**Issue by greetclammy** [SilentVoid13/Templater#1509]
From time to time, when I clip a webpage with the official Obsidian Web Clipper, *Templater* will notify me of an error:

```
Templater Error: Template parsing error, aborting. 
ENOENT: no such file or directory, open '/Users/username/Library/Mobile Documents/iCloud~md~obsidian/Documents/Vault/Saved 🔖/Untitled.md'
```

- This happens seemingly at random. Maybe once every 10 times.
- When I clip the same webpage that caused the error, the error doesn't show up again. (I'm sure of it as I have the dev console open, and I'm aware that the same error won't be duplicated in the console but instead a counter to the left of it will go up.)
- I have the *Trigger Templater on new file creation* setting turned ON to apply a template to all new notes. (The template is never applied to clipped notes. And I don't want it applied to clipped notes, just to be clear.)

What could be causing this? 🤔

<details>
<summary>Debug info</summary>

```
SYSTEM INFO:
	Obsidian version: v1.7.7
	Installer version: v1.7.7
	Operating system: Darwin Kernel Version 20.6.0: Thu Jul  6 22:12:47 PDT 2023; root:xnu-7195.141.49.702.12~1/RELEASE_X86_64 20.6.0
	Login status: not logged in
	Language: en
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: Minimal v7.7.18
	Snippets enabled: 18
	Restricted mode: off
	Plugins installed: 57
	Plugins enabled: 37
		1: Templater v2.9.1
		2: Adapt to Current View v1.0.0
		3: Create Note in Folder v1.12.4
		4: First Line is Title v1.0.0
		5: Hider v1.5.1
		6: Hotkeys for Bookmarks v1.1.1
		7: Image Toolkit v1.4.2
		8: Lazy Plugin Loader v1.0.18
		9: Minimal Theme Settings v8.1.1
		10: Pane Relief v0.5.6
		11: Quick Explorer v0.2.12
		12: Tab Switcher v1.4.0
		13: Trigger Manual Save v1.0.0
		14: Linter v1.27.1
		15: QuickAdd v1.11.5
		16: Slash Commander v0.2.16
		17: Strange New Worlds v2.1.5
		18: Style Settings v1.0.9
		19: Quick Switcher++ v4.6.2
		20: Trash Explorer v1.2.3
		21: Text Transporter v1.0.12
		22: Omnisearch v1.25.1
		23: Quick Tagger v2.2.3
		24: Auto Card Link v1.2.3
		25: Auto Link Title v1.5.4
		26: Copy Block Link v1.0.4
		27: Folder Focus Mode v0.9.13
		28: Footnote Shortcut v0.1.3
		29: Merge Notes v0.0.9
		30: Mononote v1.2.2
		31: Novel word count v4.2.0
		32: Nuke Orphans v1.2.5
		33: Outliner v4.8.1
		34: Tag Wrangler v0.6.1
		35: Text Extractor v0.5.2
		36: Zoom v1.1.2
		37: Commander v0.5.2

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
```

</details>

[Cross-posted this to the web clipper's repo.](https://github.com/obsidianmd/obsidian-clipper/issues/240)

**Comment by Zachatoo** [comment]
Some ideas I have:
- Your vault looks like it's in iCloud, maybe there's something going on there? Have you tried in a vault that isn't in iCloud?
- Have you tried disabling all plugins except for Templater, to validate that it is Templater that is causing the issue? It could be that another plugin is doing something with the clipped note and there's a race condition between Templater and the other plugin.

**Comment by greetclammy** [comment]
It appears that the plugin *Novel word count* was the culprit. The issue seems to have been resolved after I reinstalled both *Templater* and *Novel word count*.
