### ISSUE TITLE
[Bug] Templater runs every if even when it doesn't match

### ISSUE THREAD

**Issue by SlRvb** [SilentVoid13/Templater#151]
## Plugin information:
 - OS: [e.g. Windows 10]
 - Templater version: [1.5.5]
 - Obsidian version: [0.12.1]
 - Templater settings: [Template folder location: "000 Technical/010 Templates", Timeout: "5"]

## Code:
```
<%* if (tp.file.title.match(/[A-Za-z0-9]{1,}-[0-9]{1,}-[0-9]{1,} [A-Z]/)) { %>

<% tp.file.title.split("-")[2].replace(/[0-9]{1,}/, "") %>
<%* } else if (tp.file.title.match(/[A-Z0-9]{1,}-[0-9]{1,} /))  { %>

<% tp.file.title.split("-")[1].replace(/[0-9]{1,}/, "") %>

<%* } else { %>

Incorrect file name
<%* } %>
```

### Expected behavior
The code above is supposed to pull out the file title of files like `TSF-000-00 File Title` or `TSF-0 File Title` to appear as `File Title` only.

## Describe the bug
Code above results in an error stating: `cannot read property 'replace' of undefined` if the file _isn't_ `TSF-000-00`. In order for it to work, the if and else if must be switched to work with a file titled `TSF-000` or `TSF-0`. 

It seems like templater is running the code of the if that _doesn't_ match as well, resulting in the undefined error.

**Screenshots**
![Obsidian_PBdj2NofEB](https://user-images.githubusercontent.com/54087190/115981535-6889f780-a549-11eb-9d55-de7553655a93.png)

**Comment by SilentVoid13** [comment]
Hey @SlRvb, nice catch! This is now fixed in Templater 1.6.0.
Can you update and tell me if this works now for you ?
