### ISSUE TITLE
Possibility to sync YAML from template to all notes generated from the template

### ISSUE THREAD

**Issue by VakZok** [SilentVoid13/Templater#1513]
**Is your feature request related to a problem? Please describe.**
I use templates quite often, and they usually evolve over time based on the needs that arise. This results in me manually adding or removing YAML Front Matter to/from already created notes. For larger projects with many notes, this can be a tedious task.

**Describe the solution you'd like**
Possibly a button to disable/enable the function "Sync YAML Front Matter from template to all notes generated from the template.".

For example, when a note's YAML, generated from the template "Friends," contains the fields "Name," "Age," and "Birth Date," I might want to remove the field "Age" entirely and add the field "Place of Living" for all friends notes. Instead of having to do it separately for each note, I would perform the desired change in the note's template, which would automatically remove the YAML "Age" from all notes generated from this template and would add the field "Place of Living" to all these notes.

**Describe alternatives you've considered**
Doing it manually like before.

**Additional context**
None

**Comment by wwqwq2313** [comment]
Hello, we tried to solve the issue.

This is what we did:

This change adds a new setting to enable/disable YAML Front Matter sync, and implements the functionality to sync YAML Front Matter from templates to generated notes.

You can review changes in this commit: https://github.com/wwqwq2313/SilentVoid13-Templater-1513/commit/4495efe48e9e29466b964ee14d1beebd815977a6.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

Latta AI seeks to solve problems in open source projects as part of its mission to support developers around the world. Learn more about our mission at https://latta.ai/ourmission . If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by Zachatoo** [comment]
Other templating plugins can do this, I'm not interested in adding or maintaining this feature.
