### ISSUE TITLE
tp.file.title creates new Untitled note instead of processing the current one

### ISSUE THREAD

**Issue by d0verenny** [SilentVoid13/Templater#1516]
**Plugin information (please complete the following information):**

-   **OS:** Windows 11
-   **Templater version:** 2.9.1
-   **Obsidian version:** 1.7.7
-   **Templater settings:** 

**Synthax higlighting on Desktop:** ON; 
**Synthax highlighting on mobile:** OFF
**Automatic jump to cursor:** ON
**Trigger Templater on new file creation:** ON
**Regex:** OFF.

**Template folder location:** "TemplateR/" 
**Template location/hotkeys:** TemplateR/general.md

**My template:**

```
---
title: <% tp.file.title %>
type: 
created: <% tp.date.now("DD-MM-YYYY, h:mm a") %>
company: 
project: 
author: Maksim Ilinskii
aliases: 
source: 
tags: inbox
---

# [[<% tp.file.title %>]]
```
**Other settings:**
Startup templates: None
Script filed folder location: None
User scripts: None

**Describe the bug**
When using the command `Create TemplateR_Template_Location/Template.md` (mine is `TemplateR\general.md`), `tp.file.title` creates a new Untitled file instead of processing the current Note with a template.

**Expected behavior**
When using the command `Create TemplateR_Template_Location/Template.md`, Templater processes the current Note instead of creating a new one.

**Screenshots**
Template (Source mode)
![image](https://github.com/user-attachments/assets/dc8a2a7b-16ae-4b63-9321-d7c26e6b442d)
Template (Edit mode with modern properties):
![image](https://github.com/user-attachments/assets/5835dfd7-c596-431b-97ab-39a325b861f9)
An empty file with the title "experiment":
![image](https://github.com/user-attachments/assets/59a8a9ac-c802-4fff-ac29-c8f3e7e42622)
The command I use:
![image](https://github.com/user-attachments/assets/541aeb8a-2f9a-43c5-abdb-eebf566d0f2c)
The file it created after the use of the command Create:
![image](https://github.com/user-attachments/assets/02c6fe88-f640-46e3-8155-2b6ad30e0a20)

**Additional context**
It used to work fine before. Before that, `tp.file.title` would process the current note with no problem. 

My thoughts were it's either the plugins _Filename Heading Sync_ and _Title renamer_ were messing up with it. I removed them completely. I even reinstalled TemplateR. It didn't help.

I tried to turn of ALL the plugins but Templater -- it didn't help, the problem persisted.

My other suspicion was that I got that GIT plugin `LF will be replaced by CRLF the next time git touches it ` warning.

I tried both to set `– git config --local core.autocrlf` to both false and true, and commited changes after of each try. 

I also tried to normalize in git via powershell in the root directory of the vault.

```
$ echo "* text=auto" >.gitattributes
$ git add --renormalize .
$ git commit -m "Introduce end-of-line normalization"
```

Everything to no avail. 

I tried to open an old backup of my vault -- and TemplateR works as it should -- processing the current note instead of creating a new, Untitled one.

Also, for some reason, the Console in Obsidian doesn't give any feedback upon using the command.

Using `Insert` command works normally.

I can provide access to the vault, if needed...

Thanks in advance!

Update: I opened an old version of my Vault to check if it'll work, for some reason it didn't as well... I don't understand what's going on.

**Comment by Zachatoo** [comment]
Are you saying that `tp.file.title` would grab the title from the note that was open at the time the `Create note from template` command was executed? Because that is not how it is supposed to work when creating a note from a template, it should grab the name of the newly created note, usually "Untitled X".

**Comment by Zachatoo** [comment]
There are several ways to get the title of the previously open file, please search through the discussions section.

Closing because this is working as intended.

**Comment by d0verenny** [comment]
I didn't create a note named Untitled. It has always worked this way FOR YEARS: 

1. I create a note called "Foobar". (So it is in fact newly created)
2. I open command pallete and choose "Create TemplateR/general.md and click it
3. The note is processed by TemplateR and fills in. 

Now, instead of Foobar being processed, it creates a new note called Untitled.

**Comment by Zachatoo** [comment]
If you choose "Insert Templater/general.MD" then it will insert the template into the active note. "Create Templater/general.md" will always create a new note.
