### ISSUE TITLE
tp.system.alert 

### ISSUE THREAD

**Issue by roamhacker** [SilentVoid13/Templater#152]
**Is your feature request related to a problem? Please describe.**
Would like to provide user feedback while running a process, but not looking to get information from the user.

**Describe the solution you'd like**
Add a function called: tp.system.alert that displays a message to the user using a similiar UI as tp.system.prompt and tp.system.suggester. 

Could optionally allow for a few visual indicators: success, information, warning, failure

**Comment by luckman212** [comment]
Is the native `new Notice('hello')` not already a good enough solution?

**Comment by roamhacker** [comment]
I didn’t know for that. Newbie ignorance. Thanks!
