### ISSUE TITLE
Javascript flag for knowing how the template is initialized

### ISSUE THREAD

**Issue by roamhacker** [SilentVoid13/Templater#153]
**Is your feature request related to a problem? Please describe.**
Provide the template script with a way to know if it is being initiated from within a file or being initiated from the "Create new file from template action"

The reason is that different content may be inserted into a file if it is from a new document or an existing one. For example, if the document is new, perhaps inserting some front matter, where as if inserting into an existing document, it would not do this.

**Describe the solution you'd like**
Create a tp.file parameter: tp.file.start with values:
0 - from within file
1 - from Command Palette "New from template"

**Comment by SilentVoid13** [comment]
Hey @roamhacker, you can now use the new `tp.config` module as of Templater 1.6.0 to access Templater's running configuration.

For your use case, `run_mode` is what you're interested in: https://github.com/SilentVoid13/Templater/blob/169ce493cca647c58a00455fa4f621f212ca535d/src/Templater.ts#L8

Documentation is at https://silentvoid13.github.io/Templater/docs/internal-variables-functions/internal-modules/config-module

**Comment by roamhacker** [comment]
Nicely implemented. thank you and warm regards
