### ISSUE TITLE
Extract day of week from date in note title

### ISSUE THREAD

**Issue by edward-peters** [SilentVoid13/Templater#154]
If my requested functionality already exists , apologies that I missed it....
I would like to be able to add a variable to the inserted note title, to extract the day of the week from the date in the title.
So for example, if the note's title is 2021-04-26, I can use # <% tp.file.title %> in my template to insert '2021-04-26' as the H1 header for the note. I would like to be able to have templater extract the day of the week, so that I can insert '2021-04-26 Monday' as the H1 header for the note.
Is this possible?
Thank you for a magnificent plugin.

**Comment by SilentVoid13** [comment]
Hey @edward-peters this is possible! 

You can use the following template:

```
# <% tp.date.now("YYYY-MM-DD dddd", 0, tp.file.title, "YYYY-MM-DD") %>
```

Tell me if this works for you.

**Comment by edward-peters** [comment]
Wow @SilentVoid13 that is superb! Works beautifully. A very big thank you for this extraordinary plug in, and for all you are making possible for so many of us.
