### ISSUE TITLE
Is templater supported on Mobile

### ISSUE THREAD

**Issue by rishifter** [SilentVoid13/Templater#159]
Is this wonderful plugin supported on mobile? I’m on iPad OS and can’t seem to get it to work.

**Comment by DaveHenning** [comment]
Same here on Android.

**Comment by SilentVoid13** [comment]
@rishifter @DaveHenning just tested it and this works fine.
Can you update to 1.6.0 and tell me if this works now ?

**Comment by DaveHenning** [comment]
@SilentVoid13 That works! Well done.
The issue now is the whole thing fails on my daily notes because of my weather template. I understand (kinda) why they don't/can't work, but is there any way to maybe just skip over the failures so I can just process them on desktop?

I'm probably just going to remove the weather from my metadata. I haven't really found a good use for it anyway. Doesn't solve the actual problem, but gets me to usable. 

As always, thanks for the hard work. 

FWIW, here's my whole Daily Note metadata

```
aliases: ["<% tp.date.now("MMMM Do, YYYY", 0, tp.file.title, "YYYY.MM.DD") %>","<% tp.date.now("MMMM D, YYYY", 0, tp.file.title, "YYYY.MM.DD") %>","<% tp.date.now("MMM D, YYYY", 0, tp.file.title, "YYYY.MM.DD") %>","<% tp.date.now("MMM. D, YYYY", 0, tp.file.title, "YYYY.MM.DD") %>","<% tp.date.now("M/D/YYYY", 0, tp.file.title, "YYYY.MM.DD") %>","<% tp.date.now("M-D-YYYY", 0, tp.file.title, "YYYY.MM.DD") %>","<% tp.date.now("YYYY-MM-DD", 0, tp.file.title, "YYYY.MM.DD") %>","<% tp.date.now("M.D.YYYY", 0, tp.file.title, "YYYY.MM.DD") %>",]
created: ["<% tp.file.creation_date("YYYY.MM.DD h:mm A") %>"]
weather: ["<% tp.user.weather() %>"]
```

If I remove the weather line, it works.

**Comment by SilentVoid13** [comment]
@DaveHenning yeah system commands are really hard to implement on mobile, and do not have the desktop command lines abilities, that's why they're disabled. 
The weather template shouldn't fail though, but just be replaced with a dummy string, let me investigate that

**Comment by rishifter** [comment]
@SilentVoid13 Just tested and can confirm that it works fine now. The template rendered quicker compared to the desktop although I guess that might be because of the inability to run the commands.

Since many user functions are essentially curl commands, do you think it's possible/feasible to implement them using fetch api since its JS anyway?

**Comment by SilentVoid13** [comment]
@rishifter yes you can use the `fetch` API for a "cross-platform" curl
Here's an example with the `wttr.in` website:

```javascript
<%* 
let res = await fetch("https://wttr.in?format=3");
tR += await res.text();
%>
```

**Comment by SilentVoid13** [comment]
@DaveHenning the weather template (just a curl command) doesn't error out for me, it is replaced with a "Error_MobileUnsupportedTemplate" string (android). That's weird, did you update to 1.6.0?

Anyway since mobile is working now, closing this.

**Comment by rishifter** [comment]
@SilentVoid13 Thanks for the fix and the wonderful plugin in general. I must also thank you for the recent sneaky update with dynamic commands. They are solving issues for me(combining front matter and dynamic commands) where Dataview was failing. Kudos!
