### ISSUE TITLE
Header gets indented when template inserts

### ISSUE THREAD

**Issue by 23tux** [SilentVoid13/Templater#16]
**Plugin informations (please complete the following information):**
 - OS: macOS 10.15.7
 - Templater version: 0.4.2
 - Obsidian version: 0.9.15
 - Templater settings: template Folder `Template`, Timeout 5, Custom Command:
```
{{now}}
date +"%Y-%m-%dT%H:%M"
```

**Describe the bug**
When I insert a template inside a header, it gets indented (see gif)

**Expected behavior**
Indentation should stay the same.

**Screenshots**
![Kapture 2020-11-25 at 9 28 21](https://user-images.githubusercontent.com/38003/100201694-a33b2580-2f00-11eb-8882-e60722853411.gif)

**Comment by 23tux** [comment]
Any news on this? Is there a way I can help?

**Comment by SilentVoid13** [comment]
Hey @23tux, sorry for the long wait, completely missed this post.
Do you still experience this bug ?
I'm not able to reproduce this bug, this works fine for me. However, this may be a macOS specific bug, but I don't have a mac i can test this on.
Does the indentation appear on all templates ? 
Try with internal templates like for example `{{tp_today:f="YYYY-MM-DDTHH:mm"}}`

**Comment by 23tux** [comment]
Hi @SilentVoid13, no hurry!

Yes, this happens on all templates as well as for internal template, I just tried it out.

Let me know if I can be of any help, I'm happy to debug on macOS, just need some guidance.

**Comment by 23tux** [comment]
@SilentVoid13 any way I can help with this issue? I'm happy to try for a PR if you have some guidance where to start :)

**Comment by SilentVoid13** [comment]
Hey @23tux, sorry for the late response, completely forgot about this issue.
Templater had a huge update recently. It now has a new syntax, you'll need to update your existing templates.
This update should fix a lot of things, could you update to Templater's latest version, restart obsidian, update your existing templates with the new syntax and tell me if the bug still persists ?

**Comment by 23tux** [comment]
@SilentVoid13 No problem, I just tried it out, and it works like a charm!

Plus I really really like the new syntax! Thanks so much for the work!
