### ISSUE TITLE
Obsidian downloads an old version of this package

### ISSUE THREAD

**Issue by lucasew** [SilentVoid13/Templater#163]
**Plugin informations (please complete the following information):**
 - OS: NixOS (Linux)
 - Templater: 1.5.5
 - Obsidian version: 0.11.0
 - Templater settings: default, just changed template folder

**Describe the bug**
Obsidian is offering a very old version of this package (0.5.7)

**Expected behavior**
Obsidian offer the latest available version (1.5.5)

**Screenshots**
Because of this version issue, my templates were not expanding at all. Solved after updating using the releases in this GitHub.

**Additional context**

**Comment by SilentVoid13** [comment]
Hey @lucasew, Templater is compatible with obsidian v0.11.3+, you need to update your obsidian app (you said you were on 0.11.0). The update should be available once you update. 
Tell me if this works now.

**Comment by lucasew** [comment]
I've downloaded manifest, the js and the css file from the releases. Now its working :shrug:

**Comment by lucasew** [comment]
It's working. Thank you \o/
