### ISSUE TITLE
Overload Obsidian template plug-in

### ISSUE THREAD

**Issue by pancan21** [SilentVoid13/Templater#17]
1. When using the DailyNotes plug-in the Overload works as expected. However with the internal template plugin or external plugins like the Calender the Overload is not triggered. This results in all Templater templates not being replaced.
2. When using `Alt+E` all {{date}} {{time}} are not being replaced without specifying user defined templates.

It would be nice to have a general Overload triggered for all of this plugins. Or at least support all the native templates of the Obsidian templates like {{date}} {{time}} so the plug-in can replace the internal template creation while using the same syntax.

I know that {{tp_today}} can replace the functions however it makes basic templates not usable in the Templater workflow.
For now I was helping myself by adding custom commands for {{date}} {{time}} but I think it could be good to have this implemented for everyone. Especially as this workaround can not serve all formats like {{time:HH:mm}} to my knowledge.

Sorry if I missed something out. Just started using Obsidian 👍 

Issue accuring on Windows 10 using
Obsidain 0.9.15
Templater 0.4.2

**Comment by SilentVoid13** [comment]
Hey @pancan21, sorry for the late response.
I agree with you that a global overload would be cool. Unfortunately that's not possible or I would have to overload each function for each plugin manually in my code, and that's just not sustainable in the long term.
For the Templates core plugin, the idea of Templater is to kinda replace it. Everything available in the core Templates is available in Templater (including date / time formats, check arguments in internal templates), you shouldn't have to use the Templates core plugin anymore.

**Comment by pauljacobson** [comment]
@SilentVoid13 I just noticed the "Overload" option for the plugin. How does that work? Does this enable me to add a Templater field to my Daily Notes template, and have that become active? So, for example, I could add the weather option to my usual Daily Note template, and have that render a bit like I suggested in #10?

**Comment by SilentVoid13** [comment]
@pauljacobson Yes exactly ! That's why i closed your issue.

**Comment by pancan21** [comment]
@SilentVoid13 I have a idea how to prevent to make an overload for every function.
How about making the Overload function/Templater availible for the current document or better current selection to trigger the replacement for all {{templates}}?
This should work from my point of view and not create this long term support issue that you mentioned.

**Comment by rapatel0** [comment]
Sorry maybe i'm missing something, but wouldn't it be possible just to overload `{{date}}` and `{{time}}` as keywords in templater. 

I just want to point templater at my existing directory of templates, and use it as the full replacement, and not manually rename all the keys and formatting.  Seems like obsidian only has the two keywords (date and time), and there should be no conflict I if i'm just invoking templater.

**Comment by SilentVoid13** [comment]
Hey @rapatel0, you can use `{{tp_date}}` and `{{tp_time}}` as a replacement in your templates.
I don't want to overload `{{date}}` and `{{time}}`, because I don't want plugins to conflict with each other. 
Even though using the Templates core plugin along with Templater is unlikely, since Templater does everything the core Template plugin does, I prefer to avoid imposing an overload to users.
If you really want to use `{{date}}` and `{{time}}`, then don't use internal templates and define them as custom templates.
