### ISSUE TITLE
Daily_quote internal command crashes my template 

### ISSUE THREAD

**Issue by Scarlov** [SilentVoid13/Templater#177]
**Plugin informations (please complete the following information):**
 - OS: Windows 10
 - Templater version: 1.5.5
 - Obsidian version: 0.11.13
 - Templater settings: 
     -  folder location: "Templates/" 
     - Timeout: "10" 
     - My Daily Note template; command in question <% tp.web.daily_quote() %>

**Describe the bug**
For some time now I have been using the same daily note template that includes a "daily_quote()" command, and it always worked flawlessly, up until today.  The daily_quote() command caused my daily note template to time out when it was automatically created and later when I was testing it. Even when that command is the only thing in the template it still times out.

**Expected behavior**
What always happened, the quote to be generated
**Screenshots**
![image](https://user-images.githubusercontent.com/72456958/116666832-59fd6f00-a993-11eb-9b60-d3f77598ab2c.png)

**Additional context**
I do have a lot of different plugins installed but I have tried disabling the recently updated ones and it didn't change anything

**Comment by SilentVoid13** [comment]
Hey @Scarlov, it looks like the https://quotes.rest API is down, causing the template to fail. This is not a Templater bug. I hope the API will be back up soon.

**Comment by lgyz** [comment]
How about the https://unsplash API? It's also the same problem.

**Comment by SilentVoid13** [comment]
The API is back up, should be working now. Closing this.

**Comment by rockman007372** [comment]
It seems to be down again as of right now!
