### ISSUE TITLE
unable to insert dynamic commands in templates

### ISSUE THREAD

**Issue by weeyizhi** [SilentVoid13/Templater#188]
**Plugin informations (please complete the following information):**
 - OS: Windows 10
 - Templater version: 1.6.0
 - Obsidian version: 0.11.13
 - Templater settings: Template folder location: "templater", timeout: 5s

**Describe the bug**
The new dynamic commands are great, but I can't put one into my templates as they get computed into something weird.
Consider the following template:
```
# <%tp.file.title%>

<%+ tp.date.now() %>
```

after applying the template on a file, we get:
```
# 2021-05-04

NaN
```

**Expected behavior**
Dynamic commands should not be computed when applying templates. Or maybe provide the user some way to escape certain blocks.

**Comment by SilentVoid13** [comment]
Hey @weeyizhi you're right, I'll try to fix that in a future update.

**Comment by SilentVoid13** [comment]
Hey @weeyizhi @Moonbase59, this should now be fixed as of Templater 1.7.0. Update and tell me if this works now!

**Comment by Moonbase59** [comment]
@SilentVoid13 Yup, well done, thanks! Works fine now.

**Comment by perymimon** [comment]
hi Im on Templater 1.16 and that bug happen again
