### ISSUE TITLE
Templater does not replace templates.

### ISSUE THREAD

**Issue by jlojosnegros** [SilentVoid13/Templater#189]
**Plugin informations (please complete the following information):**
 - OS: Ubuntu 18.04.5 LTS
 - Templater version: 1.6.0
 - Obsidian version: 0.11.13
 - Templater settings: by default ( no change at all )
 ![Selection_024](https://user-images.githubusercontent.com/24541551/116969279-4b29fb80-acb6-11eb-911f-abd7cf6e078f.png)

**Describe the bug**
Create a new empty vault.
Deactivate Safe mode
Install "Templater"
Create a new file with some templates
```
[[{{tp_yesterday}}|<< Yesterday]] | [[{{tp_tomorrow}}|Tomorrow >>]]


{{tp_daily_quote}}

# {{tp_date}}
```
Go to the end of the file and press "Alt+R". Nothing happens
Press "Ctrl+P" to open command console and execute "Templater: Replace templates in the active file". Nothing happens

**Expected behavior**
I would expect the templates to be substituted by their values.

**Screenshots**

**Additional context**

**Comment by SilentVoid13** [comment]
Hey @jlojosnegros Templater this is not a bug, Templater had a massive update, completely refactoring the syntax.
You must convert your existing templates to the new syntax if you want to use the new Templater.

The strict equivalent to your template in the new Templater syntax would be:

```
[[<% tp.date.yesterday() %>|<< Yesterday]] | [[<% tp.date.tomorrow() %>|Tomorrow >>]]


<% tp.web.daily_quote() %>

# <% tp.date.now() %>
```

To understand the new syntax, read the complete documentation at https://silentvoid13.github.io/Templater/docs

**Comment by jlojosnegros** [comment]
My mistake ... I am sorry. I didn't see de massive update advise in the documentation.

Thanks for your help
