### ISSUE TITLE
Dynamic Commands inside a Table break Table formatting

### ISSUE THREAD

**Issue by rishifter** [SilentVoid13/Templater#190]
**Plugin informations (please complete the following information):**
 - OS: macOS
 - Templater version: 1.6.0
 - Obsidian version: 0.12.2
 - Templater settings: Template for testing  `<%+ tp.file.title %>` (chose since it's simple and output is small

**Describe the bug**
Using a dynamic command inside of a table breaks the table formatting completely and sometimes fails to render result.

**Screenshots**
<img width="775" alt="image" src="https://user-images.githubusercontent.com/3610185/116989240-200fce00-acef-11eb-8ac3-c7df65d6e6fd.png">

**Additional context**
I had used another more complex template(with a few date calculations) earlier and that failed to even calculate. The template worked fine outside the table. So I tested with something simpler like just the title and it renders now but the formatting is still ruined.

**Comment by SilentVoid13** [comment]
Hey @rishifter, thanks for the report, this should now be fixed as of Templater 1.7.0, update and tell me if this works now.

**Comment by rishifter** [comment]
Yes, it works now! Thanks for your hard-work on this plugin!
