### ISSUE TITLE
Option to specify a tag with "get random photo" tempalte

### ISSUE THREAD

**Issue by macintacos** [SilentVoid13/Templater#20]
I would really like to narrow down the types of images that get pulled down from the "get random photo" template option. Ideally, I'd like to limit it based on a tag (like "landscape", "architecture", etc.).

[The "Get a Random Photo" endpoint](https://unsplash.com/documentation#get-a-photo) seems to allow for a `query` parameter to narrow down the images it searches through. Perhaps this can be leveraged?

**Comment by SilentVoid13** [comment]
Hey @macintacos, thanks for the suggestion ! 
Just pushed a commit to add this new argument.
This will be available in the next release i publish.
