### ISSUE TITLE
Templater doesn't insert templates in latest insider version

### ISSUE THREAD

**Issue by HEmile** [SilentVoid13/Templater#21]
Getting crashes, and also no inserted template on the latest Obsidian insider release. 

 - OS: MacOS Catalina
 - Templater version: 0.4.4
 - Obsidian version: 0.9.20
 - Templater settings: [e.g. Template folder location: "Templates/", Timeout: "5" (add the templates not working with their associated command)]

**Describe the bug**
When inserting any template (also ones that don't use any internal template), nothing happens and i get a TypeError:

```
Uncaught (in promise) TypeError: Cannot read property 'workspace' of null
    at CustomPluginTemplates.<anonymous> (app.js:1)
    at app.js:1
    at Object.next (app.js:1)
    at app.js:1
    at new Promise (<anonymous>)
    at a (app.js:1)
    at CustomPluginTemplates.e.insertTemplate (app.js:1)
    at CustomModalTemplates.t.onChooseItem (app.js:1)
    at CustomModalTemplates.t.onChooseSuggestion (app.js:1)
    at CustomModalTemplates.t.selectSuggestion (app.js:1)
```

**Comment by sandrop** [comment]
Cofirming that I am seeing this as well with the exact same error message in console

**Comment by JunerLee** [comment]
+1

**Comment by SilentVoid13** [comment]
Hey everyone, well I'm sorry this is happening, must be related to the API update in 0.9.20 and the new SuggestModal.
Unfortunately, I don't have access to insider releases, so I can't fix that.
I would suggest insiders to disable the plugin temporarily until 0.9.20 is publicly released.
When it is, I will update Templater to use the new API features and fix issues.

**Comment by sdirge** [comment]
Silent email me at steve@tac0.net.

**Comment by Mpic** [comment]
Hi !

Your plugin is so powerful, I love it. 

I'm willing to help you getting an insider license, if money is a problem. Do you have a Paypal account or something else we could tip you on ?

**Comment by sdirge** [comment]
> 
> 
> Hi !
> 
> Your plugin is so powerful, I love it.
> 
> I'm willing to help you getting an insider license, if money is a problem. Do you have a Paypal account or something else we could tip you on ?

Looks like there is a place here: https://buymeacoff.ee/SilentVoid13

**Comment by sandrop** [comment]
I'd join in that pool as well

**Comment by HEmile** [comment]
Me too! It's a good plugin :)

**Comment by SilentVoid13** [comment]
Hey everyone,
First huge thanks to @sdirge and @Mpic for the donations to support my work !
This is an awesome community and I really appreciate it.
I now have an insider license, and I'll try to fix Templater and push a new release today when I have time.
Again, thank you all for the kind words, I'll try to improve this plugin as much as I can !

**Comment by SilentVoid13** [comment]
Alright, this should be good, just remembered that I can't push a new release because 0.9.16 doesn't have the new API features. This would break the plugin for people on 0.9.16.
I'll wait for the public 0.9.20 to be released to push a new release.
If you don't want to wait you can unzip the attached file inside your `.obsidian/plugins/templater-obsidian` folder (the displayed version of Templater will still be 0.4.4). This should fix the problem, tell me if it does not.

[Templater-0.5.0.zip](https://github.com/SilentVoid13/Templater/files/5646830/Templater-0.5.0.zip)

**Comment by Mpic** [comment]
It works now !

Thanks a lot to you :-)

**Comment by sandrop** [comment]
Amazing. Thank you. I was feeling things slowly slipping away without your plugin and it s ability to maintain structure :)

**Comment by HEmile** [comment]
I just tried and it works! Thank you so much :)
