### ISSUE TITLE
How to choose the order the prompts are shown in?

### ISSUE THREAD

**Issue by iroQuai** [SilentVoid13/Templater#213]
I'm creating a theme with multiple prompts in it (tp.system.prompt). I assumed the first prompt would show first and so on... This is not the case! I have no idea what order they are in... 

Question: Is there a way to choose the order of the prompts?

**Comment by SilentVoid13** [comment]
Hey @iroQuai, there are no ways to specify an order for the prompt except from top to bottom.

By default, for speed purposes, prompts are launched in a random asynchronous way, but you can force prompts to be synchronous using the `await` keyword. They will then be executed in the top to bottom order. 

This would give for example:

```
<% await tp.system.prompt("prompt1") %>
<% await tp.system.prompt("prompt2") %>
<% await tp.system.prompt("prompt3") %>
```
