### ISSUE TITLE
'ConvertFrom-Json' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by JunerLee** [SilentVoid13/Templater#22]
My Templater  code: powershell '{ "key":"value1", "Key":"value2" }' | **ConvertFrom-Json**

but I get  this from console : "'**ConvertFrom-Json**' is not recognized as an internal or external command, operable program or batch file."

**Comment by SilentVoid13** [comment]
Hey, the problem doesn't come from Templater but from your command.
You need to use quotes around your powershell command.
Whenever you're not sure about a command, launch it from windows cmd.exe and try to debug it.

This would give something like this in your case:

```powershell
powershell " '{ \"key\":\"value1\", \"Key\":\"value2\" }' | ConvertFrom-Json -AsHashtable"
```

**Comment by JunerLee** [comment]
> Hey, the problem doesn't come from Templater but from your command.
> You need to use quotes around your powershell command.
> Whenever you're not sure about a command, launch it from windows `cmd.exe` and try to debug it.
> 
> This would give something like this in your case:
> 
> ```powershell
> powershell " '{ \"key\":\"value1\", \"Key\":\"value2\" }' | ConvertFrom-Json -AsHashtable"
> ```

sorry, I see. Thanks a lot!

**Comment by HBovwinf** [comment]
powershell " '{ \"key\":\"value1\", \"Key\":\"value2\" }' | ConvertFrom-Json -AsHashtable"

**Comment by B-Art** [comment]
From PS prompt you would use:
`'{ "key":"value1", "Key":"value2" }' | ConvertFrom-Json -AsHashtable`
