### ISSUE TITLE
Allow code in codeblock

### ISSUE THREAD

**Issue by zsviczian** [SilentVoid13/Templater#222]
For javascript templates, it would be nice if I could use an embedded code block within the template as that would add syntax highlighting:

i.e. this:
![image](https://user-images.githubusercontent.com/14358394/118391196-5de7ed00-b633-11eb-8ef4-3a099b777ec8.png)

instead of this:
![image](https://user-images.githubusercontent.com/14358394/118391233-88d24100-b633-11eb-8d49-e56b4477f53b.png)

my current workaround is:
![image](https://user-images.githubusercontent.com/14358394/118391331-09913d00-b634-11eb-953f-3ebd947065f1.png)

**Comment by SilentVoid13** [comment]
Hey @zsviczian thanks for the idea, I added syntax highlighting in Templater 1.8.0!

Update and tell me if this works fine.
