### ISSUE TITLE
Configuration for built-in random images template with orientation only

### ISSUE THREAD

**Issue by misaxi** [SilentVoid13/Templater#224]
**Is your feature request related to a problem? Please describe.**
The built in function that pulls random images is a great idea. The issue i am having is that
1. Recently it pull portrait type of images more often than landscape. 
2. I use preview all the time together with edit view, portrait takes way too much space (usually entire screen)
3. I don't want to limit the dimension by setting length x width, as it limits the options from the images getting picked

**Describe the solution you'd like**
I'd like to have a way to only set the orientation **without** having to to set size.

**Comment by SilentVoid13** [comment]
Hey @misaxi, unfortunately I'm using the unsplash API (https://source.unsplash.com/) and I don't think there is a way to specify if the image should be in portrait / landscape. 
If you limit the dimension to a standard one (1920x1080, ...), you should still have plenty of images but that's the only solution to your problem. You can also try to fetch images from another API with a custom user script.
