### ISSUE TITLE
Suggestions/auto-complete wikilinks for prompts

### ISSUE THREAD

**Issue by Rhydderch** [SilentVoid13/Templater#225]
**Is your feature request related to a problem? Please describe.**
I use prompts to fill in the inline variables of my templates upon creation. One of those inline variables relates to a note. So in the prompt, I have to type the exact name of the note with double brackets.

**Describe the solution you'd like**
It would be nice to have an argument to the prompt function that allows a user to specify whether the prompt should auto-suggest/auto-complete note names from the vault.
for example: `.prompt("question","", wikilink = true)`

Auto-complete would then be active and when submitting the prompt, the output would automatically have the wikilinks format : [[prompt input]]

**Additional context**
To see an example of this auto-suggest feature, one can have a look at the Buttons plugin. When using the "new button" command, it allows one to specify a template, and it automatically auto-suggest all the templates available from the template folder. So here I think that the auto-suggest feature should start as soon as one character is typed.

**Comment by SilentVoid13** [comment]
Hey @Rhydderch you can already do that with `tp.system.suggester`. Have a look at the example of the documentation, that does exactly what you want:

```js
Picked file: [[<% (await tp.system.suggester((item) => item.basename, app.vault.getMarkdownFiles(), false, "question")).basename %>]]
```

Tell me if this works the way you want it.

Documentation at https://silentvoid13.github.io/Templater/docs/internal-variables-functions/internal-modules/system-module

**Comment by Rhydderch** [comment]
Yes, it works perfectly. Thank you very much @SilentVoid13 .

**Comment by ArneNostitz** [comment]
I use this function, but was wondering if there is a way to create an empty file-link with the entered value as name when there is no match?
