### ISSUE TITLE
Templates for multiple OSs

### ISSUE THREAD

**Issue by tgrosinger** [SilentVoid13/Templater#23]
**Is your feature request related to a problem? Please describe.**

For any given template I can only provide a single command. This means writing a template which works on two operating systems (primarily when one of them is Windows) is tricky or possibly impossible.

**Describe the solution you'd like**

This could be solved by allowing the user to provide multiple commands for a template, depending on the operating system.

At execution time, there are a couple options:

- Check `window.navigator.platform` and run the correct command.
- Attempt to detect the OS by running commands known to work only on one OS (perhaps `(gwmi win32_operatingsystem).Version` on Windows, `sw_vers -productVersion` on OSX, etc)
- Just run the template command sequentially until one returns with a success code.

**Describe alternatives you've considered**

Not using Templater 😭

**Comment by shabegom** [comment]
Do you have a use case where running the same command on multiple OS fails? The only thing I could think of is running a user system command?

**Comment by liamcain** [comment]
I believe this ticket was from _way_ before Templater was using Eta.js. Now that Templater supports arbitrary JS, it's easy enough to detect the OS using `window.navigator.platform` from within the template. Closing the issue for now.
