### ISSUE TITLE
Verify if a file exists using yersterday's date as argument

### ISSUE THREAD

**Issue by PierrickGervasi** [SilentVoid13/Templater#234]
Hi, first of all thank you for the amazing plugin Templater, it has really helped me a lot in Obsidian.
I am not a pro programmer and thus I had some questions about the tp.file.exists("[[MyFile]]") function.

```
<%* if (tp.file.exists("\"\[\["+fileToVerifyExistence+"\]\]\"")) { %>
This is a seedling file !
<%* } else { %>
This is a normal file !
<%* } %>
```
When I try this, by replacing fileToVerifyExistence with either 
- "code" (the [[code]] link exists) or 
- tp.date.yersterday("YYYY-MM-DD")

The plugin tells:
" Invalid file format, provide an Obsidian link between quotes". 

I really tried my best but I can't figure out how I can do this. Could you help me, please? Thank you :)

**Comment by SilentVoid13** [comment]
Hey @PierrickGervasi, the backslashes `\` in your command are wrong, if you want to check the existence of the `[[MyFile]]` file for example, your template should look like this:

```js
<%* if (tp.file.exists("[[MyFile]]")) { %>
This is a seedling file !
<%* } else { %>
This is a normal file !
<%* } %>
```

Tell me if this works now.

**Comment by PierrickGervasi** [comment]
Hey @SilentVoid13, I didn't say what I was trying to do. I want to create a link to yesterday's note if it exists, with my daily notes.

When I try 

```
<%* if (tp.file.exists("[[code]]")) { %>
This is a seedling file !
<%* } else { %>
This is a normal file !
<%* } %>
```

It does work.

However, when I try

```
<%* if (tp.file.exists("[[tp.date.yesterday("YYYY-MM-DD")]]")) { %>
This is a seedling file !
<%* } else { %>
This is a normal file !
<%* } %>
```

it tells me in the console: "missing ) after argument list".
That's why I tried by first method but apparently it doesn't work...

Is there a way to achieve what I want?

Thank you!

**Comment by SilentVoid13** [comment]
@PierrickGervasi Okay I understand now, yes you can do that.

Try the following (you don't want variables to be in a string, you must use string concatenation):

```js
<%* if (tp.file.exists("[[" + tp.date.yesterday("YYYY-MM-DD") + "]]")) { %>
This is a seedling file !
<%* } else { %>
This is a normal file !
<%* } %>
```

Tell me if this works the way you want it to work.

**Comment by PierrickGervasi** [comment]
It works thank you so much!!

**Comment by SilentVoid13** [comment]
Alright, glad it's working.
Closing this.
