### ISSUE TITLE
CommonJS modules in script folder: Great idea, can they be used with Dataview?

### ISSUE THREAD

**Issue by Moonbase59** [SilentVoid13/Templater#236]
From an efficiency and code reusability standpoint: Fantastic idea to use a script folder and CommonJS modules.

Some questions:

1. When do they get loaded?
   - Only once on Obsididian startup?
   - Dynamically, i.e. I could add a snippet and it would somehow "see" it?

2. Are _all_ loaded? (So we have to keep the folder small?) Or do they need to be required?

3. Would they work with _Dataview JS_ (inside `dataviewjs` code blocks)?
   Now _that_ would be something …

**Comment by SilentVoid13** [comment]
Hey @Moonbase59, to answer your questions:

1. They are loaded each time you launch Templater, dynamically. I had some feedback saying it wasn't always reloading when modifying the js file, you can just reload the obsidian app if that's the case
2. **All** `.js` files are loaded inside the specified folder.
3. No, you can't access the `tp` object from the `dataviewjs` isolated environment. I don't have a good solution for this problem now.

If you feel like it, you can have a look at how js files are loaded in Templater's code here: https://github.com/SilentVoid13/Templater/blob/b9ca081f43e679744065e10608b82cd4dd297636/src/UserTemplates/UserTemplateParser.ts#L45

**Comment by Moonbase59** [comment]
Thanks for the info!
