### ISSUE TITLE
Creating dynamic link text fails since a few days

### ISSUE THREAD

**Issue by Moonbase59** [SilentVoid13/Templater#242]
**Plugin informations (please complete the following information):**
 - OS: Linux Mint 20.1/Cinnamon
 - Templater version: 1.7.1
 - Obsidian version: 0.12.3, installer 0.12.3
 - Templater settings: —

**Describe the bug**
Trying to construct an image link, I used
```
---
location: [51.133333,10.416667]
---

<%+* tR += '<' + 'img src="https://wttr.in/{0},{1}_0tqp_lang=en.png"'.format(tp.frontmatter.location[0], tp.frontmatter.location[1]) + '>' %>
```

This never worked as a real link, but at least displayed the correct text.
Now it displays part of the code plus a clickable (broken) link.

**Expected behavior**
Display
```
<img src="https://wttr.in/51.133333,10.416667_0tgp_lang=en.png">
```

**Screenshots**

![Auswahl_034](https://user-images.githubusercontent.com/3706922/119327090-e5141100-bc82-11eb-8141-dde791c62f64.png)

**Additional context**
Haven’t touched this for a few days, so last time I know it worked was using Obsidian 0.11.3 and Templater 1.6.0. In the meantime, I …
- updated Obsidian from 0.11.3 to 0.12.3
- updated Templater from 1.6.0 to 1.7.0 to 1.7.1

**Comment by welpdx** [comment]
Yeah there is something wrong with dynamic templater code as mentioned [here](https://github.com/SilentVoid13/Templater/issues/250#issuecomment-864446876).
> So far I get around it by adding ```  before and after the code. Somehow this works.

![img](https://i.imgur.com/orGHGe5.gif)

**Comment by Moonbase59** [comment]
>     * btw, this is a cool idea, mind if I steal this for my own vault? thxs

Thanks! Inspiration often comes from seeing what others do, that’s why knowledge must be freely shared. Go ahead. And thanks for your ideas.

**Comment by shabegom** [comment]
Closing as stale. If still a problem please open a new issue.
