### ISSUE TITLE
Withdrawn: Parsing Errors

### ISSUE THREAD

**Issue by eatondpe** [SilentVoid13/Templater#246]
**Withdrawn Reason:** Issue was caused by having a folder name for scripts. Even though I wasn't using that script or calling it, it throws an error.
---

**Plugin informations (please complete the following information):**
 - OS: Windows 10
 - Templater version: 1.7.1
 - Obsidian version: 0.12.3
 - Templater settings: Template folder location: "Templater/", Timeout: "5" 
 `
<%+* let edate = moment("12-24", "MM-DD"); let from = moment().startOf('day'); edate.diff(from, "days") >= 0 ? edate.diff(from, "days") == 0 ? tR += "It’s today!" : tR += edate.diff(from, "days") : tR += edate.add(1, "year").diff(from, "days") %>`

**Describe the bug**
The above script has been working until this morning. Now it throws the `unexpected identifier` error shown below.

**Expected behavior**
This should, and did as late as yesterday, return the number of days between today and the date specified - Dec 25, in this case.
I have several of these for important dates, which is very useful.

**Screenshots**
![image](https://user-images.githubusercontent.com/67427527/119527512-62588800-bd4e-11eb-8be2-60e1c37d1df2.png)

**Additional context**
This worked fine through yesterday.

**Comment by Moonbase59** [comment]
Hey, nice use of my little date calc snippet! :-)
