### ISSUE TITLE
Plugin no longer working, exception caught in developer console

### ISSUE THREAD

**Issue by macintacos** [SilentVoid13/Templater#25]
**Plugin informations (please complete the following information):**
 - OS: macOS 10.15.7
 - Templater version: 0.4.4
 - Obsidian version: 0.9.22
 - Templater settings: 

![Obsidian v0 9 22 - Wiki 2020-12-08 at 13 19 34](https://user-images.githubusercontent.com/8128941/101524528-0b095b80-3958-11eb-9709-1dee43f9312d.png)

**Describe the bug**

I'm not exactly sure what is causing this, but the plugin is no longer working; templates no longer expand when I invoke the Templater command. When it's invoked, in the developer console I see this:

```
Uncaught (in promise) TypeError: Cannot read property 'workspace' of null
    at CustomPluginTemplates.<anonymous> (app.js:1)
    at app.js:1
    at Object.next (app.js:1)
    at app.js:1
    at new Promise (<anonymous>)
    at a (app.js:1)
    at CustomPluginTemplates.e.insertTemplate (app.js:1)
    at CustomModalTemplates.t.onChooseItem (app.js:1)
    at CustomModalTemplates.t.onChooseSuggestion (app.js:1)
    at CustomModalTemplates.t.selectSuggestion (app.js:1)
```

Here are the plugins I currently have installed (they're all up to date as of right this second, I wish there was an easier way to export the current list of plugins):

![image](https://user-images.githubusercontent.com/8128941/101524335-c978b080-3957-11eb-863a-fa06c334b9bc.png)

I can verify that "regular" templates expand when I use the built-in OBsidian functionality.

**Expected behavior**
Templates expand properly

**Comment by SilentVoid13** [comment]
Hey @macintacos, this issue has been solved in Templater 0.5.0.
Update the plugin to fix this, check #21 & #24 for reference :+1:
