### ISSUE TITLE
Is `<%+*` broken?

### ISSUE THREAD

**Issue by Moonbase59** [SilentVoid13/Templater#250]
**Plugin informations (please complete the following information):**
 - OS: Linux Mint 20.1
 - Templater version: 1.7.1
 - Obsidian version: 0.12.3, installer 0.12.3
 - Templater settings: —

**Describe the bug**
I quite rely on using `<%+* …` with Templater, for Javascript dynamic commands. This worked fine before, and suddenly doesn’t.

Here is a simple example:

```
<%+*
let test = "ärzte";
tR += test.charAt(0).toUpperCase() + test.slice(1);
%>
```

**Expected behavior**
Output of `Ärzte`.

**Screenshots**

![Auswahl_063](https://user-images.githubusercontent.com/3706922/119877285-21689b00-bf29-11eb-8908-522fa7882a37.png)

![Auswahl_064](https://user-images.githubusercontent.com/3706922/119877293-2594b880-bf29-11eb-9898-8a164c6778d8.png)

**Additional context**
This worked for a lot of versions before.

To be sure it _should_ work, here is the same using a `dataviewjs` code block:

```dataviewjs
let test = "ärzte";
dv.paragraph(test.charAt(0).toUpperCase() + test.slice(1));
```

**Comment by weeyizhi** [comment]
This is listed in the documentation as a valid templater command; so I think it's more of a feature request instead of a bug. That said, one way to achieve similar results for now is to create a user-defined function and call it within `<%+`.

**Comment by welpdx** [comment]
So far I get around it by adding ``` before and after the code. Somehow this works.

![gif](https://i.imgur.com/GaRUOlW.gif)

**Comment by shabegom** [comment]
Closing as stale. If still a problem please open a new issue.
