### ISSUE TITLE
Please update File module docs so that example with rename() has "await" in front of the tp.file.rename()

### ISSUE THREAD

**Issue by MaksimZinovev** [SilentVoid13/Templater#253]
**Plugin informations (please complete the following information):**
 - OS: MacOS Catalina
 - Templater version: 1.6.0
 - Obsidian version: 0.12.3
 - Templater settings: 
   - Template folder location: "_templates/", 
   - Timeout: "5" 

**Describe the bug**

@SilentVoid13 could you please update [File module docs](https://silentvoid13.github.io/Templater/docs/internal-variables-functions/internal-modules/file-module) so that the example with rename() has "await" in front of the tp.file.rename(). 

I know there are instruction on that here https://silentvoid13.github.io/Templater/docs/commands/execution-command/
However it would be much easier for users to use tp.file.rename() and avoid raising new tickets just because many of them are like me and not very familiar with JS.  I spent quite a lot of time trying to understand why after renaming there are two identical files, old and new one, until I found out I need to use "await" in front of the tp.file.rename().

You can see that there are at least couple of tickets that were created just because people did not know about "await" in front of the tp.file.rename():
- [Can't get tp.file.rename and tp.file.move do function correctly.... · Issue #247 · SilentVoid13/Templater](https://github.com/SilentVoid13/Templater/issues/247)
- [if tp.file.rename() is called from 'Create new note from template', content is lost/pasted into the wrong file · Issue #126 · SilentVoid13/Templater](https://github.com/SilentVoid13/Templater/issues/126)

**Expected behavior**
n/a

**Screenshots**

![File Module | Templater 2021-05-29 12-24](https://user-images.githubusercontent.com/53397443/120055561-533d4700-c07a-11eb-8843-f2d2c8be0f27.jpg)

Thank you for great plugin. I use it every day :)

**Comment by SilentVoid13** [comment]
Hey @MaksimZinovev this has been fixed, thanks for the report!
