### ISSUE TITLE
Prompt not working in mobile?

### ISSUE THREAD

**Issue by dpurnomo** [SilentVoid13/Templater#254]
**Plugin informations (please complete the following information):**
 - OS: [e.g. Windows 10] iOS and iPadOS14
 - Templater version: [e.g. 0.3.4] 1.7.1
 - Obsidian version: [e.g. 0.9.11] Mobile 0.1.0
 - Templater settings: [e.g. Template folder location: "Templates/", Timeout: "5" (add the templates not working with their associated command)]

**Describe the bug**
Any templates with prompt seems not to be working. I am not sure if this is whether it cannot access or import the .js files. For example the quickadd template is working in Desktop but not in Mobile. https://github.com/chhoumann/Templater_Templates

**Expected behavior**
Prompt dialog opens

**Comment by dpurnomo** [comment]
Looking at it again, prompt works in mobile if within the .md template. But it seems that the .JS file is not accessible.

**Comment by LaP0573** [comment]
Same happens here, it seems the JS file is not imported/accessible

**Comment by ebullient** [comment]
See #223

**Comment by shabegom** [comment]
Closing in favour of #223
