### ISSUE TITLE
Cancelled prompt dialog locked the app in mobile

### ISSUE THREAD

**Issue by dpurnomo** [SilentVoid13/Templater#256]
**Plugin informations (please complete the following information):**
- OS: [e.g. Windows 10] iOS and iPadOS14
- Templater version: [e.g. 0.3.4] 1.7.1
- Obsidian version: [e.g. 0.9.11] Mobile 0.1.0
- Templater settings: [e.g. Template folder location: "Templates/", Timeout: "5" (add the templates not working with their associated command)]

**Describe the bug**
After triggering a template that ask for input, and cancelling with pressing "Esc" or by tapping outside the box, the dialog did not properly disappear and it locks the whole app. 

**Screenshots**
![66F28A43-D055-4A68-B66B-F54A1EBDF6E9](https://user-images.githubusercontent.com/19817105/120406475-1ffa0100-c375-11eb-9cd7-6e72ba358a8f.png)

**Comment by insecurejezza** [comment]
+1

**Comment by AB1908** [comment]
Could not repro on Android. Can you share the template you used?
