### ISSUE TITLE
I wanted a template to add foldername in which the file is.

### ISSUE THREAD

**Issue by dummifiedme** [SilentVoid13/Templater#26]
I tried looking the web and found Power Shell command, but I couldn't get it to work.
Can someone help me out?
I just want the Folder Name in which a current file is. 

I refered this link: https://techibee.com/powershell/powershell-get-parent-directory-name-from-file-or-directory-path/2595

**Comment by SilentVoid13** [comment]
Hey @dummifiedme, just added a new internal template: `tp_folder` (6cd8c63).
This will retrieve the folder name of the active file. You can pass the argument `vault_path=true` to append the vault relative path to the folder name.
Enjoy !

**Comment by dummifiedme** [comment]
Thanks a lot :)
