### ISSUE TITLE
Allow tp.system.suggester to provide a Title and/or Tooltip

### ISSUE THREAD

**Issue by Bejasc** [SilentVoid13/Templater#264]
**Is your feature request related to a problem? Please describe.**
Yes - I'd like to prompt the user for input from a fixed list, multiple times in one template. 
As the suggester does not currently accept any title or tooltip property, these options are prompted in a blank box.

**Describe the solution you'd like**
Allow the tp.system.suggester to take in optional parameters for tooltip and title. 

**Describe alternatives you've considered**

**Additional context**

In my specific case, I'd like to link 2x existing notes, as per the template `<% (await tp.system.suggester("Test",(item) => item.basename, app.vault.getMarkdownFiles())).basename %>`.

Each link has a different context, but when being prompted for the input, there is no way to see which context it applies to.

Now 
 - ![image](https://user-images.githubusercontent.com/12091874/122158246-76099100-ceab-11eb-8a46-770200ee51a1.png)

Desired
 - ![image](https://user-images.githubusercontent.com/12091874/122158175-52dee180-ceab-11eb-867b-a7282b7eb97d.png)

**Comment by SilentVoid13** [comment]
Hey @Bejasc, you can now specify a placeholder for `tp.system.suggester` as of Templater 1.8.0. Update and tell me if this works for you.

Documentation at https://silentvoid13.github.io/Templater/docs/internal-variables-functions/internal-modules/system-module

**Comment by Bejasc** [comment]
Hi @SilentVoid13 - Thanks for the quick action! 

I have updated to v1.8.1 of the Templater plugin. 
I'm running Obsidian v0.12.4

I can see that the `placeholder` class has been added to the element (I am unsure if this was added previously), and I can change this manually by assigning it some text value - and it does work.

---

However, it does not appear to be assigning the value that I have specified in the template itself. 
```
<% (await tp.system.suggester((item) => item.basename, app.vault.getMarkdownFiles())).basename, "Please link previous sprint plan" %
```

I have also tried the following, with the same result. 
```
<% (await tp.system.suggester((item) => item.basename, app.vault.getMarkdownFiles())).basename, false, "Please link previous sprint plan" %
```

Both attempts above result in a field with *no* placeholder visible, the same as image 1 in the original post.

**Comment by SilentVoid13** [comment]
Hey @Bejasc sorry for the late response.

You got the syntax wrong, you should pass the argument to the `tp.system.suggester` function, not after it:

```js
<% (await tp.system.suggester((item) => item.basename, app.vault.getMarkdownFiles(), false, "Please link previous sprint plan")).basename %>
```

**Comment by gmakstutis** [comment]
Is there a way to limit the suggester to files from a specific folder in the vault?

**Comment by liamcain** [comment]
> Is there a way to limit the suggester to files from a specific folder in the vault?

Sure, just filter the list:

```js
<% (await tp.system.suggester((item) => item.basename, app.vault.getMarkdownFiles().filter(file => file.path.startsWith("<path/to/folder>")), false, "Please link previous sprint plan")).basename %>
```

**Comment by gmakstutis** [comment]
Awesome! Thanks

**Comment by dredhorse** [comment]
I know this is old, but how can I get notes only from a folder with a specific tag? 😀

**Comment by AB1908** [comment]
Best use the dataview API for that else you'll have to use the metadataCache.

**Comment by dredhorse** [comment]
will take a look, will require some js but doable.

**Comment by stefanopagliari** [comment]
> > Is there a way to limit the suggester to files from a specific folder in the vault?
> 
> Sure, just filter the list:
> 
> ```js
> <% (await tp.system.suggester((item) => item.basename, app.vault.getMarkdownFiles().filter(file => file.path.startsWith("<path/to/folder>")), false, "Please link previous sprint plan")).basename %>
> ```

I would like to search among the notes in different subfolders of the same main folder. Is it possible to adapt the query you suggested to that only files in all the subfolders of a common folder are considered?

**Comment by Ninetysome** [comment]
Hello Guys, just joined this topic since I am struggling to get suggestion from a list into a specific note (instead of multiple files from a folder). Any help?

**Comment by AB1908** [comment]
Can we create separate discussions for each request please?

**Comment by Ninetysome** [comment]
> Can we create separate discussions for each request please?

My apologize for create confusion, I didn't know I had to separate discussion

**Comment by AB1908** [comment]
All good, we can't expect folks to know everything.

**Comment by Gr-Nobel** [comment]
Can i prompt a question on the Muti choice tp suggester

![image](https://user-images.githubusercontent.com/95166364/204232200-ef17b72e-5847-46cf-8f66-c1e3eca01cb6.png)

**Comment by AB1908** [comment]
I don't see why not

**Comment by Gr-Nobel** [comment]
@AB1908 thanks. I didn't knew about placeholders.
One more question: If i have 5 tp suggestor in a page. can I replace then one by one or set a order of replacement.
currently I use the command replace all templates in this file.

**Comment by Gr-Nobel** [comment]
https://github.com/SilentVoid13/Templater/discussions/935

**Comment by Gr-Nobel** [comment]
> I don't see why not

#935

**Comment by LloydHunt** [comment]
One add'l question: I'm using suggester to pull from a specific folder. Is it possible to choose from one of TWO folders ? (My code below). Thanks !
<% (await tp.system.suggester((item) => item.basename, app.vault.getMarkdownFiles().filter(file => file.path.startsWith("020 Investments/Funds")))).basename %>
