### ISSUE TITLE
Check if a file exists through the link - case senstive?

### ISSUE THREAD

**Issue by S-Wil** [SilentVoid13/Templater#267]
It appears that file.exists is not case sensitive.  For my needs I have to understand if it is an exact match but I would like to have the option to check both a case sensitive and case insensitive match if possible.

In fact, ideally what I am trying to achieve is to inherit the case of the file if it exists.

eg. if I check for a file with the name "sample title" and the file "Sample Title" exists, then I would like to use this to create a new file with the same name and case, eg. "Sample Title".

If there is any other way to achieve the above that would be great.

Thank you

### Discussed in https://github.com/SilentVoid13/Templater/discussions/150

<div type='discussions-op-text'>

<sup>Originally posted by **e5pe** April 24, 2021</sup>
Is there any way to check if a file exists throughthe link? Like a function in the [File Module](https://silentvoid13.github.io/Templater/docs/internal-variables-functions/internal-modules/file-module).

For exaple I have this template for the daily notes:

`[[<% tp.date.now("DD-MM-YYYY", -1) %>]]`

But I just want to create it if that reference has a file already because it generates a date for yesterday. 

Thank you.</div>

**Comment by JeppeKlitgaard** [comment]
This could well be a limitation of your underlying filesystem. Windows systems are typically case-insensitive.

**Comment by S-Wil** [comment]
@JeppeKlitgaard I am experiencing this on Windows.  Thanks for the feedback.
