### ISSUE TITLE
Syntax highlighting for light themes

### ISSUE THREAD

**Issue by crissxross** [SilentVoid13/Templater#268]
**Is your feature request related to a problem? Please describe.**

Unless I'm missing something, the current CSS/SCSS syntax highlighting is only effective for dark themes. I prefer to use a light theme in Obsidian. 

**Describe the solution you'd like**

Would it be possible to have syntax highlighting that works well for light themes too?

**Describe alternatives you've considered**

 I've customised a CSS snippet as a partial workaround.

**Comment by ontrou** [comment]
@crissxross Can you share your workaround snippet for those of us who also prefer light themes? That would be most helpful.

**Comment by SilentVoid13** [comment]
Hey @crissxross, you're right I only tested it on a dark theme. 

You can have a look at the `styles.css` file in the `.obsidian/plugins/templater-obsidian` folder to customize CSS color values. 

I'm not a CSS fan and I suck at design stuff, so could you share your modified CSS file with color values that would work for all light themes so I can push an update to Templater and make it available for everyone? That would be appreciated.
A theme that would work for most people would be the best.

**Comment by MaksimZinovev** [comment]
Hi. I have the same issue. Any updates? Had to switch to dark theme 🙁
