### ISSUE TITLE
embed all H2 from file

### ISSUE THREAD

**Issue by filmgal** [SilentVoid13/Templater#274]
**Question**: Is there a way to use templater to embed all H2 sections (individually would be nice) from a file? Or to the very least a way to embed an entire file but only starting at the first H2 section?

**Setup**
File A:  "Die Hard - 1988"
File B: "Die Hard - 1988 Review"
File B content: 
```
Die Hard - 1988 Review
[[Die Hard - 1988]]
Reviews:
## reviewed:: 2020-01-01
the review
## reviewed:: 2012-01-01
the review
```
In my main movie template, I want to say:
**embed each of the h2s** from the review page **individually** or, to the very least, **embed the review page but only starting at the first h2**. (Bonus would be to check if the review file exists in the first place)

**I've tried:**
`![[<%tp.file.title%> Review]]` obviously includes the entire review file.
`![[<%tp.file.title%> Review#]]` I didn't expect this to work, at least without a wildcard at the end of "#", but I didn't know what kind of wildcard to use
`![[<%tp.file.title%> Review# reviewed::]] `I don't know what I was thinking here. Just trying anything I guess.

---

Edit: I see that this file was auto "assigned" to SilentVoid13. I didn't mean for that to happen - It's more a question for other users; I just don't know where to post "how to" questions as there is no dedicated forum for these sorts of things in Obsidian.

**Comment by SilentVoid13** [comment]
Hey @filmgal, unfortunately obsidian doesn't support wildcards in headings. 

To be able to do what you want, you have to use a bit of code to find the review file, loop through the headings and include them. Here is something to get you started:

```js
<%*
const filename = tp.file.title + " Review";
const file = tp.file.find_tfile(filename);
const cache = app.metadataCache.getFileCache(file);
for (const heading of cache.headings) {
	if (heading.level == 2) {
		tR += `![[${file.basename}#${heading.heading}]]\n`;
	}
}
%>
```

Tell me if this works for you.

**Comment by filmgal** [comment]
@SilentVoid13 I cannot thank you enough!  It works perfectly, and will be great source for figuring out other things as well.
