### ISSUE TITLE
User Scripts

### ISSUE THREAD

**Issue by zephaniahong** [SilentVoid13/Templater#279]
Hi!
I followed the instructions step by step here: https://publish.obsidian.md/shabegom/Publish/How+To+Use+Templater++JS+Scripts

I created a ‘Templaters’ folder and created a file called Notice where I the following template:
<%* tp.user.notice(tp) %>

I also created a Scripts folder and created a notice.js file where I put the following:
async function notice(tp) {
const text = await tp.system.prompt(“What’s Good?”)
new Notice(text, 5000)
}
module.exports = notice

I then tried to insert the Notice template into a new file but got the following error: Template parsing error, aborting. tp.user.notice is not a function.

Hope to get some help on this!
p.s. I’ve ensured that my settings are correct i.e. specifying the scripts folder and templaters folder.

Thank you!

**Comment by dabuzon** [comment]
I am also having a similar issue except on an even simpler command of simply tp.date.yesterday(format: string = "YYYY-MM-DD"). Templater also says there's a parsing error.

**Comment by KjellConnelly** [comment]
Try a more simple function... something like:

```javascript
function notice() {
   return "My Notice"
}
```

with 

```markdown
<%* tp.user.notice() %>
```

See if that adds "My Notice". 

Off the top of my head, and I've had the same error as you before, did you check your template folder? I think the console is telling you that there is no file named `notice.js` within your template folder (template folder has to be linked ahead of time). I know you said you checked this, but thats my best guess, so you might want to double check? 

Last but no least, I noticed your markdown had an asterisk in it. I checked my code, and it doesn't have one. Not sure if it'll make a difference. I just tested with it there, and without it, and it worked both times.

```markdown
Your Code:
<%* tp.user.notice(tp) %>
```

```markdown
My Code:
<% tp.user.notice(tp) %>
```

**Comment by Creling** [comment]
Well, I have the same issue. :(

**Comment by hanxiaomax** [comment]
I have the same issue, anybody can provide a solution?

**Comment by hanxiaomax** [comment]
> I have the same issue, anybody can provide a solution?

https://forum.obsidian.md/t/user-scripts-in-templater/20504/10

check this for solution first. and be careful that the `js` file should be a javascript file , if you create it inside Obsidian, it will be `<filename>.js.md` which will not work. you should create a javascript file and use VSCode or any other editor to edit it. Obsidian should by default not detect `.js` file.
 
@Creling @zephaniahong

**Comment by Creling** [comment]
Thank you for tips !

This snippets deserves the largest font size in the docs to help fools like me. :)

>be careful that the js file should be a javascript file , if you create it inside Obsidian, it will be <filename>.js.md which will not work. you should create a javascript file and use VSCode or any other editor to edit it.

**Comment by jgarr16** [comment]
Ditto - thanks a bunch @hanxiaomax - removing the erroneously applied `.md` solved my problem. I'm surprised I didn't see this solution elsewhere (i.e., in the forums)... But glad you shared all the same.

**Comment by zephaniahong** [comment]
Apologies. Forgot to update here after replying on the obsidian forum. 

> > I have the same issue, anybody can provide a solution?
> 
> https://forum.obsidian.md/t/user-scripts-in-templater/20504/10
> 
> check this for solution first. and be careful that the `js` file should be a javascript file , if you create it inside Obsidian, it will be `<filename>.js.md` which will not work. you should create a javascript file and use VSCode or any other editor to edit it. Obsidian should by default not detect `.js` file.
> 
> @Creling @zephaniahong

The above was the solution to my problem as well!(: Thank you!
