### ISSUE TITLE
Doesn't work well with Daily Note / Calendar

### ISSUE THREAD

**Issue by dummifiedme** [SilentVoid13/Templater#28]
I am using Templater for Obsidian 0.9.22, windows x64.

Whenever I use templater by shortcut or command like, it works like charm. But when I create a daily note, there it should automatically generate things, but rather it just has the 'source text' with very little or no conversions. WHhile if I remove the text and insert template via command or hotkey, the text is correctly  populated.

**Comment by SilentVoid13** [comment]
Hey @dummifiedme, I'm not sure i understood your problem, what do you mean by 'source text' ? 
You mean that nothing gets replaced and the template keywords are still in the note ?
If so, did you enable the "overload daily notes" option in the Templater settings ?

**Comment by dummifiedme** [comment]
Yes. The keyword are still in the note. And yes, I had enabled the overload
option.

**Comment by MitPitt** [comment]
It works when you are creating today's note with "Open today's note" button, but not when creating a daily note using the calendar

**Comment by dummifiedme** [comment]
Oh. Might be the case, I use calendar to create daily note.

**Comment by SilentVoid13** [comment]
@dummifiedme that explains everything !
Templater overloads the core Daily Note plugin function.
However, the Calendar plugin uses a copy of the core Daily Note plugin but not the "real" Daily Note plugin function.
Unfortunately, I don't think there is a good solution to make Templater work with the Calendar plugin.
I'll leave this issue open for a few days in case anyone has an idea, but I will close it afterwards.

**Comment by dummifiedme** [comment]
Can you and Calendar Plugin developer have a common ground? Or shall I make a request to him to support your Plugin?

**Comment by SilentVoid13** [comment]
No, don't worry we're trying to figure something out :+1:

**Comment by SilentVoid13** [comment]
Just pushed Templater 0.5.2, this should now work well with the Calendar plugin, update and enjoy !
