### ISSUE TITLE
tp.file.last_modified_date() not updating the date!

### ISSUE THREAD

**Issue by e-alizadeh** [SilentVoid13/Templater#286]
**Plugin informations (please complete the following information):**
 - OS: Windows 10 and also iOS
 - Templater version: 1.8.1
 - Obsidian version: 0.12.5
 - Templater settings: Template folder location: "Templates", Timeout: "5", Syntax Highlighting is ON]

**Describe the bug**
The function `tp.file.last_modified_date()` does not show the last modified date. It just shows the created time, and doesn't get updated.
By hovering over the files in Obsidian Desktop (Windows 10), I can see that last modified date is correct, by having the function in my file doesn't work. 
The following is the code I'm using:
<% tp.file.last_modified_date("dddd Do MMMM YYYY HH:mm) %>

**Expected behavior**
I'm expecting the correct modified date to be shown!

**Screenshots**

**Additional context**
I've tested this issue in Windows 10, iOS, and Android, and the issue persists.

**Comment by shabegom** [comment]
Closing as stale. If still a problem please open a new issue.

**Comment by pmlefeuvre** [comment]
@shabegom, the issue persists and the following is still not updating itself on Mac Os X 11.6.2
```
modification date: <%+ tp.file.last_modified_date() %>
```

**Comment by pmlefeuvre** [comment]
@shabegom, just a short update on `<%+ tp.file.last_modified_date() %>`, the reason it failed was that I had it in my notes metadata/header. When placed inside my note the [Dynamic command](https://silentvoid13.github.io/Templater/commands/dynamic-command.html) does work.
  
```markdown
---
tags: DailyNote 2022
creation date: 2022-06-09 14:54
last modified date: <%+ tp.file.last_modified_date() %> #remains as code
---
last modified date: <%+ tp.file.last_modified_date() %> #updates 
# Daily review
```
