### ISSUE TITLE
Add prompt to suggester

### ISSUE THREAD

**Issue by pdxrlk** [SilentVoid13/Templater#291]
I have multiple suggesters within some of my templates scripts, and it isn't clear (when running the template) what each suggester is for.  

A simple solution would be to add an optional prompt parameter to tp.system.suggester.   When displaying the suggester modal, the prompt would display similarly to how it is displayed with tp.system.prompt

There aren't really any great alternatives that I could see.  

Thanks.

**Comment by SilentVoid13** [comment]
Hey @pdxrlk, `tp.system.suggester` already has a placeholder parameter to place custom text.

For example:

```js
<% tp.system.suggester(["test"], ["test"], false, "My custom placeholder") %>
```

Documentation at
