### ISSUE TITLE
Minor code issue

### ISSUE THREAD

**Issue by lishid** [SilentVoid13/Templater#30]
https://github.com/SilentVoid13/Templater/blob/8756c9b766ef4d51037c16ad7e8d61e9b5e8082a/src/main.ts#L16

I've seen another plugin do this and asking around they seemed to have followed the code in Templater.

Here, I recommend you to use an interface instead of a class for your settings - loadData returns the result of a JSON.parse() which is a plain object.

**Comment by lishid** [comment]
Well technically not a bug, should have probably used the question template instead...

**Comment by SilentVoid13** [comment]
Thanks for the suggestion, closing this.
