### ISSUE TITLE
website edit page > not found

### ISSUE THREAD

**Issue by pleabargain** [SilentVoid13/Templater#300]
website
**Describe the bug**
go to
https://silentvoid13.github.io/Templater/docs/terminology
click on edit page
takes me to 
https://github.com/SilentVoid13/Templater/docs/edit/master/docs/terminology.md

not found

**Expected behavior**
I expect to edit the page.

**Screenshots**
![image](https://user-images.githubusercontent.com/640846/126776495-b30d7b01-ed34-478d-ae61-34e6a3c4ba0d.png)

**Comment by welpdx** [comment]
Uh, is "Edit this page" was for @SilentVoid13 or for everyone? I had always thought that it was an internal link for @SilentVoid13
