### ISSUE TITLE
Templater not working on android

### ISSUE THREAD

**Issue by mr-nano** [SilentVoid13/Templater#301]
**Plugin informations (please complete the following information):**
 - OS: andriod version 9
 - Templater version: 1.8.1
 - Obsidian version: not sure how to find it on mobile...
 - Templater settings: not applicable

**Describe the bug**
After enabling the plugin, there is not templater option on the left menu bar 

**Expected behavior**
Menu bar and settings should be available

**Screenshots**
![Screenshot_20210723-234313.jpg](https://user-images.githubusercontent.com/4840723/126824062-8cd7b242-c9a2-4279-b429-f281e92a18f2.jpg), templater is enabled.

But it does not appear on the left sidebar
![Screenshot_20210723-234405.jpg](https://user-images.githubusercontent.com/4840723/126824179-171c2295-7b72-4361-b42a-1a1961e8c8aa.jpg)

And neither does it appear in the plugin options 
![Screenshot_20210723-234505.jpg](https://user-images.githubusercontent.com/4840723/126824247-ae48a87c-34da-4a6c-9aa8-a22804f35074.jpg)

**Comment by mr-nano** [comment]
any suggestions :)

**Comment by shabegom** [comment]
@mr-nano update to the latest version and see if that works

**Comment by danebace** [comment]
Hey! Can't enable on Samsung tab s6 lite Android 11. It install but then nothing happens if you choose to enable. I update, unistall and install again... It does work on my android 8 Phone. Can you help?

**Comment by shabegom** [comment]
I've confirmed Templater is working for others using Android. Make sure you are running the latest version of Obsidian and the latest version of the Templater plugin.

**Comment by danebace** [comment]
Hey,

IChek again and it doesn't open. May be is a safety measure of the samsung
tablet... Also another pluggin donet work as you see in the video. But
others do.. In my huaewwei phone it works, so must be something with the
tablet. wich someday i figure this out. Thanks

Sam ***@***.***> escreveu no dia sábado, 15/01/2022 à(s)
21:14:

**Comment by danebace** [comment]
Hey silentVoid.
Do you suggest any workaround for this?
I always get
"failed to load plugin templater obsidian" if i try to enable it.

I unistall, reinstal, restart obsidian... nothing works.
THe other pluggins i can update and are working.

Thank you

Daniel Bacellar ***@***.***> escreveu no dia domingo,
16/01/2022 à(s) 17:34:

**Comment by vincentelizalde** [comment]
Hi,

It seams like I have the same issue. 
My build is:
Android 8.0.0 (EMUI 8.0.0, it's a Huawei)
Obsidian 1.2.0 (50), API v0.14.2
Templater 1.12.0

The plugin is not running any command line, and menu bar and settings are not available.

Does anyone found a solution ?

**Comment by shabegom** [comment]
old and not reproducible - closing
