### ISSUE TITLE
Templater corrupts pasted .pngs 

### ISSUE THREAD

**Issue by retospect** [SilentVoid13/Templater#31]
**Plugin informations (please complete the following information):**
 - OS: osx 10.0.1
 - Templater version: [e.g. 0.5.3]
 - Obsidian version: [e.g. 0.10.1]
 - Templater settings: default

**Describe the bug**
Take a screenshot and paste it: (cmd-ctrl-shift-4)(cmd-v).
Image file is corrupted if the templater is on.

**Expected behavior**
The image file should not be corrupted.

**Screenshots**
<img width="402" alt="image" src="https://user-images.githubusercontent.com/430279/102738588-6eec3680-42ff-11eb-9f95-85902b2fa2f9.png">

**Additional context**
Turned off all other plugins, this one is it. No idea what it does to the files, I'll attach one here:
![Pasted image 20201220200438](https://user-images.githubusercontent.com/430279/102738720-cbe7ec80-42ff-11eb-970a-b9305be2c7b9.png)

**Comment by lishid** [comment]
Oh yeah, there's no checks for whether newly created files are `.md` or any other file type... so it basically corrupts every attachments.

**Comment by SilentVoid13** [comment]
This should now be fixed in 0.5.4, thanks for warning me and sorry for the bother !

**Comment by retospect** [comment]
I'll test it; nowhere else do you get less than 24 hour turn time on bugs :) Thanks a lot!
