### ISSUE TITLE
Frontmatter update value

### ISSUE THREAD

**Issue by hynky1999** [SilentVoid13/Templater#322]
**Plugin informations (please complete the following information):**
 - OS: [e.g. Linux Ubuntu LTS 20.04 ]
 - Templater version: [1.8.1]
 - Obsidian version: [e.g. 0.12.12]
 - Templater settings: [ Template folder location: "Templates/", Timeout: "5" ]

**Describe the bug**
I am trying to set tags in frontmatter section.
Since setting is not support by Templater function I want to do it manually.

Snippet:
```
async function rename_new_tags(tp, tR){
    let prefix = ""
    let name = "Untitled " + Math.floor(Math.random() * 100000)
	const new_name = await tp.system.prompt("Insert name below", name)
    if(!new_name === null){
        name = new_name
    }
    let tags = await tp.system.prompt("Insert tags below (comma separated)")
    if(tags){
        let tags_sp = tags.split(",")
        for( const tag of tags_sp){
            prefix += tag.trim() + " "
        }
    }
    prefix += tp.date.now()
    tR += tags
    tp.file.rename(prefix + " " + name)
   module.exports = rename_new_tags
}
```
In template I have this:
```
tags: [<%* tp.user.rename_new_tags(tp, tR) %>]
```

**Expected behavior**
Tags inserted by user should be in array

**Observed behavior**
Nothing added to tags array

**Screenshots**
![image](https://user-images.githubusercontent.com/39408646/129018979-63bc3b4c-ef2d-404d-a1f9-abd9bf000749.png)

**Comment by shabegom** [comment]
`module.exports = rename_new_tags`

needs to be outside of the function.
