### ISSUE TITLE
Set cursor location

### ISSUE THREAD

**Issue by masonlr** [SilentVoid13/Templater#33]
**Is your feature request related to a problem? Please describe.**

Is there a way that we can control the end position of the cursor when a new file is created?

A workaround is to create an empty command, for example: `{{cursor}}` mapping to `echo`

<img width="724" alt="image" src="https://user-images.githubusercontent.com/5828176/103284412-17bb2580-49d3-11eb-9ef4-ad2fce41356a.png">

Then use a template like:

```
📆 [[{{tp_yesterday}}]] – [[{{tp_tomorrow}}]]

# {{cursor}}
```

<img width="549" alt="image" src="https://user-images.githubusercontent.com/5828176/103284451-2c97b900-49d3-11eb-8a01-4f4ce8245265.png">

**Describe the solution you'd like**

The workaround breaks if you want the cursor to be in the middle of a file – e.g., templated content above and below the end cursor location.

**Describe alternatives you've considered**

The workaround above would be okay if you could control the execution order of the templating commands. A simpler solution might be to have a `{{tp_cursor}}` command that is guaranteed to run last?

**Comment by SilentVoid13** [comment]
Alright this should be good, you can now use `{{tp_cursor}}` to set your cursor to the desired location after inserting a template.
Update to 0.5.5 to test it, and tell me if there are problems !
