### ISSUE TITLE
Support tp.file.path on mobile

### ISSUE THREAD

**Issue by b0o** [SilentVoid13/Templater#334]
I store my daily notes in subdirectories of the format `YY/MM/DD.md`. My daily notes template uses `tp.file.path()` to determine the date of a daily note. This works great on desktop but it appears that `tp.file.path()` is unsupported on mobile (iOS); I get `Error_MobileUnsupportedTemplate`. Can anything be done about this?

**Comment by shabegom** [comment]
Stale, closing. If still an issue please reopen using the bug reporting template. Thanks!

**Comment by b0o** [comment]
It’s still an issue, however now I don’t get an error message, it just fails silently.
