### ISSUE TITLE
Should `tp.file.title` be updated after a move or rename command?

### ISSUE THREAD

**Issue by gtelljohann** [SilentVoid13/Templater#338]
Hi, I'm working on my default note template, in which I'm parsing the file's title, and moving/renaming it and including a specific template depending on what tag appears in the title.  For example, a new note called `@book Harry Potter` would rename it to remove the `@book`, move it to the `/books` folder, and include my Book Template.  

The issue I'm running into is that after awaiting the file rename/move operations, `tp.file.title` is still the old title.  Similarly, when the included template is processed, `tp.file.title` is also the old title.  Is this intended or should that variable be updated after renaming the file?  If it's intended, I can find another workaround.  Thanks!

**Comment by calpa** [comment]
Templater does in before the text is written down, and data viewer plugin does the dynamic rendering.

**Comment by sytone** [comment]
hit the same issue, I use `tp.config.target_file.basename` in my files to pick up the name after a move/rename
