### ISSUE TITLE
Allow using arguments with user templates

### ISSUE THREAD

**Issue by kankaristo** [SilentVoid13/Templater#34]
It would be nice to be able to use arguments with user templates.

For example, I tried to create a user template called `{{test}}`, which just echoes some text.

If I run it as-is (without arguments), it works fine.

But, I would like to use it like this: `{{test:arg1="arg1 value"}}`

Templater could define the given arguments as environment variables, before running the template command.

So, the template command could be something like: `echo "Test: $arg1"`

When run, the example command would become: `Test: arg1 value`

**Comment by Bejasc** [comment]
@SilentVoid13 any plans on supporting this in the near future?

**Comment by mvanders** [comment]
I have the same need. I wanted to run a powershell script and pass the name of the function in my powershell module:
E.g. {PS:="Get-AzureADUser - Identity 'John Doe'"} >> powershell  –noprofile (Get-AzureADUser - Identity 'John Doe')
That would be AWESOME!

**Comment by SilentVoid13** [comment]
Hey @kankaristo @Bejasc @mvanders, this has been implemented as of Templater 1.0.0!
If you update, you will now be able to pass arguments to your templates (using the new user templates syntax).
In your previous example, this would give the following definition: `<% tp.user.test({arg1: "arg1 value", arg2: "arg2 value", ...}) %>`
Arguments will be available as environment variables.
Check https://github.com/SilentVoid13/Templater#user-templates-arguments for more informations.
Tell me if this works for you.
Closing this.
