### ISSUE TITLE
Allow including template files in other template files

### ISSUE THREAD

**Issue by kankaristo** [SilentVoid13/Templater#35]
I'd like to "include" a template file within another template file.

For example, I have a YAML `frontmatter` template:
```markdown
---
aliases: []
tags: []
cssclass: []
---
```

I also have a `zettel` template, which is currently just:
```markdown
# [[{{title_without_zettel_id}}]]
```

(`{{title_without_zettel_id}}` takes in the filename and strips the Zettel ID from the beginning)

-----

Currently, if I want to have the YAML frontmatter in my Zettel template, I have 2 (bad) options:
1. copy the contents of the `frontmatter` template into all of other templates where I want to use it
    - if I ever need to change the YAML frontmatter (Obsidian adds a new feature, etc.), I would need to remember to update all of my template files (instead of just the `frontmatter` template file)
2. I need to run Templater twice
    - first for `frontmatter`, then for `zettel`

-----

I'd like to include the `frontmatter` template inside the `zettel` template, with something like:
```markdown
{{include:template=frontmatter}}

# [[{{title_without_zettel_id}}]]
```

This way, both of the above issues would be solved cleanly.

Of course, when including files like this, cyclic includes would need to be handled (if `zettel` includes `frontmatter`, but `frontmatter` also includes `zettel`). These can be fixed by either:
- a simple maximum recursion depth (more than e.g. 10 recursive includes would give an error, pretty foolproof)
- keeping a list of all included files, and checking that a newly included file isn't already in the list ("proper" way to do the check).

-----

I could achieve something similar with a `{{frontmatter}}` user template, but then I wouldn't be able to use any of my existing templates inside of that template (again, I would have to replicate a lot of the same behavior in multiple places).

Please let me know if I'm missing something, and this is already possible. :stuck_out_tongue:

**Comment by SilentVoid13** [comment]
Alright this should be good, you can now use `{{tp_include:f=<file>}}` to include a file and its content. 
It can be a template file.
Update to 0.5.5 to test it, and tell me if there are problems !
