### ISSUE TITLE
tp.file.create_new() gives console error "e.getParentPrefix is not a function" when creating note in sub-folder

### ISSUE THREAD

**Issue by Krammy** [SilentVoid13/Templater#351]
## Plugin information
 - OS: Windows 10
 - Templater version: 1.8.1
 - Obsidian version: 0.12.12

## Templater settings

**Timeout**: 5

**00_Templates/Duplicate empty note**:
```js
<%*
new_title = tp.file.title + " (2)";
console.log("New title: " + new_title);
new_folder = tp.file.folder();
console.log("New folder: " + new_folder);

await tp.file.create_new(
	template = "",
	filename = new_title,
	open_new = false,
	folder = new_folder
);
%>
```

## Bug description
Using this template only works on notes in the vault directory, using it on notes in any sub-folder logs the console error "e.getParentPrefix is not a function".

## Steps to reproduce
1. Create the *Duplicate empty note* template in your templates folder with the code above.
2. Create a new folder in your vault directory (30_Desk, for example).
3. Create a new note in that folder (Test Note, for example).
4. Use the *Duplicate empty note* template on this note.

## Expected behaviour
The note is duplicated in the same folder with the previous note's title and empty contents (30_Desk/Test Note (2)).

## Actual behaviour
The note isn't duplicated and the error "e.getParentPrefix is not a function" appears in the console.

<img src="https://user-images.githubusercontent.com/3801870/131264534-3d40a779-bc18-4aa8-8d19-0158959e8313.png" width=50% height=50%>

## Additional info
Possibly related to [this issue on tp.move not working correctly](https://github.com/SilentVoid13/Templater/issues/341).

**Comment by welpdx** [comment]
Hi @Krammy,

The problem with your script is that, according to the documents, `tp.file.create_new()` [requires a TFolder file for it's last parameter](https://silentvoid13.github.io/Templater/docs/internal-variables-functions/internal-modules/file-module/#:~:text=folder%3F%3A%20tfolder).  

You can do that by:
```
const tfile = this.app.workspace.getActiveFile();
const tfolder = tfile.parent;
```
and replacing `new_folder` with the `tfolder` variable, or however you choose to name it.

### However, once you do this, you fix your initial problem but move on to another one. 

#### New problem:
![gif](https://i.imgur.com/6l9okBn.gif)


#### New problem with troubleshooting:
![gif](https://i.imgur.com/pp4wivY.gif)

### New problem Explained:
When you create a new file:
1. It creates a file called `Untitled`
2. Templater pastes the code in this new file and runs it
3. First part of the code is mostly setting up
4. That last `tp.file.create_new()` part creates a new file with a different name: `Untitled (2)`
5. In this new file `Untitled (2)`, Templater pastes the code in this new file and runs it
6. First part of the code is mostly setting up
7. That last `tp.file.create_new()` part creates a new file with a different name: `Untitled (2) (2)`
8. In this new file `Untitled (2) (2)`, Templater pastes the code in this new file and runs it
9. First part of the code is mostly setting up
10. ...

You see the new problem right


### My Suggestion
I suggest you don't use the Empty File Template to avoid the infinite loop. (Even if it did work, you are going to create a duplicate every time you make a new note!) And instead, simply run the script manually! Just set a keyboard short cut to make your life easier...


See? 

![gif](https://i.imgur.com/Dk6fR0i.gif)

**Comment by Krammy** [comment]
Thank you @welpdx for the detailed response, as well as all of the GIFs! Great demonstration.

I had no idea about it requiring the TFolder paramter, with `tp.file.folder()` returning a string instead.

I will try this out soon and keep you posted.

**Comment by welpdx** [comment]
@Krammy np! Let me know if it works when you get around to it.

**Comment by SilentVoid13** [comment]
Thanks a lot @welpdx for the detailed answer! Closing this.

**Comment by alchemistake** [comment]
Thanks for pinging me on this issue it solved my problem as well
