### ISSUE TITLE
Textual placeholder in template prompt

### ISSUE THREAD

**Issue by davidedellagiustina** [SilentVoid13/Templater#352]
**Is your feature request related to a problem? Please describe.**
The default Obsidian template chooser prompt has a nice textual placeholder that instantly allows me to double check if I pressed the correct keyboard shortcut for inserting a new template. However, when using templater the prompt is empty and just shows the list of the possible entries, which makes me feel a little uncomfortable. (See screenshots below)

**Describe the solution you'd like**
It would be nice if the same textual placeholder could be added to Templater's prompt, too.

**Additional context**
Default templates prompt:
![immagine](https://user-images.githubusercontent.com/22601842/131582229-13b2c792-cdba-439b-b8b9-fcd183ada3e0.png)

Templater prompt:
![immagine](https://user-images.githubusercontent.com/22601842/131582276-63e7f98d-a8c0-4b30-8453-3fe1ab041d77.png)

**Comment by welpdx** [comment]
Minor enhancement but a good suggestion nonetheless. I agree, a placeholder text in the Templater template selector thingy would help.
