### ISSUE TITLE
main.ts:41 Uncaught (in promise) TypeError

### ISSUE THREAD

**Issue by patowod** [SilentVoid13/Templater#354]
**Plugin informations (please complete the following information):**
 - OS: macOS 11.5.1
 - Templater version: 1.8.1
 - Obsidian version: 0.12.15
 - Templater settings: Folder location: templates / Timeout 6 / Syntax Highlighting: on / Trigger template on new file creation: on / empty template: new note / location of scripts: media/scripts / enable system commands: off

**Describe the bug**
main.ts:41 Uncaught (in promise) TypeError: Cannot read property 'frontmatter' of undefined

**Expected behavior**
No error ;)

**Screenshots**
n/a

**Additional context**
I’m using the template and script posted here in a slightly modified version as a base: https://forum.obsidian.md/t/hooking-into-new-file-creation/15683/5. That said, template creation on new file trigger works and the file is renamed with zettel uid + title given in the prompt. Within the template Templater is invoked through <%* tp.user.zettler(tp); %> However, following appears in the console log: 

`
Uncaught (in promise) TypeError: Cannot read property 'frontmatter' of undefined 
    at ActiveNoteTitlePlugin.refreshTitle (eval at <anonymous> (app.js:1), <anonymous>:158:72) 
    at ActiveNoteTitlePlugin.eval (eval at <anonymous> (app.js:1), <anonymous>:94:26) 
    at step (eval at <anonymous> (app.js:1), <anonymous>:79:23) 
    at Object.eval [as next] (eval at <anonymous> (app.js:1), <anonymous>:60:53) 
    at eval (eval at <anonymous> (app.js:1), <anonymous>:53:71) 
    at new Promise (<anonymous>) 
    at __awaiter (eval at <anonymous> (app.js:1), <anonymous>:49:12) 
    at ActiveNoteTitlePlugin._this.handleRename (eval at <anonymous> (app.js:1), <anonymous>:91:55) 
    at t.e.tryTrigger (app.js:1) 
    at t.e.trigger (app.js:1) 
`

I debugged the script line by line and the console error appears only upon execution of the last command 

`
await tp.file.rename(`${filename}`);
`

The syntax appears right to me, so I assumed bug report is the most applicable category. Any help or insight would greatly be appreciated. Besides that I'd like to say thanks for this great plugin.

**Comment by welpdx** [comment]
Try ``await tp.file.rename(`${filename}`);`` instead of `await tp.file.rename(${filename});`. 

[The script and setup that peterw wrote](https://forum.obsidian.md/t/hooking-into-new-file-creation/15683/4) worked very well for me. 

If you still have issues, can you show us your modified code? The error codes that console spits out is like gibberish to me and as a hobbist, I debug templater scripts solely with console.log() and `new Notice("Somefing Wong!",2000);` lol.

**Comment by patowod** [comment]
So, I guess it's now working as expected within my vault. For whatever reason my brain may have had an expectation mismatch. I just added an additional

`if (title.startsWith("Untitled") || title === '') {
      title = await tp.system.prompt("Title");
     }`

before the first if clause. This way I can use the template on file creation. If having a zettel with "zid Untitled" the original if clause works as expected, as well. Yay 🎉
