### ISSUE TITLE
tp.file.cursor() after setting note title

### ISSUE THREAD

**Issue by sammosna** [SilentVoid13/Templater#359]
**Plugin informations:**
 - OS: macOS 11.5.2
 - Templater version: 1.8.1
 - Obsidian version: 0.12.15

Hello there, when I create a new note with the _Trigger Templater on new file creation_ enabled, the first `<% tp.file.cursor() %>` is being triggered instantly making impossible to choose the name of the note.

Is it possible to invoke `<% tp.file.cursor() %>` after the title has been put?

**Comment by welpdx** [comment]
Hey @sammosna,

In your template/script, replace `<% tp.file.cursor() %>` with `<%* tp.file.cursor() %>`. 

See if that helps.

Welp

**Comment by SilentVoid13** [comment]
Hey @sammosna this automatic cursor jump is now disabled by default on 1.9.9.
You can configure a hotkey to manually trigger `tp.file.cursor` in obsidian settings.

You can enable the "Automatic jump to cursor" option in the settings if you want this behavior back.

**Comment by sammosna** [comment]
Hi @welpdx, excuse me for not getting back to you until now, but it does not work.. 
If I disable automatic jump and I use a hotkey it works but I'm wondering if it's possible to invoke the _automatic jump to cursor_ after entering the note's name. Thank you!
