### ISSUE TITLE
Nested User Templates

### ISSUE THREAD

**Issue by benwalio** [SilentVoid13/Templater#36]
**Is your feature request related to a problem? Please describe.**
I would like the ability to add Internal Templates and User Templates inside of other User Templates. This is specifically for the system command calls. So having something like: `date -j -f "%Y-%m-%d_%a" "{{tp_title}}" +"%A, %d %B %Y"` as a user template extends usage of the {{tp_title}} template and feeds it through a date converter.

Specifically, I'd like to be able to create back-dated daily notes (through the Calendar) without the interference of having to mess with multiple templates or manual interaction of having to fix links and titles.

**Describe the solution you'd like**
I'd like the Templater to execute the Internal Templates first, then execute the User Templates. If it comes across a `{{X}}` in the User Templates for the system commands, check and see if a template matches `{{X}}` and fill in the appropriate details before passing as a system command.

**Comment by benwalio** [comment]
I don't know much ts so forgive me here, but it looks like there's already something very similar in line 15 of the 'internal_command_templates.ts' script.

**Comment by kofm** [comment]
This would be awsome.
It will allow e.g. to add appointments from khal like so: `khal list {{tp_title_date}}`

**Comment by SilentVoid13** [comment]
Hey @benwalio @kofm, this has been implemented as of Templater 1.0.0!
If you update, you will now be able to use all internal templates inside your system commands.
Check https://github.com/SilentVoid13/Templater#internal-templates-in-user-templates.
Closing this.
