### ISSUE TITLE
Suggestion: Replace moment.js

### ISSUE THREAD

**Issue by itpropro** [SilentVoid13/Templater#362]
Hi,
I really love to use Templater, I just think that moment.js should be replaced for multiple reasons:
- Due to it's legacy design (non-pure functions and mutable due to OOP APIs) it can produce bugs, which happened in the past and which is one of the reasons, the project has been deprecated/finished
- The size of alternatives like luxon or day.js is much smaller (day.js 2kb Gzipped)
-  Compared with modern libraries like day.js it is relatively slow
- When accessing the moment API directly, day.js has a simpler syntax for many functions, but is still familiar for people that know moment already

I am aware that these points might not be that important in the context of Obsidian, but I wanted to raise them anyway. It's just a suggestions, I am looking forward to your feedback and keep up the good work with Templater :)

**Comment by liamcain** [comment]
The main benefit to keeping `moment.js` is that it comes bundled with Obsidian. That means plugins don't need to worry about bundle size. Also by default, the moment.js instance in Obsidian is locale-aware so plugins don't need to worry about additional date localization.

**Comment by shabegom** [comment]
moment is built into Obsidian.

**Comment by itpropro** [comment]
> moment is built into Obsidian.

I know that, but that doesn't address any of the listed points above, right? I don't think either bundle size, or localization is a problem when replacing it. It makes no notable difference with one or two calculations, but when handling a bunch of maybe more complex date calculations, it would make sense to replace moment.
