### ISSUE TITLE
Templater not working

### ISSUE THREAD

**Issue by antoniocanas** [SilentVoid13/Templater#366]
**Plugin informations (please complete the following information):**
 - OS: Macos / Android
 - Templater version: 1.8.1
 - Obsidian version: 0.12.15
 - Templater settings: trigger on

**Describe the bug**
Templater examples doesn't work as expected. But it works inside buttons plugin code

**Screenshots**
<img width="827" alt="Screenshot 2021-09-13 at 09 33 53" src="https://user-images.githubusercontent.com/1630864/133043311-ab3dde1b-f395-45c2-a30a-317397cfc630.png">

**Comment by welpdx** [comment]
Hello @antoniocanas,

Make sure to add an asterisk `*` after `<%`.  I.e.: ` <%* tp.date.now() %> `. See if that fixes your problems! :D

By the way, do you want to run this in template or dynamic mode?

Welp~

**Comment by antoniocanas** [comment]
Ok the plus sign fixed it. It was a little bit hidden in the docs :)

Thanks!

**Comment by welpdx** [comment]
np! Yea it is a bit hidden. Imma link it here just in case for others
[Templater Open Tags](https://silentvoid13.github.io/Templater/docs/commands)

**Comment by hawkiboy** [comment]
Hi, I am new and confuse. How do I find out what  template or dynamic mode? I have watched a ton of videos and am baffled. I followed exactly the Obsidian Plugins: Templater (Part 1 - Date Module) by [Productivity Guru](https://www.youtube.com/channel/UC_Xx2woqzPkcvG_ea5d276A)
and the simple date just shows as today: <%* tp.date.now() %>. 
I tried to add the+ and the* (and have no idea where this concept comes from after reading everything I could find) and it did not change anything.
If I 'replace template' then it seems to work. But I am confused about what is going on with the built-in templates vs templater.

**Comment by henrik** [comment]
welpdx's link above no longer works, but these are the current docs: https://silentvoid13.github.io/Templater/commands/overview.html

> Templater defines 2 types of opening tags, that defines 2 types of commands:
> 
> <%: Interpolation command. It will output the result of the expression that's inside.
> <%*: JavaScript execution command. It will execute the JavaScript code that's inside. It does not output anything by default.
> The closing tag for a command is always the same: %>
