### ISSUE TITLE
Add ability to write comments for templates

### ISSUE THREAD

**Issue by Trimple** [SilentVoid13/Templater#369]
Hello. Is it possible to make some kind of ignored syntax so that we can write comments to our templates without those comments being added to the target file while using a template? 

I don't know how hard it can be, but I think it can be useful, especially for those, who share their templates a lot.

**Comment by itpropro** [comment]
You can just use standard Javascript comment syntax like this:

```markdown
<% tp.date.now("YYYY-MM-DD", -1, tp.file.title, "YYYY-MM-DD") %>
<%* 
/* Your multi-line 
comment goes here */ 
%>
### **Fancy markdown** <%* // Single comment %>
More __markdown__
```

Would render like this

```markdown
2021-09-23

### **Fancy markdown** 
More __markdown__
```

**Comment by SilentVoid13** [comment]
Thanks @itpropro for answering this!
