### ISSUE TITLE
How can I get an alternative date formatting based on file.title date

### ISSUE THREAD

**Issue by DryIce1** [SilentVoid13/Templater#378]
Problem
- In my daily note, I want to display the date in this format `dddd Do MMMM, YYYY`
- I sometimes make the Daily Note ahead of time, so I want Templater to pull from the Title of the note. And not the current date.
- my attempts are throwing an error message 

Reproduced by the following code;
- `<% tp.date.now("YYYY-MM-DD", 0, tp.file.title, "dddd Do MMMM, YYYY") %>`

expected result for today would be;
- `Friday 24th September, 2021`

Actual result:
- error 
![image](https://user-images.githubusercontent.com/59501376/134592884-e2624811-f8a3-4946-a07c-db55fe107047.png)
- no change to the code

Thanks in advance!

**Comment by itpropro** [comment]
Hi @DryIce1, you are using the parameters in the wrong order. Referring to the [documentation](https://silentvoid13.github.io/Templater/docs/internal-variables-functions/internal-modules/date-module), the first parameter is the target format and the last the reference format. If your note has the title `2021-09-24` and you want it to be displayed as `Friday 24th September, 2021`, use `<% tp.date.now("dddd Do MMMM, YYYY", 0, tp.file.title, "YYYY-MM-DD") %>`.

**Comment by SilentVoid13** [comment]
Hey @DryIce1 as @itpropro said (thanks for the answer), you use the parameters in the wrong order.
