### ISSUE TITLE
Make hotkeys field wider and show assigned keys?

### ISSUE THREAD

**Issue by luckman212** [SilentVoid13/Templater#390]
**using v1.9.5**

I am really happy you added the native hotkey assignment function to Templater, so I don't need the separate Hotkeys for Templates anymore (still, thank you for your plugin @Vinzent03 !)

Would it be at all possible to make the fields that show the hotkeys wider (it cuts off a lot right now)? and also display the chosen hotkey?

![CleanShot 2021-09-29 at 17 59 34](https://user-images.githubusercontent.com/1992842/135354724-445e95e1-c411-4b9c-8b15-df2ab0622c0f.png)

...more like the way the native hotkeys window does:

![image](https://user-images.githubusercontent.com/1992842/135354772-95738e7e-3a2e-4fab-845c-a9d6f77458b5.png)

**Comment by SilentVoid13** [comment]
Hey @luckman212, thanks for the suggestion it was looking fine on my theme, my bad. Should be fixed on 1.9.6.
About the chosen hotkey, the obsidian API doesn't offer a way to view associated hotkeys, that's why I'm just redirecting to the hotkey setting tab when clicking on the icon.

**Comment by luckman212** [comment]
Perfect, looks great now! 👍  
Thank you so much.
