### ISSUE TITLE
Templater stopped working after latest update

### ISSUE THREAD

**Issue by gfidias** [SilentVoid13/Templater#392]
**Plugin informations (please complete the following information):**

-   OS: macOS 11.6
-   Templater version: 1.9.5
-   Obsidian version: 0.12.15
-   Templater settings: Template folder location: "003_templates/", Timeout: "5" 

**Describe the bug**
Thanks for your efforts but currently nothing works:
- Existing variables, that were working just fine, now not updating.
- Trying to insert template into a file: "Templater Error: Template parsing error, aborting." (no problem with these templates before).
- Creating new file with a template: "Assignment to constant variable." (no such problem before).

**Expected behavior**
The old version's behavior, the one that worked

**Screenshots**
n/a

**Additional context**
I have come to rely heavily on templater
so I reverted to 1.9.5 for the time being
Thanks again

**Comment by SilentVoid13** [comment]
Hey @gfidias, It's hard to tell you what's not working with these informations, could you show me the console error output? (Run `Ctrl+Shift+I`)

**Comment by gfidias** [comment]
OK, here it is:

**1. When creating a new Daily Notes file using a template:** 

Templater Error: Template parsing error, aborting. 
Assignment to constant variable.
log_error @ Log.ts:17


**2. When creating a new file**

Log.ts:17 Templater Error: Template parsing error, aborting. 
 Assignment to constant variable.
log_error	@	Log.ts:17
eval	@	Error.ts:16
rejected	@	tslib.es6.js:74
Promise.then (async)		
step	@	tslib.es6.js:75
eval	@	tslib.es6.js:76
__awaiter	@	tslib.es6.js:72
errorWrapper	@	Error.ts:11
eval	@	Templater.ts:258
eval	@	tslib.es6.js:76
__awaiter	@	tslib.es6.js:72
overwrite_file_commands	@	Templater.ts:251
eval	@	Templater.ts:397
fulfilled	@	tslib.es6.js:73
Promise.then (async)		
step	@	tslib.es6.js:75
eval	@	tslib.es6.js:76
__awaiter	@	tslib.es6.js:72
on_file_creation	@	Templater.ts:356
eval	@	EventHandler.ts:60
e.tryTrigger	@	app.js:1
e.trigger	@	app.js:1
t.trigger	@	app.js:1
t.onChange	@	app.js:1
e.trigger	@	app.js:1
(anonymous)	@	app.js:1
(anonymous)	@	app.js:1
(anonymous)	@	app.js:1
(anonymous)	@	app.js:1
o	@	app.js:1
e.reconcileFileCreation	@	app.js:1
(anonymous)	@	app.js:1
(anonymous)	@	app.js:1
(anonymous)	@	app.js:1
s	@	app.js:1
Promise.then (async)		
l	@	app.js:1
(anonymous)	@	app.js:1
o	@	app.js:1
e.reconcileFileInternal	@	app.js:1
(anonymous)	@	app.js:1
(anonymous)	@	app.js:1
(anonymous)	@	app.js:1
s	@	app.js:1
Promise.then (async)		
l	@	app.js:1
(anonymous)	@	app.js:1
o	@	app.js:1
e.reconcileFile	@	app.js:1
(anonymous)	@	app.js:1
(anonymous)	@	app.js:1
(anonymous)	@	app.js:1
(anonymous)	@	app.js:1
o	@	app.js:1
e.reconcileInternalFile	@	app.js:1
(anonymous)	@	app.js:1
(anonymous)	@	app.js:1
(anonymous)	@	app.js:1
s	@	app.js:1
Promise.then (async)		
l	@	app.js:1
s	@	app.js:1
Promise.then (async)		
l	@	app.js:1
(anonymous)	@	app.js:1
o	@	app.js:1
(anonymous)	@	app.js:1
n	@	app.js:1
Promise.then (async)		
e.queue	@	app.js:1
e.write	@	app.js:1
(anonymous)	@	app.js:1
(anonymous)	@	app.js:1
(anonymous)	@	app.js:1
s	@	app.js:1
Promise.then (async)		
l	@	app.js:1
(anonymous)	@	app.js:1
o	@	app.js:1
t.create	@	app.js:1
(anonymous)	@	app.js:1
(anonymous)	@	app.js:1
(anonymous)	@	app.js:1
(anonymous)	@	app.js:1
o	@	app.js:1
e.createNewMarkdownFile	@	app.js:1
(anonymous)	@	app.js:1
(anonymous)	@	app.js:1
(anonymous)	@	app.js:1
(anonymous)	@	app.js:1
o	@	app.js:1
e.createAndOpenMarkdownFile	@	app.js:1
callback	@	app.js:1
EE	@	app.js:1
e.executeCommandById	@	app.js:1
eval	@	VM202:100
o	@	VM202:23
e.onTrigger	@	app.js:1
e.handleKey	@	app.js:1
e.onKeyEvent	@	app.js:1

**3. When inserting a template in existing file**

Log.ts:17 Templater Error: Template parsing error, aborting. 
 Assignment to constant variable.
log_error	@	Log.ts:17
eval	@	Error.ts:16
rejected	@	tslib.es6.js:74
Promise.then (async)		
step	@	tslib.es6.js:75
eval	@	tslib.es6.js:76
__awaiter	@	tslib.es6.js:72
errorWrapper	@	Error.ts:11
eval	@	Templater.ts:198
eval	@	tslib.es6.js:76
__awaiter	@	tslib.es6.js:72
append_template_to_active_file	@	Templater.ts:184
onChooseItem	@	FuzzySuggester.ts:50
t.onChooseSuggestion	@	app.js:1
t.selectSuggestion	@	app.js:1
e.useSelectedItem	@	app.js:1
e.onSuggestionClick	@	app.js:1
s	@	app.js:1

**4. When creating a new note from open insert template modal**

Log.ts:17 Templater Error: Template parsing error, aborting. 
 Assignment to constant variable.
log_error	@	Log.ts:17
eval	@	Error.ts:16
rejected	@	tslib.es6.js:74
Promise.then (async)		
step	@	tslib.es6.js:75
eval	@	tslib.es6.js:76
__awaiter	@	tslib.es6.js:72
errorWrapper	@	Error.ts:11
eval	@	Templater.ts:198
eval	@	tslib.es6.js:76
__awaiter	@	tslib.es6.js:72
append_template_to_active_file	@	Templater.ts:184
onChooseItem	@	FuzzySuggester.ts:50
t.onChooseSuggestion	@	app.js:1
t.selectSuggestion	@	app.js:1
e.useSelectedItem	@	app.js:1
(anonymous)	@	app.js:1
e.handleKey	@	app.js:1
e.onKeyEvent	@	app.js:1

**Comment by SilentVoid13** [comment]
@gfidias Thank you, can you show me your template file? Also try uninstalling Templater and re-installing it, tell me if this works.

**Comment by gfidias** [comment]
I have many templates - none works.
Here is an example:

[[<% tp.date.now("YYYY-MM-DD", -1, tp.file.title) %>]] ⋮ [[<% tp.date.now("YYYY-MM-DD", +0, tp.file.title)%>]] ⋮ [[<% tp.date.now("YYYY-MM-DD", 1, tp.file.title) %>]]

## ToDo

```tasks
due on <%tp.date.now("YYYY-MM-DD", +0) %>
```

**Comment by SilentVoid13** [comment]
@gfidias everything works fine on my end, even on a fresh vault. Try uninstalling and reinstalling Templater.

**Comment by gfidias** [comment]
No, still not working here

**Comment by SilentVoid13** [comment]
Hmm that's weird, it fixed it for someone else encountering the same problem, re #391. Can you show me a screenshot of your settings? I'm running out of ideas here

**Comment by gfidias** [comment]
I created a new, empty vault and tested templater in it.
Seems to work there.
Maybe some kind of conflict with other plugins?

**Comment by SilentVoid13** [comment]
If it's working in an empty vault, it must be something like that yeah. Try disabling all other plugins except Templater, reload obsidian and test if it works.

**Comment by gfidias** [comment]
my settings

![1](https://user-images.githubusercontent.com/23036873/135498185-f15f5c2c-f196-4be4-97ca-a59b7be6fa78.jpg)

**Comment by gfidias** [comment]
Still not working after disabling all other plugins

**Comment by SilentVoid13** [comment]
I'm almost sure uninstalling / reinstalling fixes the problem. Try manually deleting the `.obsidian/plugins/templater-obsidian` folder in your vault and reinstall from the store.

**Comment by gfidias** [comment]
done that already (kept my data.json file)
not working

**Comment by SilentVoid13** [comment]
okay but that's the old `data.json` with the old setttings that makes it crash :sweat_smile: (No idea why though)
you can try to manually copy the json keys you want to keep from the old to the new after it gets created.

**Comment by gfidias** [comment]
yep, working :)
can't believe it was so simple
I had checked the data.json file before and after - the updated templater should accept the old data.json
Don't understand what happenedm but, hey, if it works, it works

**Comment by SilentVoid13** [comment]
@gfidias Glad to hear that! That's a very weird bug, not sure what's causing it. Could you link your old data.json file so I can investigate the cause of the error?

**Comment by luckman212** [comment]
FYI... I came to report the same problem with 1.9.6

when triggering a simple text-based template via Hotkey:
![image](https://user-images.githubusercontent.com/1992842/135502221-3e62a5bf-d619-4acc-ba1a-a7bf8041dbd1.png)

when creating a new empty note in any folder:
![image](https://user-images.githubusercontent.com/1992842/135502228-58a4a5e2-8d7d-4e3e-a7f7-0e3acc929125.png)

**Comment by luckman212** [comment]
I will try cleaning my JSON like @gfidias - hope that works

**Comment by gfidias** [comment]
Seems I was quick to rejoice.
User system command functions still do not work.
This is what I get:

UserSystemFunctions.ts:57 Uncaught (in promise) TypeError: Assignment to constant variable.
    at UserSystemFunctions.eval (eval at <anonymous> (app.js:1), <anonymous>:3438:25)
    at Generator.next (<anonymous>)
    at fulfilled (eval at <anonymous> (app.js:1), <anonymous>:50:58)
eval	@	UserSystemFunctions.ts:57
fulfilled	@	tslib.es6.js:73
Promise.then (async)		
h	@	app.js:1
e.onRender	@	app.js:1
requestAnimationFrame (async)		
Xe	@	app.js:1
e.queueRender	@	app.js:1
e.set	@	app.js:1
t.set	@	app.js:1
(anonymous)	@	app.js:1
(anonymous)	@	app.js:1
(anonymous)	@	app.js:1
s	@	app.js:1
Promise.then (async)		
l	@	app.js:1
(anonymous)	@	app.js:1
o	@	app.js:1
t.setMode	@	app.js:1
(anonymous)	@	app.js:1
(anonymous)	@	app.js:1
(anonymous)	@	app.js:1
(anonymous)	@	app.js:1
o	@	app.js:1
t.setState	@	app.js:1
(anonymous)	@	app.js:1
(anonymous)	@	app.js:1
(anonymous)	@	app.js:1
(anonymous)	@	app.js:1
o	@	app.js:1
t.setViewState	@	app.js:1
eval	@	main.tsx:745
a	@	main.tsx:745
eval	@	VM208:36240
wrapper	@	VM208:54
eval	@	VM209:106
E	@	VM209:91
eval	@	VM241:100
o	@	VM241:23
checkCallback	@	app.js:1
EE	@	app.js:1
e.executeCommandById	@	app.js:1
eval	@	VM241:100
o	@	VM241:23
e.onTrigger	@	app.js:1
e.handleKey	@	app.js:1
e.onKeyEvent	@	app.js:1

**Comment by gfidias** [comment]
I'm tired, reverting to 1.9.4 till problem is fixed.
Thanks

**Comment by SilentVoid13** [comment]
@gfidias @luckman212 This should be fixed in 1.9.8. Sorry for the inconvenience, my tests should have caught that bug.

**Comment by luckman212** [comment]
@SilentVoid13 I poked around in my data.json for a while. All settings from the "old" one are fine with the exception of the `templates_pairs` array. Once I add those back in, the whole thing blows up and stops working. So strange as I haven't changed those in months. Something about how they are being parsed is different I guess.

In case it helps, here is a working `data.json`:
```json
{
  "command_timeout": 5,
  "enable_folder_templates": true,
  "enable_system_commands": true,
  "enabled_templates_hotkeys": [
    "templates/Links.md",
    "templates/YAML frontmatter tags AND keywords.md",
    "templates/tags from current file as YAML.md"
  ],
  "folder_templates": [
    {
      "folder": "",
      "template": ""
    }
  ],
  "shell_path": "/usr/local/bin/homebrew_bash",
  "startup_templates": [
    ""
  ],
  "syntax_highlighting": true,
  "templates_folder": "templates",
  "trigger_on_file_creation": false,
  "user_scripts_folder": ""
}

```
and a non-working one:
```json
{
  "command_timeout": 5,
  "enable_folder_templates": true,
  "enable_system_commands": true,
  "enabled_templates_hotkeys": [
    "templates/Links.md",
    "templates/YAML frontmatter tags AND keywords.md",
    "templates/tags from current file as YAML.md"
  ],
  "folder_templates": [
    {
      "folder": "",
      "template": ""
    }
  ],
  "shell_path": "/usr/local/bin/homebrew_bash",
  "startup_templates": [
    ""
  ],
  "syntax_highlighting": true,
  "templates_folder": "templates",
  "templates_pairs": [
    [
      "lorem_short",
      "curl 'http://asdfast.beobit.net/api/?type=paragraph&length=1&startLorem=false' | jq -r '.text'"
    ],
    [
      "lorem_long",
      "curl 'http://asdfast.beobit.net/api/?type=paragraph&length=3&startLorem=false' | jq -r '.text'"
    ],
    [
      "yaml_tags_from_csv_list",
      "printf '%s\\n%s\\n' \"---\" \"tags:\"\necho \"$sel\" | ~/Sync/Scripts/csvtolist\nprintf '%s\\n' \"---\""
    ],
    [
      "yaml_tags_from_csv_inline",
      "echo \"$sel\" | ~/Sync/Scripts/wordstocsv"
    ],
    [
      "google_search_sh",
      "printf '%s' \"[$q_name](https://google.com/search?q=$q_uri)\""
    ]
  ],
  "trigger_on_file_creation": false,
  "user_scripts_folder": ""
}
```

**Comment by SilentVoid13** [comment]
@luckman212 yep that was a stupid error on the way I handle templates_pairs, sorry for the inconvenience and thanks for investigating!

**Comment by luckman212** [comment]
@SilentVoid13 Thanks, yes 1.9.8 is working with the original `data.json` now. Whew!

1 new issue (at least for me) is `<% tp.file.cursor() %>` isn't working on folder based templates. I filed a separate issue though— #393

**Comment by gfidias** [comment]
Yes, everything working now
