### ISSUE TITLE
using tp.file.cursor() on folder based new file template?

### ISSUE THREAD

**Issue by luckman212** [SilentVoid13/Templater#393]
I have a folder-based new file template like this:

```md
---
tags: [foo, bar]
client: <% tp.file.cursor() %>
---

- [ ] Do something
```

As of 1.9.8, it doesn't work -- the Eta piece after `client:` remains after the file is created and the cursor doesn't go there. I saw https://github.com/SilentVoid13/Templater/issues/359 which seems related. When I substituted `<%* tp.file.cursor() %>`  as suggested there, the Eta code disappears, but again the cursor isn't positioned there. Is there any workaround?

**Comment by Zebrazilla** [comment]
I can confirm that I am having this issue too. I'm not quite sure as of how long this would have been an issue as I haven't updated in a while.

**Comment by andrej1919** [comment]
Since 1.9.8 update I am having this issue too. I am absolutely positive since I made some notes on previous version today and it worked just fine. After update to 1.9.8 cursor stays on the note title and on the desired position of the cursor is the code: `<% tp.file.cursor() %>`

**Comment by SilentVoid13** [comment]
Hey @luckman212 you can now set the "Automatic jump to cursor" in the settings (disabled by default) on 1.9.9 to automatically trigger `tp.file.cursor` after inserting a template. Added this behavior for folder-based templates.

**Comment by luckman212** [comment]
This is excellent! Thank you @SilentVoid13 – it's working fine for me on 1.9.9

**Comment by andrej1919** [comment]
Thank you @SilentVoid13! It works on 1.9.9.
