### ISSUE TITLE
Default template for a given folder

### ISSUE THREAD

**Issue by trydalch** [SilentVoid13/Templater#394]
While most of my vault is flat and doesn't use folders, I have used folders to organize my timestamped files. I have a journal folder, a health journal folder, and other daily folders. Every page in that folder has has the same structure.

**Describe the solution you'd like**
I would like to set the default template for a given folder so that when a new file is created inside it, the default template is automatically applied.

**Describe alternatives you've considered**
Right now I just insert the template using the command pallet every time.

**Comment by SilentVoid13** [comment]
Hey @trydalch this already exists! Check folder templates in the settings (requires "Trigger on new file creation" to be enabled), this is exactly what you want.

**Comment by trydalch** [comment]
Hmm. I had enabled this, but all I got were empty files. 

I've read the documentation, and it's not clear to me how to configure it to do this.

I have 3 folders that I would like to setup this way:

- `timestamps/journal`
- `timestamps/health-journal`
- `timestamps/gospel-study`

How would I configure each of them to have a different default template that is triggered every time a file is created in each folder?

**Comment by SilentVoid13** [comment]
@trydalch did you update Template to 1.9.8? The setting looks like this:

![image](https://user-images.githubusercontent.com/51264226/135728677-12c3fb39-7383-4616-a21b-687051dde1ef.png)

This is pretty self-explanatory, you put the folder on the left and the asociated template on the right.

**Comment by trydalch** [comment]
Ah. I hadn't updated. So used to everything automatically updating that I forgot to check it. I now see the settings just as you pictured above.
