### ISSUE TITLE
Obsidian Mobile (iPadOS 15) - Modals run in reverse order

### ISSUE THREAD

**Issue by williamvz** [SilentVoid13/Templater#396]
**Plugin informations:**

-   OS: iPadOS 15
-   Templater version: 1.9.8
-   Obsidian version: 1.0.4
-   Templater settings: default settings. Current making my first steps in Templater so nothing changed. 

**Describe the bug**
I have a template that consists of three modals. When running the template though, the modals are displayed in reverse order. 

**Expected behavior**
I expect the modals to run top to bottom and not the other way around. 

**Screenshots**
https://user-images.githubusercontent.com/37240069/135745266-206cd407-4c75-4193-8a22-14a9fb7392ce.MOV

**Additional context**
Na.

**Comment by SilentVoid13** [comment]
Hey @williamvz, this isn't a bug, it comes from the fact that `tp.system.prompt` is an asynchronous function.
This means that the order the functions is "random", to force a synchronous you can add `await` in front of the functions:

```
<% await tp.system.prompt("Prompt 1") %>
<% await tp.system.prompt("Prompt 2") %>
<% await tp.system.prompt("Prompt 3") %>
```
