### ISSUE TITLE
Templater not working after update to 1.9.9

### ISSUE THREAD

**Issue by VKondakoff** [SilentVoid13/Templater#398]
**Plugin informations (please complete the following information):**

-   OS: macOS 11.6, iOS 15.1
-   Templater version: 1.9.9
-   Obsidian version: 0.12.16

1. After updating to 1.9.9. Templater forgets the 'Template folder location' value. That's it: this field is empty after update. This was reproduced both on macOS and iOS.
2. A small template does not work anymore after update to 1.9.9. It was launched by 'New file creation' trigger. The trigger is still on, but the Template does not seems to work. Here is a template in question:
```
<%* switch(tp.file.folder(false)) {
	case '':
		break;
	case 'Daily notes':
	tR+='%% [[' + tp.file.folder(false) + ']] %%\n\n'
		break;
	default:
	tR+='[[' + tp.file.folder(false) + ']]\n\n'
	} %>
```

<img width="641" alt="Снимок экрана 2021-10-04 в 19 39 13" src="https://user-images.githubusercontent.com/230824/135890631-325aae21-f809-4dc6-a5f1-0f48de21a0b3.png">

Something to do with new Folder Templates feature? Currently I have disabled the Folder templates, but my template still does not work.
3. The is nothin like 'Loading Templater plugin' in Developer console. Is this expected?
<img width="544" alt="Снимок экрана 2021-10-04 в 19 42 28" src="https://user-images.githubusercontent.com/230824/135890675-9932be1d-6c0f-495e-9528-f4a237b48da7.png">

**Comment by jd-santos** [comment]
> 2. A small template does not work anymore after update to 1.9.9. It was launched by 'New file creation' trigger. The trigger is still on, but the Template does not seems to work. Here is a template in question:

This broke for me as well. There was a setting for a default new file template that appears to be gone. My entire templating system was based off of this, I'm not sure what happened.

**Comment by SilentVoid13** [comment]
Hey @VKondakoff @jd-santos about the empty file template, it now has been replaced with folder templates in the settings. 
You can set a template to the root `/` folder if you want the old behavior back.

About the "Folder template location", try removing it and re-setting it, it might be using the old setting.
