### ISSUE TITLE
tp_include doesn't recursively execute user-defined templates

### ISSUE THREAD

**Issue by benwalio** [SilentVoid13/Templater#40]
**Plugin informations (please complete the following information):**
 - OS: OSX, most recent
 - Templater version: 0.5.5
 - Obsidian version: 0.10.7
 - Templater settings: /assets/templates/, timeout 5

**Describe the bug**
When using the new {{tp_include}} (amazing btw!) functionality, it correctly recursively executes the built in {{tp_*}} templates, but not user defined ones, like weather

**Expected behavior**
I would expect the templater to recursively execute both built in and user defined templates

**Screenshots**
<img width="646" alt="Screen Shot 2021-01-08 at 15 57 36" src="https://user-images.githubusercontent.com/13092287/104063568-5ff3f800-51ca-11eb-8c58-45744791e119.png">

<img width="516" alt="Screen Shot 2021-01-08 at 15 57 42" src="https://user-images.githubusercontent.com/13092287/104063579-63877f00-51ca-11eb-8eae-10b4fab4ac85.png">

<img width="417" alt="Screen Shot 2021-01-08 at 15 57 53" src="https://user-images.githubusercontent.com/13092287/104063580-65514280-51ca-11eb-8fa3-c4352c9c8143.png">

**Comment by SilentVoid13** [comment]
Nice catch ! I'll fix that tomorrow and push a new release, thanks for the reactivity on this !

**Comment by benwalio** [comment]
no problem! I'm trying to fix it myself, but i'm stumbling through setting up an env right now for testing. love the plugin!
