### ISSUE TITLE
tp.file.creation_date gets unix epoch date instead of file date

### ISSUE THREAD

**Issue by jojobyte** [SilentVoid13/Templater#400]
**Plugin informations (please complete the following information):**

-   OS: Pop!_OS 21.04
-   Templater version: 1.9.9
-   Obsidian version: v0.12.15
-   Templater settings: 
 -   Folder location: "Templates/"
 -  Template Used: Quick Example from https://silentvoid13.github.io/Templater/docs/#quick-example

**Describe the bug**
`tp.file.creation_date()` (likely only on linux / Pop!_OS) is returning `1969-12-31 17:00` which appears to be the Unix Epoch time. It does not appear to matter if the file has existed for a while, been copied from another directory, created via another program or terminal or within Obsidian itself.

```md
<!--- This code in a template -->
---
creation date: <% tp.file.creation_date() %>
modification date: <% tp.file.last_modified_date("dddd Do MMMM YYYY HH:mm:ss") %>
---

<!--- Is creating this code in a new file -->
---
creation date: 1969-12-31 17:00
modification date: Tuesday 5th October 2021 19:05:39
---
```

**Expected behavior**
```md
<!--- Should create something similar to this in a new file -->
---
creation date: Tuesday 5th October 2021 19:05:39
modification date: Tuesday 5th October 2021 19:05:39
---
```

**Comment by mufidu** [comment]
Same for me, I'm using elementary OS which is also an Ubuntu-based Linux distro. For me, it returns `Thursday 1st January 1970, 07:00`.

**Comment by AB1908** [comment]
Can you check if the creation date is the same at the filesystem level and also at the Obsidian metadataCache level? I've seen this happen a few times on Android but Licat has never commented on it (to my knowledge).

**Comment by mufidu** [comment]
Yep, they're the same.

**Comment by shabegom** [comment]
That command is just reading the created/modified date from the file as set in obsidian. I believe if there is an error it is upstream of the plugin. Closing.

**Comment by Talk2Giuseppe** [comment]
This bug is still resident as of August 19, 2026.

Since the developers of the plugin can't seem to fix it after nearly 5 years, does anyone have a genuine replacement for this issue?

**Comment by Zachatoo** [comment]
Store the creation date in properties/frontmatter instead, don't trust the OS to accurately preserve created/modified dates.
