### ISSUE TITLE
cursor placement is broken after recent updates

### ISSUE THREAD

**Issue by vitaly** [SilentVoid13/Templater#404]
**Plugin informations (please complete the following information):**

-   OS: Mac
-   Templater version: 1.9.9
-   Obsidian version: 12.15

**Describe the bug**

I have the following temlate:
~~~markdown
```dataview
<%tp.file.cursor(1)%>
```
~~~

**Expected behavior**

I expect an empty line with cursor in it, inside the dataview block. instead I just get the template as is.

**Comment by SilentVoid13** [comment]
Hey @vitaly, check out #399 #397 #393 #401 for more infos.
