### ISSUE TITLE
Templater formatting javascript code blocks even when syntax highlighting setting is turned off

### ISSUE THREAD

**Issue by GitMurf** [SilentVoid13/Templater#405]
Even when turning off the Syntax Highlighting setting it appears that for javascript code blocks Templater is trying to format them and in my vanilla default Obsidian theme it makes it pretty un-readable. Here is what it looks like with Templater enabled and even with Syntax Highlighting setting turned off.

![image](https://user-images.githubusercontent.com/64155612/136883955-95bb4917-8f95-463e-ab4c-d05befd5bdd1.png)

Here is what it should look like and when I have Templater turned off.

![image](https://user-images.githubusercontent.com/64155612/136883972-b44527e1-8f85-49cb-b662-18212addbd99.png)

**Comment by GitMurf** [comment]
Just posted this today (below) in Discord forgetting that I already submitted this issue last month haha. Any updates on this or any way this could be fixed @SilentVoid13 ? thanks!

Anyone else notice that with Templater installed even after disabling Syntax Highlighting setting it still does some syntax highlighting for javascript code blocks and in dark mode they do not work well. 1) would be nice if there was a compatible color scheme for dark mode and 2) most importantly, wondering why it stays on even when you disable the setting? @SV any ideas? Thanks!

**Comment by shabegom** [comment]
Syntax highlighting is broken in CM6 closing in favor or #491
