### ISSUE TITLE
tp.file.include not working on mobile

### ISSUE THREAD

**Issue by AtlcatlQ** [SilentVoid13/Templater#414]
**Plugin informations (please complete the following information):**

-   OS: Android EMUI 10
-   Templater version: 1.9.9
-   Obsidian version: 1.0.4
-   Templater settings: [e.g. Template folder location: "Templates/", Timeout: "5" (add the templates not working with their associated command)]

**Describe the bug**
include function in the file module doesn't work. throws templater parsing error

**Expected behavior**
function work properly.

**Screenshots**
![gif](https://user-images.githubusercontent.com/87624226/137562722-678f291d-c4f0-4c55-9e74-f79a7ed5377b.gif)

**Comment by shabegom** [comment]
Is this still an issue? I'm able to use `tp.file.include` on mobile.

**Comment by AtlcatlQ** [comment]
It's works perfectly!!! Thanks.
