### ISSUE TITLE
Templater doesn't use front matter

### ISSUE THREAD

**Issue by louiss0** [SilentVoid13/Templater#415]
**Plugin informations (please complete the following information):**

-   OS:  Windows 10
-   Templater version:  1.9.9
-   Obsidian version: [e.g. 0.12.15]
-   Templater settings: [
- Folder templates { 
- [/ , Resources/templates/Main Note.md]
- ]
- Trigger Templater on new file creation : true
- Automatic jump to cursor :true
- ]

**Describe the bug**

When I tried to display my front matter I got a bug the front matter is not being used at all

```

___

aliases: []
tags: []
note type: Main
___


Created:  <%  tp.date.now()  %>      <% moment().format("HH:mm:ss") %>

Note  type:  <% JSON.stringify(tp.frontmatter) %>

# <%  tp.file.title  %>
	<% tp.file.cursor(1) %>




```

turns into 

```
___

aliases: []
tags: []
note type: Main
___


Created:  2021-10-16      21:57:37

Note  type:  {}

# Untitled 1
```

**Expected behavior**

I thought i could use front matter but I can't ` tp.frontmatter ` returns an empty object I don't know why

**Screenshots**

**Additional context**

**Comment by shabegom** [comment]
Same as #449

A workaround is mentioned in that issue.
