### ISSUE TITLE
Cannot create a new note using Template Hotkeys (configuration allowed by templater to bind to hot keys)

### ISSUE THREAD

**Issue by Fierce-Ninja** [SilentVoid13/Templater#425]
**Plugin informations (please complete the following information):**

-   Windows 10
-   Templater version: 1.9.9
-   Obsidian version: 0.12.19

**Describe the bug**
NOT sure if this is a bug or just me doing something dumb.  
I cannot create a new note using Template Hotkeys. 
I created a couple of Template Hotkeys in Templater settings where I bound some specific templates to a hotkey. When I open Obsidian and no file is open, I try creating a new note using the Template hotkeys. But nothing is created and I get the error "no active view. can't append templates".  On the other hand, if I already have a note open, then the hotkey would work.

**Expected behavior**
A new note should be created with the template when pressing the Template Hotkeys even if no file is open.

**Comment by OfficerHalf** [comment]
I don't think this is a bug since the hotkey command reads "Insert" and not "Create New", but I do have the same feature request to also add a command for creating a new file with a specific template.

**Comment by pbienst** [comment]
I don't think this is what's being talked about in #73, which is just about having a hotkey to create a new new from a template, and then having a modal dialog to select the template.

The current bug report is about assigning a specific hotkey to create a new note from a specific template, without needing to select from a dialog.

Perhaps this issue can be reopened?

**Comment by AB1908** [comment]
You can assign a template to a hotkey. This inserts in active file. However, you can also create a templater script that creates a new file with a specific template and assign that template to a hotkey to get what you want. I know this sounds confusing so feel free to ask any questions.

**Comment by pbienst** [comment]
Does this also work when no file is open? Would you mind clarifying with an actual script? Thanks!

**Comment by AB1908** [comment]
Should work. Templater script should look something like:

```js
<%*
await tp.file.create_new(TemplateTFile, other args);
// other commands
%>
```

Assign this template to a hotkey to create a new file via hotkey. Or maybe even look at using QuickAdd.

**Comment by pbienst** [comment]
I'm afraid that workaround still suffers from the problem the OP mentioned. If you do it on a pane without a note, you get "no active view. can't append templates". (Besides, if you do it from an open note, that messes up the content of that note...)

**Comment by AB1908** [comment]
Oh hmm, I see. I guess QuickAdd is better for this then.
