### ISSUE TITLE
tp.date.now is not resolving in DNP on new note creation

### ISSUE THREAD

**Issue by ktitong02** [SilentVoid13/Templater#426]
**Plugin information (please complete the following information):**

-   OS: Windows 10
-   Templater version: 1.9.9
-   Obsidian version: 0.12.19

**Describe the bug**
After using the template for 2 months. This is the first time I experience this "bug" wherein tp syntax is not working properly.  I did not do any configurations lately.
![tp_issue](https://user-images.githubusercontent.com/70008108/138864119-a960eea9-0008-40a9-b320-6cb3e085fd29.png)

**Expected behavior**
Please see the screenshot. It was working previously.
![tp_expected_output](https://user-images.githubusercontent.com/70008108/138864171-81076232-8abc-4710-85c5-fcdcf8815ae4.PNG)

Thank you.

**Comment by Bejasc** [comment]
Same for me also. If I run the Replace Templates in Active File command, it works, but they are not working on template insert.

**Comment by elenapalesis** [comment]
I was having the same issue but I found that the `Trigger Templater on new file creation` setting was toggled off, even though I don't remember adjusting that setting.

**Comment by venatiodecorus** [comment]
Same issue, but `Trigger Templater on new file creation` is on. I still need to manually trigger the template for anything to show up.

**Comment by shabegom** [comment]
Is this still an issue? Are there any errors in the dev console?
