### ISSUE TITLE
Request: Add a general and an individual Template Hotkeys option to delete the content of the file before applying a template

### ISSUE THREAD

**Issue by mikkovedru** [SilentVoid13/Templater#427]
**Is your feature request related to a problem? Please describe.**
I am using this plugin https://github.com/dvcrn/obsidian-filename-heading-sync to sync the filename with the first heading. Not using the plugin is not an option, because generally it is very convenient and saves a lot of time. Unfortunately, the use of the sync plugin with the Templater causes problems.

There is no reasonable solution that could be applied in the other plugin; the changes, if they come, have to be made in Templater.

### What I want to achieve:
1. I create a new file.
2. Start typing name either fully or at least the first character.
3. Press hotkey that applies my meta template, which applies a more specific template based on the first character(s) of the file name. Something like this:
```
<%* if (tp.file.title.charAt(0) == "@") { %>
<%-tp.file.include("[[@ person template]]")%>
<%* } else if (tp.file.title.charAt(0) == "+") { %>
<%-tp.file.include("[[+ video template]]")%>
<%* } else if (tp.file.title.charAt(0) == "%") { %>
<%-tp.file.include("[[% social template]]")%>
<%* } else if (tp.file.title.charAt(0) == "~") { %>
<%-tp.file.include("[[~ pics template]]")%>
<%* } else { %>
<%-tp.file.include("[[normal template]]")%>
<%* } _%>
```
you get the idea.
4. PROFIT

### What actually happens:
1. I create a new empty file
2. I start writing the name
3. Writing the name automatically creates the first heading in the text.
4. Applying meta template makes it append to the first heading (so first comes the automatic heading, then the frontmatter, then the heading I want, and then the rest of the content).
5. Since frontmatter won't even work if it is not the very first in the file, I have to delete the title and do extra work to reorganize the document.
6. At this time the sync plugin takes the other header and changes the file name to something I don't want to.
7. And since Obsidian doesn't provide a proper Undo for the file name text (when changed by the plugin), I can't get my well-thought-out file name back... You can't imagine how irritating this is!..

It's a big mess...

What could I do instead? I could use the "Templater: Create new note from template" hotkey and select a specific template (can't use the meta-template because can't get a read on the file name as that doesn't exist yet). This defeats the main purpose of first-character(s) grouping and the whole idea behind the meta-template. It makes creating and operating notes way less convenient.

But when it actually gets worse is when I want to create a file from another already existing note. 

1. When writing a note I create a bunch of links to non-existing notes that I plan to work on someday. 
2. This "someday" arrives.
3. I click on the non-existent file name. The file with that name is created.
4. The automatic header is also created now.
5. I am applying the meta-template, which appends the content..
6. bla-bla-bla
7. DISASTER

The situation is much worse, because with the automatic file name and the lack of undoing, the file name in the starting note is also changed and is lost forever (since Obsidian doesn't support the Undo in non-opened files). And I may have created the original note years ago, so now there is no chance I will remember exactly how brilliantly I formulated the name to fit the existing notes' context.

It's a truly hair-pulling situation!..

And everything would be fixed by having the ability to apply the template to an empty file.

**Describe alternatives you've considered**
When talking about the template language, I was trying to fix the issue here, but couldn't find a way:
- `tp.file.include([[TemplateX]])` simply appends the template, without an option to overwrite the file
- `tp.file.create_new` - creates a new file. I couldn't find the ability to overwrite the currently active file either. There is an `open_new: boolean = false` optional parameter, but it only indicates if the new (second) file should also be opened in the editor.
- In documentation I encountered the [config module](https://silentvoid13.github.io/Templater/docs/internal-variables-functions/internal-modules/config-module) with the mention of `tp.config.run_mode` and an interesting-sounding name of the mode [`OverwriteActiveFile`](https://github.com/SilentVoid13/Templater/blob/master/src/Templater.ts#L26), but I have no idea what that actually is and how to use it (even if it is applicable to my situation).

**Describe the PRIMARY solution you'd like**
1. A general toggle in settings "Delete content of the file before applying the template".
2. The same individual toggle for each of the Template Hotkeys.

**Describe the additional solutions you'd like**
Would be nice to have a programmatically easy way of applying a template to a new file. The way I see it, it can be done in 3 different ways.
1. `tp.file.create_new` could include a new optional `overwrite_active_file` variable (false by default)
2. `tp.file.include` could include a new optional `overwrite_active_file` variable (false by default)
3. an entirely new function like `tp.file.overwrite_current`.

I think that 2 and 3 would be the best choices. `tp.file.create_new` is quite complex and perhaps overloaded already.

**Other**
Thank you for a great plugin, for all the work you do! Thank you in advance for even considering my suggestion.

**Comment by shabegom** [comment]
You could overwrite the file:

```
<%*
const file = tp.file.find_tfile(tp.file.title)
await app.vault.modify(file, "")
%>
```
