### ISSUE TITLE
Template parsing error while using tp.web.random_picture

### ISSUE THREAD

**Issue by chomarian** [SilentVoid13/Templater#433]
Template that uses `<% tp.web.random_picture("250x250") %>` function  has become broken after unknown event, might be after an update. It says: "Template parsing error, aborting".

If I delete this function from the template leaving other ones, it is parsed ok.

![Obsidian_2jxFnAfOJb](https://user-images.githubusercontent.com/21067296/140297068-7a28cc54-817f-4c4d-9ec6-1af0e154b2ee.png)

**Comment by JunerLee** [comment]
same problem
`ping https://source.unsplash.com`
Request Timed Out，I think it is something wrong with Unsplash.

**Comment by shabegom** [comment]
seems to be working now
