### ISSUE TITLE
provide API to other plugins who want to use templates

### ISSUE THREAD

**Issue by trashhalo** [SilentVoid13/Templater#438]
**Is your feature request related to a problem? Please describe.**

I am the author of https://github.com/trashhalo/obsidian-webhooks I'd like to use your template engine for events if the user has your plugin installed. Things like inserting today's date and stuff.

**Describe the solution you'd like**

I know this is possible because dataview offers an API and 3rd party plugins use it.

**Describe alternatives you've considered**

**Additional context**

**Comment by z2k-gwp** [comment]
If possible, I too would love to request api level access to Templater. E.g., I have a string in my plugin that has templater commands inside it - I'd love to call an exported function on the plugin (or a npm'd library ala Daily Notes) that allows templater to perform its handywork and then let my own plugin continue afterwards.
