### ISSUE TITLE
Trigger Templater on new file creation freezes Obsidian in case of sync and copy of large .md files

### ISSUE THREAD

**Issue by zsviczian** [SilentVoid13/Templater#439]
Excalidraw generates large .md files, at times well over 1MB in size. The file includes the drawing JSON and an SVG snapshot both fenced off as code blocks. When making a copy of a large drawing using Obsidian File Explorer, Obsidian freezes and won't react to anything. This can take a very long time (there were cases when I waited 20 minutes before in the end killing Obsidian). 

It seems Trigger Templater on new file creation is also triggered when synchronizing a file from another computer for the first time. This results in Obsidian freezing during sync. In such cases, Obsidian needs to be terminated and restarted and the issue is resolved. 

I recommend one of two solutions:
- a frontmatter tag to tell Templater not to process the file. I would then include this in the Excalidraw file template to avoid future issues.
- Templater skipping codeblocks

See related discord discussion here: https://discord.com/channels/686053708261228577/840286264964022302/907305782217965588

A likely linked Excalidraw issue is here: https://github.com/zsviczian/obsidian-excalidraw-plugin/issues/235

![image](https://user-images.githubusercontent.com/14358394/140793095-421a3061-c359-4160-8ab8-27eabd6fefcb.png)

![image](https://user-images.githubusercontent.com/14358394/140792851-bdadea1d-c3f7-4f44-b397-94e7b0b0c3fb.png)

**Comment by shabegom** [comment]
should be fixed in 1.14.14
