### ISSUE TITLE
tp.file.include return object promise instead of emoji

### ISSUE THREAD

**Issue by Mara-Li** [SilentVoid13/Templater#445]
**Plugin informations (please complete the following information):**

-   OS: Windows 11 & Ipad OS 15.1
-   Templater version: 1.9.9
-   Obsidian version: 1.0.5 (IpadOS)
-   Templater settings: 
	- Template settings : `Ressource/Templater`
	- Timeout: 5

**Describe the bug**
Emoji return [object promise] when called with `<% tp.file.include([[file]]) %>`

Function in the file : 
```js
# GenerateEmoji
<%* 
const folderName = tp.file.folder(true);
const emojidict = {
'M2-1. Anglais': '🇬🇧',
'M2-2.': '🔢',
'M2-17.': '☣️',
'M2-18.': '🧰',
'M2-21.': '🦺',
'M2-22': '🛂',
'M2-23': '🦀',
'M2-25.': '🩹',
'M2-25A.': '🦠',
'02.' : '🦠'
};
let emoji = '';
for (const key in emojidict) {
if (folderName.includes(key)) {
emoji = emojidict[key];
}
}
return emoji;
%>
```
Emoji called with `<% tp.file.include('[[category#generateEmoji]]') %>`

**Expected behavior**
A simple emoji. 

**Additional context**
- Error doesn't appear if the function is directly used (copy/paste)
- Error doesn't appear with normal text

**Comment by shabegom** [comment]
Add `await` to the include to resolve the promise?

**Comment by liamcain** [comment]
I think this is just an issue with the documentation not being very clear that `include` is asynchronous. I made a note that this could be improved in the documentation.

**Comment by Mara-Li** [comment]
Thanks :)

**Comment by huyz** [comment]
@liamcain where is that note to improve the documentation? I'm going to create an [issue](https://github.com/SilentVoid13/Templater/issues/720)–feel free to close if it's redundant
