### ISSUE TITLE
{{tp_date}} doesn't work for a few days now

### ISSUE THREAD

**Issue by dummifiedme** [SilentVoid13/Templater#45]
**Plugin informations (please complete the following information):**
 - OS: Windows 10
 - Templater version: 0.5.7
 - Obsidian version: 0.10.7
 - Templater settings: 
    ![image](https://user-images.githubusercontent.com/68785729/104833451-be059700-58be-11eb-96c6-b4ba75cf7015.png)

**Describe the bug**
The {{tp_date}} command isn't doing what it's supposed to. It just days as is. Screenshot Attached.

**Expected behavior**
The date should print.

**Screenshots**
![image](https://user-images.githubusercontent.com/68785729/104833442-afb77b00-58be-11eb-8a56-c593cc44d6bc.png)

**Comment by SilentVoid13** [comment]
Hello @dummifiedme, it looks like a bug on your side. 
Just tested the `{{tp_date}}` on a fresh new test vault and it's working perfectly. Do you have any messages in the console ? Try reloading obsidian and reloading the Templater plugin. Tell me if this fixes it.

**Comment by dummifiedme** [comment]
It autoatically got resolved. I don't know how :) 
I did wait for a few days, and restarts and re-installs to be sure on my part. 

Really sorry :)

**Comment by jlojosnegros** [comment]
Hi,
This problem is happening to me right now.
I have tried both reloading obsidian and with a freshly new created vault and still does not work.

obsidian v0.11.13
templater v1.5.4

**Comment by SilentVoid13** [comment]
Hey @jlojosnegros, have a look at the options to enable some settings (re #119)
