### ISSUE TITLE
Dynamic command doesn't render in PDF generation

### ISSUE THREAD

**Issue by mlisthenewcool** [SilentVoid13/Templater#454]
**Plugin informations (please complete the following information):**

-   OS: [Ubuntu 20.04]
-   Templater version: [1.9.9]
-   Obsidian version: [0.12.19]

**Describe the bug**
`<%+ tp.file.last_modified_date() %>` is displayed *as it* when using PDF generation.
On a side bug, the command is not working properly when only closing file. You have to reload Obsidian to get it working.

**Expected behavior**
Should render the correct formated date.

**Comment by shabegom** [comment]
This is the expected behaviour.
