### ISSUE TITLE
How to get last week, next week?

### ISSUE THREAD

**Issue by eryajf** [SilentVoid13/Templater#457]
I read the document, but I couldn't find a way to get these two times.
This requirement is currently implemented using system commands:

```
lastweek date -v -1w '+%Y-W%W'
nextweek date -v +1w '+%Y-W%W'
```

The calling method is as follows:

`<<[[<% tp.user.lastweek() %> | last week's weekly note]] | [[<% tp.user.nextweek() %> | next week's weekly note]]>>`

Is there a simpler way?

**Comment by shabegom** [comment]
You could use momentjs for this:

`<% moment().add(1, "week").format("YYYY-MM-DD") %>`

And `subtract()` for last week.
