### ISSUE TITLE
Internal Command Template: fully qualified filename of current note

### ISSUE THREAD

**Issue by workflowsguy** [SilentVoid13/Templater#46]
**Is your feature request related to a problem? Please describe.**
I have some use cases where a script would need to know where the file is actually located in the file system.
The {{note_title}} template only passes the name of the current note to an external command. 

**Describe the solution you'd like**
A command template like ```{{note_fullpath}``` that is the fully qualified name of the current note file, (e.g. ```/Users/guy/ownCloud/Notes/2015-07-30T0719 - Buffer.md```)

**Describe alternatives you've considered**
I have not found any alternative solutions

Thanks,
Guy

**Comment by SilentVoid13** [comment]
That's a good idea, I'll probably add that for the next release. Thanks for the suggestion !

**Comment by luckman212** [comment]
This would be great for sure!

**Comment by SilentVoid13** [comment]
Hey @workflowsguy @luckman212, this has been implemented as of Templater 1.0.0. 
If you update, you will now be able to use `<% tp.file.path() %>` to get the full path of a note.
Closing this.

**Comment by luckman212** [comment]
@SilentVoid13 Great, thank you! I'm still trying to wrap my head around all the changes in 1.x.x so I'll post back if anything. This is a whopper of an update.
