### ISSUE TITLE
Using a Templater template in a Templater teplate - How and is it advisable

### ISSUE THREAD

**Issue by 42sol-eu** [SilentVoid13/Templater#466]
I was wondering if I could include a template file in a template.

My use case: I have a great template for a Admonition box with prompting for title, text and collapsed state.
I want to use a daily journal and insert one (or more) of this boxes without only copying the code inside the other template.

I guess it should be possible.
The question is if it is also advisable and how many nesting levels would be needed to break either my brain or my second brain (Obsidian)

**Comment by AB1908** [comment]
Pardon me if I'm misunderstanding but can't you insert templates with hotkeys on the fly to achieve this?

**Comment by 42sol-eu** [comment]
That might be a valid solution or maybe a work around. I will try that!

I would like to share the following use case:

-  my daily journal page is created by a template
-  I want to add day and week navigation to it on top and on the bottom
- On workdays it should include my active projects as headings
- A nice quote in a neat box would be great to
- Maybe a list of my active calendar entries or some other special user function powered features

so my hotkey dance would start to be quite a thing also including much cursor placements

Yes this also might be solved by copying the navigation code in the template, but copying starts to produce messy results.

**Comment by AB1908** [comment]
My suggestion would be to create a daily journal template and add some JavaScript handling to work for those special conditions like workdays. Not sure how to do your last bullet though. You also might want to look into folder templates since it'll automatically apply the template for a particular folder.

Templates work perfectly fine in conjunction with Daily Notes, I use it myself.

**Comment by shabegom** [comment]
You can do this with `tp.file.include()`. If you include another template all the commands run as well. I use this to build up templates from smaller commands.

**Comment by 42sol-eu** [comment]
Great! Thank You!
Another option would be to work with Buttons from the great Button Plugin ...
