### ISSUE TITLE
Is Dynamic Template selection possible?

### ISSUE THREAD

**Issue by insecurejezza** [SilentVoid13/Templater#47]
I'm not great with Regex or command line.

Was wondering if it would be possible in theory with current capabilites of the plugin to create a single template that dynamically selects an appropriate template based on the content of the Note Title.

For example, if the note title contain the word "Note" it would use the Note template in the template folder. If it contains "Journal" it would use the Journal template.

Just thinking that this would have great synergy with Note Refactor plugin that allows you to use Templater macros but only has space for one template. A dynamic template would make a lot of note making workflows smoother.

Would love if someone could share some speculative code that I can try to apply.

**Comment by SilentVoid13** [comment]
Hey @insecurejezza, dynamic templates like you describe are not possible in Templater.
That's a good idea though, but I'm not sure how I could implement something like that.
Do you want this feature just to avoid having to select a template in the modal that pops up ?

**Comment by insecurejezza** [comment]
Not necessarily to avoid the modal, although that would remove a few key strokes.

My main use case is to make it play well with the Note Refactor Plugin. It allows you to split a single note into multiple seperate notes based on heading conditions (eg. Everything under an H1 heading becomes it's own note and the first line becomes the note name). It also applies a user defined template to the new note. Templaters internal templates are already compatible with the with note refactor, but I can only define one template. A dynamic capability would just mean that notes that are refactored will have a template applied to them that are appropriate to the note time, reducing the friction of having to go into each individual note and add the appropriate template manually.

I think having dynamic template capabilities would open up a lot more opportunities beyond my very specific (and selfish) use case though.

**Comment by SilentVoid13** [comment]
Hey @insecurejezza coming back at you because, as of Templater 1.0.0, what you describe is now possible.

You can now have a dynamic template that does something depending on the note's title, here's an example:

```ts
<%* if (tp.file.title.includes("Note")) { %>
Do stuff ...
<%* } else { %>
Do other stuff 
<%* } %>
```
Check https://github.com/SilentVoid13/Templater#eta-features for more informations.

Tell me if this works for you.
Closing this.
