### ISSUE TITLE
Send argument with templater command

### ISSUE THREAD

**Issue by paulrudy** [SilentVoid13/Templater#479]
I'm trying to set up a button, using the Buttons community plugin, that will tell Templater to populate a template based on attributes of the current file. Another use case for what I'm after, without Buttons, would be a template that grabs a variable from the current note for use in the new note. 

To do so, it would be helpful to pass agruments to Templater. I'd like this to work on mobile too, so that the solution doesn't require user scripts. An example of something that would be useful: a fifth argument to `tp.file.create_new` containing the arguments I want to pass.

I've attempted to use solutions found in https://github.com/SilentVoid13/Templater/discussions/453, and included this question in https://github.com/SilentVoid13/Templater/discussions/478#discussion-3753936

**Comment by shabegom** [comment]
Hey @paulrudy, did I solve this issue in the discord? If yes, please close this. Thanks!

If no... then my memory isn't as good as I thought it was.

**Comment by paulrudy** [comment]
Yes @shabegom you did, thank you! Using the buttons plugin in concert with your solution doesn't work due to limitations with that plugin, but simply passing an argument with templater to a templater template does work. Here's what I have based on your suggestions, for people who want a solution or starting point:


```
<%*
const arg = tp.frontmatter.arg
const template = `---
arg: ${arg}
---
`
tp.file.create_new(template, 'my/new/file')
%>
```

>Another variation is using include and then running a .replace to add the argument where you want. Imagining the argument is stored in frontmatter

```
<%*
const arg = tp.frontmatter.arg
const template = await tp.file.include("[[Template]]")
const final = template.replace("$ARG",arg) //$ARG is put in the template where you want to replace with the argument
tp.file.create_new(final, "New Note")
%> 
```
