### ISSUE TITLE
Can I declare variable in the markdown and do some query?

### ISSUE THREAD

**Issue by calpa** [SilentVoid13/Templater#48]
I want to make a dynamic query based on the parameters provided in the markdown file, is it possible with using this plugin?

**Comment by SilentVoid13** [comment]
Hey @DaveHenning, sorry for the late response.
Templater had a huge update recently. It now has a new syntax.
You are now able to add control flow in your templates. I'm not sure if that answers your question, but you can now create "dynamic" templates having different outputs depending on the markdown file properties (title, folder, ...) they are executed on.  
Check the documentation for more informations: https://silentvoid13.github.io/Templater/docs/

**Comment by calpa** [comment]
Thank you @SilentVoid13, I think frontmatter module is suitable for my use case.
