### ISSUE TITLE
Daily Quote function is not working

### ISSUE THREAD

**Issue by rapatel0** [SilentVoid13/Templater#481]
`tp.web.daily_quote()` not working. Internet connectivity is confirmed. the command was run multiple times after obsidian restarts to see if the it was a transient error. Looks like something is going wrong with QORS

Error in Obsidian:
![image](https://user-images.githubusercontent.com/18704704/146936302-228eef5a-3c9f-4bd7-aed4-acd255375130.png)

Quote endpoint seems to be working
![image](https://user-images.githubusercontent.com/18704704/146936831-131f2ff1-4538-4f9a-9ec6-8565e7be8db2.png)

-   OS: Mac OS 11.6.1
-   Templater version: 1.9.9
-   Obsidian version: 0.13.3

**Comment by om23** [comment]
https://quotes.rest/ certificate also expired today so tp.web.daily_quote() is failing

**Comment by perfctl** [comment]
back to using random quotes from quotable.io
https://gist.github.com/ScottKillen/ec858f6f7014fc41451b71e805413794

**Comment by shabegom** [comment]
An alternative qotd command:

```
<%*
const response = await fetch(`https://api.quotable.io/random`);
const     qod = await response.json();
const finalQuote = `> ${qod.content}
>
> &mdash; <cite>${qod.author}</cite>✍️`
tR += finalQuote
%>
```
