### ISSUE TITLE
Syntax Highlighting not working in CM6

### ISSUE THREAD

**Issue by chrisgrieser** [SilentVoid13/Templater#491]
**Plugin informations (please complete the following information):**

-   OS: macOS 12.0.1
-   Templater version: 1.9.9
-   Obsidian version: Obsidian 0.13.14
-   Templater settings: Syntax Highlighting enabled

**Describe the bug**
Syntax Highlighting does not work with the new editor (CM6). When using the Legacy Editor, Syntax Highlighting works again.

**Screenshots**
<img width="1067" alt="Screenshot 2021-12-30 15 46 38" src="https://user-images.githubusercontent.com/73286100/147761914-f9f72a41-e331-4233-88f1-6cb33f6dd2fe.png">

**Comment by 1039009892** [comment]
I'm experiencing the same problem and it's not resolved yet.

**Comment by HyperEpsilon** [comment]
I'm also having this issue, but I can't even get the syntax highlighting to work on the legacy editor.

- OS: Windows 10
- Templater Version: 1.12.0
- Obsidian Version: v0.14.6
- Templater Settings: Syntax Highlighting enabled

Sandbox vault for reference
![Obsidian_5qiwOeZNJr](https://user-images.githubusercontent.com/6267244/171445474-60794d14-2eee-481c-a99c-4be4e3066b75.png)

**Comment by AB1908** [comment]
A new CM6 migration guide is out for anyone that wants to take a stab at this.
