### ISSUE TITLE
Want to remove the restriction on calling templates

### ISSUE THREAD

**Issue by daoif** [SilentVoid13/Templater#492]
**What I am doing:
Use template <%\* %> to write js code, create additional files, but do not insert content in the currently opened file.
Feedback from templater:
1. When my obsidian is in an active native md document, all this can go smoothly.
2. When my obsidian is in a file rendered by a plug-in, such as mind. Calling templater will prompt the following error message: No active view, can't append templates.

(I didn't find a solution, even if I call the template in quickadd, the result is the same. At present I have been trying to use quickadd to call external js to achieve this function.)

** Hope to improve:
The template is allowed to be called without active view, because by doing so, I can make different plugins or scripts call tp functions, maintaining the syntax consistency of the template file, and no additional work is required. Thank you.

**Comment by shabegom** [comment]
This is challenging because many of the built in templater require a note to be open (active view) in order to work.

**Comment by shabegom** [comment]
Ok then use your own plugin 😊

**Comment by imeed166** [comment]
I'm sorry for commenting on a closed issue, but I have the same need, is it okay to ask for the implementation of the feature?  (I want to use the main plugin instead of a fork)

**Comment by imeed166** [comment]
I'm sorry for commenting on a closed issue, but I have the same need, is it okay to ask for the implementation of the feature?  (I want to use the main plugin instead of a fork)

**Comment by imeed166** [comment]
I'm sorry for commenting on a closed issue, but I have the same need, is it okay to ask for the implementation of the feature?  (I want to use the main plugin instead of a fork)

**Comment by daoif** [comment]
> I'm sorry for commenting on a closed issue, but I have the same need, is it okay to ask for the implementation of this feature? (I want to use the main plugin instead of a fork)

Sorry, I may have disappointed you. 
 I didn't break this limitation on the basis of templater.  Instead, a new little plugin was developed for my own needs.  This plug-in currently supports almost no syntax, but can quickly create documents according to preset templates, store them in folders divided by year, month, and date, and finally store the created document link in the clipboard. 
 If you need the features I describe, you can visit 
https://github.com/daoif/obsidian-Rule-folder-template-daoif 
to get the source code or Releases

**Comment by imeed166** [comment]
Ah, I see, thank you for explaining, and for sharing your plugin.

Nevertheless, I just wanted to upvote this feature request in the hopes that the maintainer will reconsider adding this feature request.
