### ISSUE TITLE
Click Tab to move from {{tp_cursor1}} to {{tp_cursor2}} to.....{{tp_cursorN}}

### ISSUE THREAD

**Issue by Quorafind** [SilentVoid13/Templater#50]
**Is your feature request related to a problem? Please describe.**
When I used template to generate stuff, I should use my mouse to click one by one to type different stuff.

**Describe the solution you'd like**
I found now the plugin do support {{tp_cursor}}: This will set the cursor to this location after the template has been inserted.
So I do not know if it is possible to add PLUS support to make {{tp_cursor}} allow people to move from one by one.

A possible solution: 

continuous template inserting by click a hotkey to insert a template then trigger to insert another template

For example:

When I want design a template with more than one {{tp_cursor}}, after I insert the template to note by clicking Enter, and then, I click another hotkey, it will check if there are others {{tp_cursor}} and then plugin moves cursor to next {{tp_cursor}} until there is no {{tp_cursor}} in the note.

**Comment by trydalch** [comment]
I would also find this very valuable. Similar to how code snippets behave in VSCode. Would be awesome if it highlighted the next fields and allowed for using `tab` to move to the next one, but would be nice.

I'm also open to contributing. Might take a look at it at some point.

**Comment by trydalch** [comment]
Awesome. Thanks @SilentVoid13

**Comment by Quorafind** [comment]
Quick question, how to make this work?

I set a template like this, 

![image](https://user-images.githubusercontent.com/13215013/113648302-fc8d3f80-96be-11eb-88df-b47d5a2ae3e2.png)

but it output 

![image](https://user-images.githubusercontent.com/13215013/113648498-4a09ac80-96bf-11eb-9c68-29d7c1155da1.png)

Did I miss something?

**Comment by trydalch** [comment]
I'm running into the same issue.

**Comment by SilentVoid13** [comment]
@Quorafind @trydalch you are right, sorry for the mistake. This should be fixed in 1.1.0. Update and tell if it works.

**Comment by Quorafind** [comment]
@SilentVoid13 It works fine now.
