### ISSUE TITLE
Templater syntax translate broken since new Obsidian Version

### ISSUE THREAD

**Issue by link-d** [SilentVoid13/Templater#500]
**Plugin informations (please complete the following information):**

-   OS: Windows 10, 21H2 (Build 19044.1415)
-   Templater version: 1.9.9
-   Obsidian version: 0.13.19
-   Templater settings: Template folder location: "Templates/", Syntax Highlighting [enabled], Automatic jump to cursor [enabled], Trigger Templater on new file creation [enabled], rest disabled or not set.

**Describe the bug**
I use templater for creating links to yesterdays and tomorrows daily note. My Templater template is used by the built-in plugin "Daily Note" from Obsidian. But the Templater synatx will not be translated since the new version (0.13.19). Thereby it is independet of the Mode (Source Mode or Live Preview mode).
I think that the option "Trigger Templater on new file creation" is maybe broken.
If I create a new file with Templater the syntax will be translated correctly.
My actual workaround is to open an empty note with the Obsidian built-in plugin "daily note" and insert my daily note template with the hotkey function.

**Expected behavior**
The syntax was replaced correctly in the past/previous versions, so it would be nice if this will work again :)

--- 

**EDIT (2022-01-10):**
The same issue seems to exist at MacOS, see [Issue 501](https://github.com/SilentVoid13/Templater/issues/501)

**Comment by shabegom** [comment]
Is this resolved after removing the daily quote command? If so, please close this issue. 

An alternative daily quote command:

```
<%*
const response = await fetch(`https://api.quotable.io/random`);
const     qod = await response.json();
const finalQuote = `> ${qod.content}
>
> &mdash; <cite>${qod.author}</cite>✍️`
tR += finalQuote
%>
```

**Comment by link-d** [comment]
The bug has nothing to do with the daily **quote**. It seems to be a problem in triggering the templater on new file creation and a defined template which is in my case used for the daily **note**.

**Comment by shabegom** [comment]
That setting is definitely not working which leads me to believe there is an issue with the daily note template. The most common issue people are having is with `daily_quote()` being broken, hence my question.

Are there any errors in the dev console when you create your daily note?

**Comment by shabegom** [comment]
I will try to recreate. Do you use the Filename Heading Sync plugin? There is a known conflict with that one.

**Comment by link-d** [comment]
Hey, sorry for the late reply.
Yes, I'm using Filename Heading Sync, and that seems to be the "problem" althought it had worked before with the plugin.
Then I try to find out a workaround to use the plugin as well as my daily note with templater :)
