### ISSUE TITLE
Standard Obsidian template syntax is not expanded on file creation (Obsidian 0.13.x)

### ISSUE THREAD

**Issue by RoamanEmpire** [SilentVoid13/Templater#501]
**Plugin informations (please complete the following information):**

-   OS: macOS 12.1
-   Templater version: 1.9.9
-   Obsidian version: 0.13.19
-   Templater settings: 

**Describe the bug**
I'm trying to apply the following template whenever a new file is created using Templater. 
```
---
created: {{date:YYYY-MM-DDTHH:mm:ss}}
tags: []
aliases: []
---
```
As you can see, I'm using the standard Obsidian syntax since I do not need anything fancy, but I'm using Templater for its ability to apply templates on file creation.
For some reason, this method has stopped working recently (as of Obsidian v0.13.x) and the template syntax is not expanded into an actual date but it's copied on to the newly created file.

**Expected behavior**
The syntax `{{date:YYYY-MM-DDTHH:mm:ss}}` should be expanded into an actual date, eg `2022-01-07T12:36:13`.

**Comment by karimhsa** [comment]
Plugin informations (please complete the following information):

OS: Windows 11
Templater version: 1.9.9
Obsidian version: 0.13.19

I have the same issue.
I use Templater with this sentences till yestarday well, but now them doen't work.

creation date: <% tp.file.creation_date("YYYY-MM-DD  dddd HH:mm") %>
<< [[<% tp.date.now("YYYY-MM-DD dddd", -1) %>]] | [[<% tp.date.now("YYYY-MM-DD dddd", 1) %>]] >>

Obsidian tells:
"Templater error:
Template parsing error, aborting."

In console says:
Failed to load resource: net::ERR_CERT_DATE_INVALID >> quotes.rest/qod:1
Templater Error: Template parsing error, aborting.  Failed to fetch >> Log.ts:17 

Log.ts:17 >> console.error(`Templater Error:`, e.message, "\n", e.console_msg);

**Comment by peterkehlerjr** [comment]
OS: Linux
Templater version: 1.9.9
Obsidian version: 0.13.19

Same here. Were able to narrow down the/my specific issue to this function
`<% tp.web.daily_quote() %> `
and all cases of using `<% tp.user.`-functions.  

Console output:
```
Failed to load resource: net::ERR_CERT_DATE_INVALID >> quotes.rest/qod:1
Templater Error: Template parsing error, aborting. Failed to fetch >> Log.ts:17
```

**Comment by shabegom** [comment]
Fixed `tp.web.daily_quote` in 1.9.10. @RoamanEmpire please confirm this solves your issue and if so, close this ticket. Thanks!

**Comment by karimhsa** [comment]
> Fixed `tp.web.daily_quote` in 1.9.10. @RoamanEmpire please confirm this solves your issue and if so, close this ticket. Thanks!

Confirmed, at least, for me.

Templater works again!

Thank you very much!!!!!!!!!!

**Comment by RoamanEmpire** [comment]
Yep, seems to be working again. Thank you!
