### ISSUE TITLE
Templater fails to load due to cert date invalid error

### ISSUE THREAD

**Issue by koldex** [SilentVoid13/Templater#505]
**Plugin informations (please complete the following information):**

-   OS: OSX Monterey 12.1
-   Templater version: 1.9.9
-   Obsidian version: v0.13.19
-   Templater settings: tp.web.daily_quote()

**Describe the bug**
Web module and tp.web.daily_quote() has stopped working giving error message:

quotes.rest/qod:1 Failed to load resource: net::ERR_CERT_DATE_INVALID
Log.ts:17 Templater Error: Template parsing error, aborting. 
 Failed to fetch
log_error @ Log.ts:17

**Expected behavior**
Retrieves and parses the daily quote from the API https://quotes.rest/

**Comment by shabegom** [comment]
@koldex 
Here is an alternative qotd command for now:

```
<%*
const response = await fetch(`https://api.quotable.io/random`);
const     qod = await response.json();
const finalQuote = `> ${qod.content}
>
> &mdash; <cite>${qod.author}</cite>✍️`
tR += finalQuote
%>
```
