### ISSUE TITLE
Perhaps a Documentation Error

### ISSUE THREAD

**Issue by lwb52** [SilentVoid13/Templater#51]
the plugin-document says that {{tp_date}} will return today’s date, but I can only get today’s date using {{tp_today}}, as is shown in the demo-gif…

**Comment by lucapericlp** [comment]
Experienced the same, came to open same issue so opened a PR #52 just to quickly update docs (not gif), provided that the two templates are equivalent.

**Comment by SilentVoid13** [comment]
Templater got a huge update, `tp_date` and `tp_today` were removed therefore this issue doesn't apply anymore.
You can use `<% tp.date.now() %>` as a replacement.
Closing this.
