### ISSUE TITLE
Certificate Expired Error

### ISSUE THREAD

**Issue by sinoop** [SilentVoid13/Templater#520]
**Plugin informations (please complete the following information):**

-   OS: Mac OS
-   Templater version: 1.9.9
-   Obsidian version: 0.13.19
-   Templater settings: Default Settings
- Template Command used - <% tp.web.daily_quote() %>

**Describe the bug**
When tried to fetch the a random quote, gets Invalid Certificate for https://quotes.rest/qod 

`
Log.ts:17 Templater Error: Template parsing error, aborting. 
Failed to fetch
InternalModuleWeb.ts:18 GET https://quotes.rest/qod net::ERR_CERT_DATE_INVALID
`

**Expected behavior**
No error and the template should be created with a quote. 

**Additional context**
I would expect to ignore this error and create the note.

**Comment by shabegom** [comment]
Please update to the latest version of Templater.
