### ISSUE TITLE
modification Date variable works not correct?

### ISSUE THREAD

**Issue by godwolfi** [SilentVoid13/Templater#521]
**Plugin informations (please complete the following information):**

-   OS: [Mac OS Monterey 12.1]
-   Templater version: [1.9.11]
-   Obsidian version: [e.g. 0.13.19]
-   Templater settings: [e.g. Template folder location: "Templates/", Timeout: "5" (add the templates not working with their associated command)]
 
Hello SilentVoid. First I would like to thank you for the great plug in. It is very helpful! 

Could it be that the use of the variable: modification date: <% tp.file.last_modified_date("YYYY-MM-DD HH:mm") %>
no longer works correctly?

I am using this variable in a template. 
I expect that after I create a note with this template and update it later, the current date & time of my change will be entered.
Until a few days ago, this worked like this. But today I notice that this date is no longer changed after editing a note.

**Comment by momja** [comment]
Consider looking into [dynamic templates](https://silentvoid13.github.io/Templater/commands/dynamic-command.html). I don't think there is support for dynamically changing the result in editor mode.

**Comment by godwolfi** [comment]
@momja @shabegom thank´s a lot for your answers and the solution. That´s what i want! Nice! I also found out that a mousover over the file in the file explorer also shows the data.
