### ISSUE TITLE
Templater and Calendar plugin

### ISSUE THREAD

**Issue by pillouz01** [SilentVoid13/Templater#525]
Hello,
I'm a beginner with this superb plug-in
I have created a daily note template using the calendar plugin and the normal template syntax
my question is: can I mix the default template syntax and the templater syntax in a daily note

Thanks
Patrick

**Comment by I-Pch** [comment]
Hi @pillouz01 😊 

If by "default template" you mean the templates we can create and use with the plugins `Calendar` & `Periodic Notes` 

E.g.: [embed your entire week in a weekly note](https://github.com/liamcain/obsidian-calendar-plugin#embed-your-entire-week-in-a-weekly-note)
```
## Week at a Glance

![[{{sunday:gggg-MM-DD}}]]
![[{{monday:gggg-MM-DD}}]]
![[{{tuesday:gggg-MM-DD}}]]
![[{{wednesday:gggg-MM-DD}}]]
![[{{thursday:gggg-MM-DD}}]]
![[{{friday:gggg-MM-DD}}]]
![[{{saturday:gggg-MM-DD}}]]
```

... the answer is yes, you can 😊 !

**Comment by pillouz01** [comment]
Thanks a lot !
Exactly what I need !!

Regards
Patrick
