### ISSUE TITLE
dddd formatting after comma doesn't translate

### ISSUE THREAD

**Issue by chi-wi** [SilentVoid13/Templater#53]
Pretty sure that OS is irrelevant here.

 - OS: Ubuntu LTS 20
 - Templater version: 0.5.7
 - Obsidian version: 0.10.9

**`dddd` formatting doesn't translate after comma**

The use of the following format `tp_date:f=Do MMMM YYYY, dddd` produces "1st January 2021" and **not** "1st January 2021, **Monday**"

`ddddd` does not get resolved; Square brackets also don't work.

Leaving out the comma as such `tp_date:f=Do MMMM YYYY dddd` works.

**Comment by SilentVoid13** [comment]
Hey @chi-wi, sorry for the very late response.
Templater had a huge update, `tp_date` was removed and this issue doesn't apply anymore.
In your case, you can use `<% tp.date.now("Do MMMM YYYY, dddd") %>` as a replacement.
Closing this.
