### ISSUE TITLE
[Regression] Require resolution broken after recent change

### ISSUE THREAD

**Issue by JeppeKlitgaard** [SilentVoid13/Templater#538]
The change introduced in 06fef36c66fe52fcdc7bec3f23db0beff1c3dca8 broke using `require()` against local files in template scripts.

This feature was important to me, as I have some functions that I want to use in different scripts.

The new method uses `window.eval`, which will have a different CWD than what the user would expect.

Possible solutions:
- Introduce a convenience method for importing relative to `Scripts` dir
- Patch CWD or require to restore the old (and better) logic

This can easily be reproduced by doing a relative import using `require` in a Templater script.

**Comment by shabegom** [comment]
Going to close this in favor of #539 which has some more information in it currently. Thanks for reporting!
