### ISSUE TITLE
When Templater is triggered upon new file creation, if it changes nothing, can Templater not update the "Last modified" timestamp?

### ISSUE THREAD

**Issue by DannyQuah** [SilentVoid13/Templater#542]
When, using a shell or other file manager, I move files and folders around in an Obsidian vault, Obsidian//Templater updates the "Last modified" timestamp on those moved files to the current time.  Obsidian//Templater considers those files "newly created".  Is there a workaround so I can keep the timestamps invariant (since nothing has actually changed in those files)?  

If I turn off "Trigger Templater on new file creation", the timestamp on the files just moved in, appropriately, don't update.

However, that same update occurs if you rename the top folder using the shell or other file-manager: Obsidian//Templater updates the "Last modified" timestamps on everything within.  I can understand the subtlety ("well, those files are, as far as Obsidian//Templater is concerned, newly-created and Templater looked in on them to modify what was needed, so of course those files should have their "Last-modified" timestamp updated).  However:  

1.  When you make those moves using Obsidian's own filemanager, the timestamps are unchanged - so there's some inconsistency in that the before and after system states are identical, but the difference only surfaces depending on whether it was Obsidian that operationalized the move.  Consistency, for me, seems to say that if before and after system states are identical, so should the "Last modified" timestamps, in this case, the files and folders showing the old timestamp when nothing in them has changed.  It's just that Templater considers those files "newly created" in one case, and not so in the other.
2.  If Obsidian is not running or that Templater triggers is turned off, and you make the file/folder moves using the shell or some other file manager, the timestamps remain unchanged even when Obsidian afterwards is then run or the Trigger is turned on.  I'm not asking Obsidian//Templater to go through and update everything relative to when it last saw the vault.  Quite the opposite: I prefer this outcome when it doesn't.  But I also think consistency implies that if the system states are identical, then the "Last modified" timestamps should too, regardless of whether Obsidian is running // Templater Trigger is on when the system is changed.  I prefer the outcome when Obsidian is shutdown, the move is made, and then Obsidian is brought up again, but this is obviously a kludge.

I appreciate there is a subtlety here, and I'm not arguing one behaviour is dogmatically always right and the other always wrong.  (I have a preference for unmodified files not to have their "Last modified" timestamps unchanged, so my `find` and other operations work as expected, but I can also see the argument from Obsidian//Templater's point of view: "those files were newly created and Templater could have changed them but chose not to".)  Nonetheless, however, I do think there should be consistency and no-unexpected surprises.

Thank you for such a valuable plug-in otherwise.

PS I am not using Obsidian Sync; the system is basically standalone.

**Comment by shabegom** [comment]
Templater is reading and returning the modified time provided by Obsidian. Each file has an associated `stat` object that provides a creation time and modification time. The change would need to happen upstream of Templater in Obsidian proper. In this case I'd suggest opening a feature request on the obsidian forum.
