### ISSUE TITLE
How to create from template using tp.file.create_new ?

### ISSUE THREAD

**Issue by ThisIsDoubleC** [SilentVoid13/Templater#545]
The documentation recommends that to create from a template you use the TFile but I could not find the syntax for representing a template note as a TFile or information on finding a template's TFile

Relevant documentation:  https://silentvoid13.github.io/Templater/internal-functions/internal-modules/file-module.html#tpfilecreate_newtemplate-tfile--string-filename-string-open_new-boolean--false-folder-tfolder

**Comment by AB1908** [comment]
Can use `tp.file.find_tfile()` or `app.vault.getAbstractFileByPath`.

**Comment by AB1908** [comment]
Were you able to test this out?

**Comment by ThisIsDoubleC** [comment]
> Were you able to test this out?

Thanks! tp.file.find_tfile() worked for me. I couldn't get the other way to work, what would be the right syntax for the file path expected by app.vault.getAbstractFileByPath()?

**Comment by AB1908** [comment]
It expects the vault path IIRC, e.g. `vault root/path/file`.

**Comment by AB1908** [comment]
Fiddle with it in the console. I keep forgetting whether it needs a `/` at the beginning.

**Comment by ThisIsDoubleC** [comment]
I couldn't get the app.vault.getAbstractFileByPath() to work on my side, possibly due to spaces in my file names. Since tp.file.find_tfile() worked for me I consider this issue closed. Thanks for all your help :)
