### ISSUE TITLE
Is there a way to select a different python version?

### ISSUE THREAD

**Issue by peterhowse** [SilentVoid13/Templater#55]
I have written a script to pull my teaching timetable and put it into a template. Everything works fine from terminal. When I add it to Templater, it reports "module requests not found". Upon investigation I discovered that it always selects the system python regardless of the command I run. I even tried embedding the call in a bash script to no avail.

Any suggestions would be greatly appreciated

**Comment by jayfehr** [comment]
you should be calling your scripts using the version that you want to run it in

e.g.

python2 ./myscript.py

or 

python3 ./myscript.py

**Comment by SilentVoid13** [comment]
Hey @peterhowse,
As @jayfehr suggested, you can specify the version of python you want to use using `python2` or `python3` when calling your script.
Closing this.
