### ISSUE TITLE
Templater doesn't render by Daily Note.

### ISSUE THREAD

**Issue by FoxythDou** [SilentVoid13/Templater#556]
I take daily notes, and I made it so to open as a template. Though when I open it up, It just stays like the template.
![image](https://user-images.githubusercontent.com/73705171/153316713-803b709e-1280-40cc-8fda-cf8394f7936e.png)
Any ideas

**Comment by benwalio** [comment]
I'm pretty sure you need spaces after and before the <% %> parts

so: `<% tp.date.now("MMMM, Do YYYY") %>`

**Comment by shabegom** [comment]
How are you opening the daily note? Do you have the setting turned on to run templater on all new files?

**Comment by jdubbs4051** [comment]
Can also confirm but only seems to be an issue on mobile. 
![469A2984-7CB8-46D9-B468-FA314EA188D9](https://user-images.githubusercontent.com/76002482/153579124-c2f317f2-0dd1-4b16-baa2-7595196f91f5.png)

**Comment by FoxythDou** [comment]
> How are you opening the daily note? **Do you have the setting turned on to run templater on all new files?**

@shabegom Oh! That's the solution! Thank you so much! I thought it would open a template everytime I open a new file. Well, Must have passed through my head. Thanks again!

**Comment by mnaoumov** [comment]
Templater doesn't run on Daily notes if they are created via sharing.

https://user-images.githubusercontent.com/735878/167015557-081b876c-e70e-4c62-b676-592420d5f8e0.mp4

The setting mentioned above is set and working as expected if you create daily note from within the Obsidian app, not via sharing.

**Comment by cogscides** [comment]
Plus one

**Comment by AB1908** [comment]
Can you open a separate report?

**Comment by mnaoumov** [comment]
@AB1908 https://github.com/SilentVoid13/Templater/issues/708
