### ISSUE TITLE
Run a bash script

### ISSUE THREAD

**Issue by bepolymathe** [SilentVoid13/Templater#56]
Hi, 

I try to run a bash script "with templater" but i can’t find why i have an error :

The script is very simple and work in the terminal

```
#!/usr/bin/env bash

R -e "rmarkdown::render('/home/manu/Téléchargements/test.rmd', 'word_document')"
```
My templater looks like this 

![image](https://user-images.githubusercontent.com/29939805/107128202-2cd18100-68bc-11eb-8817-875d181e06a5.png)

Any idea ?

**Comment by SilentVoid13** [comment]
Hey @bepolymathe, sorry for the late response.
Templater had a huge update, that fixes a lot of things.
It introduces a new syntax for user templates.
Could you update Templater to the latest version, update your existing templates with the new syntax and tell me if you still experience the same error ?

**Comment by Moonbase59** [comment]
Note @bepolymathe:

After the update, you will have to:
- Close and restart Obsidian (I fell into this trap: Obsidian still rendered the `{{…}}` but not the new `<% … %>` templates)
- rename your `{{compilation}}` user function to `compilation` and call it by `<% tp.user.compilation() %>`.

**Comment by SilentVoid13** [comment]
Closing this, don't hesitate to ask questions if you have some.
