### ISSUE TITLE
Move cursor to a specified position after file name population (+enter)

### ISSUE THREAD

**Issue by tangor86** [SilentVoid13/Templater#564]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I enter a file name, press enter and cursor is set to header part, not to content part.
![image](https://user-images.githubusercontent.com/1785921/154800899-e1fdf1cd-fe27-4a2a-a909-f9b3898f2225.png)
(at this screenshot the cursor is placed at the correct position (where content will be) but in real world it is set on the first line of the note - in this case yaml header)

**Describe the solution you'd like**
After I created a new note with specific template and filled in the filename and pressed enter I want the cursor to be placed in specific template place where I specified below tag, for example:
**<% tp.file.cursor_afterfilename() %>**

**It could be one-time action, only when file is initially created (for the first time), ... when I change file name later this f-ty is not really needed...**

**Describe alternatives you've considered**
Right now I tried to set:
**<% tp.file.cursor() %>**
in the template, but it places cursor there immediately after note creation, not really what I wanted... I wanted this only after I enter filename first...
I also tried to find plugins which would do this but I did not succeed... 😒

**Another suitable solution would be just to place cursor at the end of the note when I press enter at filename input field. In my case it would work.** 

P.S:
this is real sample, you can see where the cursor is here (wrong)
![image](https://user-images.githubusercontent.com/1785921/154801417-5bb69058-8725-4f5e-85aa-13baa881f0d2.png)

**Comment by AB1908** [comment]
What did you use as an argument for `tp.file.cursor()`?

**Comment by tangor86** [comment]
I think I did not specify any...

**Comment by AB1908** [comment]
Can you try `tp.file.cursor(1)`? I've forgotten how this worked haha.

**Comment by tangor86** [comment]
I just tried with:
<% tp.file.cursor(0) %>
and
<% tp.file.cursor(1) %>
and
<% tp.file.cursor(2) %>

they all work in the same way -> puts a cursor to a position of this "tag" immediately after note creation.

**Comment by tangor86** [comment]
It seems not fixed... please see gif
![cursorWrongPlacement](https://user-images.githubusercontent.com/1785921/156921365-7a4185f2-5734-486c-8209-856357213b9a.gif)

**Comment by AB1908** [comment]
Can you @ me on the templater channel on Discord?

**Comment by liamcain** [comment]
I just released v1.11.3 which should be a more complete fix for the bug, sorry about that @tangor86. I'll leave the issue open for you to confirm though.

**Comment by tangor86** [comment]
I think now it works! thanks a lot!!
![cursorWorks](https://user-images.githubusercontent.com/1785921/156939912-e52e0fb9-fca6-4e47-8665-174e01582a51.gif)
