### ISSUE TITLE
Adding the "limit" property to the tp.system.suggester() function for quicker load on large modals

### ISSUE THREAD

**Issue by GitMurf** [SilentVoid13/Templater#565]
When loading large lists (3,000+) into Templater suggest modal it is a bit slow and takes a couple seconds to load the modal. It is because all the items are loading into the modal UI with a giant scroll bar. Obsidian native handles this by using the `limit` property with the quick open file opener where it only shows the first 10 results.

`limit` property in the API: https://github.com/obsidianmd/obsidian-api/blob/71b3b362bb1f0e8f3c13f1a1d92f65427d2ad477/obsidian.d.ts#L2989

For example, Ctrl + O (quick open) of notes loads all notes + unresolved links as well but has zero lag. Is it because it only actually loads 10 or so viewable in the modal UI in core obsidian (quick open)

![image](https://user-images.githubusercontent.com/64155612/154857480-53ecd76e-a7f9-4f0e-b2e2-73be5037aea2.png)

But in templater it actually loads all 3,000 into the modal with a scroll bar? Obsidian quick open only shows like 10 results but the fuzzy still works (all links must still be loaded on the backend) and it just continues to present to user / load in the modal element the top 10 results. More like a "lazy load".

![image](https://user-images.githubusercontent.com/64155612/154857484-1886cd19-2f7a-43ae-a52f-f312f3402e94.png)

**Comment by GitMurf** [comment]
@liamcain is this supposed to be in the newest release from a couple weeks ago? v1.11.3? Or is it still waiting to be added to a new release for obsidian community repo? Thanks!

**Comment by GitMurf** [comment]
![image](https://user-images.githubusercontent.com/64155612/159091528-7668d6ef-fad5-472f-9f69-9aaa6a653abc.png)

**Comment by liamcain** [comment]
This was just merged a few minutes ago. It hasn't been released yet.

**Comment by GitMurf** [comment]
Thanks a lot for doing this!

**Comment by GitMurf** [comment]
YAY!! Thanks a lot @liamcain ! This fixed my problem :) Now suggesters load lightening fast when I load my list of markdown files from my vault to choose from!
