### ISSUE TITLE
Moving a task to new daily file doesn't correctly use templater

### ISSUE THREAD

**Issue by tim-hilde** [SilentVoid13/Templater#57]
I am using both the slated and templates plugin. When I'm moving a task to a day of which there is no file yet, the template placeholders are not replaced correctly. Instead of referring to the new date's title it is using the current one. Obviously this could also be a bug in the templater plugin, so I am posting this here and over at [https://github.com/tgrosinger/slated-obsidian](https://github.com/tgrosinger/slated-obsidian)

**Comment by SilentVoid13** [comment]
Hey @tim-hilde, sorry for the late response. This has been fixed as of Templater 1.0.0.
If you update, Templater will now use the new date's title instead of the current one.
Tell me if the fix works for you.
Closing this.
