### ISSUE TITLE
Cannot get Templater variables to work

### ISSUE THREAD

**Issue by obviousaurus** [SilentVoid13/Templater#572]
I thought I was tech savvy but I cannot for the life of me get variables from the Templater plugin to work in my copy of Obsidian. I have looked all over online and all of the instructions seem clear but my results are always the same. I have used [this page](https://silentvoid13.github.io/Templater/) as reference

Here's your code as it appears on that page:
<img width="500" alt="image" src="https://user-images.githubusercontent.com/17000416/155998923-e4b95157-90ea-403f-b1d7-37b2de738ed9.png">

Here's the result I get in my copy of Obsidian (Version 0.13.19) regardless of whether or not I'm using Live Preview mode:

<img width="500" alt="image" src="https://user-images.githubusercontent.com/17000416/155999069-d9e05c65-c2d6-4dbc-ba34-aaf6df5ab22e.png">

The dates don't automatically show up, nor does the title, or any other variable, for that matter. I can only get dates to show up correctly if I manually type them in every day. How can I get dates to auto-populate?

This happens regardless of whether I add this code directly to my template file or whether I add it to a non-template file directly.

All I want is to be able to create the `<< Yesterday` | `Today >>>` buttons like I see in this YouTube video:

https://www.youtube.com/watch?v=14GSuqWh4oU&t=282s

I don't understand what I'm doing wrong. Do I need to have an actual start date (e.g. `2022-02-28`) in my template in order for this to work? Any tips would be much appreciated. Could there be something that is blocking variables from working correctly?

**Comment by obviousaurus** [comment]
I thought that perhaps adding dashes between the date format would help since that's how I've been naming my files, but it didn't make a difference. When I switch to Viewing Mode and click on the links that use the variables, a new file gets created with this type of title

<img width="369" alt="image" src="https://user-images.githubusercontent.com/17000416/156158853-1c121a57-250a-4cd9-b67a-6660de4cac75.png">

So even the file names aren't auto-naming based off of the date format. There must be something super obvious that I'm doing wrong.

**Comment by AB1908** [comment]
Ya need to replace the templater commands in the file. Templater commands are also "resolved" upon insertion.

**Comment by DivM** [comment]
Open Command Palette (`Cmd`+`P`) and look for _'Replace templates in the active file' (`Opt` + `R`)_.  
The hotkey isn't working for me for some reason.

**Comment by AB1908** [comment]
You need to change a templater setting. Resolve templates on new file creation or whatever it's called.

**Comment by obviousaurus** [comment]
@AB1908 - Any chance you could elaborate on where I might find such a setting for resolving templates on file creation? I'm not seeing anything in the Templater settings nor any mention of such a setting in their [online documentation](https://silentvoid13.github.io/Templater/introduction.html).
