### ISSUE TITLE
WEIRD bug where hover preview of a note that has header embed inside will not render with Templater enabled

### ISSUE THREAD

**Issue by GitMurf** [SilentVoid13/Templater#577]
Newest version of Templater v1.10.0

When hover previewing a note [[link]] that has header embed inside, it will not render the header embed while Templater is enabled. The easiest way to explain is via my video below. Keep in mind I noticed that sometimes you can hover a link for the first time and it will render the header embed but then if you mouse off and try to re-hover preview, the second time it will disappear (and look just like my video below). So try hover previewing a couple times.

https://user-images.githubusercontent.com/64155612/156510628-10c54858-c9a6-4458-8ca5-f92cb6a5c508.mp4

**Comment by shabegom** [comment]
I'm unable to recreate. @GitMurf is this still occurring with most recent versions?

**Comment by GitMurf** [comment]
@shabegom this not longer appears to be an issue. I am closing this out. Thanks!
