### ISSUE TITLE
Support for tp.system.clipboard on mobile

### ISSUE THREAD

**Issue by ko13** [SilentVoid13/Templater#589]
**Is your feature request related to a problem? Please describe.**
On mobile, the tp.system.clipboard results in an error "This command is not supported on mobile."

**Describe the solution you'd like**
I'd like to use the clipboard insert also on Android device.

**Describe alternatives you've considered**
I tried to use the QuickAdd plugin to use the Obsidian built in "paste" command but I don't get it to paste on the correct spot. The templater function would just be so much better!

**Comment by hdykokd** [comment]
`navigator.clipboard.readText()` is currently available on iOS. (Tested on iOS 16.2, Obisidian 1.4.1)
I don't have Android, so I can't verify this, but the conditional statement here may no longer be necessary.

https://github.com/SilentVoid13/Templater/blame/a43f2b330e62b8b09f44be1d171c6254d6bcd4fc/src/core/functions/internal_functions/ system/InternalModuleSystem.ts#L22-L25

The clipboard parameter of the Obsidian Advanced URI was also available on iOS, which also seemed to be implemented with `navigator.clipboard.readText()`.

https://vinzent03.github.io/obsidian-advanced-uri/actions/writing
https://github.com/Vinzent03/obsidian-advanced-uri/blob/b4a4b1de443d6016cff099b5acab1c0ee14f534a/src/main.ts#L154-L156

**Comment by hdykokd** [comment]
I realized that I could simply use `<% await navigator.clipboard.readText() %>`

**Comment by FelipeRearden** [comment]
> I realized that I could simply use `<% await navigator.clipboard.readText() %>`

AMAZING !!!!!!!!

This solves a huge problem for me !!!!!!!!!!!!!!!!!

This is a true discovery for Obsidian Mobile users. Thank you very much for sharing this with us 💙💙💙

ℹ️ It works on QuickAdd as well :)

**Comment by hdykokd** [comment]
Glad I could help. It's really great that Templater makes this possible!

**Comment by FelipeRearden** [comment]
> Glad I could help. It's really great that Templater makes this possible!

Yes it is!!!! For users like me that uses Obsidian on iPad with mouse and keyboard it was a challenge to create scripts using clipboard that works on Mobile and Desktop.

Now I can finally upgrade add this not my to mobile ;)

Thanks again 😀

**Comment by Zachatoo** [comment]
This was brought to my attention in the Obsidian Discord today, I tested on Android and FeralFlora tested on iOS. Will be fixed in the next release (today or tomorrow, depending on timezones).

Thanks for everyone's contributions to this issue!
