### ISSUE TITLE
Shortcut for and Template

### ISSUE THREAD

**Issue by rajeget** [SilentVoid13/Templater#59]
Can we have a keyboard shortcut for an template . For example . I want to create template for Python code snippet , can I press a keyboard shortcut and some customized template say {{tp_mycodeblock}} is inserted .

**Comment by SilentVoid13** [comment]
Hey @rajeget, you can use the plugin obsidian-hotkeys-for-templates from Vinadon to bind a specific template to a hotkey.
Link: https://github.com/Vinzent03/obsidian-hotkeys-for-templates
Closing this.
