### ISSUE TITLE
Passing Arguments to Templates

### ISSUE THREAD

**Issue by jaltgen** [SilentVoid13/Templater#593]
**Is your feature request related to a problem? Please describe.**
I've been trying to create a child note with not just a LINK to the parent, but also a contextual frontmatter variable dependent on the parent note. 

**Describe the solution you'd like**
This would be really easy, if I could simply pass arguments / data to a called template in create_new(context?: [data0, data1].

**Describe alternatives you've considered**
For a few hours I've tried to hijack this multiple ways and it's been quite painful having to open the note for writing after creation.

**Additional context**

Here's my user script for working around it. It's not really pretty the way I'm appending the data I want.

`
//msg is passed by calling the user function like so: tp.user.create_meeting("HelloWorld")
async function meetingcreation (tp) {
    // set standard variables pulled from context of the file calling the method

    let proj = tp.frontmatter.project;

    // get TFolder from TP File object

    let project_afile = app.vault.getAbstractFileByPath(tp.file.path(relative = true))

    // create new filename
    let variable_name = await tp.system.prompt("Note Title");
    let creation_filename = tp.date.now("YYYYMMDD")+"_"+proj+"_"+variable_name;

    // create new file...
    await tp.file.create_new(
      template = tp.file.find_tfile("meeting-template_v01"),
      filename = creation_filename,
      open_new = true,
      folder = project_afile.parent
    );

    await tp.file.cursor_append("---\nproject: "+proj+"\n")

}
module.exports = meetingcreation;`

**Comment by jaltgen** [comment]
Thank you for the detailed explanation. I was thinking of something really simple like providing an optional argument like so:

_tp.file.create_new(value?: string | dict)_

I guess why this is confusing me is when tp.file refers to what file, the parent file or the new one when creating. Idk, maybe my architecture is just stupid. In the end I got it to work anyways.

**Comment by danielo515** [comment]
> There's already quite a few ways to pass arguments in templater.
> 
> * You can pass the frontmatter variables (as you did here) with tp.frontmatter
> * You can pass a value with the prompt (as you did here) with tp.system.prompt
> * You can pass a suggested value with tp.system.suggester
> * You can pass the values in your clipboard (what is copied such as using ctrl+c) with tp.system.clipboard
> * You can pass the tags in the parent file with tp.file.tags
> * You can pass the title in the parent file with tp.file.title
> * You can pass the entire text of any file with tp.file.include, store it as a string, and then do manipulation on it to get values
> * You can pass the highlighted text with tp.file.selection
> 
> There's likely other methods too. Depending on your use case, one of these may work for you
> 
> The passed info can then be manipulated with javascript using the <%* %> syntax described here. https://silentvoid13.github.io/Templater/commands/execution-command.html

Do you mind explaining yourself a bit more?
For my usecase there is no way to pass arguments to a template when using it to create a new file.
All the examples you gave about "passing arguments" seems to be directly related to the fact that you will be creating a single new note from the current template, but that doesn't hold if you are creating several new files using several templates, unless I'm missing something.

What I think is needed is a way to pass a third (or whatever position) to tp.file.create_new when calling, so the target template can have the right values to use.
Please keep in mind that the parent is not always the active file when you are using templater to execute commands, for example when creating a new project that involves several file creations or when adding values to a unrelated file like when you are creating new tasks from an unrelated current note.
