### ISSUE TITLE
Replace a file's content on startup ?

### ISSUE THREAD

**Issue by Lurux** [SilentVoid13/Templater#594]
Hi everyone !

New to Obsidian here, I have a "homepage" note that I'd like to populate with things like a link to my daily note and a daily quote on startup.

I've seen that Templater is able to rename, create or move files, but not delete them, and I haven't found a function to replace their content either. I've figured this might be possible using the `tp.obsidian` module, but I don't understand how to use it yet.

This issue will therefore serve two purposes:

- If anyone knows how do do this, I'd really appreciate your input
- If this actually not implemented, I'd like to suggest adding a function to either delete or replace a file's content

Thanks in advance for the help with this ! :slightly_smiling_face:

**Comment by Lurux** [comment]
#241 might be related: being able to live-replace transcluded files would allow us to embed a template in a file, and having that template being executed with the context of the calling file

**Comment by liamcain** [comment]
So to replace the contents you could do something like this:

Create the following files in your vault:
1. `homepage.md` - the contents here will be cleared very time you open the app so don't put anything important here!
2. `setup-homepage.md`- this will be the Startup Template that you add to your templater configuration.
3. `homepage-template.md` - this is the template for what you want the homepage to look like

Add the following to setup-homepage.md:

```md
<%*
  let homepage = tp.file.find_tfile("homepage");
  let contents = await tp.file.include("[[homepage-template]]");
  await this.app.vault.modify(homepage, contents);
  app.workspace.activeLeaf.openFile(homepage);
%>
```

Then add `setup-homepage` as a Startup Template in settings:
<img width="915" alt="image" src="https://user-images.githubusercontent.com/693981/159168562-d5376a59-fab8-4f06-9e14-c367c6813364.png">

That should do exactly what you're after.

# HOWEVER

I also want to recommend an alternative solution that might be less dangerous:

- Just enable "Open daily note on startup" instead: 
<img width="917" alt="image" src="https://user-images.githubusercontent.com/693981/159168606-4a325d49-4d4c-4b59-b65f-8d4ce5308c7d.png">

Then you can use the daily note as your home page. It's less destructive and you can just keep your daily quote in the daily note template.

**Comment by Lurux** [comment]
Thanks a lot, this worked prefectly !

I just figured out I need to use `app.*` to access the Obsidian functions, and not `tp.obsidian.*` like the documentation seems to indicate...
I was searching how to get a TFile for this function, find_tfile also doesn't appear in the doc :confused:
I'll try to see if I can update it.

Regarding the dangerousness of this action, I know this is what I want in my case, but i can understand why the dev would not want to expose such functions too easily to the users.
