### ISSUE TITLE
Templater creates a new file called "Untitled.md" with no content, then throws an error.  

### ISSUE THREAD

**Issue by wealthychef1** [SilentVoid13/Templater#598]
**Plugin information (please complete the following information):**

-   OS: macos monterey 12.3
-   Templater version: 1.12.0
-   Obsidian version: 0.12.4
-   Templater settings: [e.g. Template folder location: "Templates/", Timeout: "5" (add the templates not working with their associated command)]
Template folder location: "Templates"
Using Template Folder Action for "Projects/Thai Language/Study Blocks" and using template "Templates/Thai Language Study Block Template.md"  

**Describe the bug**
When I create a new note in the "" folder, the template executes, properly fills in the file I want with the proper title, then creates a new file called "Untitled.md" and throws the error 
```
VM126:82 Templater Error: Template parsing error, aborting. 
 Destination file already exists!
log_error @ VM126:82
```
**Expected behavior**
The template should just fill in my document.  

**Screenshots**

**Additional context**
I also posted this at https://forum.obsidian.md/t/why-is-my-template-giving-me-an-error/34508 but then I found this bug reporter.  Apologies for the dupe. 
Here is the YAML, the template and first few lines of the document:  
```
---
#_Created at 2022-03-19
Aliases: "<% tp.file.title %>"
---
#Thailand  #Language_Learning #thai/language 

<%	await(tp.file.rename(tp.date.now("YYYY_MM_DD")+" Thai Study Block")) %>

# Thai Study session for <% tp.date.now() %>
## Time estimate:  52 min
```

**Comment by wealthychef1** [comment]
I think I found the answer, sort of.  
It apparently was bad to do this in the YAML: `Aliases: "<% tp.file.title %>"`
Commenting that line out causes the file Template to work correctly.  
This still seems like a bug... :-). cheers

**Comment by wealthychef1** [comment]
OK I have boiled this down to a simple REPRODUCER.  I hope this is worth looking at.  It is mysterious. 
I have restarted obsidian and cast chicken bones into the sky for omens, but nothing is working.  

```
Bug Reproducer.  This is the entire file contents.  
<%*
await(tp.file.rename( "Thai_Study")) %>

```

**Comment by wealthychef1** [comment]
After a few followup emails on the other thread, which I apologize for the dupe, I should update this.  It seems the problem was in the folder assignment.  After assigning the template to another folder, it suddenly started working fine.  I then reassigned it back to the one I wanted, and it now works fine.  Maybe there was a typo or invisible character in the folder name, or something.  I do know that sometimes I get spurious "there is already a template assigned to that folder" error.  I'll post another report about that.  It might be the underlying cause of this bug.

**Comment by liamcain** [comment]
Glad to hear you have it working! I'm going to close this bug report for now if you don't mind. Feel free to reopen if you have more information or or are just having trouble getting things working.

**Comment by wealthychef1** [comment]
Yes thanks

**Comment by sutzig** [comment]
I've been experimenting with this issue and what I found is

- if I do not have a file open and use the Templater menu button or use a HotKey for a specific template, I get a Templater error message which reads "No active view, can't append templates;" 
- if I use a HotKey to create a new note from template, whether or not I have a file opened an empty Untitled document is created along with the new note saved in the correct directory;
- if I have a file open and use a HotKey for a specific template, the new is created and save in the correct directory and no extraneous Untitle file is created.

**Comment by wealthychef1** [comment]
This is interesting.  The behavior that I noticed happened no matter whether I created the file with "new file" from the contextual menu, or by a URI.  But it happened sporadically and seems to have stopped of its own accord.  Mostly.  :-)

**Comment by defarm** [comment]
@sutzig 
> if I use a HotKey to create a new note from template, whether or not I have a file opened an empty Untitled document is created along with the new note saved in the correct directory;

This is the exact issue I'm having. Additionally, if I call `Templater: Create new note from template` then the file I intend to create is placed in the correct folder, but Obsidian does not bring that up as the active file.
