### ISSUE TITLE
`templater_random_image` in README should be `templater_random_picture`

### ISSUE THREAD

**Issue by macintacos** [SilentVoid13/Templater#6]
I tried the `{{templater_random_image}}` and it didn't appear to be working. After checking the code, [it appears to be `{{templater_random_picture}}`](https://github.com/SilentVoid13/Templater/blob/ee50531ba643240fa05b6e2526f67b97c0f57466/src/internal_templates.ts#L19). Can the README be updated?

Thanks!

**Comment by SilentVoid13** [comment]
Nice catch, thanks for warning me !
