### ISSUE TITLE
Template for inserting full or partial path of file

### ISSUE THREAD

**Issue by brimwats** [SilentVoid13/Templater#60]
This is for use with a plugin like File path to URI (an Obsidian.md plugin) — currently Templater can insert both the folder name and the file name. Can these be combined and added to a full path insertion? Or at least a partial path (vault path) insertion?

**Comment by SilentVoid13** [comment]
Hey @brimwats, this has been implemented as of Templater 1.0.0. 
If you update, you will now be able to use `<% tp.file.path() %>` to get the full path of a note.
You can also use `<% tp.file.path(true) %>` to get the relative vault path of a note.
Closing this.
