### ISSUE TITLE
Error on Android 9: "TypeError: Object.fromEntries is not a function"

### ISSUE THREAD

**Issue by jacksteamdev** [SilentVoid13/Templater#603]
**Plugin information (please complete the following information):**

-   OS: Android 9 in Google Chrome OS Version 99.0.4844.94 (32-bit)
-   Templater version: 1.12.0
-   Obsidian version: 1.1.1 (49)
-   Templater settings: can't access Templater settings

**Describe the bug**
I'm running the Obsidian Android app on a Chromebook. This Chromebook uses Android 9.

When I try to enable Templater, it says it's enabled, but "Templater" doesn't show under the "Plugin Options" list, and Templater commands don't work. I can see Templater under "Settings -> Community Plugins", but the options button is missing.

I connected to Obsidian via ADB and saw the error "TypeError: Object.fromEntries is not a function" in the console. Upon inspection, `Object.fromEntries` is indeed undefined. It looks like this error keeps Templater from initializing.

**Expected behavior**
Templater settings should be available in the plugins list and execute Templater commands.

**Screenshots**
Error in ADB console
![image](https://user-images.githubusercontent.com/23390212/161341598-1dba10fb-ed66-45d1-9728-6e5b5adab849.png)

Templater under Settings -> Community Plugins
![image](https://user-images.githubusercontent.com/23390212/161342217-b215e765-6fcf-499c-b75d-ee8fa2ef3b79.png)

Templater is not under "Plugin Options" list
![image](https://user-images.githubusercontent.com/23390212/161342605-074092fb-2e8b-4fbd-b9b1-302e86e61061.png)

**Additional context**
Not sure why `Object.fromEntries` would be undefined, but adding a polyfill is an easy fix.

**Comment by jacksteamdev** [comment]
I discovered that different Chromebooks use different versions of Android. Perhaps this is why `Object.fromEntries` is undefined?

I have 2 Chromebooks; Templater works with one but not the other:

- ✅ Intel i3 processor, Chrome OS 64-bit with Android 11. Obsidian and Templater work just fine.
- ⚠️ ARM Octa-core processor, Chrome OS 32-bit with Android 9. Obsidian works, but Templater throws the error detailed above.

**Comment by shabegom** [comment]
Unfortunately, won't be able to support this.
