### ISSUE TITLE
Feature request: non-removable tp.file.cursor block and auto jump to it when opening a file

### ISSUE THREAD

**Issue by A-N-P** [SilentVoid13/Templater#609]
Please consider the ability to make a non-removable "tp.file.cursor" version that works in any notes. As well as the function of automatic transition to the specified position when opening a note. With saving the navigation function with hot keys. For example, such: <% tp.file.cursor (🔴)%>. So that it is not deleted automatically, after  jumping the cursor to it.
- This can be useful, for example, for notes with a long Yaml block so that when opening a note in editing mode, the upper part automatically scrolled upwards, and the top line became the string in which TP.File.cursor is located. For example, a string with the first header of the first level. It would help many users forum.obsidian.md, from such how: [Can you hide the “Metadata” box when previewing a note with YAML metadata?](https://forum.obsidian.md/t/can-you-hide-the-metadata-box-when-previewing-a-note-with-yaml-metadata/21931); [YAML YAML, Go Away](https://forum.obsidian.md/t/yaml-yaml-go-away/17352); [Hiding YAML in Edit Mode](https://forum.obsidian.md/t/hiding-yaml-in-edit-mode/17394); [Option to hide frontmatter in live preview](https://forum.obsidian.md/t/option-to-hide-frontmatter-in-live-preview/28090). 
- This would allow manually to set the position where the user would like to continue editing the next time: [Save reading position](https://forum.obsidian.md/t/save-reading-position/1785); [When opening document place the cursor at the bottom of it](https://forum.obsidian.md/t/when-opening-document-place-the-cursor-at-the-bottom-of-it/1239). 
- And it would significantly increase the convenience of the program.

**Comment by liamcain** [comment]
Why not just fold the frontmatter?

**Comment by A-N-P** [comment]
> frontmatter

Comfortable when there are a lot of notes, and long blocks of additional information are used at the top. It is also the ability to scroll blocks with Dataview tags placed under frontmatter. The main goal is the ability to move at certain places in long notes. For example, in order for the next time you open a note automatically return to the position that I would like to visit, either correct first when you open a note after a long period of time.

**Comment by liamcain** [comment]
There's a plugin called Remember cursor position that you might be interested in.
