### ISSUE TITLE
Why don't internal templates work for me?

### ISSUE THREAD

**Issue by InvisbleO** [SilentVoid13/Templater#61]
Hi, just tried using {{tp_cursor}} (and other internal templates as well), when using them in my main template (that also uses predefined patterns from Obsidian like {{date}} and creating a new file with it, the pattern is not being replaces (or cursor does not move to the place and pattern is still there). Not sure about user templates as I am newbie, but dont seem to work, either. Idea why? Am I doing something wrong? There is an Obsidian forum topic about this as well.

**Comment by kaveet** [comment]
Can you try this and post back the results?

1. Open a note you're experiencing this issue on
1. Press `Cmd+P` or `Ctrl-P` to open the command palette
1. Select "Templater: Replace templates in the active file"

**Comment by SilentVoid13** [comment]
Hey @InvisbleO, Templater had a huge update, fixing a lot of things.
It introduces a new template syntax.
Could you update Templater to the latest version, update your existing templates with the new syntax and tell me if you still experience the same problem ?

**Comment by SilentVoid13** [comment]
Closing this, don't hesitate to ask questions if you have some.
