### ISSUE TITLE
Modify YAML of a file (based on its name)

### ISSUE THREAD

**Issue by Excali6ur** [SilentVoid13/Templater#615]
Is there a way to modify YAML of a not active file?

smth alongside `tp.file.find_tfile("File").frontmatter["Key"] = New Value`

**Comment by AB1908** [comment]
Look at metaedit's API. I know some folks aren't fans of adding dependencies but it's a a rather clean approach IMO.

**Comment by Excali6ur** [comment]
https://github.com/chhoumann/MetaEdit
