### ISSUE TITLE
Template Hotkeys, but for creating a new note from template

### ISSUE THREAD

**Issue by stefandesu** [SilentVoid13/Templater#617]
**Is your feature request related to a problem? Please describe.**
For me personally, the powerful part about templates is creating new notes from a template. This is possible with the command "Templater: Create new note from template". However, if you do it often, it takes quite a long time to always select the template on which the note should be based.

**Describe the solution you'd like**
Basically the "Template Hotkeys" feature, only for creating a note from template instead of inserting from template.

**Describe alternatives you've considered**
I guess it wouldn't be too difficult to hack my way around this issue, but I think it would be nice to have it built-in.

**Additional context**
\-

Thanks!

**Comment by AB1908** [comment]
Indeed, not too hard to create a workaround. You could create a template that creates a new note instead and bind this template to a hotkey.

**Comment by stefandesu** [comment]
Thanks for the hint! After some experimenting (I couldn't figure out how to get a TFile reference), I got it to work (in case someone else is looking for this):

```
<%*
const folder = this.app.vault.getAbstractFileByPath("work")
const template = this.app.vault.getAbstractFileByPath("templates/My Template.md")
tp.file.create_new(template, null, true, folder)
_%>
```

(Note that I left the filename empty because the target file renames itself according to the current date.)

**Comment by AB1908** [comment]
Very cool!
