### ISSUE TITLE
Daily notes created by link are not templated

### ISSUE THREAD

**Issue by Mayeu** [SilentVoid13/Templater#62]
**Plugin informations (please complete the following information):**

 - OS: macOS 10.15.7
 - Templater version: 0.5.7
 - Obsidian version: 0.11.0
 - Templater settings:
   - Template folder location: "Templates/"
   - Timeout: "5" 

**Describe the bug**

I have a created a daily notes template (via the daily notes core plugin) that contains links to past and future notes.

When creating the daily notes the templates correctly kicks in, but when I click the yesterday/tomorrow note the template is not used if there were no daily notes at that time.

**Expected behavior**

When clicking link pointing to a Daily Notes file that doesn't exist, I'm expecting the notes to be filed by the templates.

**Screenshots**

See this screencast: https://user-images.githubusercontent.com/222375/108624846-b4d09280-7447-11eb-9967-57c61ece53cc.mp4

**Additional context**

I assume this is because there is no way for the template engine to know that I'm opening a new daily notes right now.

**Comment by cazminah** [comment]
I don't think this is a bug. The links in your screencast are just references to pages that don't exist yet. Hence, when you click on them, you get a blank page. You can populate it with the daily notes template by using Alt + E and selecting it from the dropdown.

Obsidian doesn't support automatically building new pages from templates yet. It's been discussed [here](https://forum.obsidian.md/t/templates-for-new-notes/322).

**Comment by SilentVoid13** [comment]
Hey @Mayeu, as @cazminah said (thanks for the answer), this issue is not related with Templater, this is something obsidian doesn't support.

Closing this.
