### ISSUE TITLE
Add a feature like tp.file.cursor but with default text in it

### ISSUE THREAD

**Issue by Archie-2021** [SilentVoid13/Templater#620]
**Is your feature request related to a problem? Please describe.**
I want to jump tp some places in the text (like tp.file.cursor does) but with a text highlighted in it (ready to decide to leave it be to default of changing it and jumping to the next point like cursor command). I have seen a lot of it in app, I don't know the name of it but it is very handy

thank you for creating this great plugin

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by welpdx** [comment]
Does #641 answer this issue? Or is this about something else? Thanks

**Comment by Archie-2021** [comment]
> Does #641 answer this issue? Or is this about something else? Thanks

Oh I almost can't remember that I posted such a request.
Yes this is an old issue that now solved.

**Comment by welpdx** [comment]
Excellent. Would you be able to close this? Thanks

**Comment by welpdx** [comment]
Oh, weird. When you comment to this, do you see an option to close?


![img](https://i.stack.imgur.com/vRuSR.png)

**Comment by Archie-2021** [comment]
> Oh, weird. When you comment to this, do you see an option to close?
> 
> ![img](https://camo.githubusercontent.com/80a368bc16d1ddc28f7245af797e1506fb4d56af792611e4c80b91c796a4591f/68747470733a2f2f692e737461636b2e696d6775722e636f6d2f76527553522e706e67)

Sorry I was looking on the top, totaly missed the button down below.
