### ISSUE TITLE
Internal Templates dynamic values

### ISSUE THREAD

**Issue by iacobson** [SilentVoid13/Templater#63]
Hi. Not sure if I'm using the plugging correctly, but this is what I experience

I have a template file like this
`created: {{tp_creation_date}} | updated: {{tp_last_modif_date}}`

If I create a new file and use the Obsidian Template plugin to insert template, it will just show the template text as it is: `created: {{tp_creation_date}} | updated: {{tp_last_modif_date}}`. If I go to markdown preview, it stays the same.

I followed the advice in this other issue:
https://github.com/SilentVoid13/Templater/issues/61#issuecomment-780611475

using `Replace templates in the active file` adds the actual values (date-time). But they become simply static values.
Eg. if I update later on the file, `tp_last_modif_date` will stay the same.

As far as I could see in the demo screencast of the plugin it looks like they have the variable in the template `tp_last_modif_date` but see the actual value in the preview. Am I wrong? 

So my question is: is there a way to make ``tp_last_modif_date` dynamically update? or what I get is the expected behavior?

**Comment by luckman212** [comment]
You need to disable the builtin Template plugin and then use Templater to insert your templates to make the substitution work.

You should bind a hotkey to it...

**Comment by iacobson** [comment]
Great, thanks, it works this way when I insert the template.
Still `{{tp_last_modif_date}}` is substituted with a string, so probably there is no way to always get the last update time

eg: _created: 2021-02-24 13:22_ | _updated: 2021-02-24 13:22_

but I make an update later on. The updated above is just a string, so it will not change. Is there a way to make it dynamic?
Eg. I modify the file now, it will show: 13:29

**Comment by ClaudioDavi** [comment]
Hey @iacobson, have you found a solution for this?

**Comment by iacobson** [comment]
Hi, unfortunately not. I don't even know if what I want is possible.
As the value is converted to plain text. So it cannot keep updating with the last update date/time

**Comment by SilentVoid13** [comment]
Hey @iacobson, as of Templater 1.6.0, you can use dynamic commands, that will be triggered and replaced in preview mode.

In your use case, this would give:

```
<%+ tp.file.last_modified_date() %>
```

To get a dynamic last modifed date whenever you enter preview mode.

Documentation at https://silentvoid13.github.io/Templater/docs/commands/dynamic-command

**Comment by ngirard** [comment]
> To get a dynamic last modifed date whenever you enter preview mode.

Heya,

my attention was caught by this new feature... it seems potentially interesting !

If you don't mind me asking here:
> If you want to refresh it, you must close the note to clear the cache and open it again.

Would the rendering be also refreshed by toggling the preview mode on and off, which seems more natural to me ?

**Comment by SilentVoid13** [comment]
Hey @ngirard, no because just toggling on and off keeps the file in cache (that's why there is cache in the first place, to avoid having to re-render the whole file when making a small change). The Dataview plugin if you're familiar with it also experience this problem of refreshing.

There are no real good solutions at the moment for that problem, but in the case of the `tp.file.last_modified_date` example, I don't think it's that bad, because the last modified information is relevant when you open the note.

**Comment by ngirard** [comment]
@SilentVoid13, thanks for your explanations !

> The Dataview plugin if you're familiar with it

I am familiar with it, although I haven't used it for long ; and if I understand correctly Dataview is able to update its output every 300ms or so if needed, so my assumption would be that they managed to either invalidate Obsidian's cache, or bypass it.

I'm not sure of anything, but it that's the case, then it could be worth looking into their code.

> in the case of the tp.file.last_modified_date example, I don't think it's that bad
Agreed !

Cheers
