### ISSUE TITLE
Daily Note 

### ISSUE THREAD

**Issue by k2mikaili** [SilentVoid13/Templater#64]
[Loom.com](https://www.loom.com/share/c494dc19a4db43d882e218098240ae29)

**Comment by pointlessone** [comment]
I had the very same issue. And someone on Discord said they had it too. The fix was to restart Obsidian. Apparently there's some issue with the plugin initialization right after installation.

**Comment by jandamm** [comment]
Had the same issue. Restarting Obsidian did fix it for me as well.

**Comment by SilentVoid13** [comment]
Hey @k2mikaili, sorry for the late response.
Templater had a huge update recently. It now has a new syntax, you'll need to update your existing templates.
This update should fix a lot of things, could you update to Templater's latest version, restart obsidian, update your existing templates with the new syntax and tell me if the bug still persists ?

**Comment by SilentVoid13** [comment]
Closing this, don't hesitate to ask questions if you have some.
