### ISSUE TITLE
Escaping out a command

### ISSUE THREAD

**Issue by dingbat91** [SilentVoid13/Templater#645]
Firstly Hi there Silentvoid. Thanks for a fantastic plugin!

I've been looking into using templater with the button plugin (by [shabegom](https://github.com/shabegom/buttons)) to create an automated system for setting up notes and structure for my tabletop games quickly. Keeping all the files for each game together, and I've run into a bit of a snag.

Currently, I have a front page that has a button on it that, when pressed, automatically creates a folder structure for that game as well as a front-page for the game via a template. 

The game page then has some lists (to be auto-generated via dataview), with buttons to add new items and correctly place them into their respective folders.

The issue I'm currently having is when the button on the front page generates the game page. The button on the game page, which has a templater command in its code block (The code I want it to use) is resolved during that page's initialisation, which then causes the button to stop working.

Is there any current way to put a templater command into a template without it being resolved on that template's use? I've been stumbling about on the issue for a while now and it's driving me crazy.

**Comment by welpdx** [comment]
If you want to output a block templater script formatted like this:
```js
<%*
...
js code...
...
%>
```
Then all you have to do is output the first `<%*`. Like this:
```js
<%* tR+= `<%* ` %>
...
js code...
...
%>
```

Hope that helps. 

~Welp

**Comment by dingbat91** [comment]
That's great! Thank you!

**Comment by welpdx** [comment]
I'm happy to help! I'm glad that worked for your use case.
