### ISSUE TITLE
Injecting some useful info as env in commands 

### ISSUE THREAD

**Issue by xeor** [SilentVoid13/Templater#65]
**Is your feature request related to a problem? Please describe.**
The script/commands that is run should have some more context so they can be smarter..

**Describe the solution you'd like**
Use options.env (https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback) where the exec is run and inject some useful variables that the script can use. Example  `obsidian_templater_path` will be the full path of the file.

**Describe alternatives you've considered**
Using some magic variables when defining the commands so the data is sent as parameter.

**Additional context**

**Comment by SilentVoid13** [comment]
Hey @xeor, this has been implemented as of Templater 1.0.0!
If you update, you will now be able to pass arguments to your templates (using the new user templates syntax).
If you defined a `test` user template, this would give the following syntax: `<% tp.user.test({arg1: "arg1 value", arg2: "arg2 value", ...}) %>`
Arguments will be available as environment variables.
Check https://github.com/SilentVoid13/Templater#user-templates-arguments for more informations.
Tell me if this works for you.
Closing this.

**Comment by xeor** [comment]
Awesome @SilentVoid13 ! Thanks for doing this!
