### ISSUE TITLE
Ability to remove multiple newlines with the whitespace control option

### ISSUE THREAD

**Issue by HyperEpsilon** [SilentVoid13/Templater#654]
**Is your feature request related to a problem? Please describe.**
Often when writing complex execution commands I find myself wanting to more cleanly separate my code from the rest of my document, especially if I put it at the top.

In practice I will have the code separated by 2 newlines, then the rest of the file. I am unable to remove both newlines with the `-` appended, and appending `--` causes the parser to break.

**Describe the solution you'd like**
Add the option to add `--` to removed 2 newlines instead of just 1, both at the beginning and the end, allowing more clear separation of code and normal writing.

**Describe alternatives you've considered**
I have been only adding a single new line at the end, which doesn't separate as nicely

**Comment by welpdx** [comment]
[Templater](https://silentvoid13.github.io/Templater/commands/whitespace-control.html) uses [Eta](https://eta.js.org/docs/syntax/whitespace-control), and the whitespace control option is limited to `_` and `-`. It doesn't seem easy to add extra whitespace control options to Eta via Templater. 

### A simple trick
I would recommend using `_%>` to remove all whitespace (include all newlines) after the snippet.
Then, at the end of your script, just add an `tR+="\n"` to add one single newline. 

Demonstration: 
![demo](https://i.imgur.com/vVSSlQV.gif)

Hope that helps.

~Welp

**Comment by HyperEpsilon** [comment]
That almost perfectly, I actually didn't realize that the `_` got newlines as well. That's a perfect example.

BTW How are you getting that syntax highlighting on the templater text?

**Comment by welpdx** [comment]
>That works almost perfectly, I actually didn't realize that the _ got newlines as well. Thank you so much. 

Awesome! I'm happy to help!

> BTW How are you getting that syntax highlighting on the templater text?

There is a setting in Templater plugin settings to turn on Syntax highlighting
![img](https://i.imgur.com/urHu0m4.jpeg)

**Comment by welpdx** [comment]
#627 as I understand is not about syntax highlighting, but about executing Obsidian commands. From `<% tp.date.now() %>` to `2022-06-02`

**Comment by HyperEpsilon** [comment]
> #627 as I understand is not about syntax highlighting, but about executing Obsidian commands. From `<% tp.date.now() %>` to `2022-06-02`

You're right, my mistake
