### ISSUE TITLE
Can Templater access YAML Frontmatter? 

### ISSUE THREAD

**Issue by quintrino** [SilentVoid13/Templater#66]
Hi, 

I'd like to be able to have a template that runs a command and uses some of the YAML Frontmatter as a variable. 

For example, if in my YAML I have
```
-----
Status:Seedling
-----
```
I'd want to be able to do {{templater_command: YAML.status}} or something similar. 

Is this currently possible? I had a look but I could find an answer one way or another.

**Comment by SilentVoid13** [comment]
Hey @quintrino, this has been implemented as of Templater 1.0.0!
If you update, you will now be able to use the Frontmatter module.
In your case, this would give `<% tp.frontmatter.Status %>` to be able to access the `Status` YAML field value.
Tell me if this works for you.
Closing this.

**Comment by quintrino** [comment]
Amazing!
