### ISSUE TITLE
Template parsing error - with tp.web.daily_quote()

### ISSUE THREAD

**Issue by plusuncold** [SilentVoid13/Templater#661]
**Plugin information (please complete the following information):**
Linux Ubuntu 22.04
Obsidian 0.14.15
Templater 1.12.0

iOS 15
Obsidian 1.2.3 (57)
Templater 1.12.0

Syntax highlighting on
Trigger Templater on new file creation on

Template file:
```
---
Tags: #daily_notes
Tick: ✅
Habits:
   Anki: 
---
# <% tp.date.now("dddd Do MMM YYYY", 0, tp.file.title, "YYYY-MM-DD") %>
<<  [[<% tp.date.now("YYYY-MM-DD", -1, tp.file.title, "YYYY-MM-DD") %>]] | [[Home]] | [[<% tp.date.now("YYYY-MM-DD", 1, tp.file.title, "YYYY-MM-DD") %>]] >>
<% tp.web.daily_quote() %>
-------
[wordle](https://www.nytimes.com/games/wordle/index.html) | [quordle](https://www.quordle.com/#/) | [worldle](https://worldle.teuteuf.fr/)

## NOTES
```

**Describe the bug**
This template is used for my daily notes. Upon creating a new daily note the template does not resolve and posts the error 

```
Templater Error: Template parsing error, aborting. 
 Failed to fetch
log_error @ plugin:templater-obsidian:82
```

Error occurs on both Linux and iOS

**Expected behavior**
The template should resolve and the date, etc be inserted.

**Comment by dredhorse** [comment]
your problem is the tp.web.daily_quote statement I would guess. try removing it and try it in its own template.
If the above is the case you should rename the issue correspondingly.

**Comment by plusuncold** [comment]
Yes, once I removed that line it worked fine - I wonder why it's causing an issue, it's the same as in the docs

**Comment by plusuncold** [comment]
Can confirm that I get the same problem inserting a template file that contains just

```
<% tp.web.daily_quote() %>
```

**Comment by dredhorse** [comment]
try https://api.quotable.io/random manually

**Comment by plusuncold** [comment]
Yes, it can't find the server. I'll close the ticket.

**Comment by dredhorse** [comment]
can you open it again? @SilentVoid13 will need to figure out why the server isn't there anymore

**Comment by welpdx** [comment]
Note: this Templater feature seems to be from a [Templater Showcase](https://github.com/SilentVoid13/Templater/discussions/157) #157, which utilizes [lukePeavey](https://github.com/lukePeavey)'s quotable. On his repo, [his api is apparently down right now](https://github.com/lukePeavey/quotable#warning-api-is-temporarily-down-warning)

 --- 

To prevent your template from aborting midway, enclose the tp.web command in a try catch. 
Please see [comment in](https://github.com/SilentVoid13/Templater/issues/595#issuecomment-1133755962)  #595

```js
<%*
    try {
        tR += await tp.web.daily_quote()
    } catch (err) {
        new Notice("Error: \n" + err , 2000);
    }
%>
```
