### ISSUE TITLE
Associate specific templates with a file via Frontmatter

### ISSUE THREAD

**Issue by HyperEpsilon** [SilentVoid13/Templater#663]
**Is your feature request related to a problem? Please describe.**
I have several 'snippet' templates that I use in only one or two notes, an example would be the structure of a TV show, or a new area on a minecraft map I'm playing. Seeing as I only use these templates on a couple files, they are needlessly clogging up the list of templates that I use on a broader set of files.

**Describe the solution you'd like**
Add support for a Frontmatter tag that would allow you to associate (or maybe just prioritize) certain templates with a specific file.

For example if I have a snippet template called "taskmaster-episode" that I use to record the details in a master file I could use either of the following methods:
```yaml
---
templater: "taskmaster-episode", "PATH/TO/TEMPLATE/taskmaster-episode.md"
---
```

Then when the template modal is opened, any templates in the frontmatter are put to the front (or added to the list if they aren't in the standard template folder)

**Describe alternatives you've considered**
There isn't really an alternative I have, I just have to deal with all the snippets clogging my template modal

**Comment by AB1908** [comment]
Can you show me your script? I think this is already doable but wanted to check how you've set things up first.

**Comment by HyperEpsilon** [comment]
I don't have any specific script set up, but the template snippets that I am inserting are generally 5-10 lines of pre-formmated markdown.

I've looked at the code a bit, and the thought I had was to modify `getItems()` in `FuzzySuggester.ts` to additionally parse the frontmatter of the active pane, search for a `templater` entry, then add any files there to the top of the list.

as for my folder structure, my template folder looks like:
```
zz_meta/Templates/
	general/     -- Where I keep my general purpose templates that I want to access across many files
	specific/    -- Where I keep my templates that are associated with one specific folder and are triggered on file creation
	snippets/    -- Where I keep my template snippets that are only used in one file, but are short and used repeatedly.
```

My desire for this change is that I can keep my general folder fairly clean, while using the frontmatter to associate specific templates from my snippets folder with their respective notes.

**Comment by AB1908** [comment]
I'd say you can create a "parent script" that checks the frontmatter instead of actually modifying the source code.

**Comment by AB1908** [comment]
Hmm I'll try and write out an example tomorrow ish

**Comment by AB1908** [comment]
Existing file:
```
---
templater: 'tv-episode'
---
```

Templater script:
```js
<%*
let content = "";
if (tp.file.frontmatter.templater) {
    const template = tp.file.frontmatter.templater;
    content += await tp.file.include(`[[${template}]]`);
} else {
    // tp.system.suggester to insert other stuff optionally
    // need to write a bit to gather all other templates
    // lets you insert the other types of templates
}
tR += content;
```

Could also do this the other way around where all templates invoke a `finally_do_this()` userscript that lets you insert any additional content as needed. If this doesn't make much sense, reach out to me on Discord and I'll see if we can discuss this over a voice chat or something.

**Comment by HyperEpsilon** [comment]
That is a really cool idea that I hadn't considered. It wouldn't work if you had multiple items, but that can be worked around with `tp.system.suggester`.

In fact, I could even add all the rest of the templates if I grab the general template folder with `app["plugins"]["plugins"]["templater-obsidian"]["settings"]["templates_folder"]`

Thank you! I will have to investigate this further.

**Comment by AB1908** [comment]
It _can_ work with multiple files. It's just a lot of work. You can crawl the dir for template files and then dynamically populate the suggester.

**Comment by welpdx** [comment]
Or you can like name all your templaters with something unique, like for example a "_template" suffix. (e.g., "daily_template.md" "monthly_template.md")

Then just do:
```js
var files = this.app.vault.getAllLoadedFiles();
const suggestNameArray = new Array();
const suggestTFileArray= new Array();

files.forEach((file) => {
	if (file.basename?.endsWith('_template') ) { 
		suggestNameArray.push(file.basename);
		suggestTFileArray.push(file);
	}
})
var outputtFile = await tp.system.suggester(suggestNameArray, suggestTFileArray);
```

**Comment by welpdx** [comment]
Or since I suspect you have alot of templates, try this:
```js
<%* 
var path = tp.obsidian.normalizePath(this.app.plugins.plugins["templater-obsidian"].templater.plugin.settings.templates_folder)
const tFolder =  await this.app.vault.getAbstractFileByPath(path)
const suggestNameArray = new Array();
allDescendants(tFolder)

// itterate through all subfolders to get all files
function allDescendants (node) {
	for (var i = 0; i < node.children?.length; i++) {
		var child = node.children[i];
		allDescendants(child);
		if ((child instanceof tp.obsidian.TFile)) {suggestNameArray.push(child.basename);}
	}
}



if (suggestNameArray.length == 0 ){ 
	new Notice("No files found! "  );
} else {
	var template = await tp.system.suggester(suggestNameArray, suggestNameArray);
	if (template == null) {
		// suggester exited with no input
		new Notice("Exited Script", 5000)
	} else {
		tR += await tp.file.include(`[[${template}]]`);
	}
}
%>
```

Both scripts are additions to @AB1908 's. You can add them to his `else` statement.

**Comment by welpdx** [comment]
In combination of @AB1908 's above script:

## Version 1: If there is a template in frontmatter, use that template

<details><summary>Version 1</summary>
<p>

```js
<%* // v1.3
let content = "";
if (tp.frontmatter?.templater) {
	try {
		const template = tp.frontmatter.templater;
		content += await tp.file.include(`[[${template}]]`);
	} catch (e) {
		new Notice("Error with getting content from template:" + e );
	}
} else {
    var path = tp.obsidian.normalizePath(this.app.plugins.plugins["templater-obsidian"].templater.plugin.settings.templates_folder)
	const tFolder =  await this.app.vault.getAbstractFileByPath(path)
	var suggestNameArray = new Array();
	allDescendants(tFolder)

	if (suggestNameArray.length == 0 ){ 
		new Notice("No files found! "  );
	} else {
		var template = await tp.system.suggester(suggestNameArray, suggestNameArray);
		if (template == null) {
			// suggester exited with no input
			new Notice("Exited Script", 5000)
		} else {
			content += await tp.file.include(`[[${template}]]`);
		}
	}
}

// iterate through all subfolders to get all files
function allDescendants (node) {
	for (var i = 0; i < node.children?.length; i++) {
		var child = node.children[i];
		allDescendants(child);
		if ((child instanceof tp.obsidian.TFile)) {suggestNameArray.push(child.basename);}
	}
}

tR += content;
%>
```

</p>
</details>


<details>
           <summary style="font-size:20">Demo v1</summary>
           <img src="https://i.imgur.com/7ojO9Ag.gif" alt="demo" />
</details>


## Version 2: Like what you mentioned above, having the template in frontmatter as another option in suggester 


<details><summary>Version 2</summary>
<p>

```js
<%*  //v1.4
let content = "";
var path = tp.obsidian.normalizePath(this.app.plugins.plugins["templater-obsidian"].templater.plugin.settings.templates_folder)
const tFolder =  await this.app.vault.getAbstractFileByPath(path)
const suggestNameArray = new Array();

if (tp.frontmatter?.templater) {
	try {
		const template = tp.frontmatter.templater;
		tp.file.include(`[[${template}]]`);
		suggestNameArray.push(template)
	} catch (e) {
		new Notice("Error with getting content from template:" + e );
		break;
	}
} else {
	new Notice("No template found in Frontmatter. ")
}

allDescendants(tFolder)

if (suggestNameArray.length == 0 ){ 
	new Notice("No files found! "  );
} else {
	var template = await tp.system.suggester(suggestNameArray, suggestNameArray);
	if (template == null) {
		// suggester exited with no input
		new Notice("Exited Script", 5000)
	} else {
		content += await tp.file.include(`[[${template}]]`);
	}
}

// itterate through all subfolders to get all files
function allDescendants (node) {
	for (var i = 0; i < node.children?.length; i++) {
		var child = node.children[i];
		allDescendants(child);
		if ((child instanceof tp.obsidian.TFile)) {suggestNameArray.push(child.basename);}
	}
}

tR += content;
%>
```

</p>
</details>


<details>
           <summary style="font-size:20">Demo v2</summary>
           <img src="https://i.imgur.com/Kmrq7lD.gif" alt="demo" />
</details>
