### ISSUE TITLE
daily quote CORS failure causes template load to fail

### ISSUE THREAD

**Issue by thesamim** [SilentVoid13/Templater#665]
**Plugin information (please complete the following information):**

-   OS: Windows 10
-   Templater version: 1.12.0
-   Obsidian version: 0.14.15
-   Templater settings: Template folder location: "Templates/"

**Describe the bug**
Daily Quote in template fails. Template loading fails altogether.

**Expected behavior**
If a part of the template fails, rest of template should ought to load.

**Attachments**
1. templaterDailyQuoteFailTrace.log
2. daily.md

**Notes:**
1. The Daily Quotes failure is annoying, but not that important.
2. Not sure what other failures could occur, but catching the exceptions and proceeding with other parsing would be ideal.

[templaterDailyQuoteFailTrace.log](https://github.com/SilentVoid13/Templater/files/8929433/templaterDailyQuoteFailTrace.log)
[daily.md](https://github.com/SilentVoid13/Templater/files/8929427/daily.md)

**Comment by welpdx** [comment]
Similar to #661, #595 
Please see [my comment in #595](https://github.com/SilentVoid13/Templater/issues/595#issuecomment-1133755962)

```js
<%*
    try {
        tR += await tp.web.daily_quote()
    } catch (err) {
        new Notice("Error: \n" + err , 2000);
    }
%>
```

Note: this Templater feature came from a [Templater Showcase](https://github.com/SilentVoid13/Templater/discussions/157) #157, which utilizes [lukePeavey](https://github.com/lukePeavey)'s quotable. On his repo, [his api is apparently down right now](https://github.com/lukePeavey/quotable#warning-api-is-temporarily-down-warning)
