### ISSUE TITLE
Error message links to the error

### ISSUE THREAD

**Issue by Saorsa32** [SilentVoid13/Templater#669]
**Is your feature request related to a problem? Please describe.**

I am very new to obsidian and coding. It would be so helpful if when the error message it would link to location of the error. When the message comes up I end up wasting so much time just figuring out which one is causing the problem. I know that you can try to fix the problem using the console, but my understanding is so limited I rarely have success in being able to fix the problem. 

**Describe the solution you'd like**

If I could just click on the error message and have it take me to what I need to fix that would be amazing. I am not sure if this is even possible, but it would be such a great help to a newbie like me. Thank you for your wonderful plug-in. I use it in almost everything I do.

**Describe alternatives you've considered**

**Additional context**

**Comment by welpdx** [comment]
### I understand, but it's natural
I identify with you. Debugging sometimes takes hours, and the mistake could be something really minor! I think that is the nature of debugging though. If you goto the [programming subreddit](https://www.reddit.com/r/programming/), you'll always find memes about how it's like 10% coding and 90% debugging.

### existing error in console
Anyways, I recently found that the errors in the in console from Chrome is not that bad. 
<details>
           <summary style="font-size:20">For example</summary>
           <img src="https://i.imgur.com/4H6CK1W.gif" alt="demo" />
</details>

The reason why it is hard to find the location of the problem sometimes is it seems all the code eventually goes into one single `app.js` file or something. 

### possible enhancement for Templater
Currently, when codding a template, the Templater plugin does do syntax highlighting, using codeMirror, which helps alot. Perhaps @SilentVoid13 could implement a linter later on as well. CodeMirror does have a [js linter addon](https://codemirror.net/5/doc/manual.html#:~:text=defines%20an%20interface%20component%20for%20showing%20linting%20warnings%2C%20with%20pluggable%20warning%20sources) but idk specifically how that can be implemented.

### alternatives
1. I think the [obsidian-codemirror-options](https://github.com/nothingislost/obsidian-codemirror-options) does something like that too. It could tell you if your code has errors for example. 

2. You could also consider using an code editor like sublime text and install a linter to help you debug coding issues. You can also use an online one like jsfiddle. Though, in both cases you won't be able to access things like the `tp` object. 

3. In any case, if you have a problem you can't figure out, you can always feel free to post your problem at [Discussions](https://github.com/SilentVoid13/Templater/discussions) and [make a post](https://github.com/SilentVoid13/Templater/discussions/new?category=help).
