### ISSUE TITLE
'Internal_Template_Error' error on the tp_title_date function

### ISSUE THREAD

**Issue by DaveHenning** [SilentVoid13/Templater#67]
**Plugin informations (please complete the following information):**
 - OS: Windows 10
 - Templater version: 0.5.7
 - Obsidian version: 0.11.9
 - Templater settings: Template folder location: "_templates", Timeout: "5" 
 

**Describe the bug**
When creating a daily template everything looks normal for a second then all of the `tp_title_date` functions convert to `Internal_Template_Error`. Specifically, what I mean is the template loads perfectly normal, all of the `tp_title_date` functions accurately show the dates they are expected to convert to, but then after about 2 seconds they all convert to `Internal_Template_Error`

**Video Example** 
https://www.loom.com/share/6e53a85cd2fa46b0b16a1b0a63983087

**Text Example**
```
# {{tp_title_date:f=YYYY.MM.DD}} {{tp_title_date:f=dddd}}
[[_dailies/{{tp_title_yesterday:f=YYYY.MM.DD}}|<< Yesterday]] | [[_dailies/{{tp_title_tomorrow:f=YYYY.MM.DD}}|Tomorrow >>]]
```
The above is properly set to the below for about two seconds, then changes to further below. 
```
# 2021.03.23 Tuesday
[[_dailies/2021.03.22|<< Yesterday]] | [[_dailies/2021.03.24|Tomorrow >>]]
```
```
# Internal_Template_Error Internal_Template_Error
[[_dailies/Internal_Template_Error|<< Yesterday]] | [[_dailies/Internal_Template_Error|Tomorrow >>]]
```

**Additional context**
This may not be a Templater bug at all. Might be due to the Obsidian 11.9 update. I am starting here as it's definitely related to `tp_title_date`

**Comment by DaveHenning** [comment]
FWIW this worked today as expected. Still on Obsidian 11.9 and Templater 0.5.7.

Interesting.

**Comment by Mpic** [comment]
I don't see a new syntax for the {{tp_title_tomorrow}} and other tp_title based dates, is there any ?
I tried <% tp.title.tomorrow %> without success.

**Comment by SilentVoid13** [comment]
Hey @Mpic, you can use the following syntax:

```
File's title date yesterday: <% tp.date.now("YYYY-MM-DD", -1, tp.file.title, "YYYY-MM-DD") %>
File's title date: <% tp.date.now("YYYY-MM-DD", 0, tp.file.title, "YYYY-MM-DD") %>
File's title date tomorrow: <% tp.date.now("YYYY-MM-DD", 1, tp.file.title, "YYYY-MM-DD") %>
```

You can change the format syntax of course.

**Comment by Mpic** [comment]
Thanks a lot !
I should have read better the new documentation (a search of "tomorrow" didn't get the line explaining this as it's called "File's title + 1 day"), sorry.

Is there a way of specifying only one optional argument ? Having to specify the format syntax each time means I have to change it everywhere if I want to change the "default" (not a real problem I guess, maybe I'm overthinking).

**Comment by SilentVoid13** [comment]
@Mpic No, if you want to specify only the last for argument for example, you have to specify the 3 first arguments. That's the only downside of the new syntax, but it's not that bad even though it makes things a bit more verbose.

**Comment by SilentVoid13** [comment]
Closing this, don't hesitate to ask questions if you have some.
