### ISSUE TITLE
insert templates for all files in a folder

### ISSUE THREAD

**Issue by ToUpgrade** [SilentVoid13/Templater#680]
**Is your feature request related to a problem? Please describe.**
I have so many notes edited before when not using Templater, now I have to insert the general_yaml_template  created by templater to every note manually.

**Describe the solution you'd like**
add a command to insert templates for all files in a specific folder

**Describe the Alternative solution**
or is there any script that can do the job?(i don't think so)

**Comment by shabegom** [comment]
Closing in favour of #660
