### ISSUE TITLE
tp.file.rename doesn't change filename

### ISSUE THREAD

**Issue by inyeollee** [SilentVoid13/Templater#681]
**Plugin information (please complete the following information):**

-   OS: macOS 12.4
-   Templater version: 1.12.0
-   Obsidian version: 0.14.15
-   Templater settings: Template folder loation: zmeta/template

**Describe the bug**
I keep the filename and the note title the same. When I change the title I need to update the filename accordingly. To automate this I made a template:
```
<%*
await tp.file.rename(tp.file.title)
-%>
```
If I run this template while in current note, the filename doesn't change. I confirmed the template runs by putting redundant string in the template. It appears in the current note after running it, but filename doesn't change. No error or diag message either.

**Expected behavior**
Filename should change following the modified note title.

**Screenshots**

**Additional context**
The same code snippet works fine when creating new note.

**Comment by AB1908** [comment]
`tp.file.title` === filename. You're probably looking for the plugin that syncs the header and file name.

**Comment by inyeollee** [comment]
Got it. Thanks.
