### ISSUE TITLE
Templater on iPad doesn't convert script to date

### ISSUE THREAD

**Issue by dtrommel** [SilentVoid13/Templater#687]
**Plugin information:**

-   OS: iPadOs 14.6
-   Templater version: 1.12.0
-   Obsidian version: 1.2.3(57)
-   Templater settings: [e.g. Template folder location: "Templates/", Timeout: "5" (add the templates not working with their associated command)]

**Describe the bug**
On my Mac I created a template for my daily notes. In the Daily Notes plugin I set the template file location to this template. This works perfectly fine on my mac, on my Ipad however the scripts are not parsed.

**Expected behavior**
<% tp.file.creation_date() %> in the template should parse to the creation date in the new note instead of displaying the script.

**Comment by dtrommel** [comment]
I have used moment() as well, unfortunately I get the same behavior

![0AA9E78C-8972-4C0E-AB8D-8835BCB86F3A](https://user-images.githubusercontent.com/80407337/178485634-496d921a-e533-403b-82c7-35f21f2c2814.jpeg)

**Comment by dtrommel** [comment]
![Uploading B1EC322A-D86E-43CB-AB13-DE9E70F6F9A7.jpeg…]()

**Comment by dtrommel** [comment]
Manually resolving the template does nothing for me…

**Comment by AB1908** [comment]
Sorry, I haven't been able to test this and won't be able to test it anytime soon. Were you able to work around the issue?

**Comment by shabegom** [comment]
can't reproduce this on iPad. Assuming it is an error in implementation and not a bug in the code.
