### ISSUE TITLE
CSSClasses on demand

### ISSUE THREAD

**Issue by ScottKillen** [SilentVoid13/Templater#699]
Specifically, I would like an included template to be able to add classes to cssClasses frontmatter data.

I would like a template to be able to specify required cssClasses so that when a file includes a template (via `tp.file.include`) required classes are added to the frontmatter.

I use helper classes that control the rendering of the file. I also include small self-contained section templates in larger complete file templates. It would be a nice feature if the small templates had a way of signaling the larger file to include certain cssClasses for proper rendering.

**Comment by AB1908** [comment]
Broadly speaking, this sounds doable with a bit of scripting. Modifying CSS classes for an existing file can get hairy though. See MetaEdit and its API for updating frontmatter/metadata.

**Comment by ScottKillen** [comment]
@AB1908 Thanks for the tip!

I think using the MetaEdit API makes a lot more sense than my request.
