### ISSUE TITLE
{{date}} and {{time}} is not working.

### ISSUE THREAD

**Issue by vincehor** [SilentVoid13/Templater#703]
My Obsidian has 2 vaults and the setup for both are the same (plugins and settings). Vault A has no issue with Templater but Vault B is unable to display date and time. It just shows {{date}} and {{time}} exactly like that (still with the curly brackets).

**Plugin information (please complete the following information):**

-   OS: [e.g. Windows 10]
-   Templater version: [e.g. 0.3.4]
-   Obsidian version: [e.g. 0.9.11]
-   Templater settings: [e.g. Template folder location: "Templates/", Timeout: "5" (add the templates not working with their associated command)]

Windows 11.
Templater 1.12.0
Obsidian v0.15.8 (installer version v0.14.15)

**Describe the bug**

I setup my templates with core plugin before adding Templater. After installing Templater, {{date}} and {{time}} for all templates do not work. The templates {{date}} and {{time}} works again after I uninstall Templater. This only happens in my Vault B.

**Expected behavior**

I expect to have the {{date}} and {{time}} to self populate when I create a new note.

**Screenshots**

The same note side by side. One in edit mode and the other in read mode.
![after templater](https://user-images.githubusercontent.com/109892410/180636184-5a5c42be-d0d8-4da1-97ab-225dbe8a7abc.jpg)

**Additional context**

**Comment by AB1908** [comment]
Hey there! This isn't a templater issue as `{{}}` is syntax for the core template plugin. Kindly read through the docs for templater.

**Comment by welpdx** [comment]
In templater, you can use something like this `<% tp.date.now() %>`

From [documentation](https://silentvoid13.github.io/Templater/internal-functions/internal-modules/date-module.html)

**Comment by vincehor** [comment]
Thank you so much. It works well now.
