### ISSUE TITLE
Templater stopped rendering output from syntax.

### ISSUE THREAD

**Issue by Miusaky** [SilentVoid13/Templater#704]
**Plugin information (please complete the following information):**

-   OS: Void Linux
-   Templater version: 1.12.0
-   Obsidian version: 0.15.8
-   Templater settings: Folder = ```TEMPLATES/```. Everything else is default.
 
**Describe the bug**
Templater has stopped converting syntax to data. Below examples do not work and instead render as is - despite having worked on previous occasions. I don't believe I have altered it at all since the last time it was working. 

```
<< [[<% tp.date.now("YYYY-MM-DD", -1) %>]] | [[<% tp.date.now("YYYY-MM-DD", 1) %>]] >>

<% tp.file.title %>
<% tp.web.daily_quote() %>
```

**Expected behavior**
Above syntax rendering dates, title and daily quote.

**Comment by AB1908** [comment]
Does the replace template command help? Can you give us steps to reproduce the error?

**Comment by Miusaky** [comment]
> Does the replace template command help? Can you give us steps to reproduce the error?

Running replace template seems to have solved it. Thanks!

**Comment by AB1908** [comment]
Do double check if the `Trigger on new file creation` setting is enabled.

**Comment by Miusaky** [comment]
> Do double check if the `Trigger on new file creation` setting is enabled.

It was enabled.
