### ISSUE TITLE
Inserting template in separate window insert it at top of the file instead cursor position

### ISSUE THREAD

**Issue by Pomroka** [SilentVoid13/Templater#715]
**Plugin information (please complete the following information):**

-   OS: [e.g. Windows 10] Windows 10
-   Templater version: [e.g. 0.3.4] 1.12.0
-   Obsidian version: [e.g. 0.9.11] 0.15.9
-   Templater settings: [e.g. Template folder location: "Templates/", Timeout: "5" (add the templates not working with their associated command)]

**Describe the bug**
Inserting template from command pallet if note is opened in separate window insert it at the beginning of the file not at the cursor position. Inserting using keyboard shortcut insert correctly at cursor position.

**Comment by AB1908** [comment]
Can you add the template and also perhaps share steps to reproduce this problem?

**Comment by Pomroka** [comment]
Any template even such simple as this table
```md
| Previous |  Up  |  Next |
| :------- | :---: | ----: |
| [[]] | [[]] | [[]] |
```
Steps:
Right click in File Explorer on note and choose `Open in new window`
Put cursor in place where you want insert template
Open `Command palette` choose `Templater: Open Insert Template modal` and choose template to insert. 
Template that i have keyboard shortcut created is inserted at cursor position

**Comment by shabegom** [comment]
Can't recreate - closing
