### ISSUE TITLE
codepage issue when accessing the clipboard

### ISSUE THREAD

**Issue by zsviczian** [SilentVoid13/Templater#72]
**Plugin informations (please complete the following information):**
 - OS: Windows 10
 - Templater version: 0.5.7
 - Obsidian version: 0.11.12
 - Templater settings: defaults: Template folder location: "Templates/", Timeout: "5" 

**Describe the bug**
I place Hungarian text containing "special" characters on the clipboard such as áéíöőüűú. I run a shell script to read the clipboard and insert it into my template but I get � in place of each character from the ASCII extended characters.
When I run the shell script directly from the command prompt, I get the correct results.

I've tried two ways to read the clipboard:
`powershell (get-clipboard -raw)`
and 
`python .scripts/get_clipboard.py`

where get_clipboard.py contains
```
from tkinter import Tk 
print(Tk().clipboard_get())
```

But it makes no difference. Seems as if when templater reads the shell results it only accepts ASCII printable characters, and ignore the ASCII Extended block.

**Expected behavior**
I expect the characters with the right codepage returned

**Comment by SilentVoid13** [comment]
Hey @zsviczian, you can now use the new internal function `tp.file.clipboard` as of Templater 1.2.0.

This should work well with special characters. Could you update Templater and tell me if this works fine ?

**Comment by SilentVoid13** [comment]
Alright, glad it's working!

Closing this.
