### ISSUE TITLE
[BUG] Quote API enbpoint is not working again

### ISSUE THREAD

**Issue by rapatel0** [SilentVoid13/Templater#739]
**Plugin information (please complete the following information):**

-   OS: macos
-   Templater version: 1.12
-   Obsidian version: 0.16

**Describe the bug**
The quote api is getting an HTTP error and breaking the template. (commenting out tp.web.quote() fixes things)

**Additional context**
I suggest that we the `tp.web....` optionally captures the exception and returns the error code as the function return value. That would ensure it doesnt break downstream processing of the template.

**Comment by shabegom** [comment]
Added logic to handle if the api is down.
