### ISSUE TITLE
Specify insertion point with internal templates

### ISSUE THREAD

**Issue by Ampa** [SilentVoid13/Templater#74]
Would it be worth adding internal templates to specify where a template should be inserted?

The two example I can think of would be...

{{tp_top}} and {{tp_bottom}}

These would be useful for inserting YAML or other header information, and footers.

I submitted another FR for create new from template... perhaps this could also be an internal template {{tp_new}}?

Thanks for the great plugin!

**Comment by SilentVoid13** [comment]
Hey @Ampa, sorry for the late response. Not sure if I understand this request correctly, is it still relevant with the new Templater update ?

**Comment by Ampa** [comment]
Hi @SilentVoid13,
I am not sure if the newer versions can manage what I asked or not. I think the answer is 'sort of'!

I have 2 templates: one is a YAML header, and the other a log of PlayTesting Data.

The YAML header is added to files that were not originally created with YAML. I am often in the middle of the note, when I realise that adding some YAML would be helpful. But I must move the insertion point to the top, before inserting the template, or I get YAML in the middle of the file.

My hope was that the template itself could specify "insert me at the top".

Similarly, my PlayTest Data should always be added to the bottom of the note, so that notes are always chronological. At present I scroll to the bottom and then insert, but I'd prefer if the template itself said "append me to the end of the note".

This may now be possible with tp.config.run_mode?

But this requires me (the user) to insert the template in a different way, rather than the logic being in the template itself.

Hope that is a little clearer?

**Comment by shabegom** [comment]
This could be done with `tp.file.include()` at the location you want the template, otherwise insert template inserts at cursor location.
