### ISSUE TITLE
Unable to call internal template in user template

### ISSUE THREAD

**Issue by wangxu94** [SilentVoid13/Templater#76]
**Plugin informations (please complete the following information):**
 - OS: Windows 10
 - Templater version: 1.0.0
 - Obsidian version: 0.11.9
 - Templater settings: Template folder location: "templates", Timeout: "10", tp.user

**Describe the bug**
I name my files according to the zettelkasten convention — e.g. 202104061325_Title. I want to create a user template to strip the zettel ID from the file name and insert the title into my note.

My user template is as follows: 
**Template name:** title
**Command:** `echo tp.file.title | wsl.exe cut -d "_" -f2`

I call this user template in a template file with the following line: `<% tp.user.title() %>`

The `echo tp.file.title` is not replaced with the file title. Instead the template echoes the "tp.file.title" literally.

**Expected behavior**
`tp.file.title` (and other internal templates) are replaced before running the user template.

**Screenshots**
User template:
![image](https://user-images.githubusercontent.com/15028233/113650177-e5ad1400-96e3-11eb-9e83-7c69bdc9b4fa.png)

Template note:
![image](https://user-images.githubusercontent.com/15028233/113650222-f493c680-96e3-11eb-9320-0d24884a8d6d.png)

Output:
![image](https://user-images.githubusercontent.com/15028233/113650261-06756980-96e4-11eb-8dfa-edc8325f6aa9.png)

This also occurs if I use `tp.file.path` instead of `tp.file.title`

Any assistance would be much appreciated. Thank you.

**Comment by SilentVoid13** [comment]
Hey @wangxu94, you are correct, the documentation in the README was not good. Thanks for the feedback.
You still need to use opening and closing tags inside the system command. Fixed it in the README.
In your case, this gives `echo <% tp.file.title %> | wsl.exe cut -d "_" -f2`
Tell me if this works now.

**Comment by wangxu94** [comment]
Yes that works now. Thanks for your help, and for building this plugin! :)
