### ISSUE TITLE
How to reference env vars or args inside Eta

### ISSUE THREAD

**Issue by luckman212** [SilentVoid13/Templater#78]
_ref: https://discord.com/channels/686053708261228577/707816848615407697/829041685752709170_

I'm struggling to wrap my head around the power of the new Templater. 🤯

Can we pass args to the Eta JS interpreter? e.g.  a template like

```
<% tp.user.google_search_js({qry: tp.file.selection()}) %>
```

and then in the plugin settings define the script as 
```
<%*
console.log('qry=' + process.env.qry);
%>
```
For me this doesn't work-- not sure how to reference args in JS.

I work around this by not using the arg but instead just placing `tp.file.selection()` directly in the template script like this:
```
<%*
let s = tp.file.selection();
var md = "[" + s + "](https://google.com/search?q=" + encodeURIComponent(s) + ")";
console.log("output: " + md);
%>
```
But, I can't figure out how to pass the contents of `md` back to Obsidian after processing it in JS (URLencoding the query in this case). I tried `echo "<%* console.log(md); %>"` but that just prints to the console, doesn't get returned back to the active note... ?

**Comment by SilentVoid13** [comment]
Hey @luckman212, you can access user templates arguments in the form of environment variables.

If I understand what you want to do correctly there are 2 ways you can do this:

1. Using string formatting (not the most elegant solution):

```
<% `[${tp.file.selection()}](https://google.com/search?q=${encodeURIComponent(tp.file.selection())})` %>
```

2. Using user templates arguments (easier to understand):

First, define a user template named `test` for example, and associate it with the following system command: 

For Linux / Mac: `echo "[$qry](https://google.com/search?q=$qry2)"`
For Windows: `powershell -command Write-Output "[$Env:qry](https://google.com/search?q=$Env:qry2)"`

Notice the 2 environment variables `qry` and `qry2`.

Then, call your newly created user template like so:
```
<% tp.user.testy({qry: tp.file.selection(), qry2: encodeURIComponent(tp.file.selection())}) %>
```

Tell me if this works for you.

**Comment by luckman212** [comment]
Hi @SilentVoid13 thank you for this help and this additional example.

So I found that running everything using the JavaScript/Eta engine is 1000% faster (instant response time) vs. around ~2s lag when using the `sh`(shell) based _**Template n°N**_ in the settings area. I guess there is a big cost to spinning up and tearing down this shell process. So I try to avoid it!

#### After a **lot** of trial and error, probably mostly due to my ignorance, I found the magic code that works.

All I need is this code in a file in my templates folder:
```
<%*
  if (tp.file.selection() === "" ) {
    console.log('nothing selected');
  } else {
    %>[<% tp.file.selection() %>](https://google.com/search?q=<% encodeURIComponent(tp.file.selection()) %>)<%*
  }
%>
```
With that, I can select some text, invoke Templater, and get an instant Markdown link with a URL-encoded Google search. This was my original goal.

#### This _also_ works, but is a lot slower:

Put this code in a file in your templates ƒ:
```
<% tp.user.google_search_sh({q_name: tp.file.selection(), q_uri: encodeURIComponent(tp.file.selection())}) %>
```
Add an internal Template in your settings, named `google_search_sh` and with this code:
```
printf '%s' "[$q_name](https://google.com/search?q=$q_uri)"
```

I would like to ask you if I may - is there any drawback to using the first (faster) method vs. the shell-based one? In general is it always better to try to find a JS-based solution for using Templates? Some more examples in the README would really be wonderful to see.

**Comment by SilentVoid13** [comment]
Glad to hear it's working.

To answer your question there are no drawbacks using the first method, because as you said it's usually much faster since it doesn't have to spawn a shell to be executed.
I'll try to make a better documentation!

Closing this.
