### ISSUE TITLE
Can we access moment() from within a template?

### ISSUE THREAD

**Issue by davecan** [SilentVoid13/Templater#79]
Is it possible to access momentjs directly from within a `<%* ... %>` block?

My daily notes are formatted like `21.04.08.Tue` and I can use Templater to generate the previous and next day links just fine. But if I click on a day (in the calendar plugin) other than today it creates the new note and runs Templater as expected. However, since my template has `# <% tp.date.now("D MMM YY") %>` in it then the current date is always added at the top of the note regardless of which day's note I create.

Is it possible to do something like this:

```
<%* var theDate = moment() %>

# <% theDate %>
```

I'm looking to capture the file name from `tp.file.title` and parse it as a date then make that available as a variable for rendering. That way the correct date will be displayed at the top of the note regardless of what day I click on.

BTW thanks for the incredible plugin, it's come a very long way since I last looked at it! 👍

**Comment by SilentVoid13** [comment]
Hey @davecan what you're describing is already possible using the `tp.date.now` internal template.
If you take a look at the examples in the README: https://github.com/SilentVoid13/Templater#examples, you can find the following snippet:

```ts
<% tp.date.now("YYYY-MM-DD", 0, tp.file.title, "YYYY-MM-DD") %>
```

This retrieves the file's title date in the format `"YYYY-MM-DD"`, adds a `0` days offset and outputs it in the `"YYYY-MM-DD"` format.

Tell me if this works for you.

**Comment by davecan** [comment]
That did it! Thanks!

For anyone else coming later, the first format param is the desired output format and the second is the format to look for in the title.

For example, to translate file title format `21.04.06.Tue` into `6 Apr 21`: 

```
<% tp.date.now("D MMM YY", 0, tp.file.title, "YY.MM.DD.ddd") %>
```

**Comment by SilentVoid13** [comment]
Awesome, closing this.
