### ISSUE TITLE
Breaking Change: Random Picture Size

### ISSUE THREAD

**Issue by ManadayM** [SilentVoid13/Templater#792]
**Plugin information (please complete the following information):**

-   OS: Mac OS 10.15.7
-   Templater version: 1.13.0
-   Obsidian version: 0.15.9
-   Templater settings: 

**Describe the bug**
The latest Templater release breaks the ideal behavior of the max image width when a user has enabled the "Readable line length" Obsidian setting (Obsidian Settings > Editor > Display > Readable line length). The generated random image now occupies the actual width which has been set in the `random_picture(900x300)` function. 

I downgraded the plugin with 1.12.0 by manually downloading the assets and it restored the expected behavior.

**Expected behavior**
The function should respect the readable line length setting i.e. max container width set by the Obsidian.

**Screenshots**
My default note template contains `<% tp.web.random_picture("900x300", "tree,landscape,water,mountain") %>` on top.

In release 1.12.0 - Respects the Obsidian setting
![Screenshot 2022-09-03 at 17 45 41](https://user-images.githubusercontent.com/521134/188270007-5d6b9df5-3b3d-48e0-a4e7-0b5e483081b3.png)

In release 1.13.0 - Ignores the Obsidian setting
![Screenshot 2022-09-03 at 17 48 48](https://user-images.githubusercontent.com/521134/188270147-1f47f073-54b4-4561-982b-47545a70bc17.png)

**Additional context**
The following code change in the latest release is breaking this behavior.

https://github.com/SilentVoid13/Templater/pull/678/files#diff-74b11ab27692d63b0d5b5bffffb9ad72bcd6a5a5c8b6ea21dbca9fa61aad9495L52

Hope it helps. Happy to help.

Thanks,
Manaday

**Comment by shabegom** [comment]
Great report. Will look into it

**Comment by shabegom** [comment]
@wernersa any thoughts here? My first instinct is to revert back to the previous way as it didn't seem to impact image display.

**Comment by welpdx** [comment]
Can't replicate with:
Windows OS
Obsidian Version: 0.16.1
Templater Version: 1.12.0

**Comment by wernersa** [comment]
Problem goes both ways here as not having the option for manually setting the display values of images can interfere with several plugins and themes that modify image display; specifically the most used theme "Minimal". This is why I suggested the initial change. See the following sandbox where I set theme to Minimal:

![Obsidian_hjoCEgbuWa](https://user-images.githubusercontent.com/13331356/188292950-37a7d452-fe19-4c79-b630-d4009561fe4a.gif)
```
SYSTEM INFO:
	Obsidian version: v0.15.9
	Installer version: v0.14.6
	Operating system: Windows 10 Home 10.0.22000
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 1
	Plugins enabled: 1
		1: Templater v1.13.0
```

The current setup will not be a breaking change for all previously formatted templates, but for templates rendered after the update.

**Comment by ManadayM** [comment]
> The current setup will not be a breaking change for all previously formatted templates, but for templates rendered after the update.
That's right. I missed mentioning that.

**Comment by wernersa** [comment]
I tested the previous way with several other themes. It seems like the most popular one, Minimal, is the only one that changes sizes of images smaller than the max container width. Adding screenshot of the themes tested; none other than Minimal affected the sizing of small images:
![image](https://user-images.githubusercontent.com/13331356/188297009-5021800c-6b37-4871-94dc-0b7870e09d09.png)

See also earlier Minimal theme issue where this has been mentioned before: https://github.com/kepano/obsidian-minimal/issues/17

I suggest reverting the change as it is easiest (and my coding skills are limited) 🙌

**Comment by welpdx** [comment]
Ok I tried again on an new vault and I was able to reproduce the error. It seems like the alt text to resize the text forces the html to force the size of the img tag and ignored the "markdown-preview-sizer" (for the preview) or the "cm-sizer" class (for the editor). 

If we can change the html tag from `width="900"` to `width="100%"` the issue would be solved.
Or change it add [overflow:hidden](https://stackoverflow.com/a/5698154/14451841) in the div the img was in, then the issue would be solved.

This looks to be an obsidian issue (of not forcing px or adding alt text for % img resizing). But a workaround for us is to use html tags instead of markdown, e.g.:
```js
<img src="${url}" width="100%" height="100%" alt="tp.web.random_picture" contenteditable="false">
```

Created a pr for this. #794

**Comment by shabegom** [comment]
It would be nice if there was a fix for this upstream of the plugin...

**Comment by welpdx** [comment]
Agreed. How should we provide this feedback to obsidian?

**Comment by liamcain** [comment]
It renders properly if Templater doesn't add the sizing data at the end of the embed (`|900x300` in this case). Is that an option?

**Comment by shabegom** [comment]
> It renders properly if Templater doesn't add the sizing data at the end of the embed (`|900x300` in this case). Is that an option?

That would be a revert to the previous behaviour. Earlier in the thread it was pointed out that this impacts image rendering in the minimal theme.

If a revert is best option then we can do that short term, but it would be great if long-term there was a way that the sizing respected readable line lengths.

**Comment by shabegom** [comment]
Ok folks. I've merged a fix that hopefully makes everyone happy.

@ManadayM the default behaviour is back to pre-0.13.0 and image sizes won't be included in the markdown output

@wernersa if you want the sizes to be included there is now an optional argument in the function:

`tp.web.random_picture(size, query, include_size)`

it defaults to false, but when marked true it will include the size specified in the markdown output. If you don't want to provide a query, you can use an empty string. example: `tp.web.random_picture("900x300", "", true)`

I hope this resolves the problem for both of y'all. I'll keep an eye out if obsidian starts handling images with relative attributes.

**Comment by welpdx** [comment]
Noice

**Comment by ManadayM** [comment]
That's great @shabegom! Thank you for your efforts and updates. I will check it today.
