### ISSUE TITLE
Get parent note title for backlink on new file creation from empty link

### ISSUE THREAD

**Issue by cedardocster** [SilentVoid13/Templater#797]
# How to get parent note title for backlink on new file creation from empty link

I know how to add the *current* note title (i.e. the newly formed note) by using this in the template:

'# <% tp.file.title%>

but how do I get the title of the note I linked *from*?  I.e. the parent note title in order to create a hard back link?

E.g. "Note A":
Hi there. Here's a [[new file]]

"new file":
Back link: [[Note A]]
'# new file

I'm (relatively)  new to Obsidian, and I imagine I may have to do some sort of JavaScript in my new file template to get the name of the most recently modified file (which I think would be the parent file), but is there an easier built-in way to get the parent note name for when you click or tap on a link to a file that doesn't exist yet?

**Comment by shabegom** [comment]
Please open this as a Discussion thread
