### ISSUE TITLE
Set folder for note created from a specific template

### ISSUE THREAD

**Issue by aviskase** [SilentVoid13/Templater#80]
I might be missing something obvious, but is there a way to set a folder path for a note created from a specific template? For example, [avirut/obsidian-metatemplates](https://github.com/avirut/obsidian-metatemplates) uses frontmatter for that.

**Comment by SilentVoid13** [comment]
Hey @aviskase, are you talking about the new feature adding a command to "create new note from template" ?

If that's the case, there are currently no ways to specify a folder path for newly created notes. 
They are created in the vault's root by default.

I'm curious though, would you prefer to:
- Be able to specify the folder path in Templater's settings
- Use the folder path defined in obsidian settings (in Settings > File & Links)

**Comment by ebullient** [comment]
You have two issues referencing metatemplates, which creates the new note based on information in the metadata of the template.

**Comment by aviskase** [comment]
Hi, sorry for late reply.

> Hey @aviskase, are you talking about the new feature adding a command to "create new note from template" ?

Yup. And to be able to set different folder path for different templates. 
I love templating features of Templater, but missing "orchestration" of metatemplates.

**Comment by Moonbase59** [comment]
Does it have to be "Folder from Template" or could live—for the time being—with "Template from Folder"?

I had a similar use case and the author of the [Hotkeys for Templates Plugin](https://github.com/Vinzent03/obsidian-hotkeys-for-templates) kindly implemented the [function to specify a Template that gets applied if a new note is created within a specified folder](https://github.com/Vinzent03/obsidian-hotkeys-for-templates/issues/7).

So if I’m in "People" and create a new note it could apply a "People Template", and in folder "Locations of Interest" it could apply a "Location Template".

**Comment by aviskase** [comment]
Hi, with the plugin https://github.com/chhoumann/quickadd I no longer need this functionality from Templater itself. 
The issue can be closed, if no one else is interested in it.

**Comment by SilentVoid13** [comment]
Hey @aviskase, thanks for the bump, you're right, I'm closing this. Templater now has the function `tp.file.move` that could also work in that specific use case.
