### ISSUE TITLE
default_value doesn't set value in `tp.system.prompt` after update

### ISSUE THREAD

**Issue by RyanQuey** [SilentVoid13/Templater#801]
**Plugin information (please complete the following information):**

-   OS: [e.g. Windows 10]
-   Templater version: 1.13.0
-   Obsidian version: 0.15.9

**Describe the bug**
After recent update (I'm not sure if it's Obsidian update or plugin update), the `tp.system.prompt` no longer has correct behavior for `default_value`. `default_value` correctly shows in the input prompt, but does not get set to the variable unless user makes some change to the value in the input field. Particularly, when `default_value` is unchanged and user simply clicks "submit" button, the value is left blank, rather than being the value originally set in `default_value`. In other words, it is almost as if it is a placeholder rather than a default value. 

**Expected behavior**
`default_value`, when unchanged, should be correctly returned from the function. 

Thanks so much, great plugin!

**Comment by shabegom** [comment]
@AB1908 could you take a look if your multi line prompt borked the default value arg?

**Comment by AB1908** [comment]
I tried my best not to haha. I'll check this soon.

**Comment by shabegom** [comment]
overloading is the right approach and I'm not sure how this would impact `default_value` since you added it as the last optional param..

**Comment by shabegom** [comment]
Figured it out. Will be fixed in next release.

**Comment by RyanQuey** [comment]
Confirmed that it now works on update, thanks!
