### ISSUE TITLE
Latest version of Templater not working on iOS

### ISSUE THREAD

**Issue by melbv** [SilentVoid13/Templater#809]
**Plugin information (please complete the following information):**

-   OS: iOS 15.6
-   Templater version: 1.13.0
-   Obsidian version: 1.3.1 (67)
-   Templater settings:
  - Template folder location: "00.01 Admin/Templates/"
  - Trigger Templater on new file creation: yes
  - Show icon in sidebar: yes
  - Timeout: "5"

**Describe the bug**
Templater does not trigger anymore any other way than through the command palette command 'Templater: insert template'. All other Templater commands do not work. In addition, no Templater variable gets substituted by their value upon triggering templates.
I pair Templater templates with the core 'Daily Note' plugin which does not trigger the substitution of the Templater variables either.
Could you guide me through how to setup Templater to get the normal behaviour back?

**Expected behavior**
Templates are called appropriately and all Templater variables get substituted with their actual value

**Comment by shabegom** [comment]
Latest version was tested on iOS prior to release. 

Just tested again and is working as expected.

Do you have any user functions?

**Comment by melbv** [comment]
Yes - i have one!
6 Sep 2022, 23:28 by ***@***.***:

**Comment by shabegom** [comment]
Try removing that and see if it fixes the issue. If there is an issue in a user plugin, templater kind of shits the bed. 

If that fixes it, post the user plugin so I can troubleshoot why it's breaking the plugin.

**Comment by melbv** [comment]
The plugin works after removal of the user function. Good news...
As for the function itself, see below:

```
class templaterFunc {
createNewFile(tp, templatelist) {
const fileName = await tp.system.prompt("File name");
const templateName = await tp.system.suggester(templatelist, templatelist);
return tp.file.create_new(tp.file.find_tfile("Template " + templateName), fileName, tp.file.folder())
}
}
```

7 Sep 2022, 03:43 by ***@***.***:

**Comment by shabegom** [comment]
I've not seen `class` be used in a user script. Normally it is a function...

**Comment by melbv** [comment]
Fair point - i am actually not using this particular script as i am now appending a template executing a templater script similar to this one to generate new notes.
I think the class declaration comes from the customjs plugin that requires to code functions within a class... I have written all my search blocks for notes with customjs...
Not a big issue if i cannot use that particular script.


7 Sep 2022, 15:52 by ***@***.***:
