### ISSUE TITLE
How to reference/retrieve frontmatter property name with a space

### ISSUE THREAD

**Issue by GitMurf** [SilentVoid13/Templater#81]
If I have a frontmatter property like "job title" how do I reference that in templater since there is a space in the property name?

![image](https://user-images.githubusercontent.com/64155612/113796324-ddfd6780-9703-11eb-9b3e-4ded7b3eb5f1.png)

**Comment by bensleveritt** [comment]
You can use `<% tp.frontmatter['job title'] %>` as Templater uses a JavaScript templating system.

**Comment by SilentVoid13** [comment]
@bensleveritt Thanks for the reply, did not even thought about the possibility of having spaces in fields lol.

As @bensleveritt said, you can specify the fields name using brackets and quotes when it contains special characters.

Tell me if this works for you.

I'll update the frontmatter section in the README to mention this.

**Comment by GitMurf** [comment]
Sorry I never saw the responses here! Thanks a lot. It is exactly what I needed.
