### ISSUE TITLE
PR #444 changed behavior of file.move

### ISSUE THREAD

**Issue by ebullient** [SilentVoid13/Templater#812]
1) Mobile no longer works due to reliance on app vault (it worked fine on mobile before this change): 
```
// TODO: Add mobile support
if (Platform.isMobileApp) {
    return UNSUPPORTED_MOBILE_TEMPLATE;
}
if (!(this.app.vault.adapter instanceof FileSystemAdapter)) {
    throw new TemplaterError(
        "app.vault is not a FileSystemAdapter instance"
    );
}
```

2) The mkdir capability is not correctly handling nested directories. Given path A/B/C/filename, I am seeing a phantom directory C created at the root level due to this change:

```
this.app.vault.adapter.mkdir(dirname(new_path).split(sep).pop());
```

**Comment by shabegom** [comment]
Maybe because of the `path` import... can we use `path` on mobile?

**Comment by shabegom** [comment]
@alchemistake, feel like taking a look at this?
