### ISSUE TITLE
tp.file.exists function appears not to work

### ISSUE THREAD

**Issue by Smitty010** [SilentVoid13/Templater#817]
**Plugin information (please complete the following information):**
-   OS:Windows 11
-   Templater version: 1.14.1 (I believe this is the latest)
-   Obsidian version: 0.16.2 (I believe this is the latest insider build)
-   Templater settings: 
  - Template folder location: Obsidian/Templates
  - Syntax Highling is on
  - Automatic jump cursor is off
  - Trigger templater on new file creation is on
  - Show icon in sidebar is on
  - No Template hotkeys
  - Enable folder templates is on
  - There is an entry in the folder templates that has "Obsidian/Journal/daily" as the directory and "Obsidian/Templates/2.Daily Note Templates.md" as the template

**Describe the bug**
Here is a snippet from the template
```
console.log(`tp.file.folder(true) = ${tp.file.folder(true)}`)
console.log(`yearLink = ${yearLink}`)
const dir = tp.file.folder(true) + "/" + yearLink;
console.log(`dir = ${dir}`)
console.log(`tp.file.exists(dir) = ${tp.file.exists(dir)}`)
console.log(`tp.file.exists(dir + "/") = ${tp.file.exists(dir + "/")}`)
console.log(`tp.file.exists(yearlink) = ${tp.file.exists(yearLink)}`)
console.log(`tp.file.exists(yearlink + '/') = ${tp.file.exists(yearLink + '/')}`)

if (!tp.file.exists(yearLink)) {
	await app.vault.createFolder(dir)
}
```

The log output is:
VM233:34 tp.file.folder(true) = Obsidian/Journal/daily
VM233:35 yearLink = 2022
VM233:37 dir = Obsidian/Journal/daily/2022
VM233:38 tp.file.exists(dir) = false
VM233:39 tp.file.exists(dir + "/") = false
VM233:40 tp.file.exists(yearlink) = false
VM233:41 tp.file.exists(yearlink + '/') = false
plugin:templater-obsidian:82 Templater Error: Template parsing error, aborting. 
 **Folder already exists.**

**Expected behavior**
The directory "Obsidian/Journal/daily/2022/" does exist.  I would have expected one of the tp.file.exists show above to confirm that.  Just to be clear, there is a directory called "Obsidian" at the same level as the 'obsidian' directory inside the vault.

What happens instead is that the the file "2022-09-14" (which is date I'm trying to create a daily note for) gets created in "Obsidian/Journal/daily" and then templater throws the error above when it tries to create the already existing directory.

I thought maybe an "await" on the tp.file.exists would help, but it doesn't make a difference.

It would have been great if app.vault.createFolder simply nooped if the directory already exists.  I'm assuming that function is not part of templater.

If there's a more reliable way to do this, I'd be happy to hear about it.  I just want to create the year folder if it doesn't exist.  The above solution is one I found in the forum.

**Screenshots**
![image](https://user-images.githubusercontent.com/3760075/189515073-ac25e755-2e88-458e-b415-03ad8ef4a126.png)

I'm not aware of any other issues in this vault.

**Comment by shabegom** [comment]
`tp.file.exists` currently only works on files and doesn't confirm the existence of directories. I've submitted a PR to update the function so it works with directories. While waiting for it to merge, you can run the internal `exists` method directly:

basic example:
```
const exists = app.fileSystemAdapter.exists("folderName")
if (!exists) {
app.vault.createFolder(folderName)
}
```

**Comment by Smitty010** [comment]
Thanks.  I'll try that.

**Comment by Smitty010** [comment]
I guess I closed this too quickly (before trying the code).  Here's the error message:

plugin:templater-obsidian:82 Templater Error: Template parsing error, aborting. 
 Cannot read properties of undefined (reading 'exists')

**Comment by Smitty010** [comment]
There must be something else going on.  I noticed that the template (as originally written) seems to work in one vault, but not the other (I have 3 vaults).  I'm beginning to wonder if one of the vaults is corrupted somehow.

**Comment by shabegom** [comment]
If you need help with your script unrelated to a bug in the code you could either:

1. Open a Discussion topic
2. Ask in the templater thread in OMG discord 

I'm trying to limit issues to bugs and feature requests.

**Comment by Smitty010** [comment]
I thought it was a bug.  Now I'm not so sure.  I'll post something new if I convince myself it's a bug.  Otherwise, I'll either get help on discord or the forum.
