### ISSUE TITLE
Formatting: Is this correct formatting?

### ISSUE THREAD

**Issue by pauljacobson** [SilentVoid13/Templater#82]
Hi there

I've tried to modify my Templater fields for the new formats, and I'm not sure if I have this right. I've added this to my Daily Notes template:

```
Today's weather in <% tp.weather %>

<% tp.date.yesterday(format: string = "YYYY-MM-DD") %> 👈  👉 <% tp.date.tomorrow(format: string = "YYYY-MM-DD") %>
```

I don't have a custom template for `yesterday` and `tomorrow`, although my `weather` Internal template looks like this:

<img width="1059" alt="Screen Shot 2021-04-07 at 11 00 31" src="https://user-images.githubusercontent.com/2912202/113831655-822cf000-9790-11eb-9416-947b592621e8.png">

I'm using the following versions:

Obsidian v0.11.13
Templater v1.1.0

**Comment by I-Pch** [comment]
I'm absolutely no expert 😅 , but following [the documentation](https://github.com/SilentVoid13/Templater#calling-user-templates) I think you should use `<% tp.user.weather() %>` instead of `<% tp.weather %>` to call the weather template 😊 .

**Comment by SilentVoid13** [comment]
Hey @pauljacobson, as @I-Pch said (thanks for the reply) a user template is a function, so you must call it like a function. That means you need to append opening and closing parenthesis at the end.

About the other templates you're using, the names and types are only for documentation purposes in the README.
You can have a lookat the examples at the bottom of the module documentation: https://github.com/SilentVoid13/Templater#examples

For you, that would give the following template:

```
Today's weather in <% tp.user.weather() %>

<% tp.date.yesterday("YYYY-MM-DD") %> 👈  👉 <% tp.date.tomorrow("YYYY-MM-DD") %>
```

Tell me if this works for you.

**Comment by pauljacobson** [comment]
> I'm absolutely no expert 😅 , but following [the documentation](https://github.com/SilentVoid13/Templater#calling-user-templates) and a very quick test, I think you should use `<% tp.user.weather() %>` instead of `<% tp.weather %>` to call the weather template 😊 .

@I-Pch  and @SilentVoid13 Ah, right. I actually did read that! Sorry! 

For the second line, how should I define the templates for "yesterday" and "tomorrow"? I'm not clear on whether I should add a template for each to the Templater options in addition to adding the strings to the template?

**Comment by SilentVoid13** [comment]
@pauljacobson I'm not sure I understand your question, I just gave you a snippet specifying how you should be using them. 
Internal templates are bundled in the plugin, you don't need to declare them anywhere you can just use them.

**Comment by pauljacobson** [comment]
Apologies @SilentVoid13 I was trying to multi-task there, and didn't read your reply correctly. Thank you again.
