### ISSUE TITLE
tp.web.random_picture doesnt work

### ISSUE THREAD

**Issue by greywall43** [SilentVoid13/Templater#823]
**Plugin information (please complete the following information):**

-   OS: Windows 10
-   Templater version: 1.14.1
-   Obsidian version: 0.15.9
-   Templater settings: default

**Describe the bug**

New daily template with the following:  

```md
<% tp.web.random_picture("400x400") %>
```
Doesn't yield an image... just get this as output in the markdown: 
```md
![tp.web.random_picture](https://images.unsplash.com/source-404?fit=crop&fm=jpg&h=800&q=60&w=1200)
```
**Expected behavior**
I use the random picture function for my daily log so it's been working fine for a few months now so it's odd all of a sudden it stopped working.

**Additional context**

This started to happen Saturday 9/10/2022 and I suspect that Unsplash has adjusted their api and/or are having issues.  As far as I can tell by looking at the [code](https://github.com/SilentVoid13/Templater/blob/master/src/core/functions/internal_functions/web/InternalModuleWeb.ts#L58),  the logic is to pull an image from this url: https://source.unsplash.com/random/

When I try that url out I get an "application error".  I'm not familiar with Unsplash's API / Community to know to figure if they've changed things.

**Comment by greywall43** [comment]
Doing some research I did come across this: https://changelog.unsplash.com/deprecations/2021/11/25/source-deprecation.html it looks like this is the "source" api and it's finally been shut down over the weekend?

Looks like the [new way](https://unsplash.com/documentation#get-a-random-photo) is to use: https://api.unsplash.com/photos/random  (however, I don't have a authentication token / account). Hopefully this bit of research will help.

**Comment by shabegom** [comment]
Hm that's unfortunate, thanks for reporting

**Comment by shabegom** [comment]
Will merge PR that fixes this on the weekend.

**Comment by greywall43** [comment]
Awesome!  Good idea on the proxy for keeping key private (and fly.io seems really cheap for hosting).  Also I really like the photo attribution idea, hoping that can be added as part of the image description (i.e. new feature request) -- I've always wondered who took the random photo sometimes.
