### ISSUE TITLE
How to config the first day of the week

### ISSUE THREAD

**Issue by Steven-AA** [SilentVoid13/Templater#825]
> Week day number. If the locale assigns Monday as the first day of the week, 0 will be Monday, -7 will be last week's day.
 
My macos system calender start from Sunday, but the Templater start from Monday. What do you mean by "local assigns", Where to change it?

**Comment by AB1908** [comment]
Can you check discussions? Talks about locale have come up several times.

**Comment by Steven-AA** [comment]
Search "locale" in discussions did not find what I want.

Just for reference if anyone has the same demand, now I am using 
`[[<% moment().isoWeekday(0).format("YYYY-MM-DD") %>]]
`
to get a weekday start from sunday.

**Comment by zyfyy** [comment]
> Search "locale" in discussions did not find what I want.
> 
> Just for reference if anyone has the same demand, now I am using `[[<% moment().isoWeekday(0).format("YYYY-MM-DD") %>]] ` to get a weekday start from sunday.

what ? any script will be excuted ??

**Comment by AB1908** [comment]
You can execute arbitrary JavaScript but inside `<%*` blocks. `moment()` appears to work in regular Templater blocks however.
