### ISSUE TITLE
Sorting patterns.

### ISSUE THREAD

**Issue by tonygrr** [SilentVoid13/Templater#83]
Hi everyone. After the last update, when you open the menu to insert a template, the order of their sorting has changed. Now it goes backwards (Z to A). I have not found a way to change this setting. Is there any way to return the previous sorting option?

![image](https://user-images.githubusercontent.com/72566774/113835219-704d4c00-9794-11eb-9ca8-3ebed34d0b56.png)

**Comment by SilentVoid13** [comment]
Hey @tonygrr, you're right, I'll sort them alphabetically.
