### ISSUE TITLE
[bug] <% tp.file.include([[Morning routine checklists]]) %>causing parsing error

### ISSUE THREAD

**Issue by Ravenclawer** [SilentVoid13/Templater#831]
**Plugin information (please complete the following information):**

-   OS: [e.g. Windows 10] win10
-   Templater version: [e.g. 0.3.4] 1.14.1
-   Obsidian version: [e.g. 0.9.11] 0.15.9
-   Templater settings: [e.g. Template folder location: "Templates/", Timeout: "5" (add the templates not working with their associated command)]
![image](https://user-images.githubusercontent.com/73892411/190839157-f1f28e29-c6b4-4b99-b727-61bda69c8087.png)

**Describe the bug**
the following syntax in a template note causes a parsing error 
<% tp.file.include([[Morning routine checklists]]) %>

![image](https://user-images.githubusercontent.com/73892411/190839142-cc08e45e-3cc9-4a4b-9cd4-d1690a4a1b22.png)

**Expected behavior**
insert checklist from the note Morning routine checklists
**Screenshots**

**Additional context**

**Comment by Ravenclawer** [comment]
![image](https://user-images.githubusercontent.com/73892411/190839279-27731f37-8c7e-4809-ae9b-f3462837e1e0.png)

**Comment by shabegom** [comment]
Looks like a conflict with another plugin. Templater doesn't touch cm6.

**Comment by b0o** [comment]
I think you’re missing quotes. Try:

```js
<% tp.file.include("[[Morning routine checklists]]") %>
```

**Comment by Ravenclawer** [comment]
https://github.com/SilentVoid13/Templater/issues/831#issuecomment-1250546094
@b0o this solved my problem. you are amazing
