### ISSUE TITLE
templates not processing on 1.14.3

### ISSUE THREAD

**Issue by Archie-2021** [SilentVoid13/Templater#836]
**Plugin information (please complete the following information):**

-   OS: [e.g. Windows 10]
-   Templater version: [0.14.3]
-   Obsidian version: [e.g. 0.9.11]
-   Templater settings: [e.g. Template folder location: "Templates/", Timeout: "5" (add the templates not working with their associated command)]

**Describe the bug**
After yesterday update nothing works anymore related to this plugin. I was expecting to it to be a bad update and find a thread about it over here but can find any, so I guess something went wrong on my update only, how can I hve my settings and reinstall?

**Expected behavior**

**Screenshots**

**Additional context**

![image](https://user-images.githubusercontent.com/85870778/191910312-e7f8d0cb-bdc7-4ecf-abeb-00ccb5b502c4.png)

**Comment by Archie-2021** [comment]
I Uninstalled and reinstalled templater and it is still not working , please help, It is a huge problem in my workflow and I need to know if it is a general issue of something is only broken in my vault now.

thanks

**Comment by shabegom** [comment]
You have an unexpected identifier in your template. It's unlikely to be a bug in templater, but if you post your template we can take a look.

**Comment by shabegom** [comment]
You should fill out the bug report issue template in its entirety to get support.

**Comment by shabegom** [comment]
Using this issue for any problems in 1.14.3.

**Comment by Archie-2021** [comment]
> You should fill out the bug report issue template in its entirety to get support.

I copied the folder for 1.14.2 and still getting the same results. I am very frustrated, I don't know what can I do. My workflow is so dependent on it I don't know what to do.

**Comment by shabegom** [comment]
@Archie-2021 I appreciate the frustration. You haven't provided enough information to help understand what the problem is. 

- what is the template you are trying to run? Share the commands you are using. 
- what user scripts do you have? Have you tried removing all user scripts?
- does the issue occur when you're creating a new note, replacing commands in an existing note? Provide a detailed description of what is happening. 
- Did you make an error when reporting what version of obsidian you're using? 0.9 would be very old. 

I'm taking time to try and help you on a free plugin. You can feel frustrated, but please be respectful of my time and provide enough information to help.

**Comment by Archie-2021** [comment]
> @Archie-2021 I appreciate the frustration. You haven't provided enough information to help understand what the problem is. 
> 
> - what is the template you are trying to run? Share the commands you are using. 
> - what user scripts do you have? Have you tried removing all user scripts?
> - does the issue occur when you're creating a new note, replacing commands in an existing note? Provide a detailed description of what is happening. 
> - Did you make an error when reporting what version of obsidian you're using? 0.9 would be very old. 
> 
> I'm taking time to try and help you on a free plugin. You can feel frustrated, but please be respectful of my time and provide enough information to help. 

The issue was that a script got modified unintentionally and caused all the plugins which  use scripts to stop working. It has happened to me before but it was never unintentional and I knew I was messing with scripts so I figured it out soon.

I apologize for freaking out and not explaining the issue fully. But this situation is such that really nothing works and is hard to describe in another way other than saying it gives me error "unexpected identifier" and not a single template or macro works.

**Comment by AB1908** [comment]
Hey @Archie-2021. If you have time, I can look over your issue on a Discord screen share to get a sense of what's happening and narrow it down.

**Comment by Archie-2021** [comment]
> Hey @Archie-2021. If you have time, I can look over your issue on a Discord screen share to get a sense of what's happening and narrow it down. The error is likely in your script and we'll need to look at it to figure out what's wrong.

Thank you but there is no script that I am working on it right now. I was just playing with a coc extension for vim for JS and I accidentally save the mess I made on the script that was in scripts folder. The thing that save me was that I replaced all .obsidian folder with a older version and it was not working still. So I figured the problem must be in scripts folder.

**Comment by AB1908** [comment]
I see. Try temporarily removing your user scripts (move them outside vault) and see if that helps.

**Comment by shabegom** [comment]
Using this issue as a catch all for any other 1.14.3 rendering problems. 

Although it appears the initial issue reported was user error...

**Comment by jrenaud90** [comment]
Hello, 
   I am having a similar problem since the recent update. The consol is throwing a Template parsing error [references templator line 82] and then a TypeError: Cannot read properties of null (reading 'path') [references templator line 3965].

I tried to remove user scripts from the vault and that did not help. 

I tried to make the template as minimal as possible to reproduce:

```md
---
CreatedOn: <% tp.file.creation_date("YY-MM-DD HH:mm:ss") %>
---

# Meeting 
#meeting

**Date**: <% tp.data.now("YYYY-MM-DD") %>
**Related Project**:
**Attendance**:

## Agenda

## Notes

## Next Steps / Action Items
```

I am running:
Windows 10
Obsidian 0.15.19
Templator 1.14.3

Thanks for all your work!

**Comment by shabegom** [comment]
@jrenaud90 awesome report! This gives me a good idea on where the problem is happening.

It must be trying to read `path` off of the TFile object and the object is undefined for some reason. 

I'll take a look at where this is happening this week. 

Thank you!!

**Comment by shabegom** [comment]
@jrenaud9

I assume in the minimal repro you mean to use `tp.date.now`. It currently says tp.data.now

How is this template getting triggered? Is it a folder template?

**Comment by jrenaud90** [comment]
> @jrenaud9
> 
> I assume in the minimal repro you mean to use `tp.date.now`. It currently says tp.data.now
> 
> How is this template getting triggered? Is it a folder template?

... I am dumb. That typo was the problem (I swear this was working a while ago must have been a new mistype). I guess anyone else who runs into this double check your spelling...

Thanks for the help! @shabegom
