### ISSUE TITLE
tp.file.exists is now asynchronous 

### ISSUE THREAD

**Issue by rapatel0** [SilentVoid13/Templater#837]
**Plugin information (please complete the following information):**

-   OS: Mac 12.6
-   Templater version: 1.14.3
-   Obsidian version: 0.16.3
-   Templater settings:

<img width="801" alt="image" src="https://user-images.githubusercontent.com/18704704/191954254-3bcd835d-57a4-4d7a-abd2-e4239823e851.png">

**Describe the bug**
I have a function I wrote to create a file conditionally based on if it exists. It broke with the recent update. and I've narrowed it down to being a problem with `tp.file.exists`. 

The if statement will always return true even if the file doesn't exist. I have a feeling that its evaluating as a promise object and then checking if the promise object exists (which of course it does).

Things Ive tried:
- I've also run `app.vault.adapter.exists()` as a work around but that doesn't work either. 
- I've attempted to run `await` commands but this causes templater to error out on script parsing

Any ideas 

```
      function createView(dateString,datePrefix, processPrefix, templateName, folderPathPrefix){

        const date = tp.date.now(dateString)
        const template = tp.file.find_tfile(templateName); 

        const folder = app.vault.getAbstractFileByPath(folderPathPrefix + datePrefix + date ); 

        const viewName = processPrefix+date;
        console.log(viewName)
        console.log(folder)

        if (!tp.file.exists(viewName)) {  //<---------------------------------------PROBLEM
            let taskProcessName =  (tp.file.create_new(template, viewName, false, folder)).basename;
            
        } 
        
    }
```

**Expected behavior**
Investigation into why `tp.file.exists` broke with the latest update

**Comment by rapatel0** [comment]
I rolled back to 1.14.1 and it doesn't have the issue.

**Comment by shabegom** [comment]
It's now asynchronous. Make your function async and await to.file.exists

**Comment by rapatel0** [comment]
Thanks for your help. Worked
