### ISSUE TITLE
Templater Completely Silent on Obsidian v0.16.3

### ISSUE THREAD

**Issue by micwaab** [SilentVoid13/Templater#838]
Templater has been functioning properly for months. Now, after a recent update, Templater templates cannot be inserted.

Currently using Templater 1.14.3
Obsidian v0.16.3
Mac OS Monterey 12.6

When I attempt to insert a Templater template via hotkey, / command, or command palette, nothing happens at all.

My expectations are that templates will be inserted when commanded to do so.

Thanks for your time.

**Comment by shabegom** [comment]
Please use the bug reporting template if experiencing an issue. You haven't provided enough information. 

- what templates are you attempting to insert?
- do you have any user functions, have you tried removing them?
- are any errors reported to the console?
- if you try to replace a command in a file, does it work? So dynamic commands work?

**Comment by micwaab** [comment]
Thanks. I discovered my hard drive was failing, likely causing the odd behavior. After checking my other machine, Templater is working as expected.

**Comment by AB1908** [comment]
Could this hard drive issue be behind the other bug reports? 😂

**Comment by micwaab** [comment]
That system is no longer in use.
