### ISSUE TITLE
Interaction with other plugins

### ISSUE THREAD

**Issue by marc0l92** [SilentVoid13/Templater#839]
Hello,
I'm the developer of the plugin [Jira Issue](https://github.com/marc0l92/obsidian-jira-issue).

I would like to expose some of the functions and data that my plugin handles to the Templater plugin so that people can use those data to build their notes template.

How can I access from Templater functions exposed by other plugins? How can I expose some of the functions and data of my plugin to Templater?

Do you know any other plugin that interacts with Templater in a similar way?

Thanks
Marco

**Comment by shabegom** [comment]
Do you want to use Jira Issue functionality inside a templater command, or templater commands inside a Jira issue code block?

The former would be work in Jira Issue to expose some sort of API. Plugins like MetaEdit have done this. 

The latter would currently require some digging into `app.plugins.plugins["obsidian-templater"]` and is a bit of a pain. I am considering making this easier, but it isn't on the short term (bug fixing is the focus right now).

**Comment by marc0l92** [comment]
I would like to use Jira Issue data to build a template.
I will check how MetaEdit is doing that so I can also expose some API that templater can use.

If you already have some advice, let me know.

**Comment by shabegom** [comment]
closing as this isn't something that should be implemented in templater.
