### ISSUE TITLE
How to automatically name the images pasted into MD Notes？

### ISSUE THREAD

**Issue by Fuguexv** [SilentVoid13/Templater#84]
Hello Author! Thank you for creating such a useful plugin, however I may need a little help. If I want the images I paste into MD Notes to be named in the format "File" + "YYMMDDHHMMSS", how this plugin should be set up?

**Comment by SilentVoid13** [comment]
Hey @Fuguexv, what you're describing is not possible with Templater. Templater is supposed to be used to create templates.
Templater doesn't handle the default filename of pasted images, the obsidian app itself is dealing with that.
Try asking on Discord forum for tricks to be able to do what you want, but I'm afraid Templater won't be of any help here.
Closing this.
