### ISSUE TITLE
Request: Allow user templates to be written in JavaScript

### ISSUE THREAD

**Issue by shabegom** [SilentVoid13/Templater#85]
**Is your feature request related to a problem? Please describe.**
 it would be great to be able to write user specified template variables in javascript. This would make them mobile compatible as well.

**Describe the solution you'd like**
- support shell or javascript by some kind of fancy logic in how user template variables or interpreted
- OR: allow user to add something to the template variable that indicates it is JS and not shell/powershell
- OR: have a toggle to switch between shell/powershell and JS

**Describe alternatives you've considered**
You can always run `node script.js` but I don't think this will work inside the mobile app.

**Additional context**
Part of this  conversation from #plugins on discord: https://discord.com/channels/686053708261228577/707816848615407697/829367626055548948

**Comment by SilentVoid13** [comment]
Hey @shabegom, this is now possible with user scripts in Templater 1.6.0. Documentation at https://silentvoid13.github.io/Templater/docs/user-functions/script-user-functions.

Templater can now load your js files from a folder inside your vault. You can then call the main function from your script using `tp.user.<my_script_name>`
