### ISSUE TITLE
Dynamic command not working with tp.file.include()

### ISSUE THREAD

**Issue by nilfric** [SilentVoid13/Templater#850]
**Plugin information (please complete the following information):**
-   OS: MacOS 12.15.1
-   Templater version: 1.14.3
-   Obsidian version: 0.15.9

**Describe the bug**
When using dynamic commands, including a file works inside a code block, but not on it's own.

Working:
\```
<%+ tp.file.include('[[Template]]') %>
\```

Not working:
<%+ tp.file.include('[[Template]]') %>

**Comment by AB1908** [comment]
Duplicate of #869?
