### ISSUE TITLE
folder template bug

### ISSUE THREAD

**Issue by YicanPeng** [SilentVoid13/Templater#855]
-   OS: Windows 10
-   Templater version: 1.14.3
-   Obsidian version: 0.15.9

**Describe the bug**
when I use the community plugin `notes refactor`, it will create a new file in the folder, but the new file can't be created as the template I've already configured for the folder

**Comment by AB1908** [comment]
Can you give us steps to reproduce? E.g.

1. Create a folder template
2. Use notes refactor to create a new note
3. Wait for folder template to trigger

I can't quite figure out why this won't trigger but a good set of repro steps will help narrow it down.

**Comment by YicanPeng** [comment]
> 

1. create a folder template
2. use note refactor `extract the content as new file`
3. finally the folder template won't be trigger，and I get a file without any template 
---
AND I think the bug is from the note refactor, note refactor has its own generating template which will cover the Templater's template.

**Comment by AB1908** [comment]
Able to repro but unclear if it's a templater bug. Your steps were a little less descriptive than I hoped but I managed to find my way around. Let me amend them:

1. Create folder template
2. Assign folder template to folder in templater settings
3. Install note refactor
4. In note refactor settings, set new note location to same folder as in templater settings for folder note
5. Split/refactor any note and enter new file name in pop up modal
6. Templater is not invoked (no console logs despite being in my template)

My template: `<%* console.log("here");tR+="stuff"; %>`

Suggested workaround: use templater scripts to refactor your notes in case your folder templates are critical as you would then have control over the content inserted. E.g., script that refactors using `tp.file.selection()` and `tp.file.create_new()`.

**Comment by shabegom** [comment]
Yeah I don't think we can address this in templater. Note Refactor could trigger templater though.
