### ISSUE TITLE
Create a command to create a new note from a specific template

### ISSUE THREAD

**Issue by Hunter-Bobeck** [SilentVoid13/Templater#857]
Can we get a feature to add additional commands to Obsidian, tied to certain templates, for the 'Templater: Create new note from template' command?

**Comment by shabegom** [comment]
I don't understand

**Comment by rapatel0** [comment]
This already exists in several forms. Look at the quickadd plugin (works with templater)

**Comment by AB1908** [comment]
If you're looking to expose a command to directly use a template, use "Add hotkeys for template". It exposes the template as a command palette command.

**Comment by Hunter-Bobeck** [comment]
> This already exists in several forms. Look at the quickadd plugin (works with templater)

This is the closest to what I'm looking for.

**Comment by Hunter-Bobeck** [comment]
> If you're looking to expose a command to directly use a template, use "Add hotkeys for template". It exposes the template as a command palette command.

The point of what I'm looking for is to create a new note at the same time.

**Comment by AB1908** [comment]
Use `tp.file.create_new()`?
