### ISSUE TITLE
API Access to Parser

### ISSUE THREAD

**Issue by rapatel0** [SilentVoid13/Templater#859]
I have several templates that interplay with both dataview and templater. I would like to use dataview to preprocess content and then use templater to render some of the date strings and other templater commands in the content.

Ideally I would like to have a `tp.parse` command that will parse aribrtrary text that contains templater strings. 

I have tried accessing the parser via  `app.plugins.getPlugins......parse_commands` command but it breaks and not sure it's actually workable

**Example (breaks on `parsedContent` line)**
```javascript
let DvTaskList  = dv.markdownTaskList(taskQuery)
let parsedContent = await app.plugins.getPlugin("templater-obsidian").templater.parser.parse_commands(DvTaskList)
tR += parsedContent;
```

**Comment by AB1908** [comment]
Can you explain an example of this use case? It's relatively rare to need something like this.

**Comment by rapatel0** [comment]
I have a pretty complex setup (probably some refactoring needed) but here is the use case

I have a central daily file that contains all of my tasks for the day. That checklist file is dynamically constructed with some templater scripts. I currently use data view to construct views for the checklist files. I would like to remove unnesessary tasks from the checklist file. 

Here's an example. (just writing this out as an example)

```
<% tp.file.include([[P-Health-Habits]]) %>
<% tp.file.include([[P-Work-Habits]])   %>
```

Currently That renders to 

```
- [ ] #Tuesday #Health Habit about stuff2
- [ ] #Friday  #Health Habit about other stuff
- [ ] #Tuesday #Work Habit about work stuff
- [ ] #Friday  #Work Habit about other work stuff
```

Then I have a dataview view that will parse out stuff for Today. What I want to do is get rid of #Friday stuff when Today==#Tuesday.


It's a bit complicated but does that make sense?

**Comment by rapatel0** [comment]
I think I can work around the problem with a temporary file or hacking the "Render template command to run at the end somehow without a race, but would rather avoid it

**Comment by shabegom** [comment]
Include will process any templater commands in the note being included. So just put your date logic there instead of trying to process it multiple times. 

It's unlikely we'll be exposing the parser anytime soon as it is significant work and there isn't a huge demand.

**Comment by rapatel0** [comment]
> It's unlikely we'll be exposing the parser anytime soon as it is significant work and there isn't a huge demand.

No worries. I'll work around the problem for now. 

> Include will process any templater commands in the note being included. So just put your date logic there instead of trying to process it multiple times.

Just to clarify the thread, the use case more complex then just date logic.

To use an analogy from C, I'm using dataview as a macro preprocessor for templater. Using dataview to query multiple files and build a template dynamically. 

Anyways, I'll punt for now. Cheers
