### ISSUE TITLE
Templater Error: Template parsing error

### ISSUE THREAD

**Issue by lumargh** [SilentVoid13/Templater#863]
-   OS: Mac OS Monterey 12.6
-   Templater version: 1.14.3
-   Obsidian version: 1.0
-   Templater settings: "Utilities/Templates"

**Describe the bug**
1. Create a file in the template location (e.g. Utilities/Templates)
2. In another file (different folder), launch command to add template; select file

**Expected behavior**
- Template is added to file.

**Bug**
- Templater Error: Template parsing error, aborting. 
- Cannot read properties of null (reading 'offsetTop')
- log_error @ plugin:templater-obsidian:82

**Comment by shabegom** [comment]
Can't troubleshoot without seeing the template. This looks like an error in your template and not a templater bug.

**Comment by lumargh** [comment]
I didn't think it was the templates just because it's happening with every one. 

https://user-images.githubusercontent.com/106437649/195723333-3bd6e893-a557-415e-a445-f77973a0f7ad.mov

**Comment by shabegom** [comment]
Do you have any user JS templates? If there is an error in those it borks the whole thing.

**Comment by lumargh** [comment]
Lol you're so right. I was working on a script and gave up. Unborked.

**Comment by sayedbakeer3** [comment]
> Do you have any user JS templates? If there is an error in those it borks the whole thing.

can you tell me what does that mean ? i had same problem so how i can fix it ?
