### ISSUE TITLE
Templater doesn't work since Upgrade yesterday

### ISSUE THREAD

**Issue by LloydHunt** [SilentVoid13/Templater#865]
Windows 11
Templater 1.14.3
Obsidian 1.0.0
Have all templates in "030 Templates" folder.
**Plugin information (please complete the following information):**

-   OS: [e.g. Windows 10]
-   Templater version: [e.g. 0.3.4]
-   Obsidian version: [e.g. 0.9.11]
-   Templater settings: [e.g. Template folder location: "Templates/", Timeout: "5" (add the templates not working with their associated command)]

**Describe the bug**
All of my templates worked last night prior to upgrade. NO templates work today. Even simple templates where I'm simply inserting text (something like):
Company:: 
Instead I receive: "Templater Error: Template parsing error, aborting....

Thank you !!!
**Expected behavior**

**Screenshots**

**Additional context**

**Comment by shabegom** [comment]
Hm. If 1.0 broke templater I'm sure I'd be hearing more about it. Can you post the full templater command and screenshot the error in the dev console?

**Comment by LloydHunt** [comment]
I agree with you 100%.
I rebuilt everything in a new vault. It's working.
Don't know what happened but appreciate your reaching out....
