### ISSUE TITLE
An error message occures, when I click the button to insert one of my templates.

### ISSUE THREAD

**Issue by merlinuwe** [SilentVoid13/Templater#868]
**Plugin information (please complete the following information):**

-   OS: Windows 10
-   Templater version: 1.14.3
-   Obsidian version: 1.0.0
-   Templater settings: [e.g. Template folder location: "Templates/", Timeout: "5" (add the templates not working with their associated command)]

**Describe the bug**

When I press the button on the left side of obsidian to include one of my templates, I get a warning "Es können keine Vorlagen angezeigt werden. Odner Vorlagen wurde nicht gefunden. "

**Expected behavior**

I expected, that I could open a new file and get one of my templates in (as before).

**Screenshots**

**Additional context**

Template folder location
Meta/Templates

Template Hotkeys (Strg-T)
Meta/Templates/Neue Notiz.md

Folder Templates

/ Meta/Templates/Folder TEMPLATE Notizen.md

IT Grundlagen/Hardware Meta/Templates/Folder TEMPLATE HowTo.md

Privat/Füller Meta/Templates/Folder TEMPLATE Füller.md

In the message is also a typo: "Odner" instead of "Ordner".

I changed the folder from "Vorlagen" to "Templates" with no result.
I reinstalled temlater with no result.
I reinstalled obsidian with no result.

**Comment by AB1908** [comment]
Your path in settings for folder templates appears to be incorrect?

**Comment by merlinuwe** [comment]
My path of Template folder location is

Meta/Templates

In this folder are 

Folder Template Füller.md
Folder Template HowTo.md
Folder Template Notiz.md
Neue Notiz.md

Is this wrong?

**Comment by AB1908** [comment]
What value have you assigned in templater settings?

**Comment by merlinuwe** [comment]
Template folder location
Meta/Templates

**Comment by AB1908** [comment]
Did the same settings work correctly in a previous version? Can you give us steps to reproduce the error in the sandbox vault?

**Comment by merlinuwe** [comment]
I'm sure, that it worked yesterday, but since yesterday I changed some things that I cannot completely remember.

Strg-n for a new file
Manually delete the already available contents in the new file.
I'm in edit mode.
I click the button to include one of my templates.
I get the error message.
Reproducible.

**Comment by AB1908** [comment]
I'm sorry, that's not quite detailed enough for me to follow. See an example here: https://github.com/SilentVoid13/Templater/issues/855#issuecomment-1279740813.

**Comment by merlinuwe** [comment]
I found the problem by myself... yes I'm a great developer ... ;-)

![buttonorfingerproblem](https://user-images.githubusercontent.com/4138869/196043340-c91399a9-1dad-45fb-8949-a3de8135c231.png)

I simply pressed the wrong button... Sorry for the inconvience. 1000 lashes and dust on my head as a sign of humility.

**Comment by AB1908** [comment]
Haha all good! Happens to everyone.
