### ISSUE TITLE
documentation unclear

### ISSUE THREAD

**Issue by lwb52** [SilentVoid13/Templater#87]
with the recent update, various aspects of the ReadMe file are rather unclear (at least to me):

-a screenshot shows that calls to curl should/must be surrounded by double-quotes (”), but the samples in the main text do not include them—when & where are they needed? inside the plugin settings, or in the template file that uses the plugin? Also, the wttr.in service requires double-quotes to set specific parameters, so how does one deal with those—are they to be escaped or not, and how? (Experimenting today with different approaches & escape characters has not succeeded.)

-a similar issue regards the format of a call to the plugin from a template document: neither the older ”{{}}” nor the newer ”<%  %>” seem to work any longer—while the newer ”<%  %>” worked this morning calling to wttr.in, it has not worked the rest of the day (although that service itself still works fine from within browsers)…

-another formatting issue also appears:
- formats are shown in 2 ways—
   - in the Internal Template chart, formatting is shown as:
   `tp.date.tomorrow(format: string = "YYYY-MM-DD”)`
   - but Examples are shown as:
   `<% tp.date.now("Do MMMM YYYY") %>`
- is `format: string = ` required or not?

**Comment by SilentVoid13** [comment]
Hey @lwb52, to answer your questions:

- I'm not sure I understand this question, what do you mean by "samples in the main text" ? All my screenshots are using quotes around the urls when using `curl`. `curl` is a shell command, it's better to use quotes around urls to avoid shell characters conflicts. The template file that calls the user command (e.g. `<% tp.user.weather() %>`) doesn't require anything, it just calls the system command associated with it.
- I'm not sure what could be causing this, the "wttr.in" sometimes does not work, probably because too many requests are made.
- As explained here: https://github.com/SilentVoid13/Templater#internal-modules, types and arguments names are for documentation purposes only, to be able to understand what the functions expected. You should not include them in your templates (like in the examples).

**Comment by jairjacom** [comment]
I am under the same dilemma, and it is probably I am no expert with JS and instructions are not 100% noob friendly. I used to have the {{tp_date}} and was working fine. With update I am not sure what to write I have tried a few per your instructions and they do not work. 

tp.date.now
<% tp.date.now %>
<% (tp.date.now) %>

None of these show the date!

**Comment by jairjacom** [comment]
Below is my template using your latest update:

## Note Type: #daily-note

## Date: <% tp.date.now %>

## Backlink
<% tp.date.yesterday %> | <% tp.date.tomorrow %>

## Quote
> <% tp.web.daily\_quote() %>

**Comment by luckman212** [comment]
@jairjacom 

try

```
<% tp.date.tomorrow() %>
<% tp.date.now() %>
<% tp.date.yesterday() %>
```

**Comment by jairjacom** [comment]
Not working. Pasting what the console says ( I have no idea what this means )

`Template parsing error, aborting. Eta Error: Bad template syntax

Invalid or unexpected token
===========================
var tR='',__l,__lP,include=E.include.bind(E)
function layout(p,d){__l=p;__lP=d}
let prs = [];
prs.push(tp.date.now());
prs.push(tp.date.yesterday());
prs.push(tp.date.tomorrow());
prs.push(tp.web.daily\_quote());
let rst = await Promise.all(prs);
tR+='## Note Type: #daily-note\n\n## Date: '
tR+=rst[0]
tR+='\n\n## Backlink\n'
tR+=rst[1]
tR+=' | '
tR+=rst[2]
tR+='\n\n## Quote\n> '
tR+=rst[3]
tR+='\n\n### TODO\n- [ ] \n- [ ] \n- [ ] \n- [ ] \n\n### Scratchpad \n- \n- \n- \n- '
if(__l)tR=await include(__l,Object.assign(tp,{body:tR},__lP))
if(cb){cb(null,tR)} return tR
`

**Comment by icr1001** [comment]
> * As explained here: https://github.com/SilentVoid13/Templater#internal-modules, types and arguments names are for documentation purposes only, to be able to understand what the functions expects. You should not include them in your templates (like in the examples).

@SilentVoid13  I think not people will carefully read the `type arguments` **warning** and the documentation. Most of them will copy what is in that table. At least, it is better to add a column with the final code, something like this:


| Internal Variable/Function  | Arguments                                                    | Description                | Example Code                                    | Example Output |
| ------------------------------------------------------------ | ------------------------------------------------------------ | -------------------------- | ----------------------------------------------- | -------------- |
| tp.date.now(format: string = "YYYY-MM-DD", offset?: number, reference?: string, reference_format?: string) | - `format`: Format for the date, refer to [format reference](https://momentjs.com/docs/#/displaying/format/)<br />- `offset`: Offset for the day, e.g. set this to `-7` to get last week's date.<br />- `reference`: The date referential, e.g: set this to the note's title<br />- `reference_format`: The date reference format. | Retrieves the date.        | `<% tp.date.now(string = "YYYY-MM-DD") %>`      | `2021-01-15`   |
| tp.date.tomorrow(format: string = "YYYY-MM-DD")              | - `format`: Format for the date, refer to [format reference](https://momentjs.com/docs/#/displaying/format/) | Retrieves tomorrow's date  | `<% tp.date.tomorrow(string = "YYYY-MM-DD") %>` | `2020-11-07`   |
| tp.date.yesterday(format: string = "YYYY-MM-DD")             | - `format`: Format for the date, refer to [format reference](https://momentjs.com/docs/#/displaying/format/) | Retrieves yesterday's date | <% tp.date.yesterday(string = "YYYY-MM-DD") %>  | `2020-11-07`   |

**Comment by lwb52** [comment]
that idea for a “sample” column was a good suggestion for clarity to aid folks like me who just copy as best they can!
it still leaves unclear how to deal with wetter.in, that requires certain options to be surrounded by double-quotes (“)—how to make sure your plugin’s own double-quote needs do not get messed up with the “included” wttr.in double-quotes…

also, if you compare the screenshot in your Readme file with the “Example” text that follows it, you will note that their formats are not identical: which version is proper?

**Comment by lwb52** [comment]
still having no luck accessing wttr.in:

error message for 3 curl calls is—
```
      try {
                        let process_env = Object.assign(Object.assign({}, process.env), user_args);
                        let cmd_options = {
                            timeout: this.plugin.settings.command_timeout * 1000,
                            cwd: this.cwd,
                            env: process_env,
                        };
                        let { stdout } = yield exec_promise(cmd, cmd_options);
                        return stdout;
                    }
                    catch (error) {
                        this.plugin.log_error(`Error with User Template ${template}`, error);
                    }
                }) (user_args) => __awaiter(this, void 0, void 0, function* () {
                    try {
                        let process_env = Object.assign(Object.assign({}, process.env), user_args);
                        let cmd_options = {
                            timeout: this.plugin.settings.command_timeout * 1000,
                            cwd: this.cwd,
                            env: process_env,
                        };
                        let { stdout } = yield exec_promise(cmd, cmd_options);
                        return stdout;
                    }
                    catch (error) {
                        this.plugin.log_error(`Error with User Template ${template}`, error);
                    }
                }) (user_args) => __awaiter(this, void 0, void 0, function* () {
                    try {
                        let process_env = Object.assign(Object.assign({}, process.env), user_args);
                        let cmd_options = {
                            timeout: this.plugin.settings.command_timeout * 1000,
                            cwd: this.cwd,
                            env: process_env,
                        };
                        let { stdout } = yield exec_promise(cmd, cmd_options);
                        return stdout;
                    }
                    catch (error) {
                        this.plugin.log_error(`Error with User Template ${template}`, error);
                    }
                })
                })
```

> that idea for a “sample” column was a good suggestion for clarity to aid folks like me who just copy as best they can!
> it still leaves unclear how to deal with wetter.in, that requires certain options to be surrounded by double-quotes (“)—how to make sure your plugin’s own double-quote needs do not get messed up with the “included” wttr.in double-quotes…
> 
> also, if you compare the screenshot in your Readme file with the “Example” text that follows it, you will note that their formats are not identical: which version is proper?
> 
> Sent from ProPad

**Comment by lwb52** [comment]
to include more info:

this is what the curl calls to wttr.in were:



As you can see, quotation marks are essential, but there is no obvious way to use them based on the new ReadMe file…

this is what I was able to deduce that the Daily Note template should now use to initiate calls to curl:

this is what the old calls used to produce as output:
Bellingham: 🌦 🌡️+48°F 🌬️↑10mph 💦 2.2mm 🌖

the error messages I sent before is all I get now.

sorry for my lack of knowledge—I’m just trying to learn.
Also, I tried this with a test vault with no plugins or themes used other than Daiy Notes and Templater, but got the same error message…

**Comment by SilentVoid13** [comment]
Hey @lwb52, show me your template, I think you might have an error in the syntax

**Comment by jairjacom** [comment]
> Hey @lwb52, to answer your questions:
> 
> * I'm not sure I understand this question, what do you mean by "samples in the main text" ? All my screenshots are using quotes around the urls when using `curl`. `curl` is a shell command, it's better to use quotes around urls to avoid shell characters conflicts. The template file that calls the user command (e.g. `<% tp.user.weather() %>`) doesn't require anything, it just calls the system command associated with it.
> * I'm not sure what could be causing this, the "wttr.in" website sometimes does not work, probably because too many requests are made.
> * As explained here: https://github.com/SilentVoid13/Templater#internal-modules, types and arguments names are for documentation purposes only, to be able to understand what the functions expects. You should not include them in your templates (like in the examples).

Thank you so much for adding a more simpler instructions for people like me, I am so thankful. I do have a question, when I use your first lines on my template and then hit Ctrl+E those lines of codes translates to METADATA INVALID YAML

I am not sure what that is. In editing mode, looks fine but once in preview it doesn't work and instead it reads METADATA INVALID YAML


https://silentvoid13.github.io/Templater/docs/

**Comment by SilentVoid13** [comment]
Hey @jairjacom that's weird, I literally copy-pasted the template from the introduction into a blank file and the YAML works fine for me.

Can you copy-paste your template here ? Something must be wrong in it.

**Comment by jairjacom** [comment]
@SilentVoid13 I figured it out. Please, accept my apology for wasting your time. I had to remove the --- lines

**Comment by SilentVoid13** [comment]
@jairjacom no problem, glad it's working now

**Comment by jairjacom** [comment]
Thank you very much!!!

**Comment by lwb52** [comment]
Thanks for your help!
Here's the portion of the template where I attempt to invoke the calls to curl:
	
Of course that’s all on one line so that all references start with ”<%space” per what I had thought the new Templater version to require
(and the opening header-#️⃣es are also followed by a space, just as before since they do not invoke the plugin).

**Comment by SilentVoid13** [comment]
@lwb52 I'm confused, you didn't post the template ?

**Comment by lwb52** [comment]
I only replied via email—I will now try inside GitHub

**Comment by lwb52** [comment]
i'd forgotten that regular email won’t post screenshots into github:
here’s how I set the plugin calls inside the plugin settings:
![Screen- 2021-04-09 at 12 37 52 PM](https://user-images.githubusercontent.com/22728371/114278516-198a8100-99e5-11eb-8835-59c05cfdbbfa.jpg)
here’s how I call that from the template (all on one line so that all references start with ”<%space” per what I had thought the new Templater version to require, and the opening hashes are also followed by a space, just as before, since they do not invoke the plugin):
![Screen- 2021-04-09 at 12 39 03 PM](https://user-images.githubusercontent.com/22728371/114278552-3cb53080-99e5-11eb-8a5f-8fc748930b6c.jpg)
this is what the old calls used to produce as output:
`Bellingham: 🌦 🌡️+48°F 🌬️↑10mph 💦 2.2mm 🌖`
error messages are all I get now.

**Comment by SilentVoid13** [comment]
@lwb52 as I thought, there is an error in your template file. You need to invoke a user function using the function invocation syntax, refer to https://silentvoid13.github.io/Templater/docs/syntax#function-invocation for more informations.

The correct template would be:

```
### <% tp.user.weathertime() %> <% tp.user.weather4() %> <% tp.user.weathermoon() %>
```

**Comment by lwb52** [comment]
Thank you very much!

**Comment by SilentVoid13** [comment]
Alright glad it's working now, tell me if something goes wrong.

Closing this.
