### ISSUE TITLE
Templater is not working

### ISSUE THREAD

**Issue by Mcezarf** [SilentVoid13/Templater#875]
I am using MacOS Ventura 13.0

Templater version 1.14.3 
Obsidian version: 1.0.0 ( Installer 0.15.0)

Attached is Templater setting  and the "lixo" note in reader mode and edit mode 

The bug is: the command is not working
![Captura de Tela 2022-10-21 às 20 15 44](https://user-images.githubusercontent.com/88067013/197304274-297970f7-61f2-454c-a3c7-a9afc3dc2c1e.jpg)
![Captura de Tela 2022-10-21 às 20 15 25](https://user-images.githubusercontent.com/88067013/197304276-61ed86ff-a35b-4b33-a23f-68af321dfb9c.jpg)
![Captura de Tela 2022-10-21 às 20 14 57](https://user-images.githubusercontent.com/88067013/197304277-aaadf767-7096-4ada-b133-780a97037a38.jpg)
![Captura de Tela 2022-10-21 às 20 14 38](https://user-images.githubusercontent.com/88067013/197304280-366b4ea8-9e89-475f-887e-31ff3e3c939c.jpg)

**Comment by shabegom** [comment]
What are you expecting to happen? The screenshot shows an empty templater command with a comment inside.

**Comment by shabegom** [comment]
Going to assume this is working again due to lack of response. If still an issue, please reach out in the #templater thread on OMG Discord. Thanks!
