### ISSUE TITLE
Use of `creases` keyword in `js` snippet doesn't produce a crease and removes line returns

### ISSUE THREAD

**Issue by jtmackoy** [SilentVoid13/Templater#880]
**Plugin information (please complete the following information):**

-   OS: Windows 10
-   Templater version: 1.14.3
-   Obsidian version: 1.0.0
-   Templater settings: Template folder location: "Templates/"

**Describe the bug**
I'm tying to implement a templater template using a `js` function that appends content to a file *and* one of the lines in that content contains the `%% fold %%` object in order to allow the `obsidian-creases` plugin to fold that content when invoked.  My problem is that when I include it like this:
```js
const activity = await tp.system.prompt("Name of Activity");
const date = tp.date.now("YYYMMDD");

tR +=`
## ${activity} %% fold %%
![[${date}_${activity}]]
`
```
... what I end up with is:
- everything on a single line (not multiple as I would expect)
- no `crease` icon where I expected it to be

... if I remove the `%% fold %%` bit, it works as expected (end up with multiple lines) - just, obviously without the crease I'm trying to insert.

**Expected behavior**
When inserting the `crease` keyword as plain text in a `js` snippet, it should be processed as plain text and result in:
- just the title and the `creases icon` on the first line
- second line contains just the link created via the `js` snippet

**Additional context**
I suspect I'm missing a `js` thing that is preventing this from working, but have tried to escape the `%%` characters without success.

**Comment by shabegom** [comment]
I copied the snippet above and it works as expected when I run it. I'm unable to reproduce.

**Comment by jtmackoy** [comment]
Thanks for checking @shabegom.

Happy to report that it is working for me, as expected, now as well.
Only change I'm aware of was an update of Obsidian (to v1.0.3) and the Templater plugin (to v1.15.3).
