### ISSUE TITLE
Prompts are displayed in random order, and in various positions on the screen

### ISSUE THREAD

**Issue by MatanRubin** [SilentVoid13/Templater#882]
First of all, thank you for you work, Templater is great!

**System Details**

-   OS: macOS Monterey 12.2
-   Templater version: 1.14.3
-   Obsidian version: 1.0.0
-   Templater settings: Template folder location: "Templates/"

**Describe the bug**

When adding a template with multiple calls to `tp.system.prompt()` and `tp.system.suggester()`, the prompts are displayed in a weird way. By "weird", I mean the following:

1. Prompts are displayed in a random order, and not according to their order in the template (as I expected would happen)
2. All prompts are displayed at the same time, unless `await` is added to the call. The documentation doesn't show `await` in the call, so this was confusing.
3. The prompts jump up and down on the screen - each one is shown in a different position on the screen.

**Expected behavior**
1. I expect prompts to appear in the order they appear in the template.
2. I expect them to be shown one at a time. For that, we probably only need to update the documentation to recommend using `await`
3. I expect all prompts and suggestion to be presented at the same location on the screen.

**Screenshots**
Note how both appear at the same time, and Gender is focused first, although it is second in the template.
![image](https://user-images.githubusercontent.com/4488227/197750670-326cb781-ef5b-4adf-a592-8d40770fb55b.png)

This is the template I used for this screenshot:

```
Name: <% tp.system.prompt("Name") %>
Gender: <% tp.system.suggester(["Male", "Female"], ["Male", "Female"], ) %>
```

**Comment by omeraloni** [comment]
Try the following syntax:
```js
<%*
	let name = await tp.system.prompt("Name")
	let gender = tp.system.suggester(["Male", "Female"], ["Male", "Female"], ) 
-%>

**Name**:: <% name %>
**Gender**:: <% gender %>
```

**Comment by MatanRubin** [comment]
Thanks bro :)
This doesn't take care of the third point, but it does for the first two, so it's definitely good enough for me.

**Comment by AB1908** [comment]
The `suggester` also needs to be awaited.
