### ISSUE TITLE
Daily note not templateing

### ISSUE THREAD

**Issue by timothyjlaurent** [SilentVoid13/Templater#89]
**Plugin informations (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Templater version: [e.g. 0.3.4]
 - Obsidian version: [e.g. 0.9.11]
 - Templater settings: [e.g. Template folder location: "Templates/", Timeout: "5" (add the templates not working with their associated command)]

I'm running templater on 
- OSX
- templater 1.1.0
- obsidian v0.11.13
- 
![image](https://user-images.githubusercontent.com/2000204/114064348-64be5b80-984e-11eb-9749-3d6fa0d94099.png)

**Describe the bug**

My daily notes isn't getting templated

**Expected behavior**
The template values would be interpolated in the daily note.
**Screenshots**
This is what it look like when I open the daily note

![image](https://user-images.githubusercontent.com/2000204/114063953-01342e00-984e-11eb-8e51-c32ba9d78c7b.png)

Here's what it looks like when I insert the template 

![image](https://user-images.githubusercontent.com/2000204/114064108-288afb00-984e-11eb-8061-f1bcb6f4345f.png)

**note the <% tp.file.cursor %>**

**Comment by SilentVoid13** [comment]
Hey @timothyjlaurent, there no errors in your template file from what i see. 
Restart obsidian, and tell me if this works now.

**Comment by timothyjlaurent** [comment]
Woot that worked -- closing - thanks.
