### ISSUE TITLE
Skipped parsing ... because file size exceeds 10000

### ISSUE THREAD

**Issue by chasing-pointers** [SilentVoid13/Templater#899]
**Plugin information (please complete the following information):**

-   OS: macOS 12.6
-   Templater version: 1.15.2
-   Obsidian version: Version 1.0.3 (Installer 0.15.9)
-   Templater settings: 
  - Template folder location: /templates
  - Syntax: on
  - Auto Jump: on
  - Trigger on creation: on
  - Show icon in sidebar: on
  - Template Hotkeys (none; only used for triggered-on-creation use cases)
  - Folder Templates: On
  - periodic_notes/__daily__
  - periodic_notes/__weekly__
  - User script functions: /functions (1 script: makeProgressBar)
  - Enable User Sys Command Fns: on
  - Timeout: 5

**Describe the bug**
Upon opening new daily or weekly templates, the message `Templater skipped parsing periodic_notes/__weekly__/2022-W45.md because file size exceeds 10000` appears.  File name is contextual, and happens for any new daily or weekly file created.  Dynamic inline scripts still resolve as expected, but not any `<%` scripts.

It appears this is a hardcoded limit (last case).  This limit either did not apply before or has only now begun failing. 
```
  static on_file_creation(templater, file) {
    return __async(this, null, function* () {
      if (!(file instanceof import_obsidian13.TFile) || file.extension !== "md") {
        return;
      }
      const template_folder = (0, import_obsidian13.normalizePath)(templater.plugin.settings.templates_folder);
      if (file.path.includes(template_folder) && template_folder !== "/") {
        return;
      }
      yield delay(300);
      if (file.stat.size == 0 && templater.plugin.settings.enable_folder_templates) {
        const folder_template_match = templater.get_new_file_template_for_folder(file.parent);
        if (!folder_template_match) {
          return;
        }
        const template_file = yield errorWrapper(() => __async(this, null, function* () {
          return resolve_tfile(folder_template_match);
        }), `Couldn't find template ${folder_template_match}`);
        if (template_file == null) {
          return;
        }
        yield templater.write_template_to_file(template_file, file);
      } else {
        if (file.stat.size <= 1e4) {
          yield templater.overwrite_file_commands(file);
        } else {
          console.log(`Templater skipped parsing ${file.path} because file size exceeds 10000`);
        }
      }
    });
  }
```

**Expected behavior**
As of Friday, this worked and has worked fine for at least 10 months.  Normally, creating a new templated file from Calendar or periodic notes commands would create a blank new file with the template parsed and scripts executed.  

Template file sizes in my case are ~= 13K-14K.

**Comment by AB1908** [comment]
Good ol XKCD workflow lol. This was a change introduced recently at the request of zsviczian.

**Comment by I-Pch** [comment]
I'm running into the exactly same issue and couldn't understand why my daily notes template wasn't working anymore (as of today ... as it was still working perfectly yesterday) when creating my daily note through Calendar/Periodic Notes. 
(The template is still perfectly parsed and working as expected when I re-apply the template through the command palette) 

Thank you @chasing-pointers for clarifying the issue 😇 !

**Comment by shabegom** [comment]
ok 1.15.3 (currently releasing) bumps the limit to 100 000

**Comment by chasing-pointers** [comment]
Thank you @shabegom !!

**Comment by I-Pch** [comment]
Yep 😊 ... Thank you very much @shabegom 🙌 !!!
