### ISSUE TITLE
Templater Is (still) Evolving! (1.2.0)

### ISSUE THREAD

**Issue by luckman212** [SilentVoid13/Templater#90]
I quit and launch Obsidian frequently throughout my day.

I know it was a big upgrade and everyone had to rewrite their scripts and templates but- can we at least make a toggle to turn off this message? 🙏 

![image](https://user-images.githubusercontent.com/1992842/114095777-d7016100-988b-11eb-887c-d424a3b203ce.png)

Thank you again @SilentVoid13 for this amazing work.

**Comment by SilentVoid13** [comment]
Hey @luckman212, I plan on removing this Notice on Monday (a week after releasing the new version).

Do you think you could wait until then ?

**Comment by luckman212** [comment]
🤔

**Comment by SilentVoid13** [comment]
Alright no worries, I'll throw a quick patch to add a toggle for the message

**Comment by luckman212** [comment]
I was fine with waiting but, hey thanks 👍  this is even better.
