### ISSUE TITLE
Templater should use the user colours for syntax highlighting

### ISSUE THREAD

**Issue by iamrecursion** [SilentVoid13/Templater#901]
**Is your feature request related to a problem? Please describe.** 

Obsidian 1.0 introduced a new simple system for customising the majority of colours in the application with simple variables. Templater doesn't respect the user's colour settings, instead using its own colours for syntax highlighting.

**Describe the solution you'd like** 

Templater should utilise the user-defined `--code-...` style variables for its syntax highlighting.

**Describe alternatives you've considered** Overriding things manually.

**Additional context**

**Comment by shabegom** [comment]
I think that would be somewhere in here. It's not clear to me at a glance how the classes are being added. 
https://github.com/SilentVoid13/Templater/tree/master/src/editor

**Comment by iamrecursion** [comment]
I think they're being added in the [styles](https://github.com/SilentVoid13/Templater/blob/master/styles.css). I'll have a look at it.

**Comment by iamrecursion** [comment]
I've PR'd a fix for this issue in #903 but it also fixes some other things.
