### ISSUE TITLE
cannot insert any template in a note which is start with a list, such as "- list item"

### ISSUE THREAD

**Issue by zhao414** [SilentVoid13/Templater#908]
**Plugin information (please complete the following information):**

SYSTEM INFO:
	Obsidian version: v1.0.3
	Installer version: v1.0.3
	Operating system: Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64 21.6.0
	Login status: logged in
	Catalyst license: supporter
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 1
	Plugins enabled: 1
		1: Templater v1.15.3

Using a sandbox vault and a Fresh installation of Templater without a change of any configuration.

**Describe the bug**
1. create a template, such as <%tp.date.now("YYYY-MM-DD")%>
2. create a empty note, without any content and without YAML neither.
3. input the following:
```markdown
- test1
- test2
- test3
```
4. move cursor after "test3" and try to insert the template just created.

**Expected behavior**
the template is inserted after "test3"
```markdown
- test1
- test2
- test32022-11-04
```
**Screenshots**
This is what actually happens:
![image](https://user-images.githubusercontent.com/15528506/199982248-e8fcba9b-a1a2-4abc-80a4-b36f383ffeb5.png)

**Additional context**
As long as the very first character is not a "- "(a dash and a space), the templater works again.

![image](https://user-images.githubusercontent.com/15528506/199982996-a47fa5f6-280d-48f2-8555-b564fa736d35.png)

**Comment by zhao414** [comment]
Currently, the workaround is keeping the fist line empty or using Obsidian front matters, so that the note is not start with "- "(a dash and a space)

**Comment by SilentVoid13** [comment]
Hey @zhao414 thank you for the detailed report.
This look like a codemirror / obsidian error. I tracked down the error to the [doc.replaceSelection](https://github.com/SilentVoid13/Templater/blob/c461524bde5deda2dabeb15e93ed0e697d94b7a9/src/core/Templater.ts#L213) call. Not sure why this doesn't have the request behaviour.

**Comment by SilentVoid13** [comment]
Created an issue on the obsidian github: https://github.com/obsidianmd/obsidian-api/issues/87

**Comment by SilentVoid13** [comment]
Closing as this will be fixed in the next major release, c.f. the github issue above
