### ISSUE TITLE
tp.frontmatter.variable returns "undefined" - but only sometimes...

### ISSUE THREAD

**Issue by eifelkiwi** [SilentVoid13/Templater#909]
**Plugin information (please complete the following information):**

-   OS: Windows 10
-   Templater version: 1.15.3
-   Obsidian version: v1.0.3
-   Templater settings: "templates/"

**Describe the bug**
I use the frontmatter variables a lot in my notes, often rerunning Templater via [Alt]+[R], when I changed/added things.
Tonight I noticed a strange behaviour, where in some notes Templater just returns "undefined" upon rerunning Templater, while in other notes, using the same variables and syntax, it proceeds as usual. No error given in the console.

**Example:** ('--- to suppress line generation)
'---
variable: test
'---

<% tp.frontmatter.variable %>

returns:

undefined

**Expected behavior**
'---
variable: test
'---

<% tp.frontmatter.variable %>

returns:

test

Which it does in some notes, but not in all.

**Screenshots**
Problem:
![Bild_2022-11-07_220348420](https://user-images.githubusercontent.com/117686077/200414974-1eafb19b-a2a9-49d4-a44d-eebc2d19d346.png)
![Bild_2022-11-07_220431969](https://user-images.githubusercontent.com/117686077/200415099-c46f7fd8-4b87-47db-b3ef-cef7cf5642b9.png)

**Additional context**
It is weird since I cannot reproduce the error on all notes...

**Comment by AB1908** [comment]
This is because the metadata isn't cached in the obsidian metadata cache by the time we get to that part in the script. Try throwing it in a variable and use that instead.

**Comment by eifelkiwi** [comment]
Hm. It is really strange, because in other vaults and even other notes in the same vault, it works perfectly fine.
Just to be clear: the problem does not occur in a template.
It just occurs in an already existing note, where I later want to retrieve the data from the frontmatter.

But I have just noticed that dataviewer also does not retrieve the three notes which produce the error. So maybe the problem lies somewhere else...

**Comment by eifelkiwi** [comment]
Okay, I found the error. My mistake. I had one (other) variable indented with a tabstop, which caused the whole frontmatter to be inlegible for both templater and dataview. I did spot it at first because I had another one indented with a space (which works).
Sorry for the confusion.

Case closed, no templater bug. ;)

**Comment by camercu** [comment]
> This is because the metadata isn't cached in the obsidian metadata cache by the time we get to that part in the script. Try throwing it in a variable and use that instead.

How do you "throw it in a variable"? I'm trying to create a meta-template that first builds the frontmatter based on the filename and folder, then includes other templates that draw on the frontmatter. The problem is, the other templates are resolved immediately, so the frontmatter is undefined at that point. How would I do this?
