### ISSUE TITLE
Template parsing error, aborting. Error: Reached inclusion depth limit (max = 10)

### ISSUE THREAD

**Issue by kiraarghy** [SilentVoid13/Templater#91]
**Plugin informations (please complete the following information):**
 - OS: macOS Catalina v 10.15.7 
 - Templater version: [e.g. 0.3.4]
 - Obsidian version: [e.g. 0.9.11]
 - Templater settings: [e.g. Template folder location: "/6. Templater/", Timeout: "5" (add the templates not working with their associated command)]

**Describe the bug**

Thanks for writing this great tool for obsidian, unfortunately I think I may have found a bug?

When I run the following user command I get the `Template parsing error, aborting. Error: Reached inclusion depth limit (max = 10)` error in the `TemplateParser.ts` file at this line https://github.com/SilentVoid13/Templater/blob/master/src/TemplateParser.ts#L95.

```bash
echo "<% tp.file.include('6.\ Templater/Kanban Template') %>" > "<% tp.file.folder(true) %>/<% tp.file.title %>.md"
```
However this works and creates the expected file with the correct title:

```bash
echo "<% tp.file.include('6.\ Templater/Kanban Template') %>" > "<% tp.file.title %>.md"
```
And this works:

```bash
echo "<% tp.file.include('6.\ Templater/Kanban Template') %>" > blah.md
```

This also seems to cause a failure condition where when internal/user templater functions are called in the future they error with the `Template parsing error, aborting. Error: Reached inclusion depth limit (max = 10)` error till I restart obsidian.

**Expected behavior**
I'm able to output the contents of a file into files in the correct directory with the correct name.

**Screenshots**
<img width="665" alt="Screenshot 2021-04-09 at 01 29 32" src="https://user-images.githubusercontent.com/21056165/114111897-0b4c4000-98d3-11eb-839a-379cd0b12c13.png">

**Additional details**

This is the template that is calling the user template

```
<% tp.file.include("6.\ Templater/General\ page\ layout.md") %>
<% tp.user.create_kanban() %>
```

This is the Kanban template I am trying to output into the file

```
---
cssclass: kanban
title: <% tp.file.title %>
created: <% tp.file.creation_date(format = "YYYY-MM-DD HH:mm") %>
---

# <% tp.file.title %>

- To Do
- In Progress
- Done
```

And this is the general page layout 

```
---
title: <% tp.file.title %>
created: <% tp.file.creation_date(format = "YYYY-MM-DD HH:mm") %>
---

# <% tp.file.title %>
```

**Comment by SilentVoid13** [comment]
Hey @kiraarghy, good catch! It was indeed a very tricky bug that happens in very specific conditions (only when you include a file in a user system command). 

This should be fixed in Templater 1.2.2, can you update and tell me if this works fine now ?

About the `<% tp.file.folder(true) %>/<% tp.file.title %>.md` part of your system command, you should be careful with it, because `tp.file.folder(true)` resolves to `/` if the file is at the root of the vault. This would result in `//<filename>.md` which isn't a valid path. Don't set the `relative` argument to true if your files are at the root of the vault. If they are in a folder, this should work fine.

**Comment by kiraarghy** [comment]
@SilentVoid13 I'll give it a go!

**Comment by kiraarghy** [comment]
It works great! Thank you for you work on this! 

Re: the system command, is there a way to get the root directory of the vault from templater?

**Comment by SilentVoid13** [comment]
@kiraarghy do you mean the absolute path to the vault ?

**Comment by kiraarghy** [comment]
Yep, but I just realised that commands I call will be in the root directory of the vault 🤦‍♀️, so no need for the absolute path at the moment.

Thanks 😄
