### ISSUE TITLE
Folder Templates not working

### ISSUE THREAD

**Issue by swehba** [SilentVoid13/Templater#919]
**Plugin information:**

-   OS: macOS 12.6
-   Templater version: 1.16.0
-   Obsidian version: 1.0.3
-   Templater settings: Templates/Templater, Timeout: 5,  

**Describe the bug**
I have Folder Templates enabled. When I create a new note in my Meetings folder, I expect the template Templates/Templater/Templater-meeting.md to be run. It is not. No error message is displayed.

**Expected behavior**
The template should be run and the placeholders should be substituted for.

**Screenshots**
![Relevant Templater settings](https://user-images.githubusercontent.com/1922612/201831833-32878a8d-3870-4a14-a871-96c4b4139434.jpg)

**Additional context**
none

Here is the template file:
[Templater-meeting.md](https://github.com/SilentVoid13/Templater/files/10009480/Templater-meeting.md)

**Comment by Zachatoo** [comment]
How are you creating the note? If you're creating it with another plugin (Daily Notes or Periodic Notes, for example) then you also need to turn on "Trigger Templater on new file creation" in templater settings.

**Comment by swehba** [comment]
@Zachatoo I select my Meetings folder (for example) and press ⌘N to create a new note. I end up with a blank note, and the template I describe above is not applied.

**Comment by Zachatoo** [comment]
Weird. I tried in my vault and in a new vault with Templater folder templates setup, a meetings folder, and your template, and the template is applied every time.

Have you tried in a new vault? Without other plugins enabled? Wondering if there's something else causing it not to work.

**Comment by swehba** [comment]
I assume it works just fine in a new “virgin” vault. Also, the effort required to diagnose why it is not working in my current environment which contains dozens of plugins is just not worth it. It likely is due to some interaction with another plugin. I’ll just let it go for now and live without this feature. Thanks for your responses. I truly appreciate it.

Cheers,
—Steve
Steve Wehba
***@***.***
760.846.1082

**Comment by swehba** [comment]
I assume it works just fine in a new “virgin” vault. However, the effort required to diagnose why it is not working in my current environment which contains dozens of plugins is just not worth it. It likely is due to some interaction with another plugin. I’ll just let it go for now and live without this feature. Thanks for your responses. I truly appreciate it.

**Comment by knopki** [comment]
btw, found conflict with [Filename Heading Sync](https://github.com/dvcrn/obsidian-filename-heading-sync) plugin. Disable _Use File Open Hook_ option as workaround.
