### ISSUE TITLE
Provide an event/hook for other plugins to hook into, to avoid race conditions 

### ISSUE THREAD

**Issue by dvcrn** [SilentVoid13/Templater#924]
**Is your feature request related to a problem? Please describe.** 

Hi! I am maintaining filename-heading-sync and it's currently not playing nicely with templater, see

- https://github.com/dvcrn/obsidian-filename-heading-sync/issues/55
- https://github.com/dvcrn/obsidian-filename-heading-sync/issues/46

**Describe the solution you'd like** 

I don't want to add an artificial delay before acting on obsidian events, but as a solution, if we could detect that templater is installed, we could wait for a custom event (emitted by Templater) before doing things like renaming files or inserting headings. 

Some ideas: 
- expose an event target to subscribe to: https://developer.mozilla.org/en-US/docs/Web/API/EventTarget
- provide a way to detect that templater is installed and enabled (like `window.templaterEnabled = true`) 

Maybe related: https://github.com/SilentVoid13/Templater/issues/883

**Comment by franciskafieh** [comment]
Also having this issue. Using the new `Vaut#process` (https://marcus.se.net/obsidian-plugin-docs/reference/typescript/classes/Vault#process) function in both plugins should supposedly fix this. Basically, `process` allows for atomic modification of the file

**Comment by franciskafieh** [comment]
if anyone wants to take on converting all of Templater's vault.modify, .append, etc to .process, it would be great. Otherwise I can get a PR out within the next week

**Comment by Zachatoo** [comment]
Templater is already emitting an event (multiple events, actually, depending on what you want). The creases plugin is the only plugin I know of that is currently hooking into these events.

Moving to `app.vault.process()` will be tricky, as Templater processes changes asynchronously, and `app.vault.process()` has to be run synchronously. There will have to be some sort of diff processing if we switch.

**Comment by franciskafieh** [comment]
No problem. For now, there's a workaround with my plugin, so not urgent on my end. Thanks for the consideration, though

**Comment by Zachatoo** [comment]
Since Templater is already emitting an event, going to mark this as closed. Thanks everyone for your contributions to this issue!

**Comment by dvcrn** [comment]
@Zachatoo how/where does it emit this event to? Can you point me into where to look at?

**Comment by Zachatoo** [comment]
Search for `workspace.trigger` in the Templater repo. You can also check the code for the Creases plugin for examples of how to listen to those events.
