### ISSUE TITLE
Bug in `tp.date.now` format rendering

### ISSUE THREAD

**Issue by ces3001** [SilentVoid13/Templater#926]
**Plugin information (please complete the following information):**

-   OS: macOS 12.6
-   Templater version: 1.16.0
-   Obsidian version: 1.0.3

**Describe the bug**
`<% tp.date.now("YYYY/MM/DD", 0, tp.file.title, "YYYY-MM-DD") %>` will _sometimes_ render correctly, and other times as if the format were `"YYYY-MM-DD-ddd”` (my title’s actual format) or `”YYYY”`, and will even erroneously use today’s date instead of the title’s. 

**Expected behavior**
Consistent rendering. 

**Screenshots**
```
#journal/<% tp.date.now("YYYY/MM/DD", 0, tp.file.title, "YYYY-MM-DD") %> 
#date/<% tp.date.now("YYYY/MM/DD", 0, tp.file.title, "YYYY-MM-DD") %> 
```
renders as
```
#journal/2022-11-17-Thu 
#date/2022/11/17 
```
but it should be
```
#journal/2022/11/17 
#date/2022/11/17 
```

**Additional context**
- The “inconsistency” is consistent. That is, it’s always particular statements that render incorrectly, even if they are copy&pasted from perfectly functioning statements that occur elsewhere. Location or order of execution seems to be part of the cause, but I don’t see the pattern. 
- Sometimes, it’ll use the wrong date, like today’s date, instead of the one from `tp.file.title`.
- I am using *daily notes* core-plug-in to create a daily note with title `YYYY-MM-DD-ddd`, with an automatic templater template.

**Comment by ces3001** [comment]
tp.file.title also gives the wrong date. 
I am using *daily notes* core-plug to create a daily note with title `YYYY-MM-DD-ddd`, with a template made for templater.

**Comment by ces3001** [comment]
I found the culprit: 
I had the following code earlier in the template:
```
- [[Dreams/<% tp.date.now("YYYY-MM-DD”), 0, tp.file.title, "YYYY-MM-DD-ddd" %> Dream|Last night’s dream]]
```
Note the misplaced `)`. No error was given upon rendering this statement, but it borked the following tp.date.now statements that used correct syntax.

**Comment by AB1908** [comment]
This will classify as a user error unfortunately. Glad to hear you were able to figure it out though!

**Comment by ces3001** [comment]
> This will classify as a user error unfortunately. Glad to hear you were able to figure it out though!

That may be by-letter-of-law true, but there is some assumptions being made in the code that create non-robust dependencies. If they are easy to fix, worth doing.

**Comment by AB1908** [comment]
Unfortunately, they aren't easy to fix, if fixable at all. I'll let an actual maintainer comment on what they want to do.

**Comment by Zachatoo** [comment]
That is technically valid syntax so there would be no way to catch it without breaking other people's workflows that rely on incomplete statements within Templater tags. Something as simple as the following example wouldn't work if we prevented templates from running that had invalid syntax within a single Templater tag.

```js
<%* if (true) { -%>
# Heading
<%* } -%>
```

**Comment by ces3001** [comment]
The bug I’m referring to isn’t the first incomplete `tp.date` syntax user error, but the _subsecuent_ errors produced by `tp.date` when there was an earlier incomplete syntax.

**Comment by Zachatoo** [comment]
Can you provide more details? You didn't provide your full template, but with the parts you shared, I did get an error from Templater saying that there's a missing `)`.

Template:
```js
[[Dreams/<% tp.date.now("YYYY-MM-DD”), 0, tp.file.title, "YYYY-MM-DD-ddd" %> Dream|Last night’s dream]]

#journal/<% tp.date.now("YYYY/MM/DD", 0, tp.file.title, "YYYY-MM-DD") %> 
#date/<% tp.date.now("YYYY/MM/DD", 0, tp.file.title, "YYYY-MM-DD") %> 
```

The error I got in the console when trying to execute the above template.
```
Templater Error: Template parsing error, aborting. 
Template syntax error: missing ) after argument list
```

**Comment by Zachatoo** [comment]
Marking as removed due to no response from issue author.

**Comment by ces3001** [comment]
Sorry for the delay in responding. 
Indeed the syntax error of the missing `)` existed. That syntax error _caused_ a further error in rendering down the line. See my comment above. https://github.com/SilentVoid13/Templater/issues/926#issuecomment-1320563747
