### ISSUE TITLE
Convert date to calendar week #help needed

### ISSUE THREAD

**Issue by DaKo0990** [SilentVoid13/Templater#929]
Hey everybody,
short question:
I create my meeting notes with QuickAdd. I created a promt where I insert the scheduled meeting date (e.g. a meeting next week --> 2022-11-30)
In the YAML of my meeting note i have two values:
meeting_date: 2022-11-30
meeting_cw: <% tp.date.now("[W]-gggg-[W]ww") %>

My topic is now, that the meeting_date is correct through my input.
The calender week is false, if i create a meeting now for next week.

Can i pass the meeting_date to tp.date.weekday?
I tried sth like: <% tp.date.weekday("YYYY-MM-DD", 0, meeting_date, "[W]-YYYY-[W]ww") %> but I get a strange result.
Maybe you have some ideas how I can handle this.

BR and thanks in advance

**Comment by Zachatoo** [comment]
Closing since this has gone stale, please comment if you're still facing issues.
