### ISSUE TITLE
Templater doesn't run its Skripts (doesn't create Templates)

### ISSUE THREAD

**Issue by Archangeloi89** [SilentVoid13/Templater#932]
Dear Templater Team, 
I have a problem with Templater and that it doesn't run template scripts. 

-   OS: [e.g. Windows 11]
-   Templater version: [1.16.0 ]
-   Obsidian version: [1.0.3]
-   Templater settings: All as standard. Tried different settings, didin't change anything. 

**Describe the bug**
Templater can't execute any Scripts. (like i.e.: <% tp.date.now("YYYY-MM-DD") %> ) I tried many thinks, but it doesn't create the template. It stays as the text command. Changing the view doesn't has an effect. (looks the same)
I activated and deactivated the Core Tamplates Plugin. And deactivated all other community plugins. Templater has no Hotkeys that I changed. The Templates I create don't run. Non had an effect. I reinstalled and uptated everything the the newest version as of today.  

I opened the console to check what it says. 
It doesn't give any errors. 
My online research found some people with the same issue. No solution has workes for me. Even though I went further.   

**Expected behavior**
I would expect thet Templater creates the templates if the scripts are all absolutly correctly written. But it doesn't.

**Additional context**
![Obsidian_D5VgreFzAo](https://user-images.githubusercontent.com/119137383/204110875-7eb92638-e4ed-4f11-b665-3f1a7c33e61f.png)
![Obsidian_MCZ7koC8AA](https://user-images.githubusercontent.com/119137383/204110876-06da0485-91b2-4062-9e66-4bff9cfbba9e.png)

**Comment by Zachatoo** [comment]
Have you tried running any of the "Templater" commands in the command palette? The default keybinding for the command palette is `Ctrl P` on Windows. In your case you'll want to run the "Replace templates in the active file" command if there's templater scripts in a file that you want to be executed.
<img width="783" alt="image" src="https://user-images.githubusercontent.com/6936914/204120286-16903d05-8dbe-4b2e-9b82-1e7bbc9818c1.png">

**Comment by Archangeloi89** [comment]
Thank you so much Zachatoo, this works and the templates are replaced. 
My question is now, why it doesn't work automaticly to run them? 
I mean, I can replace the templates now, but then they are gone and I don't get them back, even when I chancge to source mode. I have to Ctrl Z them back, which is not feasible. 
Is there a way the keep them and express them in the right way in live preview or reading mode?

**Comment by Zachatoo** [comment]
It's recommended to have a "templates" folder where you store your unapplied templates, and then execute those templates on new or existing files, so the template gets applied to the note but you still have access to your template to apply to other notes as well.

For example, I have a template called "daily-notes-template" in my "Templates" folder, and when I create a daily note I'll apply the "daily-notes-template" template to my daily note. I actually use the [folder templates](https://silentvoid13.github.io/Templater/settings.html#folder-templates) feature to do this so the template is applied automatically without having to run a command.

> My question is now, why it doesn't work automaticly to run them?
> I mean, I can replace the templates now, but then they are gone and I don't get them back, even when I chancge to source mode. I have to Ctrl Z them back, which is not feasible.
> Is there a way the keep them and express them in the right way in live preview or reading mode?

There's [dynamic commands](https://silentvoid13.github.io/Templater/commands/dynamic-command.html) but I do not suggest using them, I don't even know if they work in live preview. I highly suggest using the [dataview](https://github.com/blacksmithgu/obsidian-dataview) community plugin instead for dynamic rendering of content.

**Comment by Archangeloi89** [comment]
Thank you so much Zachatoo, so when I understand you right, then it is totaly nomal, that as soon as you run a template that it gets replaced by the information it is heading toward. The dynamic command, would then be what I thought what every template would do. 
I think I can work with that. Seems like everythink woked as intended and the problem was in front of the keyboard xD
Thanks for the fast and great help. So stoked to dip my tows into all the Templater Templates now. So much fun. 
Happy 1. Advent. 
Jiri

**Comment by AB1908** [comment]
Kindly close the issue as well.

**Comment by dang1507** [comment]
I'm having this same issue. When using the example code provided on the .io site 
```
`Date now: <% tp.date.now() %>
Date now with format: <% tp.date.now("Do MMMM YYYY") %>

Last week: <% tp.date.now("dddd Do MMMM YYYY", -7) %>
Today: <% tp.date.now("dddd Do MMMM YYYY, ddd") %>
Next week: <% tp.date.now("dddd Do MMMM YYYY", 7) %>

Last month: <% tp.date.now("YYYY-MM-DD", "P-1M") %>
Next year: <% tp.date.now("YYYY-MM-DD", "P1Y") %>

File's title date + 1 day (tomorrow): <% tp.date.now("YYYY-MM-DD", 1, tp.file.title, "YYYY-MM-DD") %>
File's title date - 1 day (yesterday): <% tp.date.now("YYYY-MM-DD", -1, tp.file.title, "YYYY-MM-DD") %>

Date tomorrow with format: <% tp.date.tomorrow("Do MMMM YYYY") %>    

This week's monday: <% tp.date.weekday("YYYY-MM-DD", 0) %>
Next monday: <% tp.date.weekday("YYYY-MM-DD", 7) %>
File's title monday: <% tp.date.weekday("YYYY-MM-DD", 0, tp.file.title, "YYYY-MM-DD") %>
File's title next monday: <% tp.date.weekday("YYYY-MM-DD", 7, tp.file.title, "YYYY-MM-DD") %>

Date yesterday with format: <% tp.date.yesterday("Do MMMM YYYY") %>`
```

None of this renders. 

I'm using Templater with Periodic Notes. I tried using the templater modal imput, and the replacement. I've uninstalled and reinstalled templater. I tried the advice above and it hasn't worked either. 

Templater 1.16.0

**Comment by Zachatoo** [comment]
> I'm having this same issue. When using the example code provided on the .io site
> 
> None of this renders.
> 
> I'm using Templater with Periodic Notes. I tried using the templater modal imput, and the replacement. I've uninstalled and reinstalled templater. I tried the advice above and it hasn't worked either.
> 
> Templater 1.16.0
> 
> I should add that this is a brand new vault I'm using to test new css styles, so it's quite plain.

@dang1507 To confirm your issue, you have done the following:
1. Created a new vault and installed only Templater.
2. Pasted in the code from the examples that you mentioned.
3. Ran the "Templater: Replace templates in the active file" command.

What happens when you do that? What does "nothing renders" mean? Does nothing happen at all? Any errors when you check the console (`cmd shift i` or `ctrl shift i`)?

When I follow those steps, any text between `<% %>` is replaced with date values based on today.

Before:
```
Date now: <% tp.date.now() %>
Date now with format: <% tp.date.now("Do MMMM YYYY") %>

Last week: <% tp.date.now("dddd Do MMMM YYYY", -7) %>
Today: <% tp.date.now("dddd Do MMMM YYYY, ddd") %>
Next week: <% tp.date.now("dddd Do MMMM YYYY", 7) %>

Last month: <% tp.date.now("YYYY-MM-DD", "P-1M") %>
Next year: <% tp.date.now("YYYY-MM-DD", "P1Y") %>

File's title date + 1 day (tomorrow): <% tp.date.now("YYYY-MM-DD", 1, tp.file.title, "YYYY-MM-DD") %>
File's title date - 1 day (yesterday): <% tp.date.now("YYYY-MM-DD", -1, tp.file.title, "YYYY-MM-DD") %>

Date tomorrow with format: <% tp.date.tomorrow("Do MMMM YYYY") %>    

This week's monday: <% tp.date.weekday("YYYY-MM-DD", 0) %>
Next monday: <% tp.date.weekday("YYYY-MM-DD", 7) %>
File's title monday: <% tp.date.weekday("YYYY-MM-DD", 0, tp.file.title, "YYYY-MM-DD") %>
File's title next monday: <% tp.date.weekday("YYYY-MM-DD", 7, tp.file.title, "YYYY-MM-DD") %>

Date yesterday with format: <% tp.date.yesterday("Do MMMM YYYY") %>
```

After: 
```
Date now: 2023-01-08
Date now with format: 8th January 2023

Last week: Sunday 1st January 2023
Today: Sunday 8th January 2023, Sun
Next week: Sunday 15th January 2023

Last month: 2022-12-08
Next year: 2024-01-08

File's title date + 1 day (tomorrow): 0001-01-02
File's title date - 1 day (yesterday): 0000-12-31

Date tomorrow with format: 9th January 2023    

This week's monday: 2023-01-08
Next monday: 2023-01-15
File's title monday: 0000-12-31
File's title next monday: 0001-01-07

Date yesterday with format: 7th January 2023
```

**Comment by dang1507** [comment]
> > I'm having this same issue. When using the example code provided on the .io site
> > None of this renders.
> > I'm using Templater with Periodic Notes. I tried using the templater modal imput, and the replacement. I've uninstalled and reinstalled templater. I tried the advice above and it hasn't worked either.
> > Templater 1.16.0
> > I should add that this is a brand new vault I'm using to test new css styles, so it's quite plain.
> 
> @dang1507 To confirm your issue, you have done the following:
> 
>     1. Created a new vault and installed only Templater.
> 
>     2. Pasted in the code from the examples that you mentioned.
> 
>     3. Ran the "Templater: Replace templates in the active file" command.
> 
> 
> What happens when you do that? What does "nothing renders" mean? Does nothing happen at all? Any errors when you check the console (`cmd shift i` or `ctrl shift i`)?
> 
> When I follow those steps, any text between `<% %>` is replaced with date values based on today.
> 
> Before:
> 
> ```
> Date now: <% tp.date.now() %>
> Date now with format: <% tp.date.now("Do MMMM YYYY") %>
> 
> Last week: <% tp.date.now("dddd Do MMMM YYYY", -7) %>
> Today: <% tp.date.now("dddd Do MMMM YYYY, ddd") %>
> Next week: <% tp.date.now("dddd Do MMMM YYYY", 7) %>
> 
> Last month: <% tp.date.now("YYYY-MM-DD", "P-1M") %>
> Next year: <% tp.date.now("YYYY-MM-DD", "P1Y") %>
> 
> File's title date + 1 day (tomorrow): <% tp.date.now("YYYY-MM-DD", 1, tp.file.title, "YYYY-MM-DD") %>
> File's title date - 1 day (yesterday): <% tp.date.now("YYYY-MM-DD", -1, tp.file.title, "YYYY-MM-DD") %>
> 
> Date tomorrow with format: <% tp.date.tomorrow("Do MMMM YYYY") %>    
> 
> This week's monday: <% tp.date.weekday("YYYY-MM-DD", 0) %>
> Next monday: <% tp.date.weekday("YYYY-MM-DD", 7) %>
> File's title monday: <% tp.date.weekday("YYYY-MM-DD", 0, tp.file.title, "YYYY-MM-DD") %>
> File's title next monday: <% tp.date.weekday("YYYY-MM-DD", 7, tp.file.title, "YYYY-MM-DD") %>
> 
> Date yesterday with format: <% tp.date.yesterday("Do MMMM YYYY") %>
> ```
> 
> After:
> 
> ```
> Date now: 2023-01-08
> Date now with format: 8th January 2023
> 
> Last week: Sunday 1st January 2023
> Today: Sunday 8th January 2023, Sun
> Next week: Sunday 15th January 2023
> 
> Last month: 2022-12-08
> Next year: 2024-01-08
> 
> File's title date + 1 day (tomorrow): 0001-01-02
> File's title date - 1 day (yesterday): 0000-12-31
> 
> Date tomorrow with format: 9th January 2023    
> 
> This week's monday: 2023-01-08
> Next monday: 2023-01-15
> File's title monday: 0000-12-31
> File's title next monday: 0001-01-07
> 
> Date yesterday with format: 7th January 2023
> ```
Hi I have a few community apps installed they include
![image](https://user-images.githubusercontent.com/60278428/211217395-d77d7f22-c739-4d82-b52f-d5f422a7aa14.png)


When I use Templater, by not render, I mean it just produces text when I use periodic notes or ctrl+p Templater: command.  or ctrl+p periodic: command. I tried the create note with template, insert template, replace template all of them. 

When I use a file that is only that text, it doesn't even create the file, but fails telling me to look at the console. I have opened it, but I am not 100% sure what I am looking for.

**Comment by AB1908** [comment]
Have you turned on the setting for "trigger on new file creation" in Templater's settings?

**Comment by dang1507** [comment]
Yes. Today I'm going to create a new vault and install only templater and see what happens. But I can't do that until later tonight.

![image](https://user-images.githubusercontent.com/60278428/211680553-78e72909-77b3-49af-9931-5b6ac15c9500.png)

**Comment by dang1507** [comment]
The issue has been resolved. I'm not sure what changed, but it is populating correctly now. 
After creating the new vault with only templater, I was successful in getting my templates in place, then when I went to my main vault, things were working. 

I have changed 0 things in my main vault other than adding notes, so I'm at a loss for what was going on.

**Comment by Zachatoo** [comment]
Marking as closed since this appears to be resolved.
