### ISSUE TITLE
Add in documentation a basic example of tp.obsidian usage

### ISSUE THREAD

**Issue by nabaco** [SilentVoid13/Templater#937]
**Is your feature request related to a problem? Please describe.**
It is unclear from documentation how to use the tp.obsidian API.

**Describe the solution you'd like**
A simple example of how to use that API will suffice. Given that I can experiment with the native obsidian API in the developer console, I'm just trying to understand how to glue it into the templates.

**Describe alternatives you've considered** 
Tried to look into the code and experiment myself, but that's not very beginner-friendly :)

**Additional context**
My current use-case is to call a command from a different plugin. In the developer console I managed the following:
```ts
app.commands['commands']['app:show-debug-info'].callback()
```
But in the template it won't work:
```ts
tp.obsidian.app.commands['commands']['app:show-debug-info'].callback()
```
![image](https://user-images.githubusercontent.com/38861757/204686027-43643964-314e-43e8-b516-20ff4a29e220.png)
![image](https://user-images.githubusercontent.com/38861757/204686102-a7f41423-987d-43a4-8fe4-ac50fd56311f.png)

Variations of the same bring the same results.
Best I got was:
```ts
app.commands['commands']['app:show-debug-info'].callback() //Without the tp.obsidian
```
which works when I trigger the template, **but** the template is replaced by "undefined", even if it inserts a text afterwards.

**Comment by danielo515** [comment]
tp.obsidian is not the same as app

**Comment by Zachatoo** [comment]
Good discussion around this [here](https://github.com/SilentVoid13/Templater/discussions/1087) that may be helpful for anyone looking to contribute here.
