### ISSUE TITLE
Replace templates one by one, not all templates in a given file

### ISSUE THREAD

**Issue by Gr-Nobel** [SilentVoid13/Templater#943]
I have more than one tp.system.prompt which i use to track habits. Here are those.::
_C++ : <% tp.system.prompt("Wow many lessons did you finished today? ", "3 lessons") %>

date: <% tp.date.now() %>
---
Problem Practiced:: <% tp.system.prompt("how many problems did you solved today?", "3 Problems") %>_

**When I use the replace command prompt all of them . Sometimes I haven't finished a habit so I click esc. Eventhough I have added value to rest fo the prompts . It returns nothing. If you add value to all of them it returns the values.**

Please solve this. Other people have requested this on Obsidian forum here is a link: https://forum.obsidian.md/t/using-templater-and-system-prompt-with-several-entries/36380

- [ ] please add a ability to replace the tamplates one by one not all templates on a given file

**Comment by Zachatoo** [comment]
This could potentially be resolved with this additional plugin, in conjunction with Templater?

https://github.com/danielo515/obsidian-modal-form

**Comment by Zachatoo** [comment]
Marking as removed due to no response from issue author.
