### ISSUE TITLE
Function argument descriptions in wrong order in documentation

### ISSUE THREAD

**Issue by TomHall2020** [SilentVoid13/Templater#946]
**Is your feature request related to a problem? Please describe.** 
Documentation of function argument descriptions appears in a different order to how they are passed into functions.
<img width="830" alt="Screenshot 2022-12-06 at 13 59 09" src="https://user-images.githubusercontent.com/72264908/205932005-754a5c3a-7532-4f83-aa5f-9a4222374e04.png">

**Describe the solution you'd like** 
Documentation to show the function signature and then the list of argument descriptions in the same order they are passed.

**Describe alternatives you've considered**
Potentially adding syntax highlighting to the signature could make this clearer, but given the work to do that it would seem to make sense to just fix the argument descriptions at the same time. While the correct argument order is clearly shown in the function signature, the combination of flat header styling and all of the type definitions makes it hard to see at a glance what order the paramters take.

**Additional context** 
I can see the function arguments are documented in docs/documentation.toml and seem to be declared in the correct order there,  but when being rendered in the template the order is being lost. 

```
{% if fn.args %}
##### Arguments

{% for key, arg in fn.args %}  <!-- order not preserved here -->
- `{{ arg.name }}`: {{ arg.description }}
{% endfor %}
{% endif %}
```

This caught me out in particular today when I was trying to work out why the placeholder string in my suggester was not displaying; eventually I realised that `throw_on_cancel` needed to be set to its default as well because it appears first. Having the argument descriptions shown in order would have made this a bit easier to work out.

**Comment by AB1908** [comment]
Been burnt by this as well. Can you implement this in a PR?

**Comment by TomHall2020** [comment]
Will give it a try, haven't contributed to an obsidian plugin before though so will have to get myself up to speed with the build process. Is there a contributing guide anywhere or just an explanation of what steps needed to get started and build the plugin (and the docs) that I've missed?

**Comment by AB1908** [comment]
There should be instructions in the readme but you shouldn't need to build the plugin and can focus on just the docs instead.

**Comment by TomHall2020** [comment]
That wasn't as bad as I thought! Short version: TOML tables (dictionaries) do not preserve insertion order when parsed, so by putting each argument as its own key into the args table it would be very difficult to resort it. I changed it to an array of tables, and then iteration in the template naturally goes in the order of declaration.

eg replace declarations like this:
```
[tp.system.functions.prompt.args.prompt_text]
name = "prompt_text"
description = "Text placed above the input field"
```

with this:
```
[[tp.system.functions.prompt.args]]
name = "prompt_text"
description = "Text placed above the input field"
```

PR prepared that makes all the relevent replacements at #947 😊

**Comment by Zachatoo** [comment]
Thank you so much for adding this!! Merged!
