### ISSUE TITLE
run obsidian linter(or any javascript) after insert template

### ISSUE THREAD

**Issue by jteng2127** [SilentVoid13/Templater#948]
**Is your feature request related to a problem? Please describe.**
I want to automatically run obsidian linter (or any javascript?) after insert some metadata template
so that when I modify my linter config, I don't need to manually lint all my metadata template file
moreover, I just need to add necessary content in different metadata template file, that will be lot cleaner

**Describe the solution you'd like**
my template file look like this
```
<% tp.file.include([[templater/mymetadata]]) %>
<%* app.commands.executeCommandById("obsidian-linter:lint-file") %>
```

expect this

```
---
mymetadata content: something
linted content: something
---
```

but it will run linter first, then insert mymetadata, result in
```
---
mymetadata content: something
---
---
linted content: something
---
```

**Describe alternatives you've considered**
current my approach is insert template, then lint it, but that just inconvenient

**Comment by evanharmon1** [comment]
I found this googling for the possibility to run linter commands from a template. Did you end up getting this working? Have you tried async or even a simple sleep command to wait a second maybe?

**Comment by Zachatoo** [comment]
If you `await` the include, it should wait to finish including before moving on to running the lint command.

```js
<% await tp.file.include([[templater/mymetadata]]) %>
<%* app.commands.executeCommandById("obsidian-linter:lint-file") %>
```

**Comment by TrueMilli** [comment]
This instead lints the TEMPLATE file, I'm very confused.

**Comment by TrueMilli** [comment]
> If you `await` the include, it should wait to finish including before moving on to running the lint command.
> 
> ```js
> <% await tp.file.include([[templater/mymetadata]]) %>
> <%* app.commands.executeCommandById("obsidian-linter:lint-file") %>
> ```
> 
> Let me know if this works or doesn't work for you.

This instead lints the TEMPLATE file, I'm very confused.

**Comment by Zachatoo** [comment]
> This instead lints the TEMPLATE file, I'm very confused.

I did some testing and that's not happening for me, which Templater command are you running?

Regardless, I found my template doesn't work, Templater overrides the work that the Linter plugin does. I've updated it to resolve in a promise that Templater won't wait for, so Templater will finish executing before the command is run, and then the command can lint the file.

```js
<% await tp.file.include([[templater/mymetadata]]) %>
<%*
// This should be the last line in your template
// Update 0 to a higher number if needed, 0 should be fine for most templates
new Promise(r => setTimeout(r, 0)).then(() => {
  app.commands.executeCommandById("obsidian-linter:lint-file")
});
-%>
```

**Comment by TrueMilli** [comment]
> > This instead lints the TEMPLATE file, I'm very confused.
> 
> I did some testing and that's not happening for me, which Templater command are you running?
> 
> Regardless, I found my template doesn't work, Templater overrides the work that the Linter plugin does. I've updated it to resolve in a promise that Templater won't wait for, so Templater will finish executing before the command is run, and then the command can lint the file.
> 
> ```js
> <% await tp.file.include([[templater/mymetadata]]) %>
> <%*
> // This should be the last line in your template
> // Update 0 to a higher number if needed, 0 should be fine for most templates
> new Promise(r => setTimeout(r, 0)).then(() => {
>   app.commands.executeCommandById("obsidian-linter:lint-file")
> });
> -%>
> ```

I'm running "Create new note from template". It works just fine applying a template with the respective line afterward, but then I can also just run the linter command.

**Comment by Zachatoo** [comment]
> I'm running "Create new note from template". It works just fine applying a template with the respective line afterward, but then I can also just run the linter command.

I'm still not seeing the template file being linted, but I did have up update my template to wait longer before running the lint command, 100 should be short enough that it's not noticeable but still works.

```js
<% await tp.file.include([[templater/mymetadata]]) %>
<%*
// 100 instead of 0
new Promise(r => setTimeout(r, 100)).then(() => {
  app.commands.executeCommandById("obsidian-linter:lint-file")
});
-%>
```

**Comment by TrueMilli** [comment]
> I'm still not seeing the template file being linted, but I did have up update my template to wait longer before running the lint command, 100 should be short enough that it's not noticeable but still works.
> 
> ```js
> <% await tp.file.include([[templater/mymetadata]]) %>
> <%*
> // 100 instead of 0
> new Promise(r => setTimeout(r, 100)).then(() => {
>   app.commands.executeCommandById("obsidian-linter:lint-file")
> });
> -%>
> ```

It's not linting the template file for me anymore, I don't know what was going on there. It's still not linting the file on creation, I've made screenshots of the whole process. Can you point out my mistake?

## Not Working on Creation

![image](https://github.com/SilentVoid13/Templater/assets/61841994/e4af780e-f75c-4312-abb4-317cead22718)
![image](https://github.com/SilentVoid13/Templater/assets/61841994/db0e48a9-4682-479e-bda2-5132542b8698)
![image](https://github.com/SilentVoid13/Templater/assets/61841994/584c3ee1-0406-4e4d-9253-6038f97f3e95)
![image](https://github.com/SilentVoid13/Templater/assets/61841994/800c0ca6-5378-4ebc-894d-832c4ce7f2fe)

## Working with "Open Insert Template Modal"

![image](https://github.com/SilentVoid13/Templater/assets/61841994/c205218b-b9f1-42e4-bf70-fdea66fecb3f)
![image](https://github.com/SilentVoid13/Templater/assets/61841994/98cc1f4e-78fc-4578-aad7-0fa3818d52ae)
![image](https://github.com/SilentVoid13/Templater/assets/61841994/b3261faf-540b-46ef-892c-166d32008cac)

**Comment by Zachatoo** [comment]
@TrueMilli Increase the timeout to be higher, 100 may not be high enough. I did 1000 and it worked on creation, though 1000 is probably overkill, you can try a few numbers until you find a sweet spot on what works.

**Comment by TrueMilli** [comment]
I have some more insight of what's happening:
- It's linting the file that's open when I run the script (before creating the new file).
- The timeout doesn't seem to do anything. Might it be engine specific? I'm running Obsidian on Windows or Android.

**Comment by Zachatoo** [comment]
[setTimeout](https://caniuse.com/?search=setTimeout) has been available on all browser engines for 10+ years, so it should be available.

No idea why it isn't working for you and it is working for me. Are Obsidian and Templater fully up to date, including the Obsidian installer version? I'm not really sure what else to check for.

**Comment by TrueMilli** [comment]
`setTimeout` is definitely working, if I add something else in the block, it's happening with the appropriate delay.

I'm also very confused.
Obsidian: v1.4.16 (Installer: v1.4.13)
Templater: 1.16.4

![image](https://github.com/SilentVoid13/Templater/assets/61841994/70c2f0d2-153f-4615-908c-30c9ee0648e8)

**Comment by Zachatoo** [comment]
!1241 in it's current state should resolve this. Still ironing out some of the specifics of how it should work, and naming things is hard, but hoping to release it soon.
