### ISSUE TITLE
Mobile-compatible download / curl of a file ?

### ISSUE THREAD

**Issue by Mpic** [SilentVoid13/Templater#96]
With the new possibilities offered by the switch to JavaScript templates, I'd like to know if we could directly download some file without using `curl` or other commands not available on mobile.

My use case is this specific user template I like to use to download the daily weather png : 

```sh
curl --silent fr.wttr.in/mylocation_2p.png --output ./daily/assets/<% tp.file.title %>-weather.png
```

**Comment by calpa** [comment]
@Mpic you can use the fetch api in JavaScript

**Comment by beaussan** [comment]
@calpa You could, but how do you write another file (the image) ? I didn't see a way to do this using the internal templates. Could you provide an example ?

**Comment by calpa** [comment]
@beaussan If you need to execute the system command, you can write `User Function`.
https://silentvoid13.github.io/Templater/docs/user-functions

**Comment by beaussan** [comment]
Right now I'm doing the system command, but it doesn't work on the mobile version :/

**Comment by SilentVoid13** [comment]
Hey @Mpic @beaussan, sorry for the late response.

You can use something along those lines:
```javascript
<%*
const filename = `/daily/assets/${tp.file.title}-weather.png`;
const img_data = await (await fetch("http://fr.wttr.in/mylocation_2p.png")).arrayBuffer();
await app.vault.createBinary(filename, img_data);
%>
```

Tell me if that works for you.

**Comment by Mpic** [comment]
Awesome, thanks ! That seems to work on PC, I have to test on mobile.
Skimming through Obsidian API, I don't see how to force overwrite of an existing file with `createBinary`, do you know if that is possible ?
