### ISSUE TITLE
Feature request: Get date relative to input-date

### ISSUE THREAD

**Issue by NorskNoobing** [SilentVoid13/Templater#965]
**Is your feature request related to a problem? Please describe.**
I want a Templater function to get a date from a date-string, and also get dates relative to the date-string using an offset param. An example of a date-string would be `2022-12-22`.

The problem that I have now is that there are only functions to get dates relative to the current date, but I would want to get dates relative to a entirely different date than today.

**Describe the solution you'd like**
I want a function to get a date relative to a string input and offset values. This could be achieved using a function like:
```
<%tp.date(DATE_STRING,FORMAT-STRING,OFFSET)%>
```
Example:
```
<%tp.date("2022-12-22","YYYY-MM-DD",1)%>
```
This would then output:
```
2022-12-23
```

**Describe alternatives you've considered**
Currently I'm using a userscript that I quickly made, which you can see [in this gist](https://gist.github.com/NorskNoobing/ef059c2af90301dd92e025cf79339be9). The thing I would want changed for a more permanent solution is to add support for the `format-string` param, and set a single param for `day-offset` instead of the current implementation where I have a separate offset for day, month, and year.

**Comment by AB1908** [comment]
Given that obsidian exposes `moment()`, it's unlikely this will be picked up.

**Comment by NorskNoobing** [comment]
> Given that obsidian exposes `moment()`, it's unlikely this will be picked up.

Thanks for mentioning this, because I was looking into using moment earlier, but didn't know it was this easy. Managed to fix the problem by using the following line to get the previous and next days respectively:

```
<% moment(tp.file.title, "YYYY-MM-DD").add(-1, "days").format("YYYY-MM-DD") %>
```

```
<% moment(tp.file.title, "YYYY-MM-DD").add(1, "days").format("YYYY-MM-DD") %>
```

You could also use `.subtract()`, but it works fine by using `.add()` with negative numbers.
