### ISSUE TITLE
New Syntax: No nesting possible? (Trying to emulate old {{tp_title_picture}})

### ISSUE THREAD

**Issue by Moonbase59** [SilentVoid13/Templater#97]
See also https://forum.obsidian.md/t/templater-plugin-new-syntax-emulate-tp-title-picture/16324.

With the _Templater_ plugin’s new syntax, I’m trying to emulate the old `{{tp_title_picture}}` behaviour (generate an unsplash.com image link based on the note’s title).

I tried both
```
<% tp.web.random_picture("1920x1080", "<% tp.file.title %>") %>
<% tp.web.random_picture("1920x1080", <% tp.file.title %>) %>
```
but it seems Templater cannot handle nested variables/functions.

Non-nested calls like
```
<% tp.web.random_picture("1920x1080", "Example") %>
```
work fine.

How would I do this? Or other "nested" Templater commands?

*I think this question is of general interest, because the new syntax allows for easy use of parameters, which in turn might come from other Templater variables or functions.*

In general, the new syntax took away a little (memorized) ease-of-use, but I like the new more structured approach in spite of making the learning curve steeper. It will allow for much more template functionality.

**Comment by SilentVoid13** [comment]
Hey @Moonbase59, you can nest variables and functions if you want.
Because you already declared a command using `<%` and `%>`, you don't have to re-declare it.
The correct syntax for what you'd like to do is:
```
<% tp.web.random_picture("1920x1080", tp.file.title) %>
```

Tell me if this works for you.

**Comment by Moonbase59** [comment]
Works just great, thanks for the fast answer and great explanation!
