### ISSUE TITLE
Change Folder Templates to "Path" Templates

### ISSUE THREAD

**Issue by issaqua** [SilentVoid13/Templater#975]
I'd like to be able to consolidate and extend the "Periodic Notes" functionality into Templater (one plugin instead of many).

The idea is that the Folder Templates would become "Path Templates" by adding an additional field (filename regex) to the "add new" mapping of folder templates.  This allows me to use the same pattern (daily/weekly/...) for plans, journals (reviews), metrics, etc..

This allows for different templates within a given folder.

I hope that makes sense and thanks in advance for considering this.

**Comment by issaqua** [comment]
After further investigation it looks like I can achieve this outcome via https://github.com/SilentVoid13/Templater/discussions/320 

I will add a comment showing the solution I came up with and then close.  Thanks!

**Comment by Zachatoo** [comment]
This has been added in 2.7.3, thanks to @harmtemolder !
