### ISSUE TITLE
Docs: `tp.file.exists()` description is ambiguous 

### ISSUE THREAD

**Issue by chrisgrieser** [SilentVoid13/Templater#977]
`tp.file.exists()` mentions that a full path is necessary, but the at the same time provides examples for a file basename and also named the argument `filename`. From my testing it seems that `tp.file.exists()` indeed requires the full path; the docs should be updated to reflect that and the argument should be renamed to `filepath`.

<img width="1233" alt="Untitled" src="https://user-images.githubusercontent.com/73286100/210220446-1cbd3602-2f50-4e70-a33a-d1ad2703e892.png">

**Comment by Zachatoo** [comment]
Agreed and resolved, thanks!
