### ISSUE TITLE
Error loading any templates or using replace in the active field

### ISSUE THREAD

**Issue by gregomuraca** [SilentVoid13/Templater#978]
**Plugin information (please complete the following information):**

-   OS: [macOS Ventura 13.1]
-   Templater version: [e.g. 1.16.0]
-   Obsidian version: [e.g. 1.1.9]
-   Templater settings: [Template folder location: "Templates", Timeout: "5" (add the templates not working with their associated command)]
[dailynotesTemplate.md](https://github.com/SilentVoid13/Templater/files/10332356/dailynotesTemplate.md)

**Describe the bug**
I can't replace the template in the active field and all the templates are not working 
**Expected behavior**
I would like to use my template when I open a new file
**Screenshots**
<img width="1725" alt="Screenshot 2023-01-02 at 10 02 03 AM" src="https://user-images.githubusercontent.com/74379365/210250056-d28d8e71-bc80-4164-ad39-114f8de9fb74.png">

**Additional context**
 I'm building my learning workflow and I would like to know if I'm doing something wrong and how to solve this problem. 
I'm not a developer my knowledge of JS is limited, I would like your help in understanding and solving the issue, thx

**Comment by YannisCS50** [comment]
same here (MacOS)
Templater don't work at all. I get an error parsing every time

**Comment by amglez** [comment]
I just have installed Templater on a Windows10, templater v.1.16, Obsidian v1.1.9.
When I call insert template, it actually inserts the command (<% whatever %>) but it does not do anything else.
Templater does not work for me, either

**Comment by gregomuraca** [comment]
Does anyone know any possible solution?

**Comment by Holiday2019** [comment]
In my computer, is also error.
![图片](https://user-images.githubusercontent.com/54856595/211037614-44f07cbd-20f4-4105-b000-e728a225efcb.png)

**Comment by Holiday2019** [comment]
> Does anyone know any possible solution?

Just use hotkey "alt+e" to use your template, and you will find it is good. And hotkey "alt+n" is also OK. 

PS: The method by click the buttom of template isn't OK in my computer, either. I haven't find the reason. It is interesting.

**Comment by Holiday2019** [comment]
> Does anyone know any possible solution?

If you can understand Chinese, please look this video: https://www.bilibili.com/video/BV1Xd4y1Y759/

**Comment by YannisCS50** [comment]
@Holiday2019 @amglez do you use MacOS?
Both me and @gregomuraca use MacOS

**Comment by gregomuraca** [comment]
Thanks for the video, I found the issue and how to solve it, basically I made some mistakes in the user script folder and this was making templater unstable. I remove the script from the userscript folder and now everything works fine 
<img width="790" alt="Screenshot 2023-01-06 at 11 03 51 AM" src="https://user-images.githubusercontent.com/74379365/211050665-2a6c9879-0c38-4ad9-a40e-1b23e4203855.png">

**Comment by gregomuraca** [comment]
The quote of the day from the templater [documentation](https://silentvoid13.github.io/Templater/introduction.html). after I fix the issue, good luck! 
> To acquire knowledge, one must study; but to acquire wisdom, one must observe.
> — <cite>Marilyn vos Savant</cite>
