### ISSUE TITLE
Create new note from template isn't keeping the template note title

### ISSUE THREAD

**Issue by mathisgauthey** [SilentVoid13/Templater#979]
**Plugin information (please complete the following information):**

-   OS: Windows 11
-   Templater version: 1.16.0
-   Obsidian version: 1.1.9
-   Templater settings: 
![image](https://user-images.githubusercontent.com/46576952/210272036-51d997e3-33cd-407d-8d96-2d971746beae.png)

**Describe the bug**
I was using the Templates plugin before. I created workout templates in my "5-Templates" folder. Then I created new notes on my "Workout_log" folder and used a template.
I want to automate the process using right click and "Create new note from template" using this plugin instead.

My problem is that the new file title isn't using what I want.

**Expected behavior**
What I want is to find an equivalent to this in the Templates plugin : 
![image](https://user-images.githubusercontent.com/46576952/210272186-cb3b9551-50d9-4967-966a-babb178d6b3b.png)

So that I can create notes with the context menu here : 
![image](https://user-images.githubusercontent.com/46576952/210272218-0a8439cd-e406-455b-95d8-44c66345e6e4.png)

And get the following result : 
![image](https://user-images.githubusercontent.com/46576952/210272337-c6b4d2ce-c002-4e00-ad97-19773eb077fc.png)

**Sorry if the answer is easy, I spent the last 3 hours trying to find a way to do that and failed. I really hope someone with the right knowledge will be able to help me out.**

Thanks in advance !

PS: I have the filename heading sync and the obsidian linter extensions, I just need the file title to update and it will sync without issues.

**Comment by AB1908** [comment]
Can you share your script? I usually like using `tp.file.create_new()` to have power over my file creation. Another approach is to use `tp.file.rename`.

**Comment by mathisgauthey** [comment]
I don't really understand how templater works to be honest. Where am I supposed to write scripts ? Inside my templates ? I used the Templates plugin ever since I started using obsidian and except for the {{date}} placeholder, there is no scripts to write.

**Comment by mathisgauthey** [comment]
Ok I ended up finding where my problem was.

There was two issues actually :
- Firstly, the filename heading sync plugin was trying too hard renaming my just created file.
- Secondly, I needed to learn how to use date, and file title.

I ended up using this script for my heading : 

````
# <% tp.date.now() + "_" + tp.file.title() %> <% tp.file.rename(tp.date.now() + "_" + tp.file.title()) %>
````

That allows me to have a clean file name for my templates instead of a `{{Date}}_Title` kind of title.
And it works wonderfully by using the template file name !

**Comment by mathisgauthey** [comment]
Edit : It is still putting `Untitled` instead of the template file name. It worked just before, but I can't manage to make it work again.

**Comment by mathisgauthey** [comment]
Thanks to #522 , I found a working solution : 

![image](https://user-images.githubusercontent.com/46576952/210280504-4b0fc845-c36d-4bb4-b323-3ea8a4e6a83f.png)


````
---
title: '<% tp.date.now() + "_" + this.app.workspace.getActiveFile().basename %> <% tp.file.rename(tp.date.now() + "_" + this.app.workspace.getActiveFile().basename) %>'
date created: 2022-12-07 23:07:37
date modified: 2023-01-02 22:55:27
tags: 
aliases: 
source: 
type: 
author: 
date: 
---

# <% tp.date.now() + "_" + this.app.workspace.getActiveFile().basename %> <% tp.file.rename(tp.date.now() + "_" + this.app.workspace.getActiveFile().basename) %>

> [!summary]
> Morning routine to start the machine.

Do the [[Standing Wrist Stretches]] + [[Kneeling Wrist Stretches]] for your injury.

Then do the [[Ultimate Mobility Warm-up Routine]] once.
````

**Comment by mathisgauthey** [comment]
Edit : `this.app.workspace.getActiveFile().basename` isn't taking the template name, it is taking the active page name.

I can't seem to find a way to get the template page name, every commands only gets me an untitled.

**Comment by mathisgauthey** [comment]
`# <% tp.date.now() + "_" + tp.config.template_file.basename %> <% tp.file.rename(tp.date.now() + "_" + tp.config.template_file.basename) %>`

The solution was found in #636 and in the [documentation](https://silentvoid13.github.io/Templater/internal-functions/internal-modules/config-module.html) and is to get the **templatefile name** by using `tp.config.template_file.basename`.

Don't know if this is the proper way to communicate about and issue on github, I'll be happy to get insights on how to do it properly if this is too much.
