### ISSUE TITLE
Add Written Numbers To Recurrence, Or Update Documentation To Reflect that Only Numerals Work

### ISSUE THREAD

**Issue by snitkofb** [SilentVoid13/Templater#989]
Currently recurrence only supports numerals (e.g., "1 month", not "one month). I suggest updating the plugin to allow written numbers, or to update the documentation to make it clear that you have to use numerals.

**Comment by Zachatoo** [comment]
Where in the documentation is recurrence mentioned? Are you referring to the `offset` parameter for [`tp.date.now(...)`](https://silentvoid13.github.io/Templater/internal-functions/internal-modules/date-module.html#tpdatenowformat-string--yyyy-mm-dd-offset-numberstring-reference-string-reference_format-string)? If so, there are some examples provided, but they don't match what you have provided.
```js
Last month: <% tp.date.now("YYYY-MM-DD", "P-1M") %>
Next year: <% tp.date.now("YYYY-MM-DD", "P1Y") %>
```

**Comment by snitkofb** [comment]
I am a dummy. And left this note in the repo.
