### ISSUE TITLE
type in multiple cursors location at the same time

### ISSUE THREAD

**Issue by mdelobelle** [SilentVoid13/Templater#99]
Hello, i am a big fan of your plugin, i use it extensively in Obsidian!!

I often want to give aliases when I create a link with templater.

Say I want to create a link `[[Path/to/Dir/Date_of_the_day Cool note | Cool note ]]` to have a human-readable alias in preview mode.
 
I would use a template like `[[<% tp.file.path() %>/<% tp.date.now('YYY-MM-DD') %> <% tp.file.cursor %> | <% tp.file.cursor %>]]`
The pain-point is that i'll have to type "Cool note" two times (with an extra `Alt+Tab` between the two to reach the second cursor).

What if we could have cursor id like `<% tp.file.cursor(1) %>`, whenever we reach this cursor with `Alt+Tab`, it would switch to multi cursor mode (like when we do `Alt+click` in editing mode) at every place where `<% tp.file.cursor(1) %>` is written (but not where `<% tp.file.cursor(2) %>`, `<% tp.file.cursor(3) %>`, etc...)?

**Comment by SilentVoid13** [comment]
Hey @mdelobelle, that's a great idea! I'll try to see if it's possible in the Codemirror API

**Comment by AngelusDomini** [comment]
Am glad to find this feature request as I've also wanted something similar. Here's another suggestion: maybe you could have multiple instances of the same number e.g. `<% tp.file.cursor(1) %>` create multiple cursors instead of using the jump-to-next-cursor-location hotkey (unless you are using other numbers e.g. `<% tp.file.cursor(2) %>`). And maybe you could keep the `<% tp.file.cursor() %>`(no number) to do the default action, which is going through the template from top to bottom.

**Comment by SilentVoid13** [comment]
@mdelobelle @AngelusDomini this feature is ready to be shipped, I'm just waiting for the obsidian API to add a way to deal with multi-cursors. You can follow the github issue here: https://github.com/obsidianmd/obsidian-api/issues/14.

**Comment by mdelobelle** [comment]
@SilentVoid13 that's great thank you. I really hope that obsidian-api team will be able to provide with this capability 🤞

**Comment by SilentVoid13** [comment]
Hey @mdelobelle @AngelusDomini, sorry for the long wait, this is now implemented in Templater 1.7.0, update to try it!

**Comment by Moonbase59** [comment]
Wow, now _this_ is a very usable and helpful function!
Thanks a bundle @mdelobelle for thinking of it, and @SilentVoid13 for implementing it!

**Comment by mdelobelle** [comment]
Great! that's brilliant, thanks a log @SilentVoid13 . this will be a great time saver for me 👍
